## XGBoost Pairwise Feature Validation Entry

This notebook is the handoff entry for feature experiments. It uses rolling k-fold validation from `code/utils/validation.py` while leaving the formal holdout config in `code/config.py` unchanged.

- Split source: `build_validation_plan(raw_df, config).validation_splits()`
- Experiment mode: notebook-local `rolling_kfold`
- Device: from `config['model_params']['xgb_rank_pairwise']['device']`
- Output: `output/xgb_pairwise_feature_validation_rolling_kfold.json`

In [1]:
import copy
import json
import os
import random
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'code').is_dir():
    PROJECT_ROOT = PROJECT_ROOT.parent
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))
sys.modules.pop('code', None)

import numpy as np
import pandas as pd
import xgboost as xgb

from code.config import config as base_config
from code.features.baseline import preprocess_stock_data_samples
from code.features.windows import feature_num_for_window
from code.models.xgboost.loss import topk_return_metrics, xgb_rank_ic_metric, xgb_rank_return_metrics
from code.models.xgboost.model import TqdmTrainingCallback, choose_best_iteration, make_dmatrix, target_range
from code.utils.log import get_logger, log_json
from code.utils.runtime_split import load_market_data
from code.utils.validation import build_validation_plan

config = copy.deepcopy(base_config)
config['validation'] = {**config['validation'], 'mode': 'rolling_kfold'}

MODEL_NAME = 'xgb_rank_pairwise'
EXPERIMENTS = (
    {'input_window': 1, 'feature_type': 'window'},
    {'input_window': 2, 'feature_type': 'window'},
    {'input_window': 4, 'feature_type': 'window'},
    {'input_window': 8, 'feature_type': 'window'},
    {'input_window': 12, 'feature_type': 'window'},
)
OUTPUT_PATH = Path('output/xgb_pairwise_window_factor_validation_rolling_kfold.json')
LOG_PATH = Path('output/xgb_pairwise_window_factor_validation_rolling_kfold.log')
logger = get_logger('xgb_pairwise_window_factor_validation_rolling_kfold', LOG_PATH)

/data/zzj/BDC2026/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
def set_seed(seed):
    # 固定实验随机性。
    random.seed(seed)
    np.random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)


def model_params():
    # 复用正式 pairwise 参数，只移除配置绑定字段。
    params = {
        key: value
        for key, value in config['model_params'][MODEL_NAME].items()
        if key not in {'input_window', 'feature_type'}
    }
    params['disable_default_eval_metric'] = 1
    return params


def split_meta(fold):
    # 记录连续时间块，完全来自 utils.validation.ValidationFold。
    return {
        'fold': fold.name,
        'train_start': str(fold.train_start.date()),
        'train_end': str(fold.train_end.date()),
        'validation_start': str(fold.validation_start.date()),
        'validation_end': str(fold.validation_end.date()),
    }


def train_eval_fold(input_window, feature_type, feature_num, features, fold, train_df, val_df):
    # 单个特征配置在单个时间 fold 上训练评估。
    dtrain, train_groups = make_dmatrix(train_df, features)
    dval, val_groups = make_dmatrix(val_df, features)
    evals_result = {}
    started = time.time()
    num_boost_round = int(config['num_boost_round'])
    booster = xgb.train(
        params=model_params(),
        dtrain=dtrain,
        num_boost_round=num_boost_round,
        evals=[(dtrain, 'train'), (dval, 'validation')],
        custom_metric=xgb_rank_return_metrics,
        maximize=True,
        evals_result=evals_result,
        verbose_eval=False,
        callbacks=[TqdmTrainingCallback(num_boost_round, f'w{input_window} {feature_type} {fold.name}')],
    )
    selection = choose_best_iteration(
        [float(value) for value in evals_result['validation']['top5_excess_return']],
        'validation_top5_excess_return',
    )
    best_iteration = int(selection['best_iteration'])
    val_pred = booster.predict(dval, iteration_range=(0, best_iteration + 1))
    val_top5 = topk_return_metrics(val_pred, dval.get_label(), val_groups, top_k=5)
    val_top10 = topk_return_metrics(val_pred, dval.get_label(), val_groups, top_k=10)
    return {
        **split_meta(fold),
        'model': MODEL_NAME,
        'input_window': input_window,
        'feature_type': feature_type,
        'feature_num': feature_num,
        'features': len(features),
        'rounds': num_boost_round,
        'best_iteration': best_iteration,
        'best_selection_metric': selection['metric'],
        'best_validation_top5_return': float(evals_result['validation']['top5_return'][best_iteration]),
        'best_validation_top5_excess_return': float(selection['score']),
        'best_validation_top5_precision': float(evals_result['validation']['top5_precision'][best_iteration]),
        'validation_rank_ic': float(xgb_rank_ic_metric(val_pred, dval)[1]),
        'validation_universe_return': float(val_top5['benchmark_top5_return_avg']),
        'validation_top5_return': float(val_top5['pred_top5_return_avg']),
        'validation_top5_excess_return': float(val_top5['pred_top5_excess_return_avg']),
        'validation_top5_excess_return_std': float(val_top5['pred_top5_excess_return_std']),
        'validation_top5_excess_return_min': float(val_top5['pred_top5_excess_return_min']),
        'validation_top5_excess_positive_rate': float(val_top5['pred_top5_excess_positive_rate']),
        'validation_top5_precision': float(val_top5['pred_top5_precision_avg']),
        'validation_top10_return': float(val_top10['pred_top10_return_avg']),
        'validation_top10_excess_return': float(val_top10['pred_top10_excess_return_avg']),
        'validation_top10_excess_return_std': float(val_top10['pred_top10_excess_return_std']),
        'validation_top10_excess_return_min': float(val_top10['pred_top10_excess_return_min']),
        'validation_top10_excess_positive_rate': float(val_top10['pred_top10_excess_positive_rate']),
        'validation_top10_precision': float(val_top10['pred_top10_precision_avg']),
        'validation_top5_by_week': val_top5['pred_top5_group_returns'],
        'validation_top5_excess_by_week': val_top5['pred_top5_excess_group_returns'],
        'validation_top10_by_week': val_top10['pred_top10_group_returns'],
        'validation_top10_excess_by_week': val_top10['pred_top10_excess_group_returns'],
        'train_groups': len(train_groups),
        'validation_groups': len(val_groups),
        'train_rows': int(dtrain.num_row()),
        'validation_rows': int(dval.num_row()),
        'seconds': time.time() - started,
    }


def summarize(rows):
    # 按 rolling fold 聚合，fold_count 用于确认 std 来自多折验证。
    df = pd.DataFrame(rows)
    metric_cols = [
        'best_validation_top5_return',
        'best_validation_top5_excess_return',
        'best_validation_top5_precision',
        'validation_rank_ic',
        'validation_universe_return',
        'validation_top5_return',
        'validation_top5_excess_return',
        'validation_top5_excess_return_std',
        'validation_top5_excess_return_min',
        'validation_top5_excess_positive_rate',
        'validation_top5_precision',
        'validation_top10_return',
        'validation_top10_excess_return',
        'validation_top10_excess_return_std',
        'validation_top10_excess_return_min',
        'validation_top10_excess_positive_rate',
        'validation_top10_precision',
    ]
    grouped = df.groupby(['input_window', 'feature_type', 'feature_num', 'features'], sort=False)
    summary = grouped[metric_cols].agg(['mean', 'std', 'min', 'max'])
    summary.columns = ['_'.join(col).rstrip('_') for col in summary.columns]
    summary['fold_count'] = grouped.size()
    summary = summary.reset_index()
    front_cols = ['input_window', 'feature_type', 'feature_num', 'features', 'fold_count']
    return summary[front_cols + [col for col in summary.columns if col not in front_cols]]


def leaderboard(summary):
    # 只展示最关键的模型选择列，完整 summary 仍写入 JSON。
    columns = [
        'input_window',
        'feature_type',
        'features',
        'fold_count',
        'validation_top5_excess_return_mean',
        'validation_top5_excess_return_std',
        'validation_top5_excess_return_min',
        'validation_top5_excess_positive_rate_mean',
        'validation_top5_precision_mean',
        'validation_rank_ic_mean',
        'validation_top5_return_mean',
        'validation_universe_return_mean',
    ]
    available = [col for col in columns if col in summary.columns]
    return summary.sort_values('validation_top5_excess_return_mean', ascending=False)[available].reset_index(drop=True)

In [3]:
set_seed(int(config['seed']))
started = time.time()
raw_df = load_market_data(config)
stock_ids = sorted(raw_df['股票代码'].unique())
stockid2idx = {sid: idx for idx, sid in enumerate(stock_ids)}
plan = build_validation_plan(raw_df, config)
folds = plan.validation_splits()
log_json(logger, 'validation_config', config['validation'])
log_json(logger, 'folds', [split_meta(fold) for fold in folds])
logger.info('data rows=%s stocks=%s date=%s..%s', len(raw_df), len(stock_ids), raw_df['日期'].min().date(), raw_df['日期'].max().date())

rows = []
datasets = {}
for experiment in EXPERIMENTS:
    input_window = int(experiment['input_window'])
    feature_type = experiment['feature_type']
    feature_num = feature_num_for_window(input_window, feature_type)
    dataset_key = f'{input_window}:{feature_type}'
    datasets[dataset_key] = {'input_window': input_window, 'feature_type': feature_type, 'feature_num': feature_num, 'folds': []}
    for fold in folds:
        logger.info('prepare input_window=%s feature_type=%s fold=%s', input_window, feature_type, fold.name)
        train_samples = plan.get_train_samples(fold, input_window)
        val_samples = plan.get_validation_samples(fold, input_window)
        train_df, features = preprocess_stock_data_samples(train_samples, feature_num, stockid2idx)
        val_df, _ = preprocess_stock_data_samples(val_samples, feature_num, stockid2idx)
        train_df = train_df.dropna(subset=['label']).sort_values(['日期', '股票代码']).reset_index(drop=True)
        val_df = val_df.dropna(subset=['label']).sort_values(['日期', '股票代码']).reset_index(drop=True)
        fold_data = {
            **split_meta(fold),
            'features': len(features),
            'train_rows': len(train_df),
            'validation_rows': len(val_df),
            'train_target_range': target_range(train_df),
            'validation_target_range': target_range(val_df),
        }
        datasets[dataset_key]['folds'].append(fold_data)
        logger.info('train input_window=%s feature_type=%s fold=%s features=%s', input_window, feature_type, fold.name, len(features))
        rows.append(train_eval_fold(input_window, feature_type, feature_num, features, fold, train_df, val_df))

summary = summarize(rows)
payload = {
    'experiment': 'xgb_rank_pairwise_window_factor_validation',
    'split_source': 'code.utils.validation.build_validation_plan(...).validation_splits()',
    'seed': int(config['seed']),
    'num_boost_round': int(config['num_boost_round']),
    'validation_config': config['validation'],
    'folds': [split_meta(fold) for fold in folds],
    'experiments': EXPERIMENTS,
    'datasets': datasets,
    'rows': rows,
    'summary': summary.to_dict('records'),
    'elapsed_seconds': time.time() - started,
}
OUTPUT_PATH.parent.mkdir(exist_ok=True)
OUTPUT_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding='utf-8')
logger.info('saved=%s elapsed=%.2fs', OUTPUT_PATH, payload['elapsed_seconds'])
leaderboard(summary)

2026-07-06 17:22:26 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | validation_config={"mode": "rolling_kfold", "num_test_weeks": 4, "num_validation_weeks": 8, "rolling_folds": 4, "rolling_gap_weeks": 0, "rolling_min_train_weeks": 120, "rolling_validation_weeks": 4}

2026-07-06 17:22:26 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | folds=[{"fold": "rolling_1", "train_end": "2026-01-26", "train_start": "2023-01-09", "validation_end": "2026-03-09", "validation_start": "2026-01-26"}, {"fold": "rolling_2", "train_end": "2026-03-09", "train_start": "2023-01-09", "validation_end": "2026-04-13", "validation_start": "2026-03-09"}, {"fold": "rolling_3", "train_end": "2026-04-13", "train_start": "2023-01-09", "validation_end": "2026-05-25", "validation_start": "2026-04-13"}, {"fold": "rolling_4", "train_end": "2026-05-25", "train_start": "2023-01-09", "validation_end": "2026-06-29", "validation_start": "2026-05-25"}]

2026-07-06 17:22:26 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | data rows=250233 stocks=300 date=2023-01-03..2026-06-26

2026-07-06 17:22:26 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=1 feature_type=window fold=rolling_1

2026-07-06 17:22:43 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=1 feature_type=window fold=rolling_1 features=69

w1 window rolling_1:   0%|                          | 0/200 [00:00<?, ?round/s]

w1 window rolling_1:   0%|                  | 1/200 [00:00<01:04,  3.11round/s]

w1 window rolling_1:   0%| | 1/200 [00:00<01:04,  3.11round/s, val_excess=-0.01

w1 window rolling_1:   1%| | 2/200 [00:00<01:03,  3.11round/s, val_excess=-0.00

w1 window rolling_1:   2%| | 3/200 [00:00<00:28,  6.90round/s, val_excess=-0.00

w1 window rolling_1:   2%| | 3/200 [00:00<00:28,  6.90round/s, val_excess=-0.00

w1 window rolling_1:   2%| | 4/200 [00:00<00:28,  6.90round/s, val_excess=0.007

w1 window rolling_1:   2%| | 5/200 [00:00<00:23,  8.34round/s, val_excess=0.007

w1 window rolling_1:   2%| | 5/200 [00:00<00:23,  8.34round/s, val_excess=0.030

w1 window rolling_1:   3%| | 6/200 [00:00<00:23,  8.34round/s, val_excess=0.031

w1 window rolling_1:   4%| | 7/200 [00:00<00:21,  9.16round/s, val_excess=0.031

w1 window rolling_1:   4%| | 7/200 [00:00<00:21,  9.16round/s, val_excess=0.018

w1 window rolling_1:   4%| | 8/200 [00:00<00:20,  9.16round/s, val_excess=0.008

w1 window rolling_1:   4%| | 9/200 [00:01<00:19,  9.64round/s, val_excess=0.008

w1 window rolling_1:   4%| | 9/200 [00:01<00:19,  9.64round/s, val_excess=0.026

w1 window rolling_1:   5%| | 10/200 [00:01<00:19,  9.64round/s, val_excess=0.02

w1 window rolling_1:   6%| | 11/200 [00:01<00:18,  9.95round/s, val_excess=0.02

w1 window rolling_1:   6%| | 11/200 [00:01<00:18,  9.95round/s, val_excess=0.01

w1 window rolling_1:   6%| | 12/200 [00:01<00:18,  9.95round/s, val_excess=0.01

w1 window rolling_1:   6%| | 13/200 [00:01<00:18, 10.09round/s, val_excess=0.01

w1 window rolling_1:   6%| | 13/200 [00:01<00:18, 10.09round/s, val_excess=0.00

w1 window rolling_1:   7%| | 14/200 [00:01<00:18, 10.09round/s, val_excess=0.00

w1 window rolling_1:   8%| | 15/200 [00:01<00:18, 10.12round/s, val_excess=0.00

w1 window rolling_1:   8%| | 15/200 [00:01<00:18, 10.12round/s, val_excess=0.00

w1 window rolling_1:   8%| | 16/200 [00:01<00:18, 10.12round/s, val_excess=0.00

w1 window rolling_1:   8%| | 17/200 [00:01<00:18, 10.14round/s, val_excess=0.00

w1 window rolling_1:   8%| | 17/200 [00:01<00:18, 10.14round/s, val_excess=0.00

w1 window rolling_1:   9%| | 18/200 [00:01<00:17, 10.14round/s, val_excess=0.00

w1 window rolling_1:  10%| | 19/200 [00:02<00:17, 10.16round/s, val_excess=0.00

w1 window rolling_1:  10%| | 19/200 [00:02<00:17, 10.16round/s, val_excess=0.00

w1 window rolling_1:  10%| | 20/200 [00:02<00:17, 10.16round/s, val_excess=0.00

w1 window rolling_1:  10%| | 21/200 [00:02<00:17, 10.16round/s, val_excess=0.00

w1 window rolling_1:  10%| | 21/200 [00:02<00:17, 10.16round/s, val_excess=0.00

w1 window rolling_1:  11%| | 22/200 [00:02<00:17, 10.16round/s, val_excess=-0.0

w1 window rolling_1:  12%| | 23/200 [00:02<00:17, 10.13round/s, val_excess=-0.0

w1 window rolling_1:  12%| | 23/200 [00:02<00:17, 10.13round/s, val_excess=-0.0

w1 window rolling_1:  12%| | 24/200 [00:02<00:17, 10.13round/s, val_excess=-0.0

w1 window rolling_1:  12%|▏| 25/200 [00:02<00:17, 10.04round/s, val_excess=-0.0

w1 window rolling_1:  12%|▏| 25/200 [00:02<00:17, 10.04round/s, val_excess=0.00

w1 window rolling_1:  13%|▏| 26/200 [00:02<00:17, 10.04round/s, val_excess=-0.0

w1 window rolling_1:  14%|▏| 27/200 [00:02<00:17, 10.11round/s, val_excess=-0.0

w1 window rolling_1:  14%|▏| 27/200 [00:02<00:17, 10.11round/s, val_excess=-0.0

w1 window rolling_1:  14%|▏| 28/200 [00:02<00:17, 10.11round/s, val_excess=-0.0

w1 window rolling_1:  14%|▏| 29/200 [00:03<00:16, 10.12round/s, val_excess=-0.0

w1 window rolling_1:  14%|▏| 29/200 [00:03<00:16, 10.12round/s, val_excess=-0.0

w1 window rolling_1:  15%|▏| 30/200 [00:03<00:16, 10.12round/s, val_excess=0.00

w1 window rolling_1:  16%|▏| 31/200 [00:03<00:16, 10.18round/s, val_excess=0.00

w1 window rolling_1:  16%|▏| 31/200 [00:03<00:16, 10.18round/s, val_excess=0.01

w1 window rolling_1:  16%|▏| 32/200 [00:03<00:16, 10.18round/s, val_excess=0.01

w1 window rolling_1:  16%|▏| 33/200 [00:03<00:16, 10.16round/s, val_excess=0.01

w1 window rolling_1:  16%|▏| 33/200 [00:03<00:16, 10.16round/s, val_excess=0.02

w1 window rolling_1:  17%|▏| 34/200 [00:03<00:16, 10.16round/s, val_excess=0.02

w1 window rolling_1:  18%|▏| 35/200 [00:03<00:16, 10.07round/s, val_excess=0.02

w1 window rolling_1:  18%|▏| 35/200 [00:03<00:16, 10.07round/s, val_excess=0.02

w1 window rolling_1:  18%|▏| 36/200 [00:03<00:16, 10.07round/s, val_excess=0.02

w1 window rolling_1:  18%|▏| 37/200 [00:03<00:16, 10.03round/s, val_excess=0.02

w1 window rolling_1:  18%|▏| 37/200 [00:03<00:16, 10.03round/s, val_excess=0.01

w1 window rolling_1:  19%|▏| 38/200 [00:03<00:16, 10.03round/s, val_excess=0.02

w1 window rolling_1:  20%|▏| 39/200 [00:04<00:16, 10.04round/s, val_excess=0.02

w1 window rolling_1:  20%|▏| 39/200 [00:04<00:16, 10.04round/s, val_excess=0.03

w1 window rolling_1:  20%|▏| 40/200 [00:04<00:15, 10.04round/s, val_excess=0.03

w1 window rolling_1:  20%|▏| 41/200 [00:04<00:15, 10.02round/s, val_excess=0.03

w1 window rolling_1:  20%|▏| 41/200 [00:04<00:15, 10.02round/s, val_excess=0.01

w1 window rolling_1:  21%|▏| 42/200 [00:04<00:15, 10.02round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 43/200 [00:04<00:15,  9.98round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 43/200 [00:04<00:15,  9.98round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 44/200 [00:04<00:15,  9.97round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 44/200 [00:04<00:15,  9.97round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 45/200 [00:04<00:15,  9.95round/s, val_excess=0.02

w1 window rolling_1:  22%|▏| 45/200 [00:04<00:15,  9.95round/s, val_excess=0.03

w1 window rolling_1:  23%|▏| 46/200 [00:04<00:15,  9.95round/s, val_excess=0.03

w1 window rolling_1:  24%|▏| 47/200 [00:04<00:15, 10.01round/s, val_excess=0.03

w1 window rolling_1:  24%|▏| 47/200 [00:04<00:15, 10.01round/s, val_excess=0.02

w1 window rolling_1:  24%|▏| 48/200 [00:04<00:15, 10.00round/s, val_excess=0.02

w1 window rolling_1:  24%|▏| 48/200 [00:04<00:15, 10.00round/s, val_excess=0.02

w1 window rolling_1:  24%|▏| 49/200 [00:05<00:15,  9.98round/s, val_excess=0.02

w1 window rolling_1:  24%|▏| 49/200 [00:05<00:15,  9.98round/s, val_excess=0.02

w1 window rolling_1:  25%|▎| 50/200 [00:05<00:15,  9.98round/s, val_excess=0.01

w1 window rolling_1:  26%|▎| 51/200 [00:05<00:14, 10.03round/s, val_excess=0.01

w1 window rolling_1:  26%|▎| 51/200 [00:05<00:14, 10.03round/s, val_excess=0.01

w1 window rolling_1:  26%|▎| 52/200 [00:05<00:14, 10.03round/s, val_excess=0.01

w1 window rolling_1:  26%|▎| 53/200 [00:05<00:14,  9.97round/s, val_excess=0.01

w1 window rolling_1:  26%|▎| 53/200 [00:05<00:14,  9.97round/s, val_excess=0.01

w1 window rolling_1:  27%|▎| 54/200 [00:05<00:14,  9.97round/s, val_excess=0.01

w1 window rolling_1:  28%|▎| 55/200 [00:05<00:14,  9.96round/s, val_excess=0.01

w1 window rolling_1:  28%|▎| 55/200 [00:05<00:14,  9.96round/s, val_excess=0.01

w1 window rolling_1:  28%|▎| 56/200 [00:05<00:14,  9.88round/s, val_excess=0.01

w1 window rolling_1:  28%|▎| 56/200 [00:05<00:14,  9.88round/s, val_excess=0.02

w1 window rolling_1:  28%|▎| 57/200 [00:05<00:14,  9.83round/s, val_excess=0.02

w1 window rolling_1:  28%|▎| 57/200 [00:05<00:14,  9.83round/s, val_excess=0.02

w1 window rolling_1:  29%|▎| 58/200 [00:05<00:14,  9.79round/s, val_excess=0.02

w1 window rolling_1:  29%|▎| 58/200 [00:05<00:14,  9.79round/s, val_excess=0.01

w1 window rolling_1:  30%|▎| 59/200 [00:06<00:14,  9.81round/s, val_excess=0.01

w1 window rolling_1:  30%|▎| 59/200 [00:06<00:14,  9.81round/s, val_excess=0.03

w1 window rolling_1:  30%|▎| 60/200 [00:06<00:14,  9.82round/s, val_excess=0.03

w1 window rolling_1:  30%|▎| 60/200 [00:06<00:14,  9.82round/s, val_excess=0.03

w1 window rolling_1:  30%|▎| 61/200 [00:06<00:14,  9.81round/s, val_excess=0.03

w1 window rolling_1:  30%|▎| 61/200 [00:06<00:14,  9.81round/s, val_excess=0.02

w1 window rolling_1:  31%|▎| 62/200 [00:06<00:14,  9.74round/s, val_excess=0.02

w1 window rolling_1:  31%|▎| 62/200 [00:06<00:14,  9.74round/s, val_excess=0.02

w1 window rolling_1:  32%|▎| 63/200 [00:06<00:14,  9.69round/s, val_excess=0.02

w1 window rolling_1:  32%|▎| 63/200 [00:06<00:14,  9.69round/s, val_excess=0.02

w1 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.66round/s, val_excess=0.02

w1 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.66round/s, val_excess=0.03

w1 window rolling_1:  32%|▎| 65/200 [00:06<00:13,  9.69round/s, val_excess=0.03

w1 window rolling_1:  32%|▎| 65/200 [00:06<00:13,  9.69round/s, val_excess=0.02

w1 window rolling_1:  33%|▎| 66/200 [00:06<00:13,  9.60round/s, val_excess=0.02

w1 window rolling_1:  33%|▎| 66/200 [00:06<00:13,  9.60round/s, val_excess=0.02

w1 window rolling_1:  34%|▎| 67/200 [00:06<00:13,  9.55round/s, val_excess=0.02

w1 window rolling_1:  34%|▎| 67/200 [00:06<00:13,  9.55round/s, val_excess=0.03

w1 window rolling_1:  34%|▎| 68/200 [00:06<00:13,  9.58round/s, val_excess=0.03

w1 window rolling_1:  34%|▎| 68/200 [00:06<00:13,  9.58round/s, val_excess=0.03

w1 window rolling_1:  34%|▎| 69/200 [00:07<00:13,  9.57round/s, val_excess=0.03

w1 window rolling_1:  34%|▎| 69/200 [00:07<00:13,  9.57round/s, val_excess=0.02

w1 window rolling_1:  35%|▎| 70/200 [00:07<00:13,  9.60round/s, val_excess=0.02

w1 window rolling_1:  35%|▎| 70/200 [00:07<00:13,  9.60round/s, val_excess=0.03

w1 window rolling_1:  36%|▎| 71/200 [00:07<00:13,  9.61round/s, val_excess=0.03

w1 window rolling_1:  36%|▎| 71/200 [00:07<00:13,  9.61round/s, val_excess=0.02

w1 window rolling_1:  36%|▎| 72/200 [00:07<00:13,  9.57round/s, val_excess=0.02

w1 window rolling_1:  36%|▎| 72/200 [00:07<00:13,  9.57round/s, val_excess=0.02

w1 window rolling_1:  36%|▎| 73/200 [00:07<00:13,  9.57round/s, val_excess=0.02

w1 window rolling_1:  36%|▎| 73/200 [00:07<00:13,  9.57round/s, val_excess=0.02

w1 window rolling_1:  37%|▎| 74/200 [00:07<00:13,  9.51round/s, val_excess=0.02

w1 window rolling_1:  37%|▎| 74/200 [00:07<00:13,  9.51round/s, val_excess=0.02

w1 window rolling_1:  38%|▍| 75/200 [00:07<00:13,  9.54round/s, val_excess=0.02

w1 window rolling_1:  38%|▍| 75/200 [00:07<00:13,  9.54round/s, val_excess=0.03

w1 window rolling_1:  38%|▍| 76/200 [00:07<00:12,  9.57round/s, val_excess=0.03

w1 window rolling_1:  38%|▍| 76/200 [00:07<00:12,  9.57round/s, val_excess=0.03

w1 window rolling_1:  38%|▍| 77/200 [00:07<00:12,  9.59round/s, val_excess=0.03

w1 window rolling_1:  38%|▍| 77/200 [00:07<00:12,  9.59round/s, val_excess=0.03

w1 window rolling_1:  39%|▍| 78/200 [00:08<00:12,  9.53round/s, val_excess=0.03

w1 window rolling_1:  39%|▍| 78/200 [00:08<00:12,  9.53round/s, val_excess=0.03

w1 window rolling_1:  40%|▍| 79/200 [00:08<00:12,  9.62round/s, val_excess=0.03

w1 window rolling_1:  40%|▍| 79/200 [00:08<00:12,  9.62round/s, val_excess=0.03

w1 window rolling_1:  40%|▍| 80/200 [00:08<00:12,  9.62round/s, val_excess=0.03

w1 window rolling_1:  40%|▍| 81/200 [00:08<00:12,  9.91round/s, val_excess=0.03

w1 window rolling_1:  40%|▍| 81/200 [00:08<00:12,  9.91round/s, val_excess=0.03

w1 window rolling_1:  41%|▍| 82/200 [00:08<00:11,  9.91round/s, val_excess=0.03

w1 window rolling_1:  42%|▍| 83/200 [00:08<00:11, 10.10round/s, val_excess=0.03

w1 window rolling_1:  42%|▍| 83/200 [00:08<00:11, 10.10round/s, val_excess=0.03

w1 window rolling_1:  42%|▍| 84/200 [00:08<00:11, 10.10round/s, val_excess=0.03

w1 window rolling_1:  42%|▍| 85/200 [00:08<00:11, 10.12round/s, val_excess=0.03

w1 window rolling_1:  42%|▍| 85/200 [00:08<00:11, 10.12round/s, val_excess=0.02

w1 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.12round/s, val_excess=0.02

w1 window rolling_1:  44%|▍| 87/200 [00:08<00:11, 10.10round/s, val_excess=0.02

w1 window rolling_1:  44%|▍| 87/200 [00:08<00:11, 10.10round/s, val_excess=0.03

w1 window rolling_1:  44%|▍| 88/200 [00:08<00:11, 10.10round/s, val_excess=0.03

w1 window rolling_1:  44%|▍| 89/200 [00:09<00:10, 10.10round/s, val_excess=0.03

w1 window rolling_1:  44%|▍| 89/200 [00:09<00:10, 10.10round/s, val_excess=0.03

w1 window rolling_1:  45%|▍| 90/200 [00:09<00:10, 10.10round/s, val_excess=0.03

w1 window rolling_1:  46%|▍| 91/200 [00:09<00:10, 10.18round/s, val_excess=0.03

w1 window rolling_1:  46%|▍| 91/200 [00:09<00:10, 10.18round/s, val_excess=0.03

w1 window rolling_1:  46%|▍| 92/200 [00:09<00:10, 10.18round/s, val_excess=0.03

w1 window rolling_1:  46%|▍| 93/200 [00:09<00:10, 10.22round/s, val_excess=0.03

w1 window rolling_1:  46%|▍| 93/200 [00:09<00:10, 10.22round/s, val_excess=0.03

w1 window rolling_1:  47%|▍| 94/200 [00:09<00:10, 10.22round/s, val_excess=0.03

w1 window rolling_1:  48%|▍| 95/200 [00:09<00:10, 10.27round/s, val_excess=0.03

w1 window rolling_1:  48%|▍| 95/200 [00:09<00:10, 10.27round/s, val_excess=0.02

w1 window rolling_1:  48%|▍| 96/200 [00:09<00:10, 10.27round/s, val_excess=0.03

w1 window rolling_1:  48%|▍| 97/200 [00:09<00:10, 10.29round/s, val_excess=0.03

w1 window rolling_1:  48%|▍| 97/200 [00:09<00:10, 10.29round/s, val_excess=0.02

w1 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.29round/s, val_excess=0.03

w1 window rolling_1:  50%|▍| 99/200 [00:10<00:09, 10.22round/s, val_excess=0.03

w1 window rolling_1:  50%|▍| 99/200 [00:10<00:09, 10.22round/s, val_excess=0.03

w1 window rolling_1:  50%|▌| 100/200 [00:10<00:09, 10.22round/s, val_excess=0.0

w1 window rolling_1:  50%|▌| 101/200 [00:10<00:09, 10.21round/s, val_excess=0.0

w1 window rolling_1:  50%|▌| 101/200 [00:10<00:09, 10.21round/s, val_excess=0.0

w1 window rolling_1:  51%|▌| 102/200 [00:10<00:09, 10.21round/s, val_excess=0.0

w1 window rolling_1:  52%|▌| 103/200 [00:10<00:09, 10.19round/s, val_excess=0.0

w1 window rolling_1:  52%|▌| 103/200 [00:10<00:09, 10.19round/s, val_excess=0.0

w1 window rolling_1:  52%|▌| 104/200 [00:10<00:09, 10.19round/s, val_excess=0.0

w1 window rolling_1:  52%|▌| 105/200 [00:10<00:09, 10.16round/s, val_excess=0.0

w1 window rolling_1:  52%|▌| 105/200 [00:10<00:09, 10.16round/s, val_excess=0.0

w1 window rolling_1:  53%|▌| 106/200 [00:10<00:09, 10.16round/s, val_excess=0.0

w1 window rolling_1:  54%|▌| 107/200 [00:10<00:09, 10.12round/s, val_excess=0.0

w1 window rolling_1:  54%|▌| 107/200 [00:10<00:09, 10.12round/s, val_excess=0.0

w1 window rolling_1:  54%|▌| 108/200 [00:10<00:09, 10.12round/s, val_excess=0.0

w1 window rolling_1:  55%|▌| 109/200 [00:11<00:09,  9.62round/s, val_excess=0.0

w1 window rolling_1:  55%|▌| 109/200 [00:11<00:09,  9.62round/s, val_excess=0.0

w1 window rolling_1:  55%|▌| 110/200 [00:11<00:09,  9.62round/s, val_excess=0.0

w1 window rolling_1:  56%|▌| 111/200 [00:11<00:09,  9.80round/s, val_excess=0.0

w1 window rolling_1:  56%|▌| 111/200 [00:11<00:09,  9.80round/s, val_excess=0.0

w1 window rolling_1:  56%|▌| 112/200 [00:11<00:08,  9.80round/s, val_excess=0.0

w1 window rolling_1:  56%|▌| 113/200 [00:11<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_1:  56%|▌| 113/200 [00:11<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_1:  57%|▌| 114/200 [00:11<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_1:  57%|▌| 115/200 [00:11<00:08, 10.02round/s, val_excess=0.0

w1 window rolling_1:  57%|▌| 115/200 [00:11<00:08, 10.02round/s, val_excess=0.0

w1 window rolling_1:  58%|▌| 116/200 [00:11<00:08, 10.02round/s, val_excess=0.0

w1 window rolling_1:  58%|▌| 117/200 [00:11<00:08, 10.03round/s, val_excess=0.0

w1 window rolling_1:  58%|▌| 117/200 [00:11<00:08, 10.03round/s, val_excess=0.0

w1 window rolling_1:  59%|▌| 118/200 [00:11<00:08, 10.03round/s, val_excess=0.0

w1 window rolling_1:  60%|▌| 119/200 [00:12<00:08, 10.12round/s, val_excess=0.0

w1 window rolling_1:  60%|▌| 119/200 [00:12<00:08, 10.12round/s, val_excess=0.0

w1 window rolling_1:  60%|▌| 120/200 [00:12<00:07, 10.12round/s, val_excess=0.0

w1 window rolling_1:  60%|▌| 121/200 [00:12<00:07, 10.20round/s, val_excess=0.0

w1 window rolling_1:  60%|▌| 121/200 [00:12<00:07, 10.20round/s, val_excess=0.0

w1 window rolling_1:  61%|▌| 122/200 [00:12<00:07, 10.20round/s, val_excess=0.0

w1 window rolling_1:  62%|▌| 123/200 [00:12<00:07, 10.28round/s, val_excess=0.0

w1 window rolling_1:  62%|▌| 123/200 [00:12<00:07, 10.28round/s, val_excess=0.0

w1 window rolling_1:  62%|▌| 124/200 [00:12<00:07, 10.28round/s, val_excess=0.0

w1 window rolling_1:  62%|▋| 125/200 [00:12<00:07, 10.23round/s, val_excess=0.0

w1 window rolling_1:  62%|▋| 125/200 [00:12<00:07, 10.23round/s, val_excess=0.0

w1 window rolling_1:  63%|▋| 126/200 [00:12<00:07, 10.23round/s, val_excess=0.0

w1 window rolling_1:  64%|▋| 127/200 [00:12<00:07,  9.80round/s, val_excess=0.0

w1 window rolling_1:  64%|▋| 127/200 [00:12<00:07,  9.80round/s, val_excess=0.0

w1 window rolling_1:  64%|▋| 128/200 [00:12<00:07,  9.80round/s, val_excess=0.0

w1 window rolling_1:  64%|▋| 129/200 [00:13<00:07, 10.04round/s, val_excess=0.0

w1 window rolling_1:  64%|▋| 129/200 [00:13<00:07, 10.04round/s, val_excess=0.0

w1 window rolling_1:  65%|▋| 130/200 [00:13<00:06, 10.04round/s, val_excess=0.0

w1 window rolling_1:  66%|▋| 131/200 [00:13<00:06, 10.31round/s, val_excess=0.0

w1 window rolling_1:  66%|▋| 131/200 [00:13<00:06, 10.31round/s, val_excess=0.0

w1 window rolling_1:  66%|▋| 132/200 [00:13<00:06, 10.31round/s, val_excess=0.0

w1 window rolling_1:  66%|▋| 133/200 [00:13<00:06, 10.54round/s, val_excess=0.0

w1 window rolling_1:  66%|▋| 133/200 [00:13<00:06, 10.54round/s, val_excess=0.0

w1 window rolling_1:  67%|▋| 134/200 [00:13<00:06, 10.54round/s, val_excess=0.0

w1 window rolling_1:  68%|▋| 135/200 [00:13<00:06, 10.59round/s, val_excess=0.0

w1 window rolling_1:  68%|▋| 135/200 [00:13<00:06, 10.59round/s, val_excess=0.0

w1 window rolling_1:  68%|▋| 136/200 [00:13<00:06, 10.59round/s, val_excess=0.0

w1 window rolling_1:  68%|▋| 137/200 [00:13<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  68%|▋| 137/200 [00:13<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  69%|▋| 138/200 [00:13<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  70%|▋| 140/200 [00:14<00:05, 10.67round/s, val_excess=0.0

w1 window rolling_1:  70%|▋| 141/200 [00:14<00:05, 10.73round/s, val_excess=0.0

w1 window rolling_1:  70%|▋| 141/200 [00:14<00:05, 10.73round/s, val_excess=0.0

w1 window rolling_1:  71%|▋| 142/200 [00:14<00:05, 10.73round/s, val_excess=0.0

w1 window rolling_1:  72%|▋| 143/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  72%|▋| 143/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  72%|▋| 144/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  72%|▋| 145/200 [00:14<00:05, 10.05round/s, val_excess=0.0

w1 window rolling_1:  72%|▋| 145/200 [00:14<00:05, 10.05round/s, val_excess=0.0

w1 window rolling_1:  73%|▋| 146/200 [00:14<00:05, 10.05round/s, val_excess=0.0

w1 window rolling_1:  74%|▋| 147/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  74%|▋| 147/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  74%|▋| 148/200 [00:14<00:05, 10.23round/s, val_excess=0.0

w1 window rolling_1:  74%|▋| 149/200 [00:14<00:04, 10.27round/s, val_excess=0.0

w1 window rolling_1:  74%|▋| 149/200 [00:14<00:04, 10.27round/s, val_excess=0.0

w1 window rolling_1:  75%|▊| 150/200 [00:15<00:04, 10.27round/s, val_excess=0.0

w1 window rolling_1:  76%|▊| 151/200 [00:15<00:04, 10.43round/s, val_excess=0.0

w1 window rolling_1:  76%|▊| 151/200 [00:15<00:04, 10.43round/s, val_excess=0.0

w1 window rolling_1:  76%|▊| 152/200 [00:15<00:04, 10.43round/s, val_excess=0.0

w1 window rolling_1:  76%|▊| 153/200 [00:15<00:04, 10.58round/s, val_excess=0.0

w1 window rolling_1:  76%|▊| 153/200 [00:15<00:04, 10.58round/s, val_excess=0.0

w1 window rolling_1:  77%|▊| 154/200 [00:15<00:04, 10.58round/s, val_excess=0.0

w1 window rolling_1:  78%|▊| 155/200 [00:15<00:04, 10.65round/s, val_excess=0.0

w1 window rolling_1:  78%|▊| 155/200 [00:15<00:04, 10.65round/s, val_excess=0.0

w1 window rolling_1:  78%|▊| 156/200 [00:15<00:04, 10.65round/s, val_excess=0.0

w1 window rolling_1:  78%|▊| 157/200 [00:15<00:04, 10.64round/s, val_excess=0.0

w1 window rolling_1:  78%|▊| 157/200 [00:15<00:04, 10.64round/s, val_excess=0.0

w1 window rolling_1:  79%|▊| 158/200 [00:15<00:03, 10.64round/s, val_excess=0.0

w1 window rolling_1:  80%|▊| 159/200 [00:15<00:03, 10.45round/s, val_excess=0.0

w1 window rolling_1:  80%|▊| 159/200 [00:15<00:03, 10.45round/s, val_excess=0.0

w1 window rolling_1:  80%|▊| 160/200 [00:16<00:03, 10.45round/s, val_excess=0.0

w1 window rolling_1:  80%|▊| 161/200 [00:16<00:03,  9.99round/s, val_excess=0.0

w1 window rolling_1:  80%|▊| 161/200 [00:16<00:03,  9.99round/s, val_excess=0.0

w1 window rolling_1:  81%|▊| 162/200 [00:16<00:03,  9.99round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 163/200 [00:16<00:03,  9.88round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 163/200 [00:16<00:03,  9.88round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 164/200 [00:16<00:03,  9.77round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 164/200 [00:16<00:03,  9.77round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 165/200 [00:16<00:03,  9.67round/s, val_excess=0.0

w1 window rolling_1:  82%|▊| 165/200 [00:16<00:03,  9.67round/s, val_excess=0.0

w1 window rolling_1:  83%|▊| 166/200 [00:16<00:03,  9.64round/s, val_excess=0.0

w1 window rolling_1:  83%|▊| 166/200 [00:16<00:03,  9.64round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 167/200 [00:16<00:03,  9.63round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 167/200 [00:16<00:03,  9.63round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 168/200 [00:16<00:03,  9.62round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 168/200 [00:16<00:03,  9.62round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 169/200 [00:16<00:03,  9.14round/s, val_excess=0.0

w1 window rolling_1:  84%|▊| 169/200 [00:16<00:03,  9.14round/s, val_excess=0.0

w1 window rolling_1:  85%|▊| 170/200 [00:17<00:03,  9.23round/s, val_excess=0.0

w1 window rolling_1:  85%|▊| 170/200 [00:17<00:03,  9.23round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 171/200 [00:17<00:03,  9.24round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 171/200 [00:17<00:03,  9.24round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 172/200 [00:17<00:03,  9.21round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 172/200 [00:17<00:03,  9.21round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 173/200 [00:17<00:02,  9.28round/s, val_excess=0.0

w1 window rolling_1:  86%|▊| 173/200 [00:17<00:02,  9.28round/s, val_excess=0.0

w1 window rolling_1:  87%|▊| 174/200 [00:17<00:02,  9.29round/s, val_excess=0.0

w1 window rolling_1:  87%|▊| 174/200 [00:17<00:02,  9.29round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 175/200 [00:17<00:02,  9.41round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 175/200 [00:17<00:02,  9.41round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 176/200 [00:17<00:02,  9.40round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 176/200 [00:17<00:02,  9.40round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 177/200 [00:17<00:02,  9.51round/s, val_excess=0.0

w1 window rolling_1:  88%|▉| 177/200 [00:17<00:02,  9.51round/s, val_excess=0.0

w1 window rolling_1:  89%|▉| 178/200 [00:17<00:02,  8.77round/s, val_excess=0.0

w1 window rolling_1:  89%|▉| 178/200 [00:17<00:02,  8.77round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 179/200 [00:18<00:02,  7.70round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 179/200 [00:18<00:02,  7.70round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 180/200 [00:18<00:02,  7.33round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 180/200 [00:18<00:02,  7.33round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 181/200 [00:18<00:02,  7.08round/s, val_excess=0.0

w1 window rolling_1:  90%|▉| 181/200 [00:18<00:02,  7.08round/s, val_excess=0.0

w1 window rolling_1:  91%|▉| 182/200 [00:18<00:02,  6.92round/s, val_excess=0.0

w1 window rolling_1:  91%|▉| 182/200 [00:18<00:02,  6.92round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 183/200 [00:18<00:02,  6.83round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 183/200 [00:18<00:02,  6.83round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 184/200 [00:18<00:02,  6.85round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 184/200 [00:18<00:02,  6.85round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 185/200 [00:19<00:02,  7.33round/s, val_excess=0.0

w1 window rolling_1:  92%|▉| 185/200 [00:19<00:02,  7.33round/s, val_excess=0.0

w1 window rolling_1:  93%|▉| 186/200 [00:19<00:01,  7.57round/s, val_excess=0.0

w1 window rolling_1:  93%|▉| 186/200 [00:19<00:01,  7.57round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 187/200 [00:19<00:01,  7.97round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 187/200 [00:19<00:01,  7.97round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 188/200 [00:19<00:01,  8.35round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 188/200 [00:19<00:01,  8.35round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 189/200 [00:19<00:01,  8.61round/s, val_excess=0.0

w1 window rolling_1:  94%|▉| 189/200 [00:19<00:01,  8.61round/s, val_excess=0.0

w1 window rolling_1:  95%|▉| 190/200 [00:19<00:01,  8.78round/s, val_excess=0.0

w1 window rolling_1:  95%|▉| 190/200 [00:19<00:01,  8.78round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 191/200 [00:19<00:01,  8.93round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 191/200 [00:19<00:01,  8.93round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 192/200 [00:19<00:00,  9.00round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 192/200 [00:19<00:00,  9.00round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 193/200 [00:19<00:00,  9.16round/s, val_excess=0.0

w1 window rolling_1:  96%|▉| 193/200 [00:19<00:00,  9.16round/s, val_excess=0.0

w1 window rolling_1:  97%|▉| 194/200 [00:20<00:00,  8.66round/s, val_excess=0.0

w1 window rolling_1:  97%|▉| 194/200 [00:20<00:00,  8.66round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 195/200 [00:20<00:00,  8.17round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 195/200 [00:20<00:00,  8.17round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 196/200 [00:20<00:00,  8.55round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 196/200 [00:20<00:00,  8.55round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 197/200 [00:20<00:00,  8.79round/s, val_excess=0.0

w1 window rolling_1:  98%|▉| 197/200 [00:20<00:00,  8.79round/s, val_excess=0.0

w1 window rolling_1:  99%|▉| 198/200 [00:20<00:00,  8.96round/s, val_excess=0.0

w1 window rolling_1:  99%|▉| 198/200 [00:20<00:00,  8.96round/s, val_excess=0.0

w1 window rolling_1: 100%|▉| 199/200 [00:20<00:00,  9.14round/s, val_excess=0.0

w1 window rolling_1: 100%|▉| 199/200 [00:20<00:00,  9.14round/s, val_excess=0.0

w1 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.07round/s, val_excess=0.0

w1 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.07round/s, val_excess=0.0

w1 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.67round/s, val_excess=0.0

2026-07-06 17:23:05 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=1 feature_type=window fold=rolling_2

2026-07-06 17:23:24 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=1 feature_type=window fold=rolling_2 features=69

w1 window rolling_2:   0%|                          | 0/200 [00:00<?, ?round/s]

w1 window rolling_2:   0%|                  | 1/200 [00:00<00:21,  9.16round/s]

w1 window rolling_2:   0%| | 1/200 [00:00<00:21,  9.16round/s, val_excess=-0.00

w1 window rolling_2:   1%| | 2/200 [00:00<00:21,  9.16round/s, val_excess=0.012

w1 window rolling_2:   2%| | 3/200 [00:00<00:18, 10.41round/s, val_excess=0.012

w1 window rolling_2:   2%| | 3/200 [00:00<00:18, 10.41round/s, val_excess=0.023

w1 window rolling_2:   2%| | 4/200 [00:00<00:18, 10.41round/s, val_excess=0.023

w1 window rolling_2:   2%| | 5/200 [00:00<00:18, 10.35round/s, val_excess=0.023

w1 window rolling_2:   2%| | 5/200 [00:00<00:18, 10.35round/s, val_excess=0.009

w1 window rolling_2:   3%| | 6/200 [00:00<00:18, 10.35round/s, val_excess=0.015

w1 window rolling_2:   4%| | 7/200 [00:00<00:19, 10.07round/s, val_excess=0.015

w1 window rolling_2:   4%| | 7/200 [00:00<00:19, 10.07round/s, val_excess=0.021

w1 window rolling_2:   4%| | 8/200 [00:00<00:19, 10.07round/s, val_excess=0.021

w1 window rolling_2:   4%| | 9/200 [00:00<00:19,  9.86round/s, val_excess=0.021

w1 window rolling_2:   4%| | 9/200 [00:00<00:19,  9.86round/s, val_excess=0.019

w1 window rolling_2:   5%| | 10/200 [00:01<00:19,  9.65round/s, val_excess=0.01

w1 window rolling_2:   5%| | 10/200 [00:01<00:19,  9.65round/s, val_excess=0.01

w1 window rolling_2:   6%| | 11/200 [00:01<00:19,  9.52round/s, val_excess=0.01

w1 window rolling_2:   6%| | 11/200 [00:01<00:19,  9.52round/s, val_excess=0.01

w1 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w1 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.51round/s, val_excess=0.02

w1 window rolling_2:   6%| | 13/200 [00:01<00:19,  9.45round/s, val_excess=0.02

w1 window rolling_2:   6%| | 13/200 [00:01<00:19,  9.45round/s, val_excess=0.01

w1 window rolling_2:   7%| | 14/200 [00:01<00:20,  9.23round/s, val_excess=0.01

w1 window rolling_2:   7%| | 14/200 [00:01<00:20,  9.23round/s, val_excess=0.02

w1 window rolling_2:   8%| | 15/200 [00:01<00:20,  9.13round/s, val_excess=0.02

w1 window rolling_2:   8%| | 15/200 [00:01<00:20,  9.13round/s, val_excess=0.03

w1 window rolling_2:   8%| | 16/200 [00:01<00:20,  9.14round/s, val_excess=0.03

w1 window rolling_2:   8%| | 16/200 [00:01<00:20,  9.14round/s, val_excess=0.03

w1 window rolling_2:   8%| | 17/200 [00:01<00:20,  9.04round/s, val_excess=0.03

w1 window rolling_2:   8%| | 17/200 [00:01<00:20,  9.04round/s, val_excess=0.02

w1 window rolling_2:   9%| | 18/200 [00:01<00:21,  8.61round/s, val_excess=0.02

w1 window rolling_2:   9%| | 18/200 [00:01<00:21,  8.61round/s, val_excess=0.03

w1 window rolling_2:  10%| | 19/200 [00:02<00:20,  8.69round/s, val_excess=0.03

w1 window rolling_2:  10%| | 19/200 [00:02<00:20,  8.69round/s, val_excess=0.03

w1 window rolling_2:  10%| | 20/200 [00:02<00:20,  8.80round/s, val_excess=0.03

w1 window rolling_2:  10%| | 20/200 [00:02<00:20,  8.80round/s, val_excess=0.03

w1 window rolling_2:  10%| | 21/200 [00:02<00:20,  8.64round/s, val_excess=0.03

w1 window rolling_2:  10%| | 21/200 [00:02<00:20,  8.64round/s, val_excess=0.02

w1 window rolling_2:  11%| | 22/200 [00:02<00:20,  8.60round/s, val_excess=0.02

w1 window rolling_2:  11%| | 22/200 [00:02<00:20,  8.60round/s, val_excess=0.02

w1 window rolling_2:  12%| | 23/200 [00:02<00:20,  8.84round/s, val_excess=0.02

w1 window rolling_2:  12%| | 23/200 [00:02<00:20,  8.84round/s, val_excess=0.03

w1 window rolling_2:  12%| | 24/200 [00:02<00:19,  8.90round/s, val_excess=0.03

w1 window rolling_2:  12%| | 24/200 [00:02<00:19,  8.90round/s, val_excess=0.02

w1 window rolling_2:  12%|▏| 25/200 [00:02<00:19,  8.93round/s, val_excess=0.02

w1 window rolling_2:  12%|▏| 25/200 [00:02<00:19,  8.93round/s, val_excess=0.02

w1 window rolling_2:  13%|▏| 26/200 [00:02<00:19,  9.01round/s, val_excess=0.02

w1 window rolling_2:  13%|▏| 26/200 [00:02<00:19,  9.01round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 27/200 [00:02<00:19,  9.01round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 27/200 [00:02<00:19,  9.01round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 28/200 [00:03<00:19,  8.99round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 28/200 [00:03<00:19,  8.99round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 29/200 [00:03<00:19,  8.87round/s, val_excess=0.02

w1 window rolling_2:  14%|▏| 29/200 [00:03<00:19,  8.87round/s, val_excess=0.02

w1 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.00round/s, val_excess=0.02

w1 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.00round/s, val_excess=0.02

w1 window rolling_2:  16%|▏| 31/200 [00:03<00:18,  8.95round/s, val_excess=0.02

w1 window rolling_2:  16%|▏| 31/200 [00:03<00:18,  8.95round/s, val_excess=0.02

w1 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.07round/s, val_excess=0.02

w1 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.07round/s, val_excess=0.03

w1 window rolling_2:  16%|▏| 33/200 [00:03<00:18,  9.07round/s, val_excess=0.03

w1 window rolling_2:  16%|▏| 33/200 [00:03<00:18,  9.07round/s, val_excess=0.02

w1 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  9.14round/s, val_excess=0.02

w1 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  9.14round/s, val_excess=0.03

w1 window rolling_2:  18%|▏| 35/200 [00:03<00:18,  9.09round/s, val_excess=0.03

w1 window rolling_2:  18%|▏| 35/200 [00:03<00:18,  9.09round/s, val_excess=0.02

w1 window rolling_2:  18%|▏| 36/200 [00:03<00:17,  9.13round/s, val_excess=0.02

w1 window rolling_2:  18%|▏| 36/200 [00:03<00:17,  9.13round/s, val_excess=0.02

w1 window rolling_2:  18%|▏| 37/200 [00:04<00:18,  8.73round/s, val_excess=0.02

w1 window rolling_2:  18%|▏| 37/200 [00:04<00:18,  8.73round/s, val_excess=0.02

w1 window rolling_2:  19%|▏| 38/200 [00:04<00:18,  8.71round/s, val_excess=0.02

w1 window rolling_2:  19%|▏| 38/200 [00:04<00:18,  8.71round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 39/200 [00:04<00:18,  8.77round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 39/200 [00:04<00:18,  8.77round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 40/200 [00:04<00:18,  8.86round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 40/200 [00:04<00:18,  8.86round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 41/200 [00:04<00:17,  8.98round/s, val_excess=0.02

w1 window rolling_2:  20%|▏| 41/200 [00:04<00:17,  8.98round/s, val_excess=0.02

w1 window rolling_2:  21%|▏| 42/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w1 window rolling_2:  21%|▏| 42/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 43/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 43/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 44/200 [00:04<00:17,  8.94round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 44/200 [00:04<00:17,  8.94round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 45/200 [00:04<00:17,  8.70round/s, val_excess=0.02

w1 window rolling_2:  22%|▏| 45/200 [00:04<00:17,  8.70round/s, val_excess=0.02

w1 window rolling_2:  23%|▏| 46/200 [00:05<00:17,  8.74round/s, val_excess=0.02

w1 window rolling_2:  23%|▏| 46/200 [00:05<00:17,  8.74round/s, val_excess=0.02

w1 window rolling_2:  24%|▏| 47/200 [00:05<00:17,  8.81round/s, val_excess=0.02

w1 window rolling_2:  24%|▏| 47/200 [00:05<00:17,  8.81round/s, val_excess=0.03

w1 window rolling_2:  24%|▏| 48/200 [00:05<00:17,  8.83round/s, val_excess=0.03

w1 window rolling_2:  24%|▏| 48/200 [00:05<00:17,  8.83round/s, val_excess=0.03

w1 window rolling_2:  24%|▏| 49/200 [00:05<00:17,  8.41round/s, val_excess=0.03

w1 window rolling_2:  24%|▏| 49/200 [00:05<00:17,  8.41round/s, val_excess=0.03

w1 window rolling_2:  25%|▎| 50/200 [00:05<00:18,  8.30round/s, val_excess=0.03

w1 window rolling_2:  25%|▎| 50/200 [00:05<00:18,  8.30round/s, val_excess=0.03

w1 window rolling_2:  26%|▎| 51/200 [00:05<00:17,  8.49round/s, val_excess=0.03

w1 window rolling_2:  26%|▎| 51/200 [00:05<00:17,  8.49round/s, val_excess=0.03

w1 window rolling_2:  26%|▎| 52/200 [00:05<00:17,  8.66round/s, val_excess=0.03

w1 window rolling_2:  26%|▎| 52/200 [00:05<00:17,  8.66round/s, val_excess=0.02

w1 window rolling_2:  26%|▎| 53/200 [00:05<00:16,  8.83round/s, val_excess=0.02

w1 window rolling_2:  26%|▎| 53/200 [00:05<00:16,  8.83round/s, val_excess=0.03

w1 window rolling_2:  27%|▎| 54/200 [00:05<00:16,  8.84round/s, val_excess=0.03

w1 window rolling_2:  27%|▎| 54/200 [00:05<00:16,  8.84round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 55/200 [00:06<00:16,  8.90round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 55/200 [00:06<00:16,  8.90round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 56/200 [00:06<00:16,  8.97round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 56/200 [00:06<00:16,  8.97round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 57/200 [00:06<00:15,  9.02round/s, val_excess=0.03

w1 window rolling_2:  28%|▎| 57/200 [00:06<00:15,  9.02round/s, val_excess=0.03

w1 window rolling_2:  29%|▎| 58/200 [00:06<00:15,  9.03round/s, val_excess=0.03

w1 window rolling_2:  29%|▎| 58/200 [00:06<00:15,  9.03round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 59/200 [00:06<00:15,  8.99round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 59/200 [00:06<00:15,  8.99round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 60/200 [00:06<00:15,  9.00round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 60/200 [00:06<00:15,  9.00round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 61/200 [00:06<00:15,  8.80round/s, val_excess=0.03

w1 window rolling_2:  30%|▎| 61/200 [00:06<00:15,  8.80round/s, val_excess=0.03

w1 window rolling_2:  31%|▎| 62/200 [00:06<00:15,  8.88round/s, val_excess=0.03

w1 window rolling_2:  31%|▎| 62/200 [00:06<00:15,  8.88round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 63/200 [00:06<00:15,  8.94round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 63/200 [00:06<00:15,  8.94round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 64/200 [00:07<00:15,  8.90round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 64/200 [00:07<00:15,  8.90round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 65/200 [00:07<00:15,  8.55round/s, val_excess=0.03

w1 window rolling_2:  32%|▎| 65/200 [00:07<00:15,  8.55round/s, val_excess=0.03

w1 window rolling_2:  33%|▎| 66/200 [00:07<00:15,  8.53round/s, val_excess=0.03

w1 window rolling_2:  33%|▎| 66/200 [00:07<00:15,  8.53round/s, val_excess=0.03

w1 window rolling_2:  34%|▎| 67/200 [00:07<00:15,  8.71round/s, val_excess=0.03

w1 window rolling_2:  34%|▎| 67/200 [00:07<00:15,  8.71round/s, val_excess=0.02

w1 window rolling_2:  34%|▎| 68/200 [00:07<00:15,  8.74round/s, val_excess=0.02

w1 window rolling_2:  34%|▎| 68/200 [00:07<00:15,  8.74round/s, val_excess=0.02

w1 window rolling_2:  34%|▎| 69/200 [00:07<00:14,  8.84round/s, val_excess=0.02

w1 window rolling_2:  34%|▎| 69/200 [00:07<00:14,  8.84round/s, val_excess=0.02

w1 window rolling_2:  35%|▎| 70/200 [00:07<00:14,  8.90round/s, val_excess=0.02

w1 window rolling_2:  35%|▎| 70/200 [00:07<00:14,  8.90round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 71/200 [00:07<00:14,  9.02round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 71/200 [00:07<00:14,  9.02round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 72/200 [00:08<00:15,  8.25round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 72/200 [00:08<00:15,  8.25round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 73/200 [00:08<00:15,  8.08round/s, val_excess=0.02

w1 window rolling_2:  36%|▎| 73/200 [00:08<00:15,  8.08round/s, val_excess=0.02

w1 window rolling_2:  37%|▎| 74/200 [00:08<00:15,  8.02round/s, val_excess=0.02

w1 window rolling_2:  37%|▎| 74/200 [00:08<00:15,  8.02round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 75/200 [00:08<00:15,  7.93round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 75/200 [00:08<00:15,  7.93round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 76/200 [00:08<00:15,  7.84round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 76/200 [00:08<00:15,  7.84round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 77/200 [00:08<00:17,  6.98round/s, val_excess=0.02

w1 window rolling_2:  38%|▍| 77/200 [00:08<00:17,  6.98round/s, val_excess=0.02

w1 window rolling_2:  39%|▍| 78/200 [00:08<00:17,  6.87round/s, val_excess=0.02

w1 window rolling_2:  39%|▍| 78/200 [00:08<00:17,  6.87round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 79/200 [00:09<00:17,  6.78round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 79/200 [00:09<00:17,  6.78round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 80/200 [00:09<00:18,  6.57round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 80/200 [00:09<00:18,  6.57round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 81/200 [00:09<00:17,  6.69round/s, val_excess=0.02

w1 window rolling_2:  40%|▍| 81/200 [00:09<00:17,  6.69round/s, val_excess=0.02

w1 window rolling_2:  41%|▍| 82/200 [00:09<00:17,  6.71round/s, val_excess=0.02

w1 window rolling_2:  41%|▍| 82/200 [00:09<00:17,  6.71round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 83/200 [00:09<00:16,  7.31round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 83/200 [00:09<00:16,  7.31round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 84/200 [00:09<00:15,  7.69round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 84/200 [00:09<00:15,  7.69round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 85/200 [00:09<00:14,  8.05round/s, val_excess=0.02

w1 window rolling_2:  42%|▍| 85/200 [00:09<00:14,  8.05round/s, val_excess=0.02

w1 window rolling_2:  43%|▍| 86/200 [00:09<00:13,  8.30round/s, val_excess=0.02

w1 window rolling_2:  43%|▍| 86/200 [00:09<00:13,  8.30round/s, val_excess=0.03

w1 window rolling_2:  44%|▍| 87/200 [00:10<00:13,  8.44round/s, val_excess=0.03

w1 window rolling_2:  44%|▍| 87/200 [00:10<00:13,  8.44round/s, val_excess=0.02

w1 window rolling_2:  44%|▍| 88/200 [00:10<00:13,  8.60round/s, val_excess=0.02

w1 window rolling_2:  44%|▍| 88/200 [00:10<00:13,  8.60round/s, val_excess=0.02

w1 window rolling_2:  44%|▍| 89/200 [00:10<00:13,  8.01round/s, val_excess=0.02

w1 window rolling_2:  44%|▍| 89/200 [00:10<00:13,  8.01round/s, val_excess=0.02

w1 window rolling_2:  45%|▍| 90/200 [00:10<00:13,  8.26round/s, val_excess=0.02

w1 window rolling_2:  45%|▍| 90/200 [00:10<00:13,  8.26round/s, val_excess=0.02

w1 window rolling_2:  46%|▍| 91/200 [00:10<00:12,  8.39round/s, val_excess=0.02

w1 window rolling_2:  46%|▍| 91/200 [00:10<00:12,  8.39round/s, val_excess=0.02

w1 window rolling_2:  46%|▍| 92/200 [00:10<00:13,  8.28round/s, val_excess=0.02

w1 window rolling_2:  46%|▍| 92/200 [00:10<00:13,  8.28round/s, val_excess=0.01

w1 window rolling_2:  46%|▍| 93/200 [00:10<00:12,  8.40round/s, val_excess=0.01

w1 window rolling_2:  46%|▍| 93/200 [00:10<00:12,  8.40round/s, val_excess=0.02

w1 window rolling_2:  47%|▍| 94/200 [00:10<00:12,  8.66round/s, val_excess=0.02

w1 window rolling_2:  47%|▍| 94/200 [00:10<00:12,  8.66round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 95/200 [00:10<00:12,  8.68round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 95/200 [00:10<00:12,  8.68round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 96/200 [00:11<00:12,  8.53round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 96/200 [00:11<00:12,  8.53round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 97/200 [00:11<00:11,  8.59round/s, val_excess=0.02

w1 window rolling_2:  48%|▍| 97/200 [00:11<00:11,  8.59round/s, val_excess=0.02

w1 window rolling_2:  49%|▍| 98/200 [00:11<00:11,  8.65round/s, val_excess=0.02

w1 window rolling_2:  49%|▍| 98/200 [00:11<00:11,  8.65round/s, val_excess=0.02

w1 window rolling_2:  50%|▍| 99/200 [00:11<00:11,  8.49round/s, val_excess=0.02

w1 window rolling_2:  50%|▍| 99/200 [00:11<00:11,  8.49round/s, val_excess=0.02

w1 window rolling_2:  50%|▌| 100/200 [00:11<00:11,  8.57round/s, val_excess=0.0

w1 window rolling_2:  50%|▌| 100/200 [00:11<00:11,  8.57round/s, val_excess=0.0

w1 window rolling_2:  50%|▌| 101/200 [00:11<00:11,  8.62round/s, val_excess=0.0

w1 window rolling_2:  50%|▌| 101/200 [00:11<00:11,  8.62round/s, val_excess=0.0

w1 window rolling_2:  51%|▌| 102/200 [00:11<00:11,  8.67round/s, val_excess=0.0

w1 window rolling_2:  51%|▌| 102/200 [00:11<00:11,  8.67round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 103/200 [00:11<00:11,  8.52round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 103/200 [00:11<00:11,  8.52round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 104/200 [00:12<00:12,  7.76round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 104/200 [00:12<00:12,  7.76round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 105/200 [00:12<00:12,  7.31round/s, val_excess=0.0

w1 window rolling_2:  52%|▌| 105/200 [00:12<00:12,  7.31round/s, val_excess=0.0

w1 window rolling_2:  53%|▌| 106/200 [00:12<00:12,  7.28round/s, val_excess=0.0

w1 window rolling_2:  53%|▌| 106/200 [00:12<00:12,  7.28round/s, val_excess=0.0

w1 window rolling_2:  54%|▌| 107/200 [00:12<00:12,  7.41round/s, val_excess=0.0

w1 window rolling_2:  54%|▌| 107/200 [00:12<00:12,  7.41round/s, val_excess=0.0

w1 window rolling_2:  54%|▌| 108/200 [00:12<00:12,  7.37round/s, val_excess=0.0

w1 window rolling_2:  54%|▌| 108/200 [00:12<00:12,  7.37round/s, val_excess=0.0

w1 window rolling_2:  55%|▌| 109/200 [00:12<00:12,  7.45round/s, val_excess=0.0

w1 window rolling_2:  55%|▌| 109/200 [00:12<00:12,  7.45round/s, val_excess=0.0

w1 window rolling_2:  55%|▌| 110/200 [00:12<00:11,  7.59round/s, val_excess=0.0

w1 window rolling_2:  55%|▌| 110/200 [00:12<00:11,  7.59round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 111/200 [00:13<00:11,  7.64round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 111/200 [00:13<00:11,  7.64round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 112/200 [00:13<00:11,  7.60round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 112/200 [00:13<00:11,  7.60round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 113/200 [00:13<00:11,  7.63round/s, val_excess=0.0

w1 window rolling_2:  56%|▌| 113/200 [00:13<00:11,  7.63round/s, val_excess=0.0

w1 window rolling_2:  57%|▌| 114/200 [00:13<00:11,  7.68round/s, val_excess=0.0

w1 window rolling_2:  57%|▌| 114/200 [00:13<00:11,  7.68round/s, val_excess=0.0

w1 window rolling_2:  57%|▌| 115/200 [00:13<00:10,  7.74round/s, val_excess=0.0

w1 window rolling_2:  57%|▌| 115/200 [00:13<00:10,  7.74round/s, val_excess=0.0

w1 window rolling_2:  58%|▌| 116/200 [00:13<00:10,  7.73round/s, val_excess=0.0

w1 window rolling_2:  58%|▌| 116/200 [00:13<00:10,  7.73round/s, val_excess=0.0

w1 window rolling_2:  58%|▌| 117/200 [00:13<00:10,  7.71round/s, val_excess=0.0

w1 window rolling_2:  58%|▌| 117/200 [00:13<00:10,  7.71round/s, val_excess=0.0

w1 window rolling_2:  59%|▌| 118/200 [00:13<00:10,  7.71round/s, val_excess=0.0

w1 window rolling_2:  59%|▌| 118/200 [00:13<00:10,  7.71round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 119/200 [00:14<00:10,  7.68round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 119/200 [00:14<00:10,  7.68round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 120/200 [00:14<00:10,  7.80round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 120/200 [00:14<00:10,  7.80round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 121/200 [00:14<00:10,  7.81round/s, val_excess=0.0

w1 window rolling_2:  60%|▌| 121/200 [00:14<00:10,  7.81round/s, val_excess=0.0

w1 window rolling_2:  61%|▌| 122/200 [00:14<00:10,  7.76round/s, val_excess=0.0

w1 window rolling_2:  61%|▌| 122/200 [00:14<00:10,  7.76round/s, val_excess=0.0

w1 window rolling_2:  62%|▌| 123/200 [00:14<00:09,  7.76round/s, val_excess=0.0

w1 window rolling_2:  62%|▌| 123/200 [00:14<00:09,  7.76round/s, val_excess=0.0

w1 window rolling_2:  62%|▌| 124/200 [00:14<00:09,  7.77round/s, val_excess=0.0

w1 window rolling_2:  62%|▌| 124/200 [00:14<00:09,  7.77round/s, val_excess=0.0

w1 window rolling_2:  62%|▋| 125/200 [00:14<00:09,  7.76round/s, val_excess=0.0

w1 window rolling_2:  62%|▋| 125/200 [00:14<00:09,  7.76round/s, val_excess=0.0

w1 window rolling_2:  63%|▋| 126/200 [00:14<00:09,  7.75round/s, val_excess=0.0

w1 window rolling_2:  63%|▋| 126/200 [00:14<00:09,  7.75round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 127/200 [00:15<00:09,  7.77round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 127/200 [00:15<00:09,  7.77round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 128/200 [00:15<00:09,  7.81round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 128/200 [00:15<00:09,  7.81round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 129/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  64%|▋| 129/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  65%|▋| 130/200 [00:15<00:08,  7.95round/s, val_excess=0.0

w1 window rolling_2:  65%|▋| 130/200 [00:15<00:08,  7.95round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 131/200 [00:15<00:08,  7.89round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 131/200 [00:15<00:08,  7.89round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 132/200 [00:15<00:08,  7.91round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 132/200 [00:15<00:08,  7.91round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 133/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  66%|▋| 133/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  67%|▋| 134/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  67%|▋| 134/200 [00:15<00:08,  7.92round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 135/200 [00:16<00:08,  7.88round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 135/200 [00:16<00:08,  7.88round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 136/200 [00:16<00:08,  7.85round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 136/200 [00:16<00:08,  7.85round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 137/200 [00:16<00:08,  7.79round/s, val_excess=0.0

w1 window rolling_2:  68%|▋| 137/200 [00:16<00:08,  7.79round/s, val_excess=0.0

w1 window rolling_2:  69%|▋| 138/200 [00:16<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  69%|▋| 138/200 [00:16<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 139/200 [00:16<00:07,  7.75round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 139/200 [00:16<00:07,  7.75round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 140/200 [00:16<00:07,  7.76round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 140/200 [00:16<00:07,  7.76round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 141/200 [00:16<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  70%|▋| 141/200 [00:16<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  71%|▋| 142/200 [00:17<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  71%|▋| 142/200 [00:17<00:07,  7.77round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 143/200 [00:17<00:07,  7.74round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 143/200 [00:17<00:07,  7.74round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 144/200 [00:17<00:07,  7.73round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 144/200 [00:17<00:07,  7.73round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 145/200 [00:17<00:07,  7.74round/s, val_excess=0.0

w1 window rolling_2:  72%|▋| 145/200 [00:17<00:07,  7.74round/s, val_excess=0.0

w1 window rolling_2:  73%|▋| 146/200 [00:17<00:06,  7.78round/s, val_excess=0.0

w1 window rolling_2:  73%|▋| 146/200 [00:17<00:06,  7.78round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 147/200 [00:17<00:06,  7.76round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 147/200 [00:17<00:06,  7.76round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 148/200 [00:17<00:06,  7.82round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 148/200 [00:17<00:06,  7.82round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 149/200 [00:17<00:06,  7.92round/s, val_excess=0.0

w1 window rolling_2:  74%|▋| 149/200 [00:17<00:06,  7.92round/s, val_excess=0.0

w1 window rolling_2:  75%|▊| 150/200 [00:18<00:06,  7.93round/s, val_excess=0.0

w1 window rolling_2:  75%|▊| 150/200 [00:18<00:06,  7.93round/s, val_excess=-0.

w1 window rolling_2:  76%|▊| 151/200 [00:18<00:06,  7.88round/s, val_excess=-0.

w1 window rolling_2:  76%|▊| 151/200 [00:18<00:06,  7.88round/s, val_excess=0.0

w1 window rolling_2:  76%|▊| 152/200 [00:18<00:06,  7.86round/s, val_excess=0.0

w1 window rolling_2:  76%|▊| 152/200 [00:18<00:06,  7.86round/s, val_excess=-0.

w1 window rolling_2:  76%|▊| 153/200 [00:18<00:05,  7.87round/s, val_excess=-0.

w1 window rolling_2:  76%|▊| 153/200 [00:18<00:05,  7.87round/s, val_excess=0.0

w1 window rolling_2:  77%|▊| 154/200 [00:18<00:05,  7.86round/s, val_excess=0.0

w1 window rolling_2:  77%|▊| 154/200 [00:18<00:05,  7.86round/s, val_excess=0.0

w1 window rolling_2:  78%|▊| 155/200 [00:18<00:05,  7.92round/s, val_excess=0.0

w1 window rolling_2:  78%|▊| 155/200 [00:18<00:05,  7.92round/s, val_excess=-0.

w1 window rolling_2:  78%|▊| 156/200 [00:18<00:05,  8.26round/s, val_excess=-0.

w1 window rolling_2:  78%|▊| 156/200 [00:18<00:05,  8.26round/s, val_excess=-0.

w1 window rolling_2:  78%|▊| 157/200 [00:18<00:05,  8.47round/s, val_excess=-0.

w1 window rolling_2:  78%|▊| 157/200 [00:18<00:05,  8.47round/s, val_excess=-0.

w1 window rolling_2:  79%|▊| 158/200 [00:18<00:04,  8.69round/s, val_excess=-0.

w1 window rolling_2:  79%|▊| 158/200 [00:18<00:04,  8.69round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 159/200 [00:19<00:04,  8.76round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 159/200 [00:19<00:04,  8.76round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 160/200 [00:19<00:04,  8.89round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 160/200 [00:19<00:04,  8.89round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 161/200 [00:19<00:04,  8.60round/s, val_excess=-0.

w1 window rolling_2:  80%|▊| 161/200 [00:19<00:04,  8.60round/s, val_excess=0.0

w1 window rolling_2:  81%|▊| 162/200 [00:19<00:04,  8.32round/s, val_excess=0.0

w1 window rolling_2:  81%|▊| 162/200 [00:19<00:04,  8.32round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 163/200 [00:19<00:04,  8.18round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 163/200 [00:19<00:04,  8.18round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 164/200 [00:19<00:04,  8.09round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 164/200 [00:19<00:04,  8.09round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 165/200 [00:19<00:04,  7.92round/s, val_excess=0.0

w1 window rolling_2:  82%|▊| 165/200 [00:19<00:04,  7.92round/s, val_excess=0.0

w1 window rolling_2:  83%|▊| 166/200 [00:19<00:04,  7.89round/s, val_excess=0.0

w1 window rolling_2:  83%|▊| 166/200 [00:19<00:04,  7.89round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 167/200 [00:20<00:04,  7.84round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 167/200 [00:20<00:04,  7.84round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 168/200 [00:20<00:04,  7.78round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 168/200 [00:20<00:04,  7.78round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 169/200 [00:20<00:03,  7.82round/s, val_excess=0.0

w1 window rolling_2:  84%|▊| 169/200 [00:20<00:03,  7.82round/s, val_excess=0.0

w1 window rolling_2:  85%|▊| 170/200 [00:20<00:03,  7.89round/s, val_excess=0.0

w1 window rolling_2:  85%|▊| 170/200 [00:20<00:03,  7.89round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 171/200 [00:20<00:03,  7.82round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 171/200 [00:20<00:03,  7.82round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 172/200 [00:20<00:03,  7.81round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 172/200 [00:20<00:03,  7.81round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 173/200 [00:20<00:03,  7.83round/s, val_excess=0.0

w1 window rolling_2:  86%|▊| 173/200 [00:20<00:03,  7.83round/s, val_excess=0.0

w1 window rolling_2:  87%|▊| 174/200 [00:21<00:03,  7.88round/s, val_excess=0.0

w1 window rolling_2:  87%|▊| 174/200 [00:21<00:03,  7.88round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 175/200 [00:21<00:03,  7.89round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 175/200 [00:21<00:03,  7.89round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 176/200 [00:21<00:03,  7.98round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 176/200 [00:21<00:03,  7.98round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 177/200 [00:21<00:02,  8.03round/s, val_excess=0.0

w1 window rolling_2:  88%|▉| 177/200 [00:21<00:02,  8.03round/s, val_excess=0.0

w1 window rolling_2:  89%|▉| 178/200 [00:21<00:02,  8.04round/s, val_excess=0.0

w1 window rolling_2:  89%|▉| 178/200 [00:21<00:02,  8.04round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 179/200 [00:21<00:02,  8.07round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 179/200 [00:21<00:02,  8.07round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 180/200 [00:21<00:02,  7.99round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 180/200 [00:21<00:02,  7.99round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 181/200 [00:21<00:02,  8.01round/s, val_excess=0.0

w1 window rolling_2:  90%|▉| 181/200 [00:21<00:02,  8.01round/s, val_excess=0.0

w1 window rolling_2:  91%|▉| 182/200 [00:21<00:02,  8.34round/s, val_excess=0.0

w1 window rolling_2:  91%|▉| 182/200 [00:21<00:02,  8.34round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 183/200 [00:22<00:01,  8.56round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 183/200 [00:22<00:01,  8.56round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 184/200 [00:22<00:01,  8.74round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 184/200 [00:22<00:01,  8.74round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 185/200 [00:22<00:01,  8.87round/s, val_excess=0.0

w1 window rolling_2:  92%|▉| 185/200 [00:22<00:01,  8.87round/s, val_excess=0.0

w1 window rolling_2:  93%|▉| 186/200 [00:22<00:01,  8.90round/s, val_excess=0.0

w1 window rolling_2:  93%|▉| 186/200 [00:22<00:01,  8.90round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 187/200 [00:22<00:01,  9.03round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 187/200 [00:22<00:01,  9.03round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 188/200 [00:22<00:01,  8.79round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 188/200 [00:22<00:01,  8.79round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 189/200 [00:22<00:01,  8.69round/s, val_excess=0.0

w1 window rolling_2:  94%|▉| 189/200 [00:22<00:01,  8.69round/s, val_excess=0.0

w1 window rolling_2:  95%|▉| 190/200 [00:22<00:01,  8.42round/s, val_excess=0.0

w1 window rolling_2:  95%|▉| 190/200 [00:22<00:01,  8.42round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 191/200 [00:23<00:01,  8.50round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 191/200 [00:23<00:01,  8.50round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 192/200 [00:23<00:00,  8.65round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 192/200 [00:23<00:00,  8.65round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 193/200 [00:23<00:00,  8.41round/s, val_excess=0.0

w1 window rolling_2:  96%|▉| 193/200 [00:23<00:00,  8.41round/s, val_excess=0.0

w1 window rolling_2:  97%|▉| 194/200 [00:23<00:00,  8.63round/s, val_excess=0.0

w1 window rolling_2:  97%|▉| 194/200 [00:23<00:00,  8.63round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 195/200 [00:23<00:00,  8.75round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 195/200 [00:23<00:00,  8.75round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 196/200 [00:23<00:00,  8.86round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 196/200 [00:23<00:00,  8.86round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 197/200 [00:23<00:00,  8.92round/s, val_excess=0.0

w1 window rolling_2:  98%|▉| 197/200 [00:23<00:00,  8.92round/s, val_excess=0.0

w1 window rolling_2:  99%|▉| 198/200 [00:23<00:00,  9.00round/s, val_excess=0.0

w1 window rolling_2:  99%|▉| 198/200 [00:23<00:00,  9.00round/s, val_excess=0.0

w1 window rolling_2: 100%|▉| 199/200 [00:23<00:00,  9.03round/s, val_excess=0.0

w1 window rolling_2: 100%|▉| 199/200 [00:23<00:00,  9.03round/s, val_excess=0.0

w1 window rolling_2: 100%|█| 200/200 [00:24<00:00,  9.04round/s, val_excess=0.0

w1 window rolling_2: 100%|█| 200/200 [00:24<00:00,  9.04round/s, val_excess=0.0

w1 window rolling_2: 100%|█| 200/200 [00:24<00:00,  8.33round/s, val_excess=0.0

2026-07-06 17:23:49 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=1 feature_type=window fold=rolling_3

2026-07-06 17:24:09 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=1 feature_type=window fold=rolling_3 features=69

w1 window rolling_3:   0%|                          | 0/200 [00:00<?, ?round/s]

w1 window rolling_3:   0%|                  | 1/200 [00:00<00:22,  8.68round/s]

w1 window rolling_3:   0%| | 1/200 [00:00<00:22,  8.68round/s, val_excess=-0.01

w1 window rolling_3:   1%| | 2/200 [00:00<00:22,  8.68round/s, val_excess=0.017

w1 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.40round/s, val_excess=0.017

w1 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.40round/s, val_excess=-0.01

w1 window rolling_3:   2%| | 4/200 [00:00<00:18, 10.40round/s, val_excess=0.008

w1 window rolling_3:   2%| | 5/200 [00:00<00:18, 10.34round/s, val_excess=0.008

w1 window rolling_3:   2%| | 5/200 [00:00<00:18, 10.34round/s, val_excess=0.017

w1 window rolling_3:   3%| | 6/200 [00:00<00:18, 10.34round/s, val_excess=0.009

w1 window rolling_3:   4%| | 7/200 [00:00<00:19, 10.12round/s, val_excess=0.009

w1 window rolling_3:   4%| | 7/200 [00:00<00:19, 10.12round/s, val_excess=0.015

w1 window rolling_3:   4%| | 8/200 [00:00<00:18, 10.12round/s, val_excess=0.013

w1 window rolling_3:   4%| | 9/200 [00:00<00:19,  9.84round/s, val_excess=0.013

w1 window rolling_3:   4%| | 9/200 [00:00<00:19,  9.84round/s, val_excess=0.001

w1 window rolling_3:   5%| | 10/200 [00:01<00:19,  9.73round/s, val_excess=0.00

w1 window rolling_3:   5%| | 10/200 [00:01<00:19,  9.73round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 11/200 [00:01<00:19,  9.62round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 11/200 [00:01<00:19,  9.62round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 12/200 [00:01<00:19,  9.44round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 12/200 [00:01<00:19,  9.44round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 13/200 [00:01<00:19,  9.38round/s, val_excess=-0.0

w1 window rolling_3:   6%| | 13/200 [00:01<00:19,  9.38round/s, val_excess=0.00

w1 window rolling_3:   7%| | 14/200 [00:01<00:20,  9.28round/s, val_excess=0.00

w1 window rolling_3:   7%| | 14/200 [00:01<00:20,  9.28round/s, val_excess=-0.0

w1 window rolling_3:   8%| | 15/200 [00:01<00:19,  9.27round/s, val_excess=-0.0

w1 window rolling_3:   8%| | 15/200 [00:01<00:19,  9.27round/s, val_excess=-0.0

w1 window rolling_3:   8%| | 16/200 [00:01<00:20,  9.06round/s, val_excess=-0.0

w1 window rolling_3:   8%| | 16/200 [00:01<00:20,  9.06round/s, val_excess=0.00

w1 window rolling_3:   8%| | 17/200 [00:01<00:20,  9.03round/s, val_excess=0.00

w1 window rolling_3:   8%| | 17/200 [00:01<00:20,  9.03round/s, val_excess=0.00

w1 window rolling_3:   9%| | 18/200 [00:01<00:20,  9.00round/s, val_excess=0.00

w1 window rolling_3:   9%| | 18/200 [00:01<00:20,  9.00round/s, val_excess=0.01

w1 window rolling_3:  10%| | 19/200 [00:02<00:23,  7.80round/s, val_excess=0.01

w1 window rolling_3:  10%| | 19/200 [00:02<00:23,  7.80round/s, val_excess=-0.0

w1 window rolling_3:  10%| | 20/200 [00:02<00:22,  8.04round/s, val_excess=-0.0

w1 window rolling_3:  10%| | 20/200 [00:02<00:22,  8.04round/s, val_excess=0.00

w1 window rolling_3:  10%| | 21/200 [00:02<00:21,  8.30round/s, val_excess=0.00

w1 window rolling_3:  10%| | 21/200 [00:02<00:21,  8.30round/s, val_excess=0.00

w1 window rolling_3:  11%| | 22/200 [00:02<00:20,  8.56round/s, val_excess=0.00

w1 window rolling_3:  11%| | 22/200 [00:02<00:20,  8.56round/s, val_excess=0.01

w1 window rolling_3:  12%| | 23/200 [00:02<00:20,  8.72round/s, val_excess=0.01

w1 window rolling_3:  12%| | 23/200 [00:02<00:20,  8.72round/s, val_excess=0.01

w1 window rolling_3:  12%| | 24/200 [00:02<00:19,  8.81round/s, val_excess=0.01

w1 window rolling_3:  12%| | 24/200 [00:02<00:19,  8.81round/s, val_excess=0.00

w1 window rolling_3:  12%|▏| 25/200 [00:02<00:20,  8.71round/s, val_excess=0.00

w1 window rolling_3:  12%|▏| 25/200 [00:02<00:20,  8.71round/s, val_excess=0.00

w1 window rolling_3:  13%|▏| 26/200 [00:02<00:19,  8.78round/s, val_excess=0.00

w1 window rolling_3:  13%|▏| 26/200 [00:02<00:19,  8.78round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 27/200 [00:02<00:19,  8.81round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 27/200 [00:02<00:19,  8.81round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 28/200 [00:03<00:19,  8.81round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 28/200 [00:03<00:19,  8.81round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 29/200 [00:03<00:19,  8.83round/s, val_excess=0.00

w1 window rolling_3:  14%|▏| 29/200 [00:03<00:19,  8.83round/s, val_excess=0.00

w1 window rolling_3:  15%|▏| 30/200 [00:03<00:19,  8.84round/s, val_excess=0.00

w1 window rolling_3:  15%|▏| 30/200 [00:03<00:19,  8.84round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 31/200 [00:03<00:19,  8.88round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 31/200 [00:03<00:19,  8.88round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 32/200 [00:03<00:18,  8.89round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 32/200 [00:03<00:18,  8.89round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 33/200 [00:03<00:19,  8.72round/s, val_excess=0.00

w1 window rolling_3:  16%|▏| 33/200 [00:03<00:19,  8.72round/s, val_excess=0.00

w1 window rolling_3:  17%|▏| 34/200 [00:03<00:19,  8.55round/s, val_excess=0.00

w1 window rolling_3:  17%|▏| 34/200 [00:03<00:19,  8.55round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 35/200 [00:03<00:19,  8.61round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 35/200 [00:03<00:19,  8.61round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 36/200 [00:03<00:18,  8.71round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 36/200 [00:03<00:18,  8.71round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 37/200 [00:04<00:18,  8.79round/s, val_excess=0.00

w1 window rolling_3:  18%|▏| 37/200 [00:04<00:18,  8.79round/s, val_excess=0.00

w1 window rolling_3:  19%|▏| 38/200 [00:04<00:18,  8.88round/s, val_excess=0.00

w1 window rolling_3:  19%|▏| 38/200 [00:04<00:18,  8.88round/s, val_excess=0.00

w1 window rolling_3:  20%|▏| 39/200 [00:04<00:18,  8.81round/s, val_excess=0.00

w1 window rolling_3:  20%|▏| 39/200 [00:04<00:18,  8.81round/s, val_excess=0.01

w1 window rolling_3:  20%|▏| 40/200 [00:04<00:18,  8.79round/s, val_excess=0.01

w1 window rolling_3:  20%|▏| 40/200 [00:04<00:18,  8.79round/s, val_excess=0.01

w1 window rolling_3:  20%|▏| 41/200 [00:04<00:18,  8.77round/s, val_excess=0.01

w1 window rolling_3:  20%|▏| 41/200 [00:04<00:18,  8.77round/s, val_excess=0.01

w1 window rolling_3:  21%|▏| 42/200 [00:04<00:19,  8.24round/s, val_excess=0.01

w1 window rolling_3:  21%|▏| 42/200 [00:04<00:19,  8.24round/s, val_excess=0.01

w1 window rolling_3:  22%|▏| 43/200 [00:04<00:19,  8.09round/s, val_excess=0.01

w1 window rolling_3:  22%|▏| 43/200 [00:04<00:19,  8.09round/s, val_excess=0.01

w1 window rolling_3:  22%|▏| 44/200 [00:04<00:18,  8.33round/s, val_excess=0.01

w1 window rolling_3:  22%|▏| 44/200 [00:04<00:18,  8.33round/s, val_excess=0.00

w1 window rolling_3:  22%|▏| 45/200 [00:05<00:18,  8.49round/s, val_excess=0.00

w1 window rolling_3:  22%|▏| 45/200 [00:05<00:18,  8.49round/s, val_excess=0.01

w1 window rolling_3:  23%|▏| 46/200 [00:05<00:17,  8.63round/s, val_excess=0.01

w1 window rolling_3:  23%|▏| 46/200 [00:05<00:17,  8.63round/s, val_excess=0.00

w1 window rolling_3:  24%|▏| 47/200 [00:05<00:17,  8.71round/s, val_excess=0.00

w1 window rolling_3:  24%|▏| 47/200 [00:05<00:17,  8.71round/s, val_excess=0.00

w1 window rolling_3:  24%|▏| 48/200 [00:05<00:17,  8.82round/s, val_excess=0.00

w1 window rolling_3:  24%|▏| 48/200 [00:05<00:17,  8.82round/s, val_excess=0.01

w1 window rolling_3:  24%|▏| 49/200 [00:05<00:17,  8.84round/s, val_excess=0.01

w1 window rolling_3:  24%|▏| 49/200 [00:05<00:17,  8.84round/s, val_excess=0.01

w1 window rolling_3:  25%|▎| 50/200 [00:05<00:16,  8.84round/s, val_excess=0.01

w1 window rolling_3:  25%|▎| 50/200 [00:05<00:16,  8.84round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 51/200 [00:05<00:16,  8.77round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 51/200 [00:05<00:16,  8.77round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 52/200 [00:05<00:16,  8.83round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 52/200 [00:05<00:16,  8.83round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 53/200 [00:05<00:17,  8.56round/s, val_excess=0.01

w1 window rolling_3:  26%|▎| 53/200 [00:05<00:17,  8.56round/s, val_excess=0.00

w1 window rolling_3:  27%|▎| 54/200 [00:06<00:16,  8.62round/s, val_excess=0.00

w1 window rolling_3:  27%|▎| 54/200 [00:06<00:16,  8.62round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 55/200 [00:06<00:16,  8.72round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 55/200 [00:06<00:16,  8.72round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 56/200 [00:06<00:16,  8.76round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 56/200 [00:06<00:16,  8.76round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 57/200 [00:06<00:16,  8.82round/s, val_excess=0.00

w1 window rolling_3:  28%|▎| 57/200 [00:06<00:16,  8.82round/s, val_excess=0.00

w1 window rolling_3:  29%|▎| 58/200 [00:06<00:16,  8.86round/s, val_excess=0.00

w1 window rolling_3:  29%|▎| 58/200 [00:06<00:16,  8.86round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 59/200 [00:06<00:17,  7.94round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 59/200 [00:06<00:17,  7.94round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 60/200 [00:06<00:19,  7.29round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 60/200 [00:06<00:19,  7.29round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 61/200 [00:07<00:20,  6.94round/s, val_excess=0.01

w1 window rolling_3:  30%|▎| 61/200 [00:07<00:20,  6.94round/s, val_excess=0.01

w1 window rolling_3:  31%|▎| 62/200 [00:07<00:20,  6.81round/s, val_excess=0.01

w1 window rolling_3:  31%|▎| 62/200 [00:07<00:20,  6.81round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 63/200 [00:07<00:19,  7.05round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 63/200 [00:07<00:19,  7.05round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 64/200 [00:07<00:18,  7.20round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 64/200 [00:07<00:18,  7.20round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 65/200 [00:07<00:18,  7.35round/s, val_excess=0.01

w1 window rolling_3:  32%|▎| 65/200 [00:07<00:18,  7.35round/s, val_excess=0.00

w1 window rolling_3:  33%|▎| 66/200 [00:07<00:17,  7.46round/s, val_excess=0.00

w1 window rolling_3:  33%|▎| 66/200 [00:07<00:17,  7.46round/s, val_excess=0.00

w1 window rolling_3:  34%|▎| 67/200 [00:07<00:17,  7.66round/s, val_excess=0.00

w1 window rolling_3:  34%|▎| 67/200 [00:07<00:17,  7.66round/s, val_excess=0.00

w1 window rolling_3:  34%|▎| 68/200 [00:07<00:16,  8.05round/s, val_excess=0.00

w1 window rolling_3:  34%|▎| 68/200 [00:07<00:16,  8.05round/s, val_excess=0.01

w1 window rolling_3:  34%|▎| 69/200 [00:08<00:15,  8.30round/s, val_excess=0.01

w1 window rolling_3:  34%|▎| 69/200 [00:08<00:15,  8.30round/s, val_excess=0.01

w1 window rolling_3:  35%|▎| 70/200 [00:08<00:15,  8.56round/s, val_excess=0.01

w1 window rolling_3:  35%|▎| 70/200 [00:08<00:15,  8.56round/s, val_excess=0.01

w1 window rolling_3:  36%|▎| 71/200 [00:08<00:14,  8.68round/s, val_excess=0.01

w1 window rolling_3:  36%|▎| 71/200 [00:08<00:14,  8.68round/s, val_excess=0.01

w1 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  8.76round/s, val_excess=0.01

w1 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  8.76round/s, val_excess=0.00

w1 window rolling_3:  36%|▎| 73/200 [00:08<00:14,  8.84round/s, val_excess=0.00

w1 window rolling_3:  36%|▎| 73/200 [00:08<00:14,  8.84round/s, val_excess=0.00

w1 window rolling_3:  37%|▎| 74/200 [00:08<00:14,  8.81round/s, val_excess=0.00

w1 window rolling_3:  37%|▎| 74/200 [00:08<00:14,  8.81round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 75/200 [00:08<00:14,  8.69round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 75/200 [00:08<00:14,  8.69round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 76/200 [00:08<00:14,  8.61round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 76/200 [00:08<00:14,  8.61round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 77/200 [00:08<00:14,  8.53round/s, val_excess=0.00

w1 window rolling_3:  38%|▍| 77/200 [00:08<00:14,  8.53round/s, val_excess=0.00

w1 window rolling_3:  39%|▍| 78/200 [00:09<00:14,  8.26round/s, val_excess=0.00

w1 window rolling_3:  39%|▍| 78/200 [00:09<00:14,  8.26round/s, val_excess=0.01

w1 window rolling_3:  40%|▍| 79/200 [00:09<00:15,  8.03round/s, val_excess=0.01

w1 window rolling_3:  40%|▍| 79/200 [00:09<00:15,  8.03round/s, val_excess=0.01

w1 window rolling_3:  40%|▍| 80/200 [00:09<00:15,  7.91round/s, val_excess=0.01

w1 window rolling_3:  40%|▍| 80/200 [00:09<00:15,  7.91round/s, val_excess=0.00

w1 window rolling_3:  40%|▍| 81/200 [00:09<00:15,  7.91round/s, val_excess=0.00

w1 window rolling_3:  41%|▍| 82/200 [00:09<00:13,  8.80round/s, val_excess=0.00

w1 window rolling_3:  41%|▍| 82/200 [00:09<00:13,  8.80round/s, val_excess=0.01

w1 window rolling_3:  42%|▍| 83/200 [00:09<00:13,  8.80round/s, val_excess=0.02

w1 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.26round/s, val_excess=0.02

w1 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.26round/s, val_excess=0.01

w1 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.37round/s, val_excess=0.01

w1 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.37round/s, val_excess=0.02

w1 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.41round/s, val_excess=0.02

w1 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.41round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 87/200 [00:10<00:11,  9.47round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 87/200 [00:10<00:11,  9.47round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 88/200 [00:10<00:11,  9.54round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 88/200 [00:10<00:11,  9.54round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 89/200 [00:10<00:11,  9.58round/s, val_excess=0.00

w1 window rolling_3:  44%|▍| 89/200 [00:10<00:11,  9.58round/s, val_excess=0.00

w1 window rolling_3:  45%|▍| 90/200 [00:10<00:11,  9.61round/s, val_excess=0.00

w1 window rolling_3:  45%|▍| 90/200 [00:10<00:11,  9.61round/s, val_excess=0.00

w1 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.64round/s, val_excess=0.00

w1 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.64round/s, val_excess=0.00

w1 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.54round/s, val_excess=0.00

w1 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.54round/s, val_excess=0.01

w1 window rolling_3:  46%|▍| 93/200 [00:10<00:11,  9.64round/s, val_excess=0.01

w1 window rolling_3:  46%|▍| 93/200 [00:10<00:11,  9.64round/s, val_excess=0.01

w1 window rolling_3:  47%|▍| 94/200 [00:10<00:11,  9.62round/s, val_excess=0.01

w1 window rolling_3:  47%|▍| 94/200 [00:10<00:11,  9.62round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  9.54round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  9.54round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 96/200 [00:10<00:10,  9.59round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 96/200 [00:10<00:10,  9.59round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 97/200 [00:11<00:10,  9.65round/s, val_excess=0.01

w1 window rolling_3:  48%|▍| 97/200 [00:11<00:10,  9.65round/s, val_excess=0.01

w1 window rolling_3:  49%|▍| 98/200 [00:11<00:10,  9.65round/s, val_excess=0.01

w1 window rolling_3:  49%|▍| 98/200 [00:11<00:10,  9.65round/s, val_excess=0.01

w1 window rolling_3:  50%|▍| 99/200 [00:11<00:10,  9.62round/s, val_excess=0.01

w1 window rolling_3:  50%|▍| 99/200 [00:11<00:10,  9.62round/s, val_excess=0.01

w1 window rolling_3:  50%|▌| 100/200 [00:11<00:10,  9.62round/s, val_excess=0.0

w1 window rolling_3:  50%|▌| 101/200 [00:11<00:10,  9.79round/s, val_excess=0.0

w1 window rolling_3:  50%|▌| 101/200 [00:11<00:10,  9.79round/s, val_excess=0.0

w1 window rolling_3:  51%|▌| 102/200 [00:11<00:09,  9.81round/s, val_excess=0.0

w1 window rolling_3:  51%|▌| 102/200 [00:11<00:09,  9.81round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 103/200 [00:11<00:09,  9.85round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 103/200 [00:11<00:09,  9.85round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 104/200 [00:11<00:09,  9.84round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 104/200 [00:11<00:09,  9.84round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 105/200 [00:11<00:09,  9.78round/s, val_excess=0.0

w1 window rolling_3:  52%|▌| 105/200 [00:11<00:09,  9.78round/s, val_excess=0.0

w1 window rolling_3:  53%|▌| 106/200 [00:11<00:09,  9.75round/s, val_excess=0.0

w1 window rolling_3:  53%|▌| 106/200 [00:11<00:09,  9.75round/s, val_excess=0.0

w1 window rolling_3:  54%|▌| 107/200 [00:12<00:09,  9.68round/s, val_excess=0.0

w1 window rolling_3:  54%|▌| 107/200 [00:12<00:09,  9.68round/s, val_excess=0.0

w1 window rolling_3:  54%|▌| 108/200 [00:12<00:09,  9.76round/s, val_excess=0.0

w1 window rolling_3:  54%|▌| 108/200 [00:12<00:09,  9.76round/s, val_excess=0.0

w1 window rolling_3:  55%|▌| 109/200 [00:12<00:09,  9.76round/s, val_excess=0.0

w1 window rolling_3:  55%|▌| 110/200 [00:12<00:09,  9.98round/s, val_excess=0.0

w1 window rolling_3:  55%|▌| 110/200 [00:12<00:09,  9.98round/s, val_excess=0.0

w1 window rolling_3:  56%|▌| 111/200 [00:12<00:08,  9.98round/s, val_excess=0.0

w1 window rolling_3:  56%|▌| 112/200 [00:12<00:08, 10.01round/s, val_excess=0.0

w1 window rolling_3:  56%|▌| 112/200 [00:12<00:08, 10.01round/s, val_excess=0.0

w1 window rolling_3:  56%|▌| 113/200 [00:12<00:08, 10.01round/s, val_excess=0.0

w1 window rolling_3:  57%|▌| 114/200 [00:12<00:08, 10.02round/s, val_excess=0.0

w1 window rolling_3:  57%|▌| 114/200 [00:12<00:08, 10.02round/s, val_excess=0.0

w1 window rolling_3:  57%|▌| 115/200 [00:12<00:08,  9.92round/s, val_excess=0.0

w1 window rolling_3:  57%|▌| 115/200 [00:12<00:08,  9.92round/s, val_excess=0.0

w1 window rolling_3:  58%|▌| 116/200 [00:13<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_3:  58%|▌| 116/200 [00:13<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_3:  58%|▌| 117/200 [00:13<00:08,  9.90round/s, val_excess=0.0

w1 window rolling_3:  59%|▌| 118/200 [00:13<00:08,  9.95round/s, val_excess=0.0

w1 window rolling_3:  59%|▌| 118/200 [00:13<00:08,  9.95round/s, val_excess=0.0

w1 window rolling_3:  60%|▌| 119/200 [00:13<00:08,  9.95round/s, val_excess=0.0

w1 window rolling_3:  60%|▌| 120/200 [00:13<00:07, 10.00round/s, val_excess=0.0

w1 window rolling_3:  60%|▌| 120/200 [00:13<00:07, 10.00round/s, val_excess=0.0

w1 window rolling_3:  60%|▌| 121/200 [00:13<00:07,  9.95round/s, val_excess=0.0

w1 window rolling_3:  60%|▌| 121/200 [00:13<00:07,  9.95round/s, val_excess=0.0

w1 window rolling_3:  61%|▌| 122/200 [00:13<00:07,  9.95round/s, val_excess=0.0

w1 window rolling_3:  62%|▌| 123/200 [00:13<00:07, 10.04round/s, val_excess=0.0

w1 window rolling_3:  62%|▌| 123/200 [00:13<00:07, 10.04round/s, val_excess=0.0

w1 window rolling_3:  62%|▌| 124/200 [00:13<00:07, 10.01round/s, val_excess=0.0

w1 window rolling_3:  62%|▌| 124/200 [00:13<00:07, 10.01round/s, val_excess=0.0

w1 window rolling_3:  62%|▋| 125/200 [00:13<00:07, 10.01round/s, val_excess=0.0

w1 window rolling_3:  63%|▋| 126/200 [00:13<00:07, 10.03round/s, val_excess=0.0

w1 window rolling_3:  63%|▋| 126/200 [00:13<00:07, 10.03round/s, val_excess=0.0

w1 window rolling_3:  64%|▋| 127/200 [00:14<00:07, 10.03round/s, val_excess=0.0

w1 window rolling_3:  64%|▋| 128/200 [00:14<00:07, 10.09round/s, val_excess=0.0

w1 window rolling_3:  64%|▋| 128/200 [00:14<00:07, 10.09round/s, val_excess=0.0

w1 window rolling_3:  64%|▋| 129/200 [00:14<00:07, 10.09round/s, val_excess=0.0

w1 window rolling_3:  65%|▋| 130/200 [00:14<00:06, 10.14round/s, val_excess=0.0

w1 window rolling_3:  65%|▋| 130/200 [00:14<00:06, 10.14round/s, val_excess=0.0

w1 window rolling_3:  66%|▋| 131/200 [00:14<00:06, 10.14round/s, val_excess=0.0

w1 window rolling_3:  66%|▋| 132/200 [00:14<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  66%|▋| 132/200 [00:14<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  66%|▋| 133/200 [00:14<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  67%|▋| 134/200 [00:14<00:06, 10.21round/s, val_excess=0.0

w1 window rolling_3:  67%|▋| 134/200 [00:14<00:06, 10.21round/s, val_excess=0.0

w1 window rolling_3:  68%|▋| 135/200 [00:14<00:06, 10.21round/s, val_excess=0.0

w1 window rolling_3:  68%|▋| 136/200 [00:14<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  68%|▋| 136/200 [00:14<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  68%|▋| 137/200 [00:15<00:06, 10.15round/s, val_excess=0.0

w1 window rolling_3:  69%|▋| 138/200 [00:15<00:06, 10.16round/s, val_excess=0.0

w1 window rolling_3:  69%|▋| 138/200 [00:15<00:06, 10.16round/s, val_excess=0.0

w1 window rolling_3:  70%|▋| 139/200 [00:15<00:06, 10.16round/s, val_excess=0.0

w1 window rolling_3:  70%|▋| 140/200 [00:15<00:05, 10.21round/s, val_excess=0.0

w1 window rolling_3:  70%|▋| 140/200 [00:15<00:05, 10.21round/s, val_excess=0.0

w1 window rolling_3:  70%|▋| 141/200 [00:15<00:05, 10.21round/s, val_excess=0.0

w1 window rolling_3:  71%|▋| 142/200 [00:15<00:05, 10.19round/s, val_excess=0.0

w1 window rolling_3:  71%|▋| 142/200 [00:15<00:05, 10.19round/s, val_excess=0.0

w1 window rolling_3:  72%|▋| 143/200 [00:15<00:05, 10.19round/s, val_excess=0.0

w1 window rolling_3:  72%|▋| 144/200 [00:15<00:05, 10.15round/s, val_excess=0.0

w1 window rolling_3:  72%|▋| 144/200 [00:15<00:05, 10.15round/s, val_excess=0.0

w1 window rolling_3:  72%|▋| 145/200 [00:15<00:05, 10.15round/s, val_excess=0.0

w1 window rolling_3:  73%|▋| 146/200 [00:15<00:05, 10.08round/s, val_excess=0.0

w1 window rolling_3:  73%|▋| 146/200 [00:15<00:05, 10.08round/s, val_excess=0.0

w1 window rolling_3:  74%|▋| 147/200 [00:16<00:05, 10.08round/s, val_excess=0.0

w1 window rolling_3:  74%|▋| 148/200 [00:16<00:05, 10.03round/s, val_excess=0.0

w1 window rolling_3:  74%|▋| 148/200 [00:16<00:05, 10.03round/s, val_excess=0.0

w1 window rolling_3:  74%|▋| 149/200 [00:16<00:05, 10.03round/s, val_excess=0.0

w1 window rolling_3:  75%|▊| 150/200 [00:16<00:04, 10.13round/s, val_excess=0.0

w1 window rolling_3:  75%|▊| 150/200 [00:16<00:04, 10.13round/s, val_excess=0.0

w1 window rolling_3:  76%|▊| 151/200 [00:16<00:04, 10.13round/s, val_excess=0.0

w1 window rolling_3:  76%|▊| 152/200 [00:16<00:04, 10.14round/s, val_excess=0.0

w1 window rolling_3:  76%|▊| 152/200 [00:16<00:04, 10.14round/s, val_excess=0.0

w1 window rolling_3:  76%|▊| 153/200 [00:16<00:04, 10.14round/s, val_excess=0.0

w1 window rolling_3:  77%|▊| 154/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w1 window rolling_3:  77%|▊| 154/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w1 window rolling_3:  78%|▊| 155/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w1 window rolling_3:  78%|▊| 156/200 [00:16<00:04, 10.10round/s, val_excess=0.0

w1 window rolling_3:  78%|▊| 156/200 [00:16<00:04, 10.10round/s, val_excess=0.0

w1 window rolling_3:  78%|▊| 157/200 [00:17<00:04, 10.10round/s, val_excess=0.0

w1 window rolling_3:  79%|▊| 158/200 [00:17<00:04, 10.15round/s, val_excess=0.0

w1 window rolling_3:  79%|▊| 158/200 [00:17<00:04, 10.15round/s, val_excess=0.0

w1 window rolling_3:  80%|▊| 159/200 [00:17<00:04, 10.15round/s, val_excess=0.0

w1 window rolling_3:  80%|▊| 160/200 [00:17<00:03, 10.18round/s, val_excess=0.0

w1 window rolling_3:  80%|▊| 160/200 [00:17<00:03, 10.18round/s, val_excess=0.0

w1 window rolling_3:  80%|▊| 161/200 [00:17<00:03, 10.18round/s, val_excess=0.0

w1 window rolling_3:  81%|▊| 162/200 [00:17<00:03, 10.16round/s, val_excess=0.0

w1 window rolling_3:  81%|▊| 162/200 [00:17<00:03, 10.16round/s, val_excess=0.0

w1 window rolling_3:  82%|▊| 163/200 [00:17<00:03, 10.16round/s, val_excess=0.0

w1 window rolling_3:  82%|▊| 164/200 [00:17<00:03, 10.06round/s, val_excess=0.0

w1 window rolling_3:  82%|▊| 164/200 [00:17<00:03, 10.06round/s, val_excess=0.0

w1 window rolling_3:  82%|▊| 165/200 [00:17<00:03, 10.06round/s, val_excess=0.0

w1 window rolling_3:  83%|▊| 166/200 [00:17<00:03,  9.94round/s, val_excess=0.0

w1 window rolling_3:  83%|▊| 166/200 [00:17<00:03,  9.94round/s, val_excess=0.0

w1 window rolling_3:  84%|▊| 167/200 [00:18<00:03,  9.94round/s, val_excess=0.0

w1 window rolling_3:  84%|▊| 168/200 [00:18<00:03, 10.02round/s, val_excess=0.0

w1 window rolling_3:  84%|▊| 168/200 [00:18<00:03, 10.02round/s, val_excess=0.0

w1 window rolling_3:  84%|▊| 169/200 [00:18<00:03, 10.02round/s, val_excess=0.0

w1 window rolling_3:  85%|▊| 170/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  85%|▊| 170/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  86%|▊| 171/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  86%|▊| 172/200 [00:18<00:02, 10.12round/s, val_excess=0.0

w1 window rolling_3:  86%|▊| 172/200 [00:18<00:02, 10.12round/s, val_excess=0.0

w1 window rolling_3:  86%|▊| 173/200 [00:18<00:02, 10.12round/s, val_excess=0.0

w1 window rolling_3:  87%|▊| 174/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  87%|▊| 174/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  88%|▉| 175/200 [00:18<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  88%|▉| 176/200 [00:18<00:02, 10.06round/s, val_excess=0.0

w1 window rolling_3:  88%|▉| 176/200 [00:18<00:02, 10.06round/s, val_excess=0.0

w1 window rolling_3:  88%|▉| 177/200 [00:19<00:02, 10.06round/s, val_excess=0.0

w1 window rolling_3:  89%|▉| 178/200 [00:19<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  89%|▉| 178/200 [00:19<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  90%|▉| 179/200 [00:19<00:02, 10.05round/s, val_excess=0.0

w1 window rolling_3:  90%|▉| 180/200 [00:19<00:01, 10.10round/s, val_excess=0.0

w1 window rolling_3:  90%|▉| 180/200 [00:19<00:01, 10.10round/s, val_excess=0.0

w1 window rolling_3:  90%|▉| 181/200 [00:19<00:01, 10.10round/s, val_excess=0.0

w1 window rolling_3:  91%|▉| 182/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  91%|▉| 182/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  92%|▉| 183/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  92%|▉| 184/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  92%|▉| 184/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  92%|▉| 185/200 [00:19<00:01, 10.05round/s, val_excess=0.0

w1 window rolling_3:  93%|▉| 186/200 [00:19<00:01, 10.07round/s, val_excess=0.0

w1 window rolling_3:  93%|▉| 186/200 [00:19<00:01, 10.07round/s, val_excess=0.0

w1 window rolling_3:  94%|▉| 187/200 [00:20<00:01, 10.07round/s, val_excess=0.0

w1 window rolling_3:  94%|▉| 188/200 [00:20<00:01, 10.09round/s, val_excess=0.0

w1 window rolling_3:  94%|▉| 188/200 [00:20<00:01, 10.09round/s, val_excess=0.0

w1 window rolling_3:  94%|▉| 189/200 [00:20<00:01, 10.09round/s, val_excess=0.0

w1 window rolling_3:  95%|▉| 190/200 [00:20<00:00, 10.08round/s, val_excess=0.0

w1 window rolling_3:  95%|▉| 190/200 [00:20<00:00, 10.08round/s, val_excess=0.0

w1 window rolling_3:  96%|▉| 191/200 [00:20<00:00, 10.08round/s, val_excess=0.0

w1 window rolling_3:  96%|▉| 192/200 [00:20<00:00,  9.95round/s, val_excess=0.0

w1 window rolling_3:  96%|▉| 192/200 [00:20<00:00,  9.95round/s, val_excess=0.0

w1 window rolling_3:  96%|▉| 193/200 [00:20<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3:  96%|▉| 193/200 [00:20<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3:  97%|▉| 194/200 [00:20<00:00,  9.90round/s, val_excess=0.0

w1 window rolling_3:  97%|▉| 194/200 [00:20<00:00,  9.90round/s, val_excess=0.0

w1 window rolling_3:  98%|▉| 195/200 [00:20<00:00,  9.90round/s, val_excess=0.0

w1 window rolling_3:  98%|▉| 196/200 [00:20<00:00,  9.93round/s, val_excess=0.0

w1 window rolling_3:  98%|▉| 196/200 [00:20<00:00,  9.93round/s, val_excess=0.0

w1 window rolling_3:  98%|▉| 197/200 [00:21<00:00,  9.92round/s, val_excess=0.0

w1 window rolling_3:  98%|▉| 197/200 [00:21<00:00,  9.92round/s, val_excess=0.0

w1 window rolling_3:  99%|▉| 198/200 [00:21<00:00,  9.91round/s, val_excess=0.0

w1 window rolling_3:  99%|▉| 198/200 [00:21<00:00,  9.91round/s, val_excess=0.0

w1 window rolling_3: 100%|▉| 199/200 [00:21<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3: 100%|▉| 199/200 [00:21<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.89round/s, val_excess=0.0

w1 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.37round/s, val_excess=0.0

2026-07-06 17:24:30 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=1 feature_type=window fold=rolling_4

2026-07-06 17:24:51 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=1 feature_type=window fold=rolling_4 features=69

w1 window rolling_4:   0%|                          | 0/200 [00:00<?, ?round/s]

w1 window rolling_4:   0%|                  | 1/200 [00:00<00:21,  9.47round/s]

w1 window rolling_4:   0%| | 1/200 [00:00<00:21,  9.47round/s, val_excess=0.001

w1 window rolling_4:   1%| | 2/200 [00:00<00:20,  9.47round/s, val_excess=0.008

w1 window rolling_4:   2%| | 3/200 [00:00<00:17, 11.11round/s, val_excess=0.008

w1 window rolling_4:   2%| | 3/200 [00:00<00:17, 11.11round/s, val_excess=0.019

w1 window rolling_4:   2%| | 4/200 [00:00<00:17, 11.11round/s, val_excess=0.001

w1 window rolling_4:   2%| | 5/200 [00:00<00:17, 11.02round/s, val_excess=0.001

w1 window rolling_4:   2%| | 5/200 [00:00<00:17, 11.02round/s, val_excess=-0.01

w1 window rolling_4:   3%| | 6/200 [00:00<00:17, 11.02round/s, val_excess=-0.00

w1 window rolling_4:   4%| | 7/200 [00:00<00:17, 10.84round/s, val_excess=-0.00

w1 window rolling_4:   4%| | 7/200 [00:00<00:17, 10.84round/s, val_excess=0.009

w1 window rolling_4:   4%| | 8/200 [00:00<00:17, 10.84round/s, val_excess=-0.00

w1 window rolling_4:   4%| | 9/200 [00:00<00:17, 10.63round/s, val_excess=-0.00

w1 window rolling_4:   4%| | 9/200 [00:00<00:17, 10.63round/s, val_excess=-0.01

w1 window rolling_4:   5%| | 10/200 [00:00<00:17, 10.63round/s, val_excess=-0.0

w1 window rolling_4:   6%| | 11/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w1 window rolling_4:   6%| | 11/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w1 window rolling_4:   6%| | 12/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w1 window rolling_4:   6%| | 13/200 [00:01<00:17, 10.41round/s, val_excess=-0.0

w1 window rolling_4:   6%| | 13/200 [00:01<00:17, 10.41round/s, val_excess=0.00

w1 window rolling_4:   7%| | 14/200 [00:01<00:17, 10.41round/s, val_excess=0.00

w1 window rolling_4:   8%| | 15/200 [00:01<00:18, 10.25round/s, val_excess=0.00

w1 window rolling_4:   8%| | 15/200 [00:01<00:18, 10.25round/s, val_excess=0.00

w1 window rolling_4:   8%| | 16/200 [00:01<00:17, 10.25round/s, val_excess=0.00

w1 window rolling_4:   8%| | 17/200 [00:01<00:17, 10.23round/s, val_excess=0.00

w1 window rolling_4:   8%| | 17/200 [00:01<00:17, 10.23round/s, val_excess=0.00

w1 window rolling_4:   9%| | 18/200 [00:01<00:17, 10.23round/s, val_excess=0.00

w1 window rolling_4:  10%| | 19/200 [00:01<00:17, 10.17round/s, val_excess=0.00

w1 window rolling_4:  10%| | 19/200 [00:01<00:17, 10.17round/s, val_excess=-0.0

w1 window rolling_4:  10%| | 20/200 [00:01<00:17, 10.17round/s, val_excess=0.00

w1 window rolling_4:  10%| | 21/200 [00:02<00:17, 10.15round/s, val_excess=0.00

w1 window rolling_4:  10%| | 21/200 [00:02<00:17, 10.15round/s, val_excess=0.00

w1 window rolling_4:  11%| | 22/200 [00:02<00:17, 10.15round/s, val_excess=0.01

w1 window rolling_4:  12%| | 23/200 [00:02<00:17, 10.13round/s, val_excess=0.01

w1 window rolling_4:  12%| | 23/200 [00:02<00:17, 10.13round/s, val_excess=0.00

w1 window rolling_4:  12%| | 24/200 [00:02<00:17, 10.13round/s, val_excess=0.01

w1 window rolling_4:  12%|▏| 25/200 [00:02<00:17, 10.08round/s, val_excess=0.01

w1 window rolling_4:  12%|▏| 25/200 [00:02<00:17, 10.08round/s, val_excess=0.00

w1 window rolling_4:  13%|▏| 26/200 [00:02<00:17, 10.08round/s, val_excess=0.01

w1 window rolling_4:  14%|▏| 27/200 [00:02<00:17, 10.08round/s, val_excess=0.01

w1 window rolling_4:  14%|▏| 27/200 [00:02<00:17, 10.08round/s, val_excess=0.00

w1 window rolling_4:  14%|▏| 28/200 [00:02<00:17, 10.08round/s, val_excess=0.01

w1 window rolling_4:  14%|▏| 29/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w1 window rolling_4:  14%|▏| 29/200 [00:02<00:17, 10.04round/s, val_excess=0.00

w1 window rolling_4:  15%|▏| 30/200 [00:02<00:16, 10.04round/s, val_excess=0.01

w1 window rolling_4:  16%|▏| 31/200 [00:03<00:16,  9.98round/s, val_excess=0.01

w1 window rolling_4:  16%|▏| 31/200 [00:03<00:16,  9.98round/s, val_excess=0.01

w1 window rolling_4:  16%|▏| 32/200 [00:03<00:16,  9.98round/s, val_excess=0.00

w1 window rolling_4:  16%|▏| 33/200 [00:03<00:16, 10.00round/s, val_excess=0.00

w1 window rolling_4:  16%|▏| 33/200 [00:03<00:16, 10.00round/s, val_excess=0.00

w1 window rolling_4:  17%|▏| 34/200 [00:03<00:16,  9.99round/s, val_excess=0.00

w1 window rolling_4:  17%|▏| 34/200 [00:03<00:16,  9.99round/s, val_excess=0.00

w1 window rolling_4:  18%|▏| 35/200 [00:03<00:16,  9.99round/s, val_excess=0.00

w1 window rolling_4:  18%|▏| 36/200 [00:03<00:16, 10.02round/s, val_excess=0.00

w1 window rolling_4:  18%|▏| 36/200 [00:03<00:16, 10.02round/s, val_excess=0.00

w1 window rolling_4:  18%|▏| 37/200 [00:03<00:16, 10.02round/s, val_excess=0.00

w1 window rolling_4:  19%|▏| 38/200 [00:03<00:16,  9.97round/s, val_excess=0.00

w1 window rolling_4:  19%|▏| 38/200 [00:03<00:16,  9.97round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 39/200 [00:03<00:16,  9.94round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 39/200 [00:03<00:16,  9.94round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 40/200 [00:03<00:16,  9.90round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 40/200 [00:03<00:16,  9.90round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 41/200 [00:04<00:16,  9.76round/s, val_excess=0.00

w1 window rolling_4:  20%|▏| 41/200 [00:04<00:16,  9.76round/s, val_excess=0.00

w1 window rolling_4:  21%|▏| 42/200 [00:04<00:16,  9.72round/s, val_excess=0.00

w1 window rolling_4:  21%|▏| 42/200 [00:04<00:16,  9.72round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 43/200 [00:04<00:16,  9.74round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 43/200 [00:04<00:16,  9.74round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 44/200 [00:04<00:16,  9.71round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 44/200 [00:04<00:16,  9.71round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 45/200 [00:04<00:15,  9.74round/s, val_excess=0.00

w1 window rolling_4:  22%|▏| 45/200 [00:04<00:15,  9.74round/s, val_excess=0.00

w1 window rolling_4:  23%|▏| 46/200 [00:04<00:15,  9.81round/s, val_excess=0.00

w1 window rolling_4:  23%|▏| 46/200 [00:04<00:15,  9.81round/s, val_excess=0.00

w1 window rolling_4:  24%|▏| 47/200 [00:04<00:15,  9.80round/s, val_excess=0.00

w1 window rolling_4:  24%|▏| 47/200 [00:04<00:15,  9.80round/s, val_excess=-0.0

w1 window rolling_4:  24%|▏| 48/200 [00:04<00:15,  9.82round/s, val_excess=-0.0

w1 window rolling_4:  24%|▏| 48/200 [00:04<00:15,  9.82round/s, val_excess=0.01

w1 window rolling_4:  24%|▏| 49/200 [00:04<00:15,  9.83round/s, val_excess=0.01

w1 window rolling_4:  24%|▏| 49/200 [00:04<00:15,  9.83round/s, val_excess=0.00

w1 window rolling_4:  25%|▎| 50/200 [00:04<00:15,  9.87round/s, val_excess=0.00

w1 window rolling_4:  25%|▎| 50/200 [00:04<00:15,  9.87round/s, val_excess=-0.0

w1 window rolling_4:  26%|▎| 51/200 [00:05<00:15,  9.87round/s, val_excess=-0.0

w1 window rolling_4:  26%|▎| 52/200 [00:05<00:14,  9.91round/s, val_excess=-0.0

w1 window rolling_4:  26%|▎| 52/200 [00:05<00:14,  9.91round/s, val_excess=-0.0

w1 window rolling_4:  26%|▎| 53/200 [00:05<00:14,  9.83round/s, val_excess=-0.0

w1 window rolling_4:  26%|▎| 53/200 [00:05<00:14,  9.83round/s, val_excess=-0.0

w1 window rolling_4:  27%|▎| 54/200 [00:05<00:14,  9.86round/s, val_excess=-0.0

w1 window rolling_4:  27%|▎| 54/200 [00:05<00:14,  9.86round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 55/200 [00:05<00:14,  9.87round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 55/200 [00:05<00:14,  9.87round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 56/200 [00:05<00:14,  9.89round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 56/200 [00:05<00:14,  9.89round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 57/200 [00:05<00:14,  9.92round/s, val_excess=-0.0

w1 window rolling_4:  28%|▎| 57/200 [00:05<00:14,  9.92round/s, val_excess=0.00

w1 window rolling_4:  29%|▎| 58/200 [00:05<00:14,  9.82round/s, val_excess=0.00

w1 window rolling_4:  29%|▎| 58/200 [00:05<00:14,  9.82round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 59/200 [00:05<00:14,  9.80round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 59/200 [00:05<00:14,  9.80round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 60/200 [00:05<00:14,  9.85round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 60/200 [00:05<00:14,  9.85round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.86round/s, val_excess=0.00

w1 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.86round/s, val_excess=0.00

w1 window rolling_4:  31%|▎| 62/200 [00:06<00:13,  9.88round/s, val_excess=0.00

w1 window rolling_4:  31%|▎| 62/200 [00:06<00:13,  9.88round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 63/200 [00:06<00:13,  9.86round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 63/200 [00:06<00:13,  9.86round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 64/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 64/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 65/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  32%|▎| 65/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  33%|▎| 66/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  33%|▎| 66/200 [00:06<00:13,  9.90round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 67/200 [00:06<00:13,  9.88round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 67/200 [00:06<00:13,  9.88round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 68/200 [00:06<00:13,  9.78round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 68/200 [00:06<00:13,  9.78round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 69/200 [00:06<00:13,  9.70round/s, val_excess=0.00

w1 window rolling_4:  34%|▎| 69/200 [00:06<00:13,  9.70round/s, val_excess=0.00

w1 window rolling_4:  35%|▎| 70/200 [00:06<00:13,  9.76round/s, val_excess=0.00

w1 window rolling_4:  35%|▎| 70/200 [00:06<00:13,  9.76round/s, val_excess=0.00

w1 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.80round/s, val_excess=0.00

w1 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.80round/s, val_excess=-0.0

w1 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.83round/s, val_excess=-0.0

w1 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.83round/s, val_excess=0.00

w1 window rolling_4:  36%|▎| 73/200 [00:07<00:12,  9.80round/s, val_excess=0.00

w1 window rolling_4:  36%|▎| 73/200 [00:07<00:12,  9.80round/s, val_excess=0.00

w1 window rolling_4:  37%|▎| 74/200 [00:07<00:12,  9.78round/s, val_excess=0.00

w1 window rolling_4:  37%|▎| 74/200 [00:07<00:12,  9.78round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 75/200 [00:07<00:12,  9.78round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 75/200 [00:07<00:12,  9.78round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 76/200 [00:07<00:12,  9.77round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 76/200 [00:07<00:12,  9.77round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 77/200 [00:07<00:12,  9.74round/s, val_excess=0.00

w1 window rolling_4:  38%|▍| 77/200 [00:07<00:12,  9.74round/s, val_excess=0.00

w1 window rolling_4:  39%|▍| 78/200 [00:07<00:12,  9.69round/s, val_excess=0.00

w1 window rolling_4:  39%|▍| 78/200 [00:07<00:12,  9.69round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 79/200 [00:07<00:12,  9.61round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 79/200 [00:07<00:12,  9.61round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.67round/s, val_excess=0.00

w1 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.67round/s, val_excess=0.00

w1 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.74round/s, val_excess=0.00

w1 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.74round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.71round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.71round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 84/200 [00:08<00:12,  9.64round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 84/200 [00:08<00:12,  9.64round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 85/200 [00:08<00:11,  9.69round/s, val_excess=0.00

w1 window rolling_4:  42%|▍| 85/200 [00:08<00:11,  9.69round/s, val_excess=0.00

w1 window rolling_4:  43%|▍| 86/200 [00:08<00:11,  9.68round/s, val_excess=0.00

w1 window rolling_4:  43%|▍| 86/200 [00:08<00:11,  9.68round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 87/200 [00:08<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 87/200 [00:08<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 88/200 [00:08<00:11,  9.61round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 88/200 [00:08<00:11,  9.61round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 89/200 [00:08<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  44%|▍| 89/200 [00:08<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.60round/s, val_excess=-0.0

w1 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.60round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.59round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.52round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.52round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 93/200 [00:09<00:11,  9.62round/s, val_excess=-0.0

w1 window rolling_4:  46%|▍| 93/200 [00:09<00:11,  9.62round/s, val_excess=-0.0

w1 window rolling_4:  47%|▍| 94/200 [00:09<00:11,  9.57round/s, val_excess=-0.0

w1 window rolling_4:  47%|▍| 94/200 [00:09<00:11,  9.57round/s, val_excess=-0.0

w1 window rolling_4:  48%|▍| 95/200 [00:09<00:10,  9.61round/s, val_excess=-0.0

w1 window rolling_4:  48%|▍| 95/200 [00:09<00:10,  9.61round/s, val_excess=0.00

w1 window rolling_4:  48%|▍| 96/200 [00:09<00:10,  9.66round/s, val_excess=0.00

w1 window rolling_4:  48%|▍| 96/200 [00:09<00:10,  9.66round/s, val_excess=0.00

w1 window rolling_4:  48%|▍| 97/200 [00:09<00:10,  9.60round/s, val_excess=0.00

w1 window rolling_4:  48%|▍| 97/200 [00:09<00:10,  9.60round/s, val_excess=-0.0

w1 window rolling_4:  49%|▍| 98/200 [00:09<00:10,  9.52round/s, val_excess=-0.0

w1 window rolling_4:  49%|▍| 98/200 [00:09<00:10,  9.52round/s, val_excess=-0.0

w1 window rolling_4:  50%|▍| 99/200 [00:09<00:10,  9.54round/s, val_excess=-0.0

w1 window rolling_4:  50%|▍| 99/200 [00:09<00:10,  9.54round/s, val_excess=-0.0

w1 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.60round/s, val_excess=-0.

w1 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.60round/s, val_excess=-0.

w1 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.60round/s, val_excess=-0.

w1 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.60round/s, val_excess=-0.

w1 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.59round/s, val_excess=-0.

w1 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.59round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 103/200 [00:10<00:10,  9.65round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 103/200 [00:10<00:10,  9.65round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 104/200 [00:10<00:10,  9.58round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 104/200 [00:10<00:10,  9.58round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 105/200 [00:10<00:09,  9.56round/s, val_excess=-0.

w1 window rolling_4:  52%|▌| 105/200 [00:10<00:09,  9.56round/s, val_excess=-0.

w1 window rolling_4:  53%|▌| 106/200 [00:10<00:09,  9.49round/s, val_excess=-0.

w1 window rolling_4:  53%|▌| 106/200 [00:10<00:09,  9.49round/s, val_excess=-0.

w1 window rolling_4:  54%|▌| 107/200 [00:10<00:09,  9.47round/s, val_excess=-0.

w1 window rolling_4:  54%|▌| 107/200 [00:10<00:09,  9.47round/s, val_excess=-0.

w1 window rolling_4:  54%|▌| 108/200 [00:10<00:09,  9.46round/s, val_excess=-0.

w1 window rolling_4:  54%|▌| 108/200 [00:10<00:09,  9.46round/s, val_excess=-0.

w1 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.48round/s, val_excess=-0.

w1 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.48round/s, val_excess=-0.

w1 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.45round/s, val_excess=-0.

w1 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.45round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.40round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.40round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 112/200 [00:11<00:09,  9.41round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 112/200 [00:11<00:09,  9.41round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 113/200 [00:11<00:09,  9.34round/s, val_excess=-0.

w1 window rolling_4:  56%|▌| 113/200 [00:11<00:09,  9.34round/s, val_excess=-0.

w1 window rolling_4:  57%|▌| 114/200 [00:11<00:09,  9.33round/s, val_excess=-0.

w1 window rolling_4:  57%|▌| 114/200 [00:11<00:09,  9.33round/s, val_excess=-0.

w1 window rolling_4:  57%|▌| 115/200 [00:11<00:09,  9.34round/s, val_excess=-0.

w1 window rolling_4:  57%|▌| 115/200 [00:11<00:09,  9.34round/s, val_excess=-0.

w1 window rolling_4:  58%|▌| 116/200 [00:11<00:08,  9.35round/s, val_excess=-0.

w1 window rolling_4:  58%|▌| 116/200 [00:11<00:08,  9.35round/s, val_excess=-0.

w1 window rolling_4:  58%|▌| 117/200 [00:11<00:08,  9.39round/s, val_excess=-0.

w1 window rolling_4:  58%|▌| 117/200 [00:11<00:08,  9.39round/s, val_excess=-0.

w1 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.40round/s, val_excess=-0.

w1 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.40round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.42round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.42round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.41round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.41round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.36round/s, val_excess=-0.

w1 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.36round/s, val_excess=-0.

w1 window rolling_4:  61%|▌| 122/200 [00:12<00:08,  9.33round/s, val_excess=-0.

w1 window rolling_4:  61%|▌| 122/200 [00:12<00:08,  9.33round/s, val_excess=-0.

w1 window rolling_4:  62%|▌| 123/200 [00:12<00:08,  9.25round/s, val_excess=-0.

w1 window rolling_4:  62%|▌| 123/200 [00:12<00:08,  9.25round/s, val_excess=-0.

w1 window rolling_4:  62%|▌| 124/200 [00:12<00:08,  9.28round/s, val_excess=-0.

w1 window rolling_4:  62%|▌| 124/200 [00:12<00:08,  9.28round/s, val_excess=-0.

w1 window rolling_4:  62%|▋| 125/200 [00:12<00:08,  9.26round/s, val_excess=-0.

w1 window rolling_4:  62%|▋| 125/200 [00:12<00:08,  9.26round/s, val_excess=-0.

w1 window rolling_4:  63%|▋| 126/200 [00:12<00:07,  9.31round/s, val_excess=-0.

w1 window rolling_4:  63%|▋| 126/200 [00:12<00:07,  9.31round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 127/200 [00:12<00:07,  9.27round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 127/200 [00:12<00:07,  9.27round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.32round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.32round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.27round/s, val_excess=-0.

w1 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.27round/s, val_excess=-0.

w1 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.34round/s, val_excess=-0.

w1 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.34round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 131/200 [00:13<00:07,  9.40round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 131/200 [00:13<00:07,  9.40round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 132/200 [00:13<00:07,  9.51round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 132/200 [00:13<00:07,  9.51round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 133/200 [00:13<00:07,  9.48round/s, val_excess=-0.

w1 window rolling_4:  66%|▋| 133/200 [00:13<00:07,  9.48round/s, val_excess=-0.

w1 window rolling_4:  67%|▋| 134/200 [00:13<00:06,  9.52round/s, val_excess=-0.

w1 window rolling_4:  67%|▋| 134/200 [00:13<00:06,  9.52round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 135/200 [00:13<00:06,  9.44round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 135/200 [00:13<00:06,  9.44round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 136/200 [00:13<00:06,  9.42round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 136/200 [00:13<00:06,  9.42round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.50round/s, val_excess=-0.

w1 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.50round/s, val_excess=-0.

w1 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.51round/s, val_excess=-0.

w1 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.51round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.46round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.46round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 141/200 [00:14<00:06,  9.46round/s, val_excess=-0.

w1 window rolling_4:  70%|▋| 141/200 [00:14<00:06,  9.46round/s, val_excess=-0.

w1 window rolling_4:  71%|▋| 142/200 [00:14<00:06,  9.51round/s, val_excess=-0.

w1 window rolling_4:  71%|▋| 142/200 [00:14<00:06,  9.51round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 143/200 [00:14<00:06,  9.47round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 143/200 [00:14<00:06,  9.47round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 144/200 [00:14<00:05,  9.45round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 144/200 [00:14<00:05,  9.45round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 145/200 [00:14<00:05,  9.50round/s, val_excess=-0.

w1 window rolling_4:  72%|▋| 145/200 [00:14<00:05,  9.50round/s, val_excess=-0.

w1 window rolling_4:  73%|▋| 146/200 [00:14<00:05,  9.47round/s, val_excess=-0.

w1 window rolling_4:  73%|▋| 146/200 [00:14<00:05,  9.47round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.47round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.47round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.51round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.51round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.51round/s, val_excess=-0.

w1 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.51round/s, val_excess=-0.

w1 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.50round/s, val_excess=-0.

w1 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.50round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 151/200 [00:15<00:05,  9.57round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 151/200 [00:15<00:05,  9.57round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 152/200 [00:15<00:05,  9.55round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 152/200 [00:15<00:05,  9.55round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 153/200 [00:15<00:04,  9.51round/s, val_excess=-0.

w1 window rolling_4:  76%|▊| 153/200 [00:15<00:04,  9.51round/s, val_excess=-0.

w1 window rolling_4:  77%|▊| 154/200 [00:15<00:04,  9.51round/s, val_excess=-0.

w1 window rolling_4:  77%|▊| 154/200 [00:15<00:04,  9.51round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 155/200 [00:15<00:04,  9.48round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 155/200 [00:15<00:04,  9.48round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.50round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.50round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.55round/s, val_excess=-0.

w1 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.55round/s, val_excess=-0.

w1 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.55round/s, val_excess=-0.

w1 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.55round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.61round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.61round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 160/200 [00:16<00:04,  9.67round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 160/200 [00:16<00:04,  9.67round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 161/200 [00:16<00:04,  9.59round/s, val_excess=-0.

w1 window rolling_4:  80%|▊| 161/200 [00:16<00:04,  9.59round/s, val_excess=-0.

w1 window rolling_4:  81%|▊| 162/200 [00:16<00:03,  9.58round/s, val_excess=-0.

w1 window rolling_4:  81%|▊| 162/200 [00:16<00:03,  9.58round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 163/200 [00:16<00:03,  9.55round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 163/200 [00:16<00:03,  9.55round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 164/200 [00:16<00:03,  9.52round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 164/200 [00:16<00:03,  9.52round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 165/200 [00:16<00:03,  9.52round/s, val_excess=-0.

w1 window rolling_4:  82%|▊| 165/200 [00:16<00:03,  9.52round/s, val_excess=-0.

w1 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.50round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w1 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w1 window rolling_4:  85%|▊| 170/200 [00:17<00:03,  9.60round/s, val_excess=-0.

w1 window rolling_4:  85%|▊| 170/200 [00:17<00:03,  9.60round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 171/200 [00:17<00:03,  9.65round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 171/200 [00:17<00:03,  9.65round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 172/200 [00:17<00:02,  9.69round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 172/200 [00:17<00:02,  9.69round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 173/200 [00:17<00:02,  9.72round/s, val_excess=-0.

w1 window rolling_4:  86%|▊| 173/200 [00:17<00:02,  9.72round/s, val_excess=-0.

w1 window rolling_4:  87%|▊| 174/200 [00:17<00:02,  9.70round/s, val_excess=-0.

w1 window rolling_4:  87%|▊| 174/200 [00:17<00:02,  9.70round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  9.61round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  9.61round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  9.67round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  9.67round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  9.73round/s, val_excess=-0.

w1 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  9.73round/s, val_excess=-0.

w1 window rolling_4:  89%|▉| 178/200 [00:18<00:02,  9.73round/s, val_excess=-0.

w1 window rolling_4:  89%|▉| 178/200 [00:18<00:02,  9.73round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 179/200 [00:18<00:02,  9.72round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 179/200 [00:18<00:02,  9.72round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 180/200 [00:18<00:02,  9.69round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 180/200 [00:18<00:02,  9.69round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 181/200 [00:18<00:01,  9.70round/s, val_excess=-0.

w1 window rolling_4:  90%|▉| 181/200 [00:18<00:01,  9.70round/s, val_excess=-0.

w1 window rolling_4:  91%|▉| 182/200 [00:18<00:01,  9.58round/s, val_excess=-0.

w1 window rolling_4:  91%|▉| 182/200 [00:18<00:01,  9.58round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 183/200 [00:18<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 183/200 [00:18<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 184/200 [00:18<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 184/200 [00:18<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.54round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.58round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.58round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 188/200 [00:19<00:01,  9.64round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 188/200 [00:19<00:01,  9.64round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 189/200 [00:19<00:01,  9.66round/s, val_excess=-0.

w1 window rolling_4:  94%|▉| 189/200 [00:19<00:01,  9.66round/s, val_excess=-0.

w1 window rolling_4:  95%|▉| 190/200 [00:19<00:01,  9.68round/s, val_excess=-0.

w1 window rolling_4:  95%|▉| 190/200 [00:19<00:01,  9.68round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 191/200 [00:19<00:00,  9.66round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 191/200 [00:19<00:00,  9.66round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 192/200 [00:19<00:00,  9.70round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 192/200 [00:19<00:00,  9.70round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 193/200 [00:19<00:00,  9.66round/s, val_excess=-0.

w1 window rolling_4:  96%|▉| 193/200 [00:19<00:00,  9.66round/s, val_excess=-0.

w1 window rolling_4:  97%|▉| 194/200 [00:19<00:00,  9.63round/s, val_excess=-0.

w1 window rolling_4:  97%|▉| 194/200 [00:19<00:00,  9.63round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.63round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.63round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  9.64round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  9.64round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 197/200 [00:20<00:00,  9.61round/s, val_excess=-0.

w1 window rolling_4:  98%|▉| 197/200 [00:20<00:00,  9.61round/s, val_excess=-0.

w1 window rolling_4:  99%|▉| 198/200 [00:20<00:00,  9.58round/s, val_excess=-0.

w1 window rolling_4:  99%|▉| 198/200 [00:20<00:00,  9.58round/s, val_excess=-0.

w1 window rolling_4: 100%|▉| 199/200 [00:20<00:00,  9.53round/s, val_excess=-0.

w1 window rolling_4: 100%|▉| 199/200 [00:20<00:00,  9.53round/s, val_excess=-0.

w1 window rolling_4: 100%|█| 200/200 [00:20<00:00,  9.50round/s, val_excess=-0.

w1 window rolling_4: 100%|█| 200/200 [00:20<00:00,  9.50round/s, val_excess=-0.

w1 window rolling_4: 100%|█| 200/200 [00:20<00:00,  9.70round/s, val_excess=-0.

2026-07-06 17:25:12 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=2 feature_type=window fold=rolling_1

2026-07-06 17:25:31 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=2 feature_type=window fold=rolling_1 features=69

w2 window rolling_1:   0%|                          | 0/200 [00:00<?, ?round/s]

w2 window rolling_1:   0%| | 1/200 [00:00<00:19, 10.21round/s, val_excess=-0.00

w2 window rolling_1:   1%| | 2/200 [00:00<00:17, 11.43round/s, val_excess=-0.00

w2 window rolling_1:   1%| | 2/200 [00:00<00:17, 11.43round/s, val_excess=0.008

w2 window rolling_1:   2%| | 3/200 [00:00<00:17, 11.43round/s, val_excess=-0.00

w2 window rolling_1:   2%| | 4/200 [00:00<00:16, 11.61round/s, val_excess=-0.00

w2 window rolling_1:   2%| | 4/200 [00:00<00:16, 11.61round/s, val_excess=-0.00

w2 window rolling_1:   2%| | 5/200 [00:00<00:16, 11.61round/s, val_excess=0.002

w2 window rolling_1:   3%| | 6/200 [00:00<00:17, 11.28round/s, val_excess=0.002

w2 window rolling_1:   3%| | 6/200 [00:00<00:17, 11.28round/s, val_excess=0.017

w2 window rolling_1:   4%| | 7/200 [00:00<00:17, 11.28round/s, val_excess=0.011

w2 window rolling_1:   4%| | 8/200 [00:00<00:17, 11.00round/s, val_excess=0.011

w2 window rolling_1:   4%| | 8/200 [00:00<00:17, 11.00round/s, val_excess=0.016

w2 window rolling_1:   4%| | 9/200 [00:00<00:17, 11.00round/s, val_excess=0.009

w2 window rolling_1:   5%| | 10/200 [00:00<00:17, 10.84round/s, val_excess=0.00

w2 window rolling_1:   5%| | 10/200 [00:00<00:17, 10.84round/s, val_excess=0.00

w2 window rolling_1:   6%| | 11/200 [00:01<00:17, 10.84round/s, val_excess=0.00

w2 window rolling_1:   6%| | 12/200 [00:01<00:17, 10.71round/s, val_excess=0.00

w2 window rolling_1:   6%| | 12/200 [00:01<00:17, 10.71round/s, val_excess=-0.0

w2 window rolling_1:   6%| | 13/200 [00:01<00:17, 10.71round/s, val_excess=-0.0

w2 window rolling_1:   7%| | 14/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w2 window rolling_1:   7%| | 14/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w2 window rolling_1:   8%| | 15/200 [00:01<00:17, 10.54round/s, val_excess=0.00

w2 window rolling_1:   8%| | 16/200 [00:01<00:17, 10.53round/s, val_excess=0.00

w2 window rolling_1:   8%| | 16/200 [00:01<00:17, 10.53round/s, val_excess=0.00

w2 window rolling_1:   8%| | 17/200 [00:01<00:17, 10.53round/s, val_excess=-0.0

w2 window rolling_1:   9%| | 18/200 [00:01<00:17, 10.54round/s, val_excess=-0.0

w2 window rolling_1:   9%| | 18/200 [00:01<00:17, 10.54round/s, val_excess=0.00

w2 window rolling_1:  10%| | 19/200 [00:01<00:17, 10.54round/s, val_excess=0.00

w2 window rolling_1:  10%| | 20/200 [00:01<00:17, 10.56round/s, val_excess=0.00

w2 window rolling_1:  10%| | 20/200 [00:01<00:17, 10.56round/s, val_excess=0.00

w2 window rolling_1:  10%| | 21/200 [00:01<00:16, 10.56round/s, val_excess=0.00

w2 window rolling_1:  11%| | 22/200 [00:02<00:16, 10.58round/s, val_excess=0.00

w2 window rolling_1:  11%| | 22/200 [00:02<00:16, 10.58round/s, val_excess=0.00

w2 window rolling_1:  12%| | 23/200 [00:02<00:16, 10.58round/s, val_excess=0.00

w2 window rolling_1:  12%| | 24/200 [00:02<00:16, 10.70round/s, val_excess=0.00

w2 window rolling_1:  12%| | 24/200 [00:02<00:16, 10.70round/s, val_excess=0.00

w2 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.70round/s, val_excess=0.00

w2 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.60round/s, val_excess=0.00

w2 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.60round/s, val_excess=0.00

w2 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.60round/s, val_excess=0.00

w2 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.64round/s, val_excess=0.00

w2 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.64round/s, val_excess=0.00

w2 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.64round/s, val_excess=0.00

w2 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.62round/s, val_excess=0.00

w2 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.62round/s, val_excess=0.01

w2 window rolling_1:  16%|▏| 31/200 [00:02<00:15, 10.62round/s, val_excess=0.02

w2 window rolling_1:  16%|▏| 32/200 [00:02<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  16%|▏| 32/200 [00:02<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  16%|▏| 33/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  17%|▏| 34/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  17%|▏| 34/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  18%|▏| 35/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  18%|▏| 36/200 [00:03<00:15, 10.69round/s, val_excess=0.02

w2 window rolling_1:  18%|▏| 36/200 [00:03<00:15, 10.69round/s, val_excess=0.02

w2 window rolling_1:  18%|▏| 37/200 [00:03<00:15, 10.69round/s, val_excess=0.02

w2 window rolling_1:  19%|▏| 38/200 [00:03<00:15, 10.74round/s, val_excess=0.02

w2 window rolling_1:  19%|▏| 38/200 [00:03<00:15, 10.74round/s, val_excess=0.02

w2 window rolling_1:  20%|▏| 39/200 [00:03<00:14, 10.74round/s, val_excess=0.02

w2 window rolling_1:  20%|▏| 40/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  20%|▏| 40/200 [00:03<00:15, 10.66round/s, val_excess=0.02

w2 window rolling_1:  20%|▏| 41/200 [00:03<00:14, 10.66round/s, val_excess=0.02

w2 window rolling_1:  21%|▏| 42/200 [00:03<00:14, 10.63round/s, val_excess=0.02

w2 window rolling_1:  21%|▏| 42/200 [00:03<00:14, 10.63round/s, val_excess=0.03

w2 window rolling_1:  22%|▏| 43/200 [00:04<00:14, 10.63round/s, val_excess=0.03

w2 window rolling_1:  22%|▏| 44/200 [00:04<00:14, 10.60round/s, val_excess=0.03

w2 window rolling_1:  22%|▏| 44/200 [00:04<00:14, 10.60round/s, val_excess=0.03

w2 window rolling_1:  22%|▏| 45/200 [00:04<00:14, 10.60round/s, val_excess=0.03

w2 window rolling_1:  23%|▏| 46/200 [00:04<00:14, 10.63round/s, val_excess=0.03

w2 window rolling_1:  23%|▏| 46/200 [00:04<00:14, 10.63round/s, val_excess=0.03

w2 window rolling_1:  24%|▏| 47/200 [00:04<00:14, 10.63round/s, val_excess=0.05

w2 window rolling_1:  24%|▏| 48/200 [00:04<00:14, 10.73round/s, val_excess=0.05

w2 window rolling_1:  24%|▏| 48/200 [00:04<00:14, 10.73round/s, val_excess=0.04

w2 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.73round/s, val_excess=0.04

w2 window rolling_1:  25%|▎| 50/200 [00:04<00:13, 10.74round/s, val_excess=0.04

w2 window rolling_1:  25%|▎| 50/200 [00:04<00:13, 10.74round/s, val_excess=0.04

w2 window rolling_1:  26%|▎| 51/200 [00:04<00:13, 10.74round/s, val_excess=0.04

w2 window rolling_1:  26%|▎| 52/200 [00:04<00:13, 10.64round/s, val_excess=0.04

w2 window rolling_1:  26%|▎| 52/200 [00:04<00:13, 10.64round/s, val_excess=0.05

w2 window rolling_1:  26%|▎| 53/200 [00:04<00:13, 10.64round/s, val_excess=0.03

w2 window rolling_1:  27%|▎| 54/200 [00:05<00:13, 10.71round/s, val_excess=0.03

w2 window rolling_1:  27%|▎| 54/200 [00:05<00:13, 10.71round/s, val_excess=0.03

w2 window rolling_1:  28%|▎| 55/200 [00:05<00:13, 10.71round/s, val_excess=0.03

w2 window rolling_1:  28%|▎| 56/200 [00:05<00:13, 10.67round/s, val_excess=0.03

w2 window rolling_1:  28%|▎| 56/200 [00:05<00:13, 10.67round/s, val_excess=0.05

w2 window rolling_1:  28%|▎| 57/200 [00:05<00:13, 10.67round/s, val_excess=0.03

w2 window rolling_1:  29%|▎| 58/200 [00:05<00:13, 10.79round/s, val_excess=0.03

w2 window rolling_1:  29%|▎| 58/200 [00:05<00:13, 10.79round/s, val_excess=0.03

w2 window rolling_1:  30%|▎| 59/200 [00:05<00:13, 10.79round/s, val_excess=0.03

w2 window rolling_1:  30%|▎| 60/200 [00:05<00:12, 10.79round/s, val_excess=0.03

w2 window rolling_1:  30%|▎| 60/200 [00:05<00:12, 10.79round/s, val_excess=0.02

w2 window rolling_1:  30%|▎| 61/200 [00:05<00:12, 10.79round/s, val_excess=0.02

w2 window rolling_1:  31%|▎| 62/200 [00:05<00:13, 10.19round/s, val_excess=0.02

w2 window rolling_1:  31%|▎| 62/200 [00:05<00:13, 10.19round/s, val_excess=0.02

w2 window rolling_1:  32%|▎| 63/200 [00:05<00:13, 10.19round/s, val_excess=0.02

w2 window rolling_1:  32%|▎| 64/200 [00:06<00:13, 10.09round/s, val_excess=0.02

w2 window rolling_1:  32%|▎| 64/200 [00:06<00:13, 10.09round/s, val_excess=0.02

w2 window rolling_1:  32%|▎| 65/200 [00:06<00:13, 10.09round/s, val_excess=0.03

w2 window rolling_1:  33%|▎| 66/200 [00:06<00:13, 10.19round/s, val_excess=0.03

w2 window rolling_1:  33%|▎| 66/200 [00:06<00:13, 10.19round/s, val_excess=0.02

w2 window rolling_1:  34%|▎| 67/200 [00:06<00:13, 10.19round/s, val_excess=0.03

w2 window rolling_1:  34%|▎| 68/200 [00:06<00:12, 10.38round/s, val_excess=0.03

w2 window rolling_1:  34%|▎| 68/200 [00:06<00:12, 10.38round/s, val_excess=0.03

w2 window rolling_1:  34%|▎| 69/200 [00:06<00:12, 10.38round/s, val_excess=0.03

w2 window rolling_1:  35%|▎| 70/200 [00:06<00:12, 10.40round/s, val_excess=0.03

w2 window rolling_1:  35%|▎| 70/200 [00:06<00:12, 10.40round/s, val_excess=0.02

w2 window rolling_1:  36%|▎| 71/200 [00:06<00:12, 10.40round/s, val_excess=0.02

w2 window rolling_1:  36%|▎| 72/200 [00:06<00:12, 10.50round/s, val_excess=0.02

w2 window rolling_1:  36%|▎| 72/200 [00:06<00:12, 10.50round/s, val_excess=0.02

w2 window rolling_1:  36%|▎| 73/200 [00:06<00:12, 10.50round/s, val_excess=0.02

w2 window rolling_1:  37%|▎| 74/200 [00:06<00:12, 10.48round/s, val_excess=0.02

w2 window rolling_1:  37%|▎| 74/200 [00:06<00:12, 10.48round/s, val_excess=0.02

w2 window rolling_1:  38%|▍| 75/200 [00:07<00:11, 10.48round/s, val_excess=0.03

w2 window rolling_1:  38%|▍| 76/200 [00:07<00:11, 10.55round/s, val_excess=0.03

w2 window rolling_1:  38%|▍| 76/200 [00:07<00:11, 10.55round/s, val_excess=0.02

w2 window rolling_1:  38%|▍| 77/200 [00:07<00:11, 10.55round/s, val_excess=0.02

w2 window rolling_1:  39%|▍| 78/200 [00:07<00:11, 10.63round/s, val_excess=0.02

w2 window rolling_1:  39%|▍| 78/200 [00:07<00:11, 10.63round/s, val_excess=0.02

w2 window rolling_1:  40%|▍| 79/200 [00:07<00:11, 10.63round/s, val_excess=0.02

w2 window rolling_1:  40%|▍| 80/200 [00:07<00:11, 10.68round/s, val_excess=0.02

w2 window rolling_1:  40%|▍| 80/200 [00:07<00:11, 10.68round/s, val_excess=0.02

w2 window rolling_1:  40%|▍| 81/200 [00:07<00:11, 10.68round/s, val_excess=0.02

w2 window rolling_1:  41%|▍| 82/200 [00:07<00:11, 10.44round/s, val_excess=0.02

w2 window rolling_1:  41%|▍| 82/200 [00:07<00:11, 10.44round/s, val_excess=0.02

w2 window rolling_1:  42%|▍| 83/200 [00:07<00:11, 10.44round/s, val_excess=0.02

w2 window rolling_1:  42%|▍| 84/200 [00:07<00:11,  9.92round/s, val_excess=0.02

w2 window rolling_1:  42%|▍| 84/200 [00:07<00:11,  9.92round/s, val_excess=0.02

w2 window rolling_1:  42%|▍| 85/200 [00:08<00:11,  9.92round/s, val_excess=0.02

w2 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.24round/s, val_excess=0.02

w2 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.24round/s, val_excess=0.02

w2 window rolling_1:  44%|▍| 87/200 [00:08<00:11, 10.24round/s, val_excess=0.02

w2 window rolling_1:  44%|▍| 88/200 [00:08<00:10, 10.37round/s, val_excess=0.02

w2 window rolling_1:  44%|▍| 88/200 [00:08<00:10, 10.37round/s, val_excess=0.02

w2 window rolling_1:  44%|▍| 89/200 [00:08<00:10, 10.37round/s, val_excess=0.02

w2 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.45round/s, val_excess=0.02

w2 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.45round/s, val_excess=0.02

w2 window rolling_1:  46%|▍| 91/200 [00:08<00:10, 10.45round/s, val_excess=0.03

w2 window rolling_1:  46%|▍| 92/200 [00:08<00:10, 10.64round/s, val_excess=0.03

w2 window rolling_1:  46%|▍| 92/200 [00:08<00:10, 10.64round/s, val_excess=0.03

w2 window rolling_1:  46%|▍| 93/200 [00:08<00:10, 10.64round/s, val_excess=0.02

w2 window rolling_1:  47%|▍| 94/200 [00:08<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  47%|▍| 94/200 [00:08<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  48%|▍| 95/200 [00:08<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  48%|▍| 96/200 [00:09<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  48%|▍| 96/200 [00:09<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  48%|▍| 97/200 [00:09<00:09, 10.61round/s, val_excess=0.02

w2 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.68round/s, val_excess=0.02

w2 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.68round/s, val_excess=0.02

w2 window rolling_1:  50%|▍| 99/200 [00:09<00:09, 10.68round/s, val_excess=0.01

w2 window rolling_1:  50%|▌| 100/200 [00:09<00:09, 10.68round/s, val_excess=0.0

w2 window rolling_1:  50%|▌| 100/200 [00:09<00:09, 10.68round/s, val_excess=0.0

w2 window rolling_1:  50%|▌| 101/200 [00:09<00:09, 10.68round/s, val_excess=0.0

w2 window rolling_1:  51%|▌| 102/200 [00:09<00:09, 10.73round/s, val_excess=0.0

w2 window rolling_1:  51%|▌| 102/200 [00:09<00:09, 10.73round/s, val_excess=0.0

w2 window rolling_1:  52%|▌| 103/200 [00:09<00:09, 10.73round/s, val_excess=0.0

w2 window rolling_1:  52%|▌| 104/200 [00:09<00:08, 10.67round/s, val_excess=0.0

w2 window rolling_1:  52%|▌| 104/200 [00:09<00:08, 10.67round/s, val_excess=0.0

w2 window rolling_1:  52%|▌| 105/200 [00:09<00:08, 10.67round/s, val_excess=0.0

w2 window rolling_1:  53%|▌| 106/200 [00:09<00:08, 10.74round/s, val_excess=0.0

w2 window rolling_1:  53%|▌| 106/200 [00:09<00:08, 10.74round/s, val_excess=0.0

w2 window rolling_1:  54%|▌| 107/200 [00:10<00:08, 10.74round/s, val_excess=0.0

w2 window rolling_1:  54%|▌| 108/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  54%|▌| 108/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  55%|▌| 109/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  55%|▌| 110/200 [00:10<00:08, 10.75round/s, val_excess=0.0

w2 window rolling_1:  55%|▌| 110/200 [00:10<00:08, 10.75round/s, val_excess=0.0

w2 window rolling_1:  56%|▌| 111/200 [00:10<00:08, 10.75round/s, val_excess=0.0

w2 window rolling_1:  56%|▌| 112/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  56%|▌| 112/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  56%|▌| 113/200 [00:10<00:08, 10.76round/s, val_excess=0.0

w2 window rolling_1:  57%|▌| 114/200 [00:10<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  57%|▌| 114/200 [00:10<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  57%|▌| 115/200 [00:10<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  58%|▌| 116/200 [00:10<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  58%|▌| 116/200 [00:10<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  58%|▌| 117/200 [00:11<00:07, 10.77round/s, val_excess=0.0

w2 window rolling_1:  59%|▌| 118/200 [00:11<00:07, 10.79round/s, val_excess=0.0

w2 window rolling_1:  59%|▌| 118/200 [00:11<00:07, 10.79round/s, val_excess=0.0

w2 window rolling_1:  60%|▌| 119/200 [00:11<00:07, 10.79round/s, val_excess=0.0

w2 window rolling_1:  60%|▌| 120/200 [00:11<00:07, 10.67round/s, val_excess=0.0

w2 window rolling_1:  60%|▌| 120/200 [00:11<00:07, 10.67round/s, val_excess=0.0

w2 window rolling_1:  60%|▌| 121/200 [00:11<00:07, 10.67round/s, val_excess=0.0

w2 window rolling_1:  61%|▌| 122/200 [00:11<00:07, 10.73round/s, val_excess=0.0

w2 window rolling_1:  61%|▌| 122/200 [00:11<00:07, 10.73round/s, val_excess=0.0

w2 window rolling_1:  62%|▌| 123/200 [00:11<00:07, 10.73round/s, val_excess=0.0

w2 window rolling_1:  62%|▌| 124/200 [00:11<00:07, 10.78round/s, val_excess=0.0

w2 window rolling_1:  62%|▌| 124/200 [00:11<00:07, 10.78round/s, val_excess=0.0

w2 window rolling_1:  62%|▋| 125/200 [00:11<00:06, 10.78round/s, val_excess=0.0

w2 window rolling_1:  63%|▋| 126/200 [00:11<00:06, 10.78round/s, val_excess=0.0

w2 window rolling_1:  63%|▋| 126/200 [00:11<00:06, 10.78round/s, val_excess=0.0

w2 window rolling_1:  64%|▋| 127/200 [00:11<00:06, 10.78round/s, val_excess=0.0

w2 window rolling_1:  64%|▋| 128/200 [00:12<00:06, 10.80round/s, val_excess=0.0

w2 window rolling_1:  64%|▋| 128/200 [00:12<00:06, 10.80round/s, val_excess=0.0

w2 window rolling_1:  64%|▋| 129/200 [00:12<00:06, 10.80round/s, val_excess=0.0

w2 window rolling_1:  65%|▋| 130/200 [00:12<00:06, 10.83round/s, val_excess=0.0

w2 window rolling_1:  65%|▋| 130/200 [00:12<00:06, 10.83round/s, val_excess=0.0

w2 window rolling_1:  66%|▋| 131/200 [00:12<00:06, 10.83round/s, val_excess=0.0

w2 window rolling_1:  66%|▋| 132/200 [00:12<00:06, 10.85round/s, val_excess=0.0

w2 window rolling_1:  66%|▋| 132/200 [00:12<00:06, 10.85round/s, val_excess=0.0

w2 window rolling_1:  66%|▋| 133/200 [00:12<00:06, 10.85round/s, val_excess=0.0

w2 window rolling_1:  67%|▋| 134/200 [00:12<00:06, 10.85round/s, val_excess=0.0

w2 window rolling_1:  67%|▋| 134/200 [00:12<00:06, 10.85round/s, val_excess=0.0

w2 window rolling_1:  68%|▋| 135/200 [00:12<00:05, 10.85round/s, val_excess=0.0

w2 window rolling_1:  68%|▋| 136/200 [00:12<00:05, 10.80round/s, val_excess=0.0

w2 window rolling_1:  68%|▋| 136/200 [00:12<00:05, 10.80round/s, val_excess=0.0

w2 window rolling_1:  68%|▋| 137/200 [00:12<00:05, 10.80round/s, val_excess=0.0

w2 window rolling_1:  69%|▋| 138/200 [00:12<00:05, 10.75round/s, val_excess=0.0

w2 window rolling_1:  69%|▋| 138/200 [00:12<00:05, 10.75round/s, val_excess=0.0

w2 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.75round/s, val_excess=0.0

w2 window rolling_1:  70%|▋| 140/200 [00:13<00:05, 10.76round/s, val_excess=0.0

w2 window rolling_1:  70%|▋| 140/200 [00:13<00:05, 10.76round/s, val_excess=0.0

w2 window rolling_1:  70%|▋| 141/200 [00:13<00:05, 10.76round/s, val_excess=0.0

w2 window rolling_1:  71%|▋| 142/200 [00:13<00:05, 10.69round/s, val_excess=0.0

w2 window rolling_1:  71%|▋| 142/200 [00:13<00:05, 10.69round/s, val_excess=0.0

w2 window rolling_1:  72%|▋| 143/200 [00:13<00:05, 10.69round/s, val_excess=0.0

w2 window rolling_1:  72%|▋| 144/200 [00:13<00:05, 10.62round/s, val_excess=0.0

w2 window rolling_1:  72%|▋| 144/200 [00:13<00:05, 10.62round/s, val_excess=0.0

w2 window rolling_1:  72%|▋| 145/200 [00:13<00:05, 10.62round/s, val_excess=0.0

w2 window rolling_1:  73%|▋| 146/200 [00:13<00:05, 10.60round/s, val_excess=0.0

w2 window rolling_1:  73%|▋| 146/200 [00:13<00:05, 10.60round/s, val_excess=0.0

w2 window rolling_1:  74%|▋| 147/200 [00:13<00:04, 10.60round/s, val_excess=0.0

w2 window rolling_1:  74%|▋| 148/200 [00:13<00:04, 10.64round/s, val_excess=0.0

w2 window rolling_1:  74%|▋| 148/200 [00:13<00:04, 10.64round/s, val_excess=0.0

w2 window rolling_1:  74%|▋| 149/200 [00:13<00:04, 10.64round/s, val_excess=0.0

w2 window rolling_1:  75%|▊| 150/200 [00:14<00:04, 10.70round/s, val_excess=0.0

w2 window rolling_1:  75%|▊| 150/200 [00:14<00:04, 10.70round/s, val_excess=0.0

w2 window rolling_1:  76%|▊| 151/200 [00:14<00:04, 10.70round/s, val_excess=0.0

w2 window rolling_1:  76%|▊| 152/200 [00:14<00:04, 10.73round/s, val_excess=0.0

w2 window rolling_1:  76%|▊| 152/200 [00:14<00:04, 10.73round/s, val_excess=0.0

w2 window rolling_1:  76%|▊| 153/200 [00:14<00:04, 10.73round/s, val_excess=0.0

w2 window rolling_1:  77%|▊| 154/200 [00:14<00:04, 10.67round/s, val_excess=0.0

w2 window rolling_1:  77%|▊| 154/200 [00:14<00:04, 10.67round/s, val_excess=0.0

w2 window rolling_1:  78%|▊| 155/200 [00:14<00:04, 10.67round/s, val_excess=0.0

w2 window rolling_1:  78%|▊| 156/200 [00:14<00:04, 10.63round/s, val_excess=0.0

w2 window rolling_1:  78%|▊| 156/200 [00:14<00:04, 10.63round/s, val_excess=0.0

w2 window rolling_1:  78%|▊| 157/200 [00:14<00:04, 10.63round/s, val_excess=0.0

w2 window rolling_1:  79%|▊| 158/200 [00:14<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  79%|▊| 158/200 [00:14<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  80%|▊| 159/200 [00:14<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  80%|▊| 160/200 [00:15<00:03, 10.72round/s, val_excess=0.0

w2 window rolling_1:  80%|▊| 160/200 [00:15<00:03, 10.72round/s, val_excess=0.0

w2 window rolling_1:  80%|▊| 161/200 [00:15<00:03, 10.72round/s, val_excess=0.0

w2 window rolling_1:  81%|▊| 162/200 [00:15<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  81%|▊| 162/200 [00:15<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  82%|▊| 163/200 [00:15<00:03, 10.65round/s, val_excess=0.0

w2 window rolling_1:  82%|▊| 164/200 [00:15<00:03, 10.71round/s, val_excess=0.0

w2 window rolling_1:  82%|▊| 164/200 [00:15<00:03, 10.71round/s, val_excess=0.0

w2 window rolling_1:  82%|▊| 165/200 [00:15<00:03, 10.71round/s, val_excess=0.0

w2 window rolling_1:  83%|▊| 166/200 [00:15<00:03, 10.70round/s, val_excess=0.0

w2 window rolling_1:  83%|▊| 166/200 [00:15<00:03, 10.70round/s, val_excess=0.0

w2 window rolling_1:  84%|▊| 167/200 [00:15<00:03, 10.70round/s, val_excess=0.0

w2 window rolling_1:  84%|▊| 168/200 [00:15<00:02, 10.69round/s, val_excess=0.0

w2 window rolling_1:  84%|▊| 168/200 [00:15<00:02, 10.69round/s, val_excess=0.0

w2 window rolling_1:  84%|▊| 169/200 [00:15<00:02, 10.69round/s, val_excess=0.0

w2 window rolling_1:  85%|▊| 170/200 [00:15<00:02, 10.67round/s, val_excess=0.0

w2 window rolling_1:  85%|▊| 170/200 [00:15<00:02, 10.67round/s, val_excess=0.0

w2 window rolling_1:  86%|▊| 171/200 [00:16<00:02, 10.67round/s, val_excess=0.0

w2 window rolling_1:  86%|▊| 172/200 [00:16<00:02, 10.63round/s, val_excess=0.0

w2 window rolling_1:  86%|▊| 172/200 [00:16<00:02, 10.63round/s, val_excess=0.0

w2 window rolling_1:  86%|▊| 173/200 [00:16<00:02, 10.63round/s, val_excess=0.0

w2 window rolling_1:  87%|▊| 174/200 [00:16<00:02, 10.61round/s, val_excess=0.0

w2 window rolling_1:  87%|▊| 174/200 [00:16<00:02, 10.61round/s, val_excess=0.0

w2 window rolling_1:  88%|▉| 175/200 [00:16<00:02, 10.61round/s, val_excess=0.0

w2 window rolling_1:  88%|▉| 176/200 [00:16<00:02, 10.55round/s, val_excess=0.0

w2 window rolling_1:  88%|▉| 176/200 [00:16<00:02, 10.55round/s, val_excess=0.0

w2 window rolling_1:  88%|▉| 177/200 [00:16<00:02, 10.55round/s, val_excess=0.0

w2 window rolling_1:  89%|▉| 178/200 [00:16<00:02, 10.62round/s, val_excess=0.0

w2 window rolling_1:  89%|▉| 178/200 [00:16<00:02, 10.62round/s, val_excess=0.0

w2 window rolling_1:  90%|▉| 179/200 [00:16<00:01, 10.62round/s, val_excess=0.0

w2 window rolling_1:  90%|▉| 180/200 [00:16<00:01, 10.63round/s, val_excess=0.0

w2 window rolling_1:  90%|▉| 180/200 [00:16<00:01, 10.63round/s, val_excess=0.0

w2 window rolling_1:  90%|▉| 181/200 [00:17<00:01, 10.63round/s, val_excess=0.0

w2 window rolling_1:  91%|▉| 182/200 [00:17<00:01, 10.66round/s, val_excess=0.0

w2 window rolling_1:  91%|▉| 182/200 [00:17<00:01, 10.66round/s, val_excess=0.0

w2 window rolling_1:  92%|▉| 183/200 [00:17<00:01, 10.66round/s, val_excess=0.0

w2 window rolling_1:  92%|▉| 184/200 [00:17<00:01, 10.65round/s, val_excess=0.0

w2 window rolling_1:  92%|▉| 184/200 [00:17<00:01, 10.65round/s, val_excess=0.0

w2 window rolling_1:  92%|▉| 185/200 [00:17<00:01, 10.65round/s, val_excess=0.0

w2 window rolling_1:  93%|▉| 186/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  93%|▉| 186/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  94%|▉| 187/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  94%|▉| 188/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  94%|▉| 188/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  94%|▉| 189/200 [00:17<00:01, 10.68round/s, val_excess=0.0

w2 window rolling_1:  95%|▉| 190/200 [00:17<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  95%|▉| 190/200 [00:17<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  96%|▉| 191/200 [00:17<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  96%|▉| 192/200 [00:18<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  96%|▉| 192/200 [00:18<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  96%|▉| 193/200 [00:18<00:00, 10.61round/s, val_excess=0.0

w2 window rolling_1:  97%|▉| 194/200 [00:18<00:00, 10.72round/s, val_excess=0.0

w2 window rolling_1:  97%|▉| 194/200 [00:18<00:00, 10.72round/s, val_excess=0.0

w2 window rolling_1:  98%|▉| 195/200 [00:18<00:00, 10.72round/s, val_excess=0.0

w2 window rolling_1:  98%|▉| 196/200 [00:18<00:00, 10.71round/s, val_excess=0.0

w2 window rolling_1:  98%|▉| 196/200 [00:18<00:00, 10.71round/s, val_excess=0.0

w2 window rolling_1:  98%|▉| 197/200 [00:18<00:00, 10.71round/s, val_excess=0.0

w2 window rolling_1:  99%|▉| 198/200 [00:18<00:00, 10.67round/s, val_excess=0.0

w2 window rolling_1:  99%|▉| 198/200 [00:18<00:00, 10.67round/s, val_excess=0.0

w2 window rolling_1: 100%|▉| 199/200 [00:18<00:00, 10.67round/s, val_excess=0.0

w2 window rolling_1: 100%|█| 200/200 [00:18<00:00, 10.74round/s, val_excess=0.0

w2 window rolling_1: 100%|█| 200/200 [00:18<00:00, 10.74round/s, val_excess=0.0

w2 window rolling_1: 100%|█| 200/200 [00:18<00:00, 10.65round/s, val_excess=0.0

2026-07-06 17:25:50 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=2 feature_type=window fold=rolling_2

2026-07-06 17:26:11 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=2 feature_type=window fold=rolling_2 features=69

w2 window rolling_2:   0%|                          | 0/200 [00:00<?, ?round/s]

w2 window rolling_2:   0%| | 1/200 [00:00<00:19, 10.10round/s, val_excess=-0.00

w2 window rolling_2:   1%| | 2/200 [00:00<00:17, 11.39round/s, val_excess=-0.00

w2 window rolling_2:   1%| | 2/200 [00:00<00:17, 11.39round/s, val_excess=0.020

w2 window rolling_2:   2%| | 3/200 [00:00<00:17, 11.39round/s, val_excess=0.032

w2 window rolling_2:   2%| | 4/200 [00:00<00:17, 11.34round/s, val_excess=0.032

w2 window rolling_2:   2%| | 4/200 [00:00<00:17, 11.34round/s, val_excess=0.024

w2 window rolling_2:   2%| | 5/200 [00:00<00:17, 11.34round/s, val_excess=0.021

w2 window rolling_2:   3%| | 6/200 [00:00<00:17, 11.05round/s, val_excess=0.021

w2 window rolling_2:   3%| | 6/200 [00:00<00:17, 11.05round/s, val_excess=0.027

w2 window rolling_2:   4%| | 7/200 [00:00<00:17, 11.05round/s, val_excess=0.029

w2 window rolling_2:   4%| | 8/200 [00:00<00:17, 10.68round/s, val_excess=0.029

w2 window rolling_2:   4%| | 8/200 [00:00<00:17, 10.68round/s, val_excess=0.031

w2 window rolling_2:   4%| | 9/200 [00:00<00:17, 10.68round/s, val_excess=0.024

w2 window rolling_2:   5%| | 10/200 [00:00<00:17, 10.65round/s, val_excess=0.02

w2 window rolling_2:   5%| | 10/200 [00:00<00:17, 10.65round/s, val_excess=0.01

w2 window rolling_2:   6%| | 11/200 [00:01<00:17, 10.65round/s, val_excess=0.01

w2 window rolling_2:   6%| | 12/200 [00:01<00:17, 10.50round/s, val_excess=0.01

w2 window rolling_2:   6%| | 12/200 [00:01<00:17, 10.50round/s, val_excess=0.02

w2 window rolling_2:   6%| | 13/200 [00:01<00:17, 10.50round/s, val_excess=0.01

w2 window rolling_2:   7%| | 14/200 [00:01<00:17, 10.48round/s, val_excess=0.01

w2 window rolling_2:   7%| | 14/200 [00:01<00:17, 10.48round/s, val_excess=0.01

w2 window rolling_2:   8%| | 15/200 [00:01<00:17, 10.48round/s, val_excess=0.01

w2 window rolling_2:   8%| | 16/200 [00:01<00:17, 10.51round/s, val_excess=0.01

w2 window rolling_2:   8%| | 16/200 [00:01<00:17, 10.51round/s, val_excess=0.02

w2 window rolling_2:   8%| | 17/200 [00:01<00:17, 10.51round/s, val_excess=0.01

w2 window rolling_2:   9%| | 18/200 [00:01<00:17, 10.57round/s, val_excess=0.01

w2 window rolling_2:   9%| | 18/200 [00:01<00:17, 10.57round/s, val_excess=0.02

w2 window rolling_2:  10%| | 19/200 [00:01<00:17, 10.57round/s, val_excess=0.02

w2 window rolling_2:  10%| | 20/200 [00:01<00:17, 10.44round/s, val_excess=0.02

w2 window rolling_2:  10%| | 20/200 [00:01<00:17, 10.44round/s, val_excess=0.02

w2 window rolling_2:  10%| | 21/200 [00:01<00:17, 10.44round/s, val_excess=0.02

w2 window rolling_2:  11%| | 22/200 [00:02<00:17, 10.34round/s, val_excess=0.02

w2 window rolling_2:  11%| | 22/200 [00:02<00:17, 10.34round/s, val_excess=0.02

w2 window rolling_2:  12%| | 23/200 [00:02<00:17, 10.34round/s, val_excess=0.01

w2 window rolling_2:  12%| | 24/200 [00:02<00:17, 10.30round/s, val_excess=0.01

w2 window rolling_2:  12%| | 24/200 [00:02<00:17, 10.30round/s, val_excess=0.02

w2 window rolling_2:  12%|▏| 25/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w2 window rolling_2:  13%|▏| 26/200 [00:02<00:17, 10.20round/s, val_excess=0.01

w2 window rolling_2:  13%|▏| 26/200 [00:02<00:17, 10.20round/s, val_excess=0.01

w2 window rolling_2:  14%|▏| 27/200 [00:02<00:16, 10.20round/s, val_excess=0.00

w2 window rolling_2:  14%|▏| 28/200 [00:02<00:16, 10.31round/s, val_excess=0.00

w2 window rolling_2:  14%|▏| 28/200 [00:02<00:16, 10.31round/s, val_excess=0.01

w2 window rolling_2:  14%|▏| 29/200 [00:02<00:16, 10.31round/s, val_excess=0.01

w2 window rolling_2:  15%|▏| 30/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w2 window rolling_2:  15%|▏| 30/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w2 window rolling_2:  16%|▏| 31/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w2 window rolling_2:  16%|▏| 32/200 [00:03<00:16, 10.27round/s, val_excess=0.01

w2 window rolling_2:  16%|▏| 32/200 [00:03<00:16, 10.27round/s, val_excess=0.01

w2 window rolling_2:  16%|▏| 33/200 [00:03<00:16, 10.27round/s, val_excess=0.02

w2 window rolling_2:  17%|▏| 34/200 [00:03<00:16, 10.29round/s, val_excess=0.02

w2 window rolling_2:  17%|▏| 34/200 [00:03<00:16, 10.29round/s, val_excess=0.02

w2 window rolling_2:  18%|▏| 35/200 [00:03<00:16, 10.29round/s, val_excess=0.02

w2 window rolling_2:  18%|▏| 36/200 [00:03<00:15, 10.27round/s, val_excess=0.02

w2 window rolling_2:  18%|▏| 36/200 [00:03<00:15, 10.27round/s, val_excess=0.01

w2 window rolling_2:  18%|▏| 37/200 [00:03<00:15, 10.27round/s, val_excess=0.01

w2 window rolling_2:  19%|▏| 38/200 [00:03<00:15, 10.27round/s, val_excess=0.01

w2 window rolling_2:  19%|▏| 38/200 [00:03<00:15, 10.27round/s, val_excess=0.02

w2 window rolling_2:  20%|▏| 39/200 [00:03<00:15, 10.27round/s, val_excess=0.02

w2 window rolling_2:  20%|▏| 40/200 [00:03<00:15, 10.30round/s, val_excess=0.02

w2 window rolling_2:  20%|▏| 40/200 [00:03<00:15, 10.30round/s, val_excess=0.01

w2 window rolling_2:  20%|▏| 41/200 [00:03<00:15, 10.30round/s, val_excess=0.02

w2 window rolling_2:  21%|▏| 42/200 [00:04<00:15, 10.20round/s, val_excess=0.02

w2 window rolling_2:  21%|▏| 42/200 [00:04<00:15, 10.20round/s, val_excess=0.01

w2 window rolling_2:  22%|▏| 43/200 [00:04<00:15, 10.20round/s, val_excess=0.01

w2 window rolling_2:  22%|▏| 44/200 [00:04<00:15, 10.22round/s, val_excess=0.01

w2 window rolling_2:  22%|▏| 44/200 [00:04<00:15, 10.22round/s, val_excess=0.01

w2 window rolling_2:  22%|▏| 45/200 [00:04<00:15, 10.22round/s, val_excess=0.01

w2 window rolling_2:  23%|▏| 46/200 [00:04<00:15, 10.18round/s, val_excess=0.01

w2 window rolling_2:  23%|▏| 46/200 [00:04<00:15, 10.18round/s, val_excess=0.01

w2 window rolling_2:  24%|▏| 47/200 [00:04<00:15, 10.18round/s, val_excess=0.01

w2 window rolling_2:  24%|▏| 48/200 [00:04<00:14, 10.14round/s, val_excess=0.01

w2 window rolling_2:  24%|▏| 48/200 [00:04<00:14, 10.14round/s, val_excess=0.01

w2 window rolling_2:  24%|▏| 49/200 [00:04<00:14, 10.14round/s, val_excess=0.01

w2 window rolling_2:  25%|▎| 50/200 [00:04<00:14, 10.19round/s, val_excess=0.01

w2 window rolling_2:  25%|▎| 50/200 [00:04<00:14, 10.19round/s, val_excess=0.00

w2 window rolling_2:  26%|▎| 51/200 [00:04<00:14, 10.19round/s, val_excess=0.00

w2 window rolling_2:  26%|▎| 52/200 [00:05<00:14, 10.10round/s, val_excess=0.00

w2 window rolling_2:  26%|▎| 52/200 [00:05<00:14, 10.10round/s, val_excess=0.00

w2 window rolling_2:  26%|▎| 53/200 [00:05<00:14, 10.10round/s, val_excess=0.01

w2 window rolling_2:  27%|▎| 54/200 [00:05<00:14, 10.13round/s, val_excess=0.01

w2 window rolling_2:  27%|▎| 54/200 [00:05<00:14, 10.13round/s, val_excess=0.01

w2 window rolling_2:  28%|▎| 55/200 [00:05<00:14, 10.13round/s, val_excess=0.01

w2 window rolling_2:  28%|▎| 56/200 [00:05<00:14, 10.15round/s, val_excess=0.01

w2 window rolling_2:  28%|▎| 56/200 [00:05<00:14, 10.15round/s, val_excess=0.01

w2 window rolling_2:  28%|▎| 57/200 [00:05<00:14, 10.15round/s, val_excess=0.01

w2 window rolling_2:  29%|▎| 58/200 [00:05<00:13, 10.18round/s, val_excess=0.01

w2 window rolling_2:  29%|▎| 58/200 [00:05<00:13, 10.18round/s, val_excess=0.01

w2 window rolling_2:  30%|▎| 59/200 [00:05<00:13, 10.18round/s, val_excess=0.01

w2 window rolling_2:  30%|▎| 60/200 [00:05<00:13, 10.23round/s, val_excess=0.01

w2 window rolling_2:  30%|▎| 60/200 [00:05<00:13, 10.23round/s, val_excess=0.01

w2 window rolling_2:  30%|▎| 61/200 [00:05<00:13, 10.23round/s, val_excess=0.01

w2 window rolling_2:  31%|▎| 62/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  31%|▎| 62/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  32%|▎| 63/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  32%|▎| 64/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  32%|▎| 64/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  32%|▎| 65/200 [00:06<00:13, 10.22round/s, val_excess=0.01

w2 window rolling_2:  33%|▎| 66/200 [00:06<00:13, 10.20round/s, val_excess=0.01

w2 window rolling_2:  33%|▎| 66/200 [00:06<00:13, 10.20round/s, val_excess=0.01

w2 window rolling_2:  34%|▎| 67/200 [00:06<00:13, 10.20round/s, val_excess=0.01

w2 window rolling_2:  34%|▎| 68/200 [00:06<00:13, 10.08round/s, val_excess=0.01

w2 window rolling_2:  34%|▎| 68/200 [00:06<00:13, 10.08round/s, val_excess=0.01

w2 window rolling_2:  34%|▎| 69/200 [00:06<00:12, 10.08round/s, val_excess=0.01

w2 window rolling_2:  35%|▎| 70/200 [00:06<00:12, 10.14round/s, val_excess=0.01

w2 window rolling_2:  35%|▎| 70/200 [00:06<00:12, 10.14round/s, val_excess=0.02

w2 window rolling_2:  36%|▎| 71/200 [00:06<00:12, 10.14round/s, val_excess=0.02

w2 window rolling_2:  36%|▎| 72/200 [00:06<00:12, 10.09round/s, val_excess=0.02

w2 window rolling_2:  36%|▎| 72/200 [00:06<00:12, 10.09round/s, val_excess=0.03

w2 window rolling_2:  36%|▎| 73/200 [00:07<00:12, 10.09round/s, val_excess=0.03

w2 window rolling_2:  37%|▎| 74/200 [00:07<00:12, 10.05round/s, val_excess=0.03

w2 window rolling_2:  37%|▎| 74/200 [00:07<00:12, 10.05round/s, val_excess=0.03

w2 window rolling_2:  38%|▍| 75/200 [00:07<00:12, 10.05round/s, val_excess=0.03

w2 window rolling_2:  38%|▍| 76/200 [00:07<00:12, 10.18round/s, val_excess=0.03

w2 window rolling_2:  38%|▍| 76/200 [00:07<00:12, 10.18round/s, val_excess=0.01

w2 window rolling_2:  38%|▍| 77/200 [00:07<00:12, 10.18round/s, val_excess=0.01

w2 window rolling_2:  39%|▍| 78/200 [00:07<00:11, 10.18round/s, val_excess=0.01

w2 window rolling_2:  39%|▍| 78/200 [00:07<00:11, 10.18round/s, val_excess=0.01

w2 window rolling_2:  40%|▍| 79/200 [00:07<00:11, 10.18round/s, val_excess=0.00

w2 window rolling_2:  40%|▍| 80/200 [00:07<00:11, 10.28round/s, val_excess=0.00

w2 window rolling_2:  40%|▍| 80/200 [00:07<00:11, 10.28round/s, val_excess=0.00

w2 window rolling_2:  40%|▍| 81/200 [00:07<00:11, 10.28round/s, val_excess=0.01

w2 window rolling_2:  41%|▍| 82/200 [00:07<00:11, 10.31round/s, val_excess=0.01

w2 window rolling_2:  41%|▍| 82/200 [00:07<00:11, 10.31round/s, val_excess=0.01

w2 window rolling_2:  42%|▍| 83/200 [00:08<00:11, 10.31round/s, val_excess=0.01

w2 window rolling_2:  42%|▍| 84/200 [00:08<00:11, 10.34round/s, val_excess=0.01

w2 window rolling_2:  42%|▍| 84/200 [00:08<00:11, 10.34round/s, val_excess=0.01

w2 window rolling_2:  42%|▍| 85/200 [00:08<00:11, 10.34round/s, val_excess=0.01

w2 window rolling_2:  43%|▍| 86/200 [00:08<00:11, 10.23round/s, val_excess=0.01

w2 window rolling_2:  43%|▍| 86/200 [00:08<00:11, 10.23round/s, val_excess=0.01

w2 window rolling_2:  44%|▍| 87/200 [00:08<00:11, 10.23round/s, val_excess=0.01

w2 window rolling_2:  44%|▍| 88/200 [00:08<00:10, 10.23round/s, val_excess=0.01

w2 window rolling_2:  44%|▍| 88/200 [00:08<00:10, 10.23round/s, val_excess=0.01

w2 window rolling_2:  44%|▍| 89/200 [00:08<00:10, 10.23round/s, val_excess=0.01

w2 window rolling_2:  45%|▍| 90/200 [00:08<00:10, 10.29round/s, val_excess=0.01

w2 window rolling_2:  45%|▍| 90/200 [00:08<00:10, 10.29round/s, val_excess=0.01

w2 window rolling_2:  46%|▍| 91/200 [00:08<00:10, 10.29round/s, val_excess=0.01

w2 window rolling_2:  46%|▍| 92/200 [00:08<00:10, 10.17round/s, val_excess=0.01

w2 window rolling_2:  46%|▍| 92/200 [00:08<00:10, 10.17round/s, val_excess=0.01

w2 window rolling_2:  46%|▍| 93/200 [00:09<00:10, 10.17round/s, val_excess=0.01

w2 window rolling_2:  47%|▍| 94/200 [00:09<00:10, 10.12round/s, val_excess=0.01

w2 window rolling_2:  47%|▍| 94/200 [00:09<00:10, 10.12round/s, val_excess=0.01

w2 window rolling_2:  48%|▍| 95/200 [00:09<00:10, 10.12round/s, val_excess=0.01

w2 window rolling_2:  48%|▍| 96/200 [00:09<00:10, 10.27round/s, val_excess=0.01

w2 window rolling_2:  48%|▍| 96/200 [00:09<00:10, 10.27round/s, val_excess=0.01

w2 window rolling_2:  48%|▍| 97/200 [00:09<00:10, 10.27round/s, val_excess=0.01

w2 window rolling_2:  49%|▍| 98/200 [00:09<00:10, 10.15round/s, val_excess=0.01

w2 window rolling_2:  49%|▍| 98/200 [00:09<00:10, 10.15round/s, val_excess=0.01

w2 window rolling_2:  50%|▍| 99/200 [00:09<00:09, 10.15round/s, val_excess=0.01

w2 window rolling_2:  50%|▌| 100/200 [00:09<00:09, 10.05round/s, val_excess=0.0

w2 window rolling_2:  50%|▌| 100/200 [00:09<00:09, 10.05round/s, val_excess=0.0

w2 window rolling_2:  50%|▌| 101/200 [00:09<00:09, 10.05round/s, val_excess=0.0

w2 window rolling_2:  51%|▌| 102/200 [00:09<00:09, 10.11round/s, val_excess=0.0

w2 window rolling_2:  51%|▌| 102/200 [00:09<00:09, 10.11round/s, val_excess=0.0

w2 window rolling_2:  52%|▌| 103/200 [00:10<00:09, 10.11round/s, val_excess=0.0

w2 window rolling_2:  52%|▌| 104/200 [00:10<00:09, 10.15round/s, val_excess=0.0

w2 window rolling_2:  52%|▌| 104/200 [00:10<00:09, 10.15round/s, val_excess=0.0

w2 window rolling_2:  52%|▌| 105/200 [00:10<00:09, 10.15round/s, val_excess=0.0

w2 window rolling_2:  53%|▌| 106/200 [00:10<00:09, 10.07round/s, val_excess=0.0

w2 window rolling_2:  53%|▌| 106/200 [00:10<00:09, 10.07round/s, val_excess=0.0

w2 window rolling_2:  54%|▌| 107/200 [00:10<00:09, 10.07round/s, val_excess=0.0

w2 window rolling_2:  54%|▌| 108/200 [00:10<00:09, 10.08round/s, val_excess=0.0

w2 window rolling_2:  54%|▌| 108/200 [00:10<00:09, 10.08round/s, val_excess=0.0

w2 window rolling_2:  55%|▌| 109/200 [00:10<00:09, 10.08round/s, val_excess=0.0

w2 window rolling_2:  55%|▌| 110/200 [00:10<00:08, 10.14round/s, val_excess=0.0

w2 window rolling_2:  55%|▌| 110/200 [00:10<00:08, 10.14round/s, val_excess=0.0

w2 window rolling_2:  56%|▌| 111/200 [00:10<00:08, 10.14round/s, val_excess=0.0

w2 window rolling_2:  56%|▌| 112/200 [00:10<00:08, 10.19round/s, val_excess=0.0

w2 window rolling_2:  56%|▌| 112/200 [00:10<00:08, 10.19round/s, val_excess=0.0

w2 window rolling_2:  56%|▌| 113/200 [00:11<00:08, 10.19round/s, val_excess=0.0

w2 window rolling_2:  57%|▌| 114/200 [00:11<00:08, 10.08round/s, val_excess=0.0

w2 window rolling_2:  57%|▌| 114/200 [00:11<00:08, 10.08round/s, val_excess=0.0

w2 window rolling_2:  57%|▌| 115/200 [00:11<00:08, 10.08round/s, val_excess=0.0

w2 window rolling_2:  58%|▌| 116/200 [00:11<00:08, 10.22round/s, val_excess=0.0

w2 window rolling_2:  58%|▌| 116/200 [00:11<00:08, 10.22round/s, val_excess=0.0

w2 window rolling_2:  58%|▌| 117/200 [00:11<00:08, 10.22round/s, val_excess=0.0

w2 window rolling_2:  59%|▌| 118/200 [00:11<00:08, 10.25round/s, val_excess=0.0

w2 window rolling_2:  59%|▌| 118/200 [00:11<00:08, 10.25round/s, val_excess=0.0

w2 window rolling_2:  60%|▌| 119/200 [00:11<00:07, 10.25round/s, val_excess=0.0

w2 window rolling_2:  60%|▌| 120/200 [00:11<00:07, 10.23round/s, val_excess=0.0

w2 window rolling_2:  60%|▌| 120/200 [00:11<00:07, 10.23round/s, val_excess=0.0

w2 window rolling_2:  60%|▌| 121/200 [00:11<00:07, 10.23round/s, val_excess=0.0

w2 window rolling_2:  61%|▌| 122/200 [00:11<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  61%|▌| 122/200 [00:11<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  62%|▌| 123/200 [00:12<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  62%|▌| 124/200 [00:12<00:07, 10.13round/s, val_excess=0.0

w2 window rolling_2:  62%|▌| 124/200 [00:12<00:07, 10.13round/s, val_excess=0.0

w2 window rolling_2:  62%|▋| 125/200 [00:12<00:07, 10.13round/s, val_excess=0.0

w2 window rolling_2:  63%|▋| 126/200 [00:12<00:07, 10.21round/s, val_excess=0.0

w2 window rolling_2:  63%|▋| 126/200 [00:12<00:07, 10.21round/s, val_excess=0.0

w2 window rolling_2:  64%|▋| 127/200 [00:12<00:07, 10.21round/s, val_excess=0.0

w2 window rolling_2:  64%|▋| 128/200 [00:12<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  64%|▋| 128/200 [00:12<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  64%|▋| 129/200 [00:12<00:07, 10.11round/s, val_excess=0.0

w2 window rolling_2:  65%|▋| 130/200 [00:12<00:06, 10.18round/s, val_excess=0.0

w2 window rolling_2:  65%|▋| 130/200 [00:12<00:06, 10.18round/s, val_excess=0.0

w2 window rolling_2:  66%|▋| 131/200 [00:12<00:06, 10.18round/s, val_excess=0.0

w2 window rolling_2:  66%|▋| 132/200 [00:12<00:06, 10.15round/s, val_excess=0.0

w2 window rolling_2:  66%|▋| 132/200 [00:12<00:06, 10.15round/s, val_excess=0.0

w2 window rolling_2:  66%|▋| 133/200 [00:12<00:06, 10.15round/s, val_excess=0.0

w2 window rolling_2:  67%|▋| 134/200 [00:13<00:06, 10.30round/s, val_excess=0.0

w2 window rolling_2:  67%|▋| 134/200 [00:13<00:06, 10.30round/s, val_excess=0.0

w2 window rolling_2:  68%|▋| 135/200 [00:13<00:06, 10.30round/s, val_excess=0.0

w2 window rolling_2:  68%|▋| 136/200 [00:13<00:06, 10.38round/s, val_excess=0.0

w2 window rolling_2:  68%|▋| 136/200 [00:13<00:06, 10.38round/s, val_excess=0.0

w2 window rolling_2:  68%|▋| 137/200 [00:13<00:06, 10.38round/s, val_excess=0.0

w2 window rolling_2:  69%|▋| 138/200 [00:13<00:05, 10.36round/s, val_excess=0.0

w2 window rolling_2:  69%|▋| 138/200 [00:13<00:05, 10.36round/s, val_excess=0.0

w2 window rolling_2:  70%|▋| 139/200 [00:13<00:05, 10.36round/s, val_excess=0.0

w2 window rolling_2:  70%|▋| 140/200 [00:13<00:05, 10.37round/s, val_excess=0.0

w2 window rolling_2:  70%|▋| 140/200 [00:13<00:05, 10.37round/s, val_excess=0.0

w2 window rolling_2:  70%|▋| 141/200 [00:13<00:05, 10.37round/s, val_excess=0.0

w2 window rolling_2:  71%|▋| 142/200 [00:13<00:05, 10.43round/s, val_excess=0.0

w2 window rolling_2:  71%|▋| 142/200 [00:13<00:05, 10.43round/s, val_excess=0.0

w2 window rolling_2:  72%|▋| 143/200 [00:13<00:05, 10.43round/s, val_excess=0.0

w2 window rolling_2:  72%|▋| 144/200 [00:14<00:05, 10.45round/s, val_excess=0.0

w2 window rolling_2:  72%|▋| 144/200 [00:14<00:05, 10.45round/s, val_excess=0.0

w2 window rolling_2:  72%|▋| 145/200 [00:14<00:05, 10.45round/s, val_excess=0.0

w2 window rolling_2:  73%|▋| 146/200 [00:14<00:05, 10.33round/s, val_excess=0.0

w2 window rolling_2:  73%|▋| 146/200 [00:14<00:05, 10.33round/s, val_excess=0.0

w2 window rolling_2:  74%|▋| 147/200 [00:14<00:05, 10.33round/s, val_excess=0.0

w2 window rolling_2:  74%|▋| 148/200 [00:14<00:04, 10.49round/s, val_excess=0.0

w2 window rolling_2:  74%|▋| 148/200 [00:14<00:04, 10.49round/s, val_excess=-0.

w2 window rolling_2:  74%|▋| 149/200 [00:14<00:04, 10.49round/s, val_excess=-0.

w2 window rolling_2:  75%|▊| 150/200 [00:14<00:04, 10.56round/s, val_excess=-0.

w2 window rolling_2:  75%|▊| 150/200 [00:14<00:04, 10.56round/s, val_excess=-0.

w2 window rolling_2:  76%|▊| 151/200 [00:14<00:04, 10.56round/s, val_excess=-0.

w2 window rolling_2:  76%|▊| 152/200 [00:14<00:04, 10.46round/s, val_excess=-0.

w2 window rolling_2:  76%|▊| 152/200 [00:14<00:04, 10.46round/s, val_excess=-0.

w2 window rolling_2:  76%|▊| 153/200 [00:14<00:04, 10.46round/s, val_excess=-0.

w2 window rolling_2:  77%|▊| 154/200 [00:15<00:04, 10.21round/s, val_excess=-0.

w2 window rolling_2:  77%|▊| 154/200 [00:15<00:04, 10.21round/s, val_excess=-0.

w2 window rolling_2:  78%|▊| 155/200 [00:15<00:04, 10.21round/s, val_excess=-0.

w2 window rolling_2:  78%|▊| 156/200 [00:15<00:04,  9.92round/s, val_excess=-0.

w2 window rolling_2:  78%|▊| 156/200 [00:15<00:04,  9.92round/s, val_excess=-0.

w2 window rolling_2:  78%|▊| 157/200 [00:15<00:04,  9.79round/s, val_excess=-0.

w2 window rolling_2:  78%|▊| 157/200 [00:15<00:04,  9.79round/s, val_excess=-0.

w2 window rolling_2:  79%|▊| 158/200 [00:15<00:04,  9.51round/s, val_excess=-0.

w2 window rolling_2:  79%|▊| 158/200 [00:15<00:04,  9.51round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 159/200 [00:15<00:04,  9.49round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 159/200 [00:15<00:04,  9.49round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 160/200 [00:15<00:04,  9.40round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 160/200 [00:15<00:04,  9.40round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 161/200 [00:15<00:04,  9.41round/s, val_excess=0.0

w2 window rolling_2:  80%|▊| 161/200 [00:15<00:04,  9.41round/s, val_excess=0.0

w2 window rolling_2:  81%|▊| 162/200 [00:15<00:04,  9.38round/s, val_excess=0.0

w2 window rolling_2:  81%|▊| 162/200 [00:15<00:04,  9.38round/s, val_excess=-0.

w2 window rolling_2:  82%|▊| 163/200 [00:15<00:03,  9.37round/s, val_excess=-0.

w2 window rolling_2:  82%|▊| 163/200 [00:15<00:03,  9.37round/s, val_excess=0.0

w2 window rolling_2:  82%|▊| 164/200 [00:16<00:03,  9.31round/s, val_excess=0.0

w2 window rolling_2:  82%|▊| 164/200 [00:16<00:03,  9.31round/s, val_excess=0.0

w2 window rolling_2:  82%|▊| 165/200 [00:16<00:03,  9.28round/s, val_excess=0.0

w2 window rolling_2:  82%|▊| 165/200 [00:16<00:03,  9.28round/s, val_excess=0.0

w2 window rolling_2:  83%|▊| 166/200 [00:16<00:03,  9.31round/s, val_excess=0.0

w2 window rolling_2:  83%|▊| 166/200 [00:16<00:03,  9.31round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 167/200 [00:16<00:03,  9.34round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 167/200 [00:16<00:03,  9.34round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 168/200 [00:16<00:03,  9.32round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 168/200 [00:16<00:03,  9.32round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 169/200 [00:16<00:03,  9.30round/s, val_excess=0.0

w2 window rolling_2:  84%|▊| 169/200 [00:16<00:03,  9.30round/s, val_excess=0.0

w2 window rolling_2:  85%|▊| 170/200 [00:16<00:03,  9.26round/s, val_excess=0.0

w2 window rolling_2:  85%|▊| 170/200 [00:16<00:03,  9.26round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 171/200 [00:16<00:03,  9.32round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 171/200 [00:16<00:03,  9.32round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 172/200 [00:16<00:03,  9.27round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 172/200 [00:16<00:03,  9.27round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 173/200 [00:17<00:02,  9.31round/s, val_excess=0.0

w2 window rolling_2:  86%|▊| 173/200 [00:17<00:02,  9.31round/s, val_excess=0.0

w2 window rolling_2:  87%|▊| 174/200 [00:17<00:02,  9.27round/s, val_excess=0.0

w2 window rolling_2:  87%|▊| 174/200 [00:17<00:02,  9.27round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 175/200 [00:17<00:02,  9.29round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 175/200 [00:17<00:02,  9.29round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 176/200 [00:17<00:02,  9.13round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 176/200 [00:17<00:02,  9.13round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 177/200 [00:17<00:02,  9.14round/s, val_excess=0.0

w2 window rolling_2:  88%|▉| 177/200 [00:17<00:02,  9.14round/s, val_excess=0.0

w2 window rolling_2:  89%|▉| 178/200 [00:17<00:02,  9.16round/s, val_excess=0.0

w2 window rolling_2:  89%|▉| 178/200 [00:17<00:02,  9.16round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 179/200 [00:17<00:02,  9.13round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 179/200 [00:17<00:02,  9.13round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 180/200 [00:17<00:02,  9.09round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 180/200 [00:17<00:02,  9.09round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 181/200 [00:17<00:02,  8.98round/s, val_excess=0.0

w2 window rolling_2:  90%|▉| 181/200 [00:17<00:02,  8.98round/s, val_excess=0.0

w2 window rolling_2:  91%|▉| 182/200 [00:18<00:01,  9.04round/s, val_excess=0.0

w2 window rolling_2:  91%|▉| 182/200 [00:18<00:01,  9.04round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 183/200 [00:18<00:01,  9.11round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 183/200 [00:18<00:01,  9.11round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 184/200 [00:18<00:01,  9.11round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 184/200 [00:18<00:01,  9.11round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 185/200 [00:18<00:01,  9.10round/s, val_excess=0.0

w2 window rolling_2:  92%|▉| 185/200 [00:18<00:01,  9.10round/s, val_excess=0.0

w2 window rolling_2:  93%|▉| 186/200 [00:18<00:01,  9.04round/s, val_excess=0.0

w2 window rolling_2:  93%|▉| 186/200 [00:18<00:01,  9.04round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 187/200 [00:18<00:01,  8.57round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 187/200 [00:18<00:01,  8.57round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 188/200 [00:18<00:01,  8.26round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 188/200 [00:18<00:01,  8.26round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 189/200 [00:18<00:01,  8.07round/s, val_excess=0.0

w2 window rolling_2:  94%|▉| 189/200 [00:18<00:01,  8.07round/s, val_excess=0.0

w2 window rolling_2:  95%|▉| 190/200 [00:19<00:01,  7.96round/s, val_excess=0.0

w2 window rolling_2:  95%|▉| 190/200 [00:19<00:01,  7.96round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 191/200 [00:19<00:01,  7.85round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 191/200 [00:19<00:01,  7.85round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 192/200 [00:19<00:01,  7.90round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 192/200 [00:19<00:01,  7.90round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 193/200 [00:19<00:00,  7.90round/s, val_excess=0.0

w2 window rolling_2:  96%|▉| 193/200 [00:19<00:00,  7.90round/s, val_excess=0.0

w2 window rolling_2:  97%|▉| 194/200 [00:19<00:00,  7.95round/s, val_excess=0.0

w2 window rolling_2:  97%|▉| 194/200 [00:19<00:00,  7.95round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 195/200 [00:19<00:00,  8.35round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 195/200 [00:19<00:00,  8.35round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 196/200 [00:19<00:00,  8.58round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 196/200 [00:19<00:00,  8.58round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 197/200 [00:19<00:00,  8.72round/s, val_excess=0.0

w2 window rolling_2:  98%|▉| 197/200 [00:19<00:00,  8.72round/s, val_excess=0.0

w2 window rolling_2:  99%|▉| 198/200 [00:19<00:00,  8.83round/s, val_excess=0.0

w2 window rolling_2:  99%|▉| 198/200 [00:19<00:00,  8.83round/s, val_excess=0.0

w2 window rolling_2: 100%|▉| 199/200 [00:20<00:00,  8.89round/s, val_excess=0.0

w2 window rolling_2: 100%|▉| 199/200 [00:20<00:00,  8.89round/s, val_excess=0.0

w2 window rolling_2: 100%|█| 200/200 [00:20<00:00,  8.94round/s, val_excess=0.0

w2 window rolling_2: 100%|█| 200/200 [00:20<00:00,  8.94round/s, val_excess=0.0

w2 window rolling_2: 100%|█| 200/200 [00:20<00:00,  9.91round/s, val_excess=0.0

2026-07-06 17:26:32 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=2 feature_type=window fold=rolling_3

2026-07-06 17:26:53 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=2 feature_type=window fold=rolling_3 features=69

w2 window rolling_3:   0%|                          | 0/200 [00:00<?, ?round/s]

w2 window rolling_3:   0%|                  | 1/200 [00:00<00:26,  7.42round/s]

w2 window rolling_3:   0%| | 1/200 [00:00<00:26,  7.42round/s, val_excess=-0.00

w2 window rolling_3:   1%| | 2/200 [00:00<00:26,  7.42round/s, val_excess=0.003

w2 window rolling_3:   2%| | 3/200 [00:00<00:20,  9.60round/s, val_excess=0.003

w2 window rolling_3:   2%| | 3/200 [00:00<00:20,  9.60round/s, val_excess=0.003

w2 window rolling_3:   2%| | 4/200 [00:00<00:20,  9.60round/s, val_excess=-0.00

w2 window rolling_3:   2%| | 5/200 [00:00<00:19, 10.01round/s, val_excess=-0.00

w2 window rolling_3:   2%| | 5/200 [00:00<00:19, 10.01round/s, val_excess=0.018

w2 window rolling_3:   3%| | 6/200 [00:00<00:19, 10.01round/s, val_excess=0.002

w2 window rolling_3:   4%| | 7/200 [00:00<00:19,  9.95round/s, val_excess=0.002

w2 window rolling_3:   4%| | 7/200 [00:00<00:19,  9.95round/s, val_excess=0.011

w2 window rolling_3:   4%| | 8/200 [00:00<00:19,  9.95round/s, val_excess=0.014

w2 window rolling_3:   4%| | 9/200 [00:00<00:19,  9.70round/s, val_excess=0.014

w2 window rolling_3:   4%| | 9/200 [00:00<00:19,  9.70round/s, val_excess=0.013

w2 window rolling_3:   5%| | 10/200 [00:01<00:19,  9.69round/s, val_excess=0.01

w2 window rolling_3:   5%| | 10/200 [00:01<00:19,  9.69round/s, val_excess=0.00

w2 window rolling_3:   6%| | 11/200 [00:01<00:19,  9.70round/s, val_excess=0.00

w2 window rolling_3:   6%| | 11/200 [00:01<00:19,  9.70round/s, val_excess=0.01

w2 window rolling_3:   6%| | 12/200 [00:01<00:19,  9.73round/s, val_excess=0.01

w2 window rolling_3:   6%| | 12/200 [00:01<00:19,  9.73round/s, val_excess=0.00

w2 window rolling_3:   6%| | 13/200 [00:01<00:19,  9.65round/s, val_excess=0.00

w2 window rolling_3:   6%| | 13/200 [00:01<00:19,  9.65round/s, val_excess=0.01

w2 window rolling_3:   7%| | 14/200 [00:01<00:19,  9.66round/s, val_excess=0.01

w2 window rolling_3:   7%| | 14/200 [00:01<00:19,  9.66round/s, val_excess=0.01

w2 window rolling_3:   8%| | 15/200 [00:01<00:19,  9.56round/s, val_excess=0.01

w2 window rolling_3:   8%| | 15/200 [00:01<00:19,  9.56round/s, val_excess=0.01

w2 window rolling_3:   8%| | 16/200 [00:01<00:19,  9.47round/s, val_excess=0.01

w2 window rolling_3:   8%| | 16/200 [00:01<00:19,  9.47round/s, val_excess=0.01

w2 window rolling_3:   8%| | 17/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w2 window rolling_3:   8%| | 17/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w2 window rolling_3:   9%| | 18/200 [00:01<00:19,  9.47round/s, val_excess=0.01

w2 window rolling_3:   9%| | 18/200 [00:01<00:19,  9.47round/s, val_excess=0.00

w2 window rolling_3:  10%| | 19/200 [00:01<00:19,  9.46round/s, val_excess=0.00

w2 window rolling_3:  10%| | 19/200 [00:01<00:19,  9.46round/s, val_excess=0.00

w2 window rolling_3:  10%| | 20/200 [00:02<00:18,  9.51round/s, val_excess=0.00

w2 window rolling_3:  10%| | 20/200 [00:02<00:18,  9.51round/s, val_excess=-0.0

w2 window rolling_3:  10%| | 21/200 [00:02<00:18,  9.52round/s, val_excess=-0.0

w2 window rolling_3:  10%| | 21/200 [00:02<00:18,  9.52round/s, val_excess=0.00

w2 window rolling_3:  11%| | 22/200 [00:02<00:18,  9.47round/s, val_excess=0.00

w2 window rolling_3:  11%| | 22/200 [00:02<00:18,  9.47round/s, val_excess=0.00

w2 window rolling_3:  12%| | 23/200 [00:02<00:18,  9.54round/s, val_excess=0.00

w2 window rolling_3:  12%| | 23/200 [00:02<00:18,  9.54round/s, val_excess=0.00

w2 window rolling_3:  12%| | 24/200 [00:02<00:18,  9.40round/s, val_excess=0.00

w2 window rolling_3:  12%| | 24/200 [00:02<00:18,  9.40round/s, val_excess=0.00

w2 window rolling_3:  12%|▏| 25/200 [00:02<00:18,  9.40round/s, val_excess=0.00

w2 window rolling_3:  12%|▏| 25/200 [00:02<00:18,  9.40round/s, val_excess=0.00

w2 window rolling_3:  13%|▏| 26/200 [00:02<00:18,  9.38round/s, val_excess=0.00

w2 window rolling_3:  13%|▏| 26/200 [00:02<00:18,  9.38round/s, val_excess=0.01

w2 window rolling_3:  14%|▏| 27/200 [00:02<00:18,  9.45round/s, val_excess=0.01

w2 window rolling_3:  14%|▏| 27/200 [00:02<00:18,  9.45round/s, val_excess=0.00

w2 window rolling_3:  14%|▏| 28/200 [00:02<00:18,  9.47round/s, val_excess=0.00

w2 window rolling_3:  14%|▏| 28/200 [00:02<00:18,  9.47round/s, val_excess=0.00

w2 window rolling_3:  14%|▏| 29/200 [00:03<00:18,  9.37round/s, val_excess=0.00

w2 window rolling_3:  14%|▏| 29/200 [00:03<00:18,  9.37round/s, val_excess=0.00

w2 window rolling_3:  15%|▏| 30/200 [00:03<00:18,  9.33round/s, val_excess=0.00

w2 window rolling_3:  15%|▏| 30/200 [00:03<00:18,  9.33round/s, val_excess=0.00

w2 window rolling_3:  16%|▏| 31/200 [00:03<00:17,  9.40round/s, val_excess=0.00

w2 window rolling_3:  16%|▏| 31/200 [00:03<00:17,  9.40round/s, val_excess=0.01

w2 window rolling_3:  16%|▏| 32/200 [00:03<00:17,  9.45round/s, val_excess=0.01

w2 window rolling_3:  16%|▏| 32/200 [00:03<00:17,  9.45round/s, val_excess=0.00

w2 window rolling_3:  16%|▏| 33/200 [00:03<00:17,  9.51round/s, val_excess=0.00

w2 window rolling_3:  16%|▏| 33/200 [00:03<00:17,  9.51round/s, val_excess=0.01

w2 window rolling_3:  17%|▏| 34/200 [00:03<00:17,  9.42round/s, val_excess=0.01

w2 window rolling_3:  17%|▏| 34/200 [00:03<00:17,  9.42round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 35/200 [00:03<00:17,  9.21round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 35/200 [00:03<00:17,  9.21round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 36/200 [00:03<00:17,  9.26round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 36/200 [00:03<00:17,  9.26round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 37/200 [00:03<00:17,  9.29round/s, val_excess=0.01

w2 window rolling_3:  18%|▏| 37/200 [00:03<00:17,  9.29round/s, val_excess=0.01

w2 window rolling_3:  19%|▏| 38/200 [00:04<00:17,  9.16round/s, val_excess=0.01

w2 window rolling_3:  19%|▏| 38/200 [00:04<00:17,  9.16round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 39/200 [00:04<00:18,  8.92round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 39/200 [00:04<00:18,  8.92round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 40/200 [00:04<00:18,  8.87round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 40/200 [00:04<00:18,  8.87round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 41/200 [00:04<00:18,  8.83round/s, val_excess=0.01

w2 window rolling_3:  20%|▏| 41/200 [00:04<00:18,  8.83round/s, val_excess=0.01

w2 window rolling_3:  21%|▏| 42/200 [00:04<00:17,  8.78round/s, val_excess=0.01

w2 window rolling_3:  21%|▏| 42/200 [00:04<00:17,  8.78round/s, val_excess=0.01

w2 window rolling_3:  22%|▏| 43/200 [00:04<00:17,  8.81round/s, val_excess=0.01

w2 window rolling_3:  22%|▏| 43/200 [00:04<00:17,  8.81round/s, val_excess=-0.0

w2 window rolling_3:  22%|▏| 44/200 [00:04<00:17,  8.89round/s, val_excess=-0.0

w2 window rolling_3:  22%|▏| 44/200 [00:04<00:17,  8.89round/s, val_excess=-0.0

w2 window rolling_3:  22%|▏| 45/200 [00:04<00:17,  9.02round/s, val_excess=-0.0

w2 window rolling_3:  22%|▏| 45/200 [00:04<00:17,  9.02round/s, val_excess=0.00

w2 window rolling_3:  23%|▏| 46/200 [00:04<00:16,  9.08round/s, val_excess=0.00

w2 window rolling_3:  23%|▏| 46/200 [00:04<00:16,  9.08round/s, val_excess=-0.0

w2 window rolling_3:  24%|▏| 47/200 [00:05<00:16,  9.03round/s, val_excess=-0.0

w2 window rolling_3:  24%|▏| 47/200 [00:05<00:16,  9.03round/s, val_excess=0.00

w2 window rolling_3:  24%|▏| 48/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  24%|▏| 48/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  24%|▏| 49/200 [00:05<00:16,  9.12round/s, val_excess=0.00

w2 window rolling_3:  24%|▏| 49/200 [00:05<00:16,  9.12round/s, val_excess=0.00

w2 window rolling_3:  25%|▎| 50/200 [00:05<00:16,  9.11round/s, val_excess=0.00

w2 window rolling_3:  25%|▎| 50/200 [00:05<00:16,  9.11round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 51/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 51/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 52/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 52/200 [00:05<00:16,  9.13round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 53/200 [00:05<00:16,  9.12round/s, val_excess=0.00

w2 window rolling_3:  26%|▎| 53/200 [00:05<00:16,  9.12round/s, val_excess=0.01

w2 window rolling_3:  27%|▎| 54/200 [00:05<00:18,  7.86round/s, val_excess=0.01

w2 window rolling_3:  27%|▎| 54/200 [00:05<00:18,  7.86round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 55/200 [00:06<00:19,  7.31round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 55/200 [00:06<00:19,  7.31round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 56/200 [00:06<00:20,  6.92round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 56/200 [00:06<00:20,  6.92round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 57/200 [00:06<00:20,  6.83round/s, val_excess=0.00

w2 window rolling_3:  28%|▎| 57/200 [00:06<00:20,  6.83round/s, val_excess=-0.0

w2 window rolling_3:  29%|▎| 58/200 [00:06<00:20,  7.01round/s, val_excess=-0.0

w2 window rolling_3:  29%|▎| 58/200 [00:06<00:20,  7.01round/s, val_excess=0.00

w2 window rolling_3:  30%|▎| 59/200 [00:06<00:19,  7.11round/s, val_excess=0.00

w2 window rolling_3:  30%|▎| 59/200 [00:06<00:19,  7.11round/s, val_excess=-0.0

w2 window rolling_3:  30%|▎| 60/200 [00:06<00:19,  7.20round/s, val_excess=-0.0

w2 window rolling_3:  30%|▎| 60/200 [00:06<00:19,  7.20round/s, val_excess=-0.0

w2 window rolling_3:  30%|▎| 61/200 [00:06<00:19,  7.24round/s, val_excess=-0.0

w2 window rolling_3:  30%|▎| 61/200 [00:06<00:19,  7.24round/s, val_excess=0.00

w2 window rolling_3:  31%|▎| 62/200 [00:06<00:18,  7.32round/s, val_excess=0.00

w2 window rolling_3:  31%|▎| 62/200 [00:06<00:18,  7.32round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 63/200 [00:07<00:18,  7.35round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 63/200 [00:07<00:18,  7.35round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 64/200 [00:07<00:17,  7.78round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 64/200 [00:07<00:17,  7.78round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 65/200 [00:07<00:16,  8.18round/s, val_excess=0.00

w2 window rolling_3:  32%|▎| 65/200 [00:07<00:16,  8.18round/s, val_excess=0.00

w2 window rolling_3:  33%|▎| 66/200 [00:07<00:15,  8.40round/s, val_excess=0.00

w2 window rolling_3:  33%|▎| 66/200 [00:07<00:15,  8.40round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 67/200 [00:07<00:15,  8.49round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 67/200 [00:07<00:15,  8.49round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 68/200 [00:07<00:15,  8.65round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 68/200 [00:07<00:15,  8.65round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 69/200 [00:07<00:14,  8.76round/s, val_excess=0.00

w2 window rolling_3:  34%|▎| 69/200 [00:07<00:14,  8.76round/s, val_excess=0.01

w2 window rolling_3:  35%|▎| 70/200 [00:07<00:14,  8.91round/s, val_excess=0.01

w2 window rolling_3:  35%|▎| 70/200 [00:07<00:14,  8.91round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 71/200 [00:08<00:14,  9.00round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 71/200 [00:08<00:14,  9.00round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  9.07round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  9.07round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 73/200 [00:08<00:13,  9.10round/s, val_excess=0.00

w2 window rolling_3:  36%|▎| 73/200 [00:08<00:13,  9.10round/s, val_excess=0.01

w2 window rolling_3:  37%|▎| 74/200 [00:08<00:13,  9.13round/s, val_excess=0.01

w2 window rolling_3:  37%|▎| 74/200 [00:08<00:13,  9.13round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 75/200 [00:08<00:13,  9.22round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 75/200 [00:08<00:13,  9.22round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 76/200 [00:08<00:13,  9.13round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 76/200 [00:08<00:13,  9.13round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 77/200 [00:08<00:13,  9.14round/s, val_excess=0.01

w2 window rolling_3:  38%|▍| 77/200 [00:08<00:13,  9.14round/s, val_excess=0.01

w2 window rolling_3:  39%|▍| 78/200 [00:08<00:13,  9.20round/s, val_excess=0.01

w2 window rolling_3:  39%|▍| 78/200 [00:08<00:13,  9.20round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 79/200 [00:08<00:13,  9.22round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 79/200 [00:08<00:13,  9.22round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 80/200 [00:08<00:13,  9.10round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 80/200 [00:08<00:13,  9.10round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 81/200 [00:09<00:13,  9.12round/s, val_excess=0.01

w2 window rolling_3:  40%|▍| 81/200 [00:09<00:13,  9.12round/s, val_excess=0.01

w2 window rolling_3:  41%|▍| 82/200 [00:09<00:12,  9.09round/s, val_excess=0.01

w2 window rolling_3:  41%|▍| 82/200 [00:09<00:12,  9.09round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 83/200 [00:09<00:12,  9.12round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 83/200 [00:09<00:12,  9.12round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.13round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.13round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.07round/s, val_excess=0.01

w2 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.07round/s, val_excess=0.01

w2 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.16round/s, val_excess=0.01

w2 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.16round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 87/200 [00:09<00:12,  9.17round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 87/200 [00:09<00:12,  9.17round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 88/200 [00:09<00:12,  9.06round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 88/200 [00:09<00:12,  9.06round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  9.13round/s, val_excess=0.01

w2 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  9.13round/s, val_excess=0.01

w2 window rolling_3:  45%|▍| 90/200 [00:10<00:12,  9.12round/s, val_excess=0.01

w2 window rolling_3:  45%|▍| 90/200 [00:10<00:12,  9.12round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.11round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.11round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.02round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.02round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 93/200 [00:10<00:12,  8.80round/s, val_excess=0.01

w2 window rolling_3:  46%|▍| 93/200 [00:10<00:12,  8.80round/s, val_excess=0.01

w2 window rolling_3:  47%|▍| 94/200 [00:10<00:12,  8.80round/s, val_excess=0.01

w2 window rolling_3:  47%|▍| 94/200 [00:10<00:12,  8.80round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  8.85round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  8.85round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 96/200 [00:10<00:11,  8.88round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 96/200 [00:10<00:11,  8.88round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 97/200 [00:10<00:11,  8.85round/s, val_excess=0.01

w2 window rolling_3:  48%|▍| 97/200 [00:10<00:11,  8.85round/s, val_excess=0.01

w2 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  8.86round/s, val_excess=0.01

w2 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  8.86round/s, val_excess=0.01

w2 window rolling_3:  50%|▍| 99/200 [00:11<00:11,  8.72round/s, val_excess=0.01

w2 window rolling_3:  50%|▍| 99/200 [00:11<00:11,  8.72round/s, val_excess=0.01

w2 window rolling_3:  50%|▌| 100/200 [00:11<00:11,  8.80round/s, val_excess=0.0

w2 window rolling_3:  50%|▌| 100/200 [00:11<00:11,  8.80round/s, val_excess=0.0

w2 window rolling_3:  50%|▌| 101/200 [00:11<00:11,  8.90round/s, val_excess=0.0

w2 window rolling_3:  50%|▌| 101/200 [00:11<00:11,  8.90round/s, val_excess=0.0

w2 window rolling_3:  51%|▌| 102/200 [00:11<00:10,  8.99round/s, val_excess=0.0

w2 window rolling_3:  51%|▌| 102/200 [00:11<00:10,  8.99round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 103/200 [00:11<00:11,  8.76round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 103/200 [00:11<00:11,  8.76round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 104/200 [00:11<00:10,  8.89round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 104/200 [00:11<00:10,  8.89round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 105/200 [00:11<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_3:  52%|▌| 105/200 [00:11<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_3:  53%|▌| 106/200 [00:11<00:10,  8.93round/s, val_excess=0.0

w2 window rolling_3:  53%|▌| 106/200 [00:11<00:10,  8.93round/s, val_excess=0.0

w2 window rolling_3:  54%|▌| 107/200 [00:12<00:10,  8.85round/s, val_excess=0.0

w2 window rolling_3:  54%|▌| 107/200 [00:12<00:10,  8.85round/s, val_excess=0.0

w2 window rolling_3:  54%|▌| 108/200 [00:12<00:10,  8.75round/s, val_excess=0.0

w2 window rolling_3:  54%|▌| 108/200 [00:12<00:10,  8.75round/s, val_excess=0.0

w2 window rolling_3:  55%|▌| 109/200 [00:12<00:12,  7.56round/s, val_excess=0.0

w2 window rolling_3:  55%|▌| 109/200 [00:12<00:12,  7.56round/s, val_excess=0.0

w2 window rolling_3:  55%|▌| 110/200 [00:12<00:12,  7.28round/s, val_excess=0.0

w2 window rolling_3:  55%|▌| 110/200 [00:12<00:12,  7.28round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 111/200 [00:12<00:12,  7.05round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 111/200 [00:12<00:12,  7.05round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 112/200 [00:12<00:12,  6.89round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 112/200 [00:12<00:12,  6.89round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 113/200 [00:12<00:12,  6.76round/s, val_excess=0.0

w2 window rolling_3:  56%|▌| 113/200 [00:12<00:12,  6.76round/s, val_excess=0.0

w2 window rolling_3:  57%|▌| 114/200 [00:13<00:12,  6.72round/s, val_excess=0.0

w2 window rolling_3:  57%|▌| 114/200 [00:13<00:12,  6.72round/s, val_excess=0.0

w2 window rolling_3:  57%|▌| 115/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  57%|▌| 115/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  58%|▌| 116/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  58%|▌| 116/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  58%|▌| 117/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  58%|▌| 117/200 [00:13<00:12,  6.67round/s, val_excess=0.0

w2 window rolling_3:  59%|▌| 118/200 [00:13<00:12,  6.66round/s, val_excess=0.0

w2 window rolling_3:  59%|▌| 118/200 [00:13<00:12,  6.66round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 119/200 [00:13<00:12,  6.69round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 119/200 [00:13<00:12,  6.69round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 120/200 [00:13<00:11,  7.25round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 120/200 [00:13<00:11,  7.25round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 121/200 [00:14<00:10,  7.68round/s, val_excess=0.0

w2 window rolling_3:  60%|▌| 121/200 [00:14<00:10,  7.68round/s, val_excess=0.0

w2 window rolling_3:  61%|▌| 122/200 [00:14<00:09,  8.02round/s, val_excess=0.0

w2 window rolling_3:  61%|▌| 122/200 [00:14<00:09,  8.02round/s, val_excess=0.0

w2 window rolling_3:  62%|▌| 123/200 [00:14<00:09,  8.31round/s, val_excess=0.0

w2 window rolling_3:  62%|▌| 123/200 [00:14<00:09,  8.31round/s, val_excess=0.0

w2 window rolling_3:  62%|▌| 124/200 [00:14<00:08,  8.48round/s, val_excess=0.0

w2 window rolling_3:  62%|▌| 124/200 [00:14<00:08,  8.48round/s, val_excess=0.0

w2 window rolling_3:  62%|▋| 125/200 [00:14<00:08,  8.61round/s, val_excess=0.0

w2 window rolling_3:  62%|▋| 125/200 [00:14<00:08,  8.61round/s, val_excess=0.0

w2 window rolling_3:  63%|▋| 126/200 [00:14<00:08,  8.76round/s, val_excess=0.0

w2 window rolling_3:  63%|▋| 126/200 [00:14<00:08,  8.76round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 127/200 [00:14<00:08,  8.67round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 127/200 [00:14<00:08,  8.67round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 128/200 [00:14<00:08,  8.80round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 128/200 [00:14<00:08,  8.80round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 129/200 [00:14<00:08,  8.82round/s, val_excess=0.0

w2 window rolling_3:  64%|▋| 129/200 [00:14<00:08,  8.82round/s, val_excess=0.0

w2 window rolling_3:  65%|▋| 130/200 [00:15<00:07,  8.81round/s, val_excess=0.0

w2 window rolling_3:  65%|▋| 130/200 [00:15<00:07,  8.81round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 131/200 [00:15<00:07,  8.82round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 131/200 [00:15<00:07,  8.82round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 132/200 [00:15<00:07,  8.86round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 132/200 [00:15<00:07,  8.86round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 133/200 [00:15<00:07,  8.94round/s, val_excess=0.0

w2 window rolling_3:  66%|▋| 133/200 [00:15<00:07,  8.94round/s, val_excess=0.0

w2 window rolling_3:  67%|▋| 134/200 [00:15<00:07,  8.96round/s, val_excess=0.0

w2 window rolling_3:  67%|▋| 134/200 [00:15<00:07,  8.96round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 135/200 [00:15<00:07,  8.95round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 135/200 [00:15<00:07,  8.95round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 136/200 [00:15<00:07,  8.92round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 136/200 [00:15<00:07,  8.92round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 137/200 [00:15<00:07,  8.91round/s, val_excess=0.0

w2 window rolling_3:  68%|▋| 137/200 [00:15<00:07,  8.91round/s, val_excess=0.0

w2 window rolling_3:  69%|▋| 138/200 [00:15<00:06,  8.88round/s, val_excess=0.0

w2 window rolling_3:  69%|▋| 138/200 [00:15<00:06,  8.88round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 139/200 [00:16<00:06,  8.96round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 139/200 [00:16<00:06,  8.96round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 140/200 [00:16<00:06,  8.93round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 140/200 [00:16<00:06,  8.93round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 141/200 [00:16<00:06,  8.99round/s, val_excess=0.0

w2 window rolling_3:  70%|▋| 141/200 [00:16<00:06,  8.99round/s, val_excess=0.0

w2 window rolling_3:  71%|▋| 142/200 [00:16<00:06,  8.93round/s, val_excess=0.0

w2 window rolling_3:  71%|▋| 142/200 [00:16<00:06,  8.93round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 143/200 [00:16<00:06,  8.78round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 143/200 [00:16<00:06,  8.78round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 144/200 [00:16<00:06,  8.83round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 144/200 [00:16<00:06,  8.83round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 145/200 [00:16<00:06,  8.77round/s, val_excess=0.0

w2 window rolling_3:  72%|▋| 145/200 [00:16<00:06,  8.77round/s, val_excess=0.0

w2 window rolling_3:  73%|▋| 146/200 [00:16<00:06,  8.90round/s, val_excess=0.0

w2 window rolling_3:  73%|▋| 146/200 [00:16<00:06,  8.90round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 147/200 [00:16<00:05,  8.93round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 147/200 [00:16<00:05,  8.93round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 148/200 [00:17<00:05,  8.88round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 148/200 [00:17<00:05,  8.88round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 149/200 [00:17<00:05,  8.90round/s, val_excess=0.0

w2 window rolling_3:  74%|▋| 149/200 [00:17<00:05,  8.90round/s, val_excess=0.0

w2 window rolling_3:  75%|▊| 150/200 [00:17<00:05,  8.96round/s, val_excess=0.0

w2 window rolling_3:  75%|▊| 150/200 [00:17<00:05,  8.96round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 151/200 [00:17<00:05,  9.01round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 151/200 [00:17<00:05,  9.01round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 152/200 [00:17<00:05,  9.07round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 152/200 [00:17<00:05,  9.07round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 153/200 [00:17<00:05,  9.11round/s, val_excess=0.0

w2 window rolling_3:  76%|▊| 153/200 [00:17<00:05,  9.11round/s, val_excess=0.0

w2 window rolling_3:  77%|▊| 154/200 [00:17<00:05,  9.10round/s, val_excess=0.0

w2 window rolling_3:  77%|▊| 154/200 [00:17<00:05,  9.10round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 155/200 [00:17<00:04,  9.15round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 155/200 [00:17<00:04,  9.15round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 156/200 [00:17<00:04,  9.11round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 156/200 [00:17<00:04,  9.11round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 157/200 [00:18<00:04,  9.07round/s, val_excess=0.0

w2 window rolling_3:  78%|▊| 157/200 [00:18<00:04,  9.07round/s, val_excess=0.0

w2 window rolling_3:  79%|▊| 158/200 [00:18<00:04,  8.98round/s, val_excess=0.0

w2 window rolling_3:  79%|▊| 158/200 [00:18<00:04,  8.98round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 159/200 [00:18<00:04,  8.99round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 159/200 [00:18<00:04,  8.99round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 160/200 [00:18<00:04,  9.02round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 160/200 [00:18<00:04,  9.02round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 161/200 [00:18<00:04,  9.03round/s, val_excess=0.0

w2 window rolling_3:  80%|▊| 161/200 [00:18<00:04,  9.03round/s, val_excess=0.0

w2 window rolling_3:  81%|▊| 162/200 [00:18<00:04,  9.01round/s, val_excess=0.0

w2 window rolling_3:  81%|▊| 162/200 [00:18<00:04,  9.01round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 163/200 [00:18<00:04,  8.60round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 163/200 [00:18<00:04,  8.60round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 164/200 [00:18<00:04,  8.18round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 164/200 [00:18<00:04,  8.18round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 165/200 [00:19<00:04,  8.06round/s, val_excess=0.0

w2 window rolling_3:  82%|▊| 165/200 [00:19<00:04,  8.06round/s, val_excess=0.0

w2 window rolling_3:  83%|▊| 166/200 [00:19<00:04,  7.91round/s, val_excess=0.0

w2 window rolling_3:  83%|▊| 166/200 [00:19<00:04,  7.91round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 167/200 [00:19<00:04,  8.15round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 167/200 [00:19<00:04,  8.15round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 168/200 [00:19<00:03,  8.42round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 168/200 [00:19<00:03,  8.42round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 169/200 [00:19<00:03,  8.62round/s, val_excess=0.0

w2 window rolling_3:  84%|▊| 169/200 [00:19<00:03,  8.62round/s, val_excess=0.0

w2 window rolling_3:  85%|▊| 170/200 [00:19<00:03,  8.78round/s, val_excess=0.0

w2 window rolling_3:  85%|▊| 170/200 [00:19<00:03,  8.78round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 171/200 [00:19<00:03,  8.86round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 171/200 [00:19<00:03,  8.86round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 172/200 [00:19<00:03,  8.92round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 172/200 [00:19<00:03,  8.92round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 173/200 [00:19<00:03,  8.94round/s, val_excess=0.0

w2 window rolling_3:  86%|▊| 173/200 [00:19<00:03,  8.94round/s, val_excess=0.0

w2 window rolling_3:  87%|▊| 174/200 [00:20<00:02,  8.95round/s, val_excess=0.0

w2 window rolling_3:  87%|▊| 174/200 [00:20<00:02,  8.95round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 175/200 [00:20<00:02,  8.87round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 175/200 [00:20<00:02,  8.87round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 176/200 [00:20<00:02,  8.42round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 176/200 [00:20<00:02,  8.42round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 177/200 [00:20<00:02,  7.69round/s, val_excess=0.0

w2 window rolling_3:  88%|▉| 177/200 [00:20<00:02,  7.69round/s, val_excess=0.0

w2 window rolling_3:  89%|▉| 178/200 [00:20<00:03,  7.27round/s, val_excess=0.0

w2 window rolling_3:  89%|▉| 178/200 [00:20<00:03,  7.27round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 179/200 [00:20<00:02,  7.60round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 179/200 [00:20<00:02,  7.60round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 180/200 [00:20<00:02,  7.93round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 180/200 [00:20<00:02,  7.93round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 181/200 [00:20<00:02,  8.17round/s, val_excess=0.0

w2 window rolling_3:  90%|▉| 181/200 [00:20<00:02,  8.17round/s, val_excess=0.0

w2 window rolling_3:  91%|▉| 182/200 [00:21<00:02,  8.47round/s, val_excess=0.0

w2 window rolling_3:  91%|▉| 182/200 [00:21<00:02,  8.47round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 183/200 [00:21<00:02,  8.13round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 183/200 [00:21<00:02,  8.13round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 184/200 [00:21<00:01,  8.45round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 184/200 [00:21<00:01,  8.45round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 185/200 [00:21<00:01,  8.64round/s, val_excess=0.0

w2 window rolling_3:  92%|▉| 185/200 [00:21<00:01,  8.64round/s, val_excess=0.0

w2 window rolling_3:  93%|▉| 186/200 [00:21<00:01,  8.74round/s, val_excess=0.0

w2 window rolling_3:  93%|▉| 186/200 [00:21<00:01,  8.74round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 187/200 [00:21<00:01,  8.81round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 187/200 [00:21<00:01,  8.81round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 188/200 [00:21<00:01,  8.95round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 188/200 [00:21<00:01,  8.95round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 189/200 [00:21<00:01,  9.02round/s, val_excess=0.0

w2 window rolling_3:  94%|▉| 189/200 [00:21<00:01,  9.02round/s, val_excess=0.0

w2 window rolling_3:  95%|▉| 190/200 [00:21<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_3:  95%|▉| 190/200 [00:21<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 191/200 [00:22<00:00,  9.06round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 191/200 [00:22<00:00,  9.06round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 192/200 [00:22<00:00,  8.97round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 192/200 [00:22<00:00,  8.97round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 193/200 [00:22<00:00,  9.03round/s, val_excess=0.0

w2 window rolling_3:  96%|▉| 193/200 [00:22<00:00,  9.03round/s, val_excess=0.0

w2 window rolling_3:  97%|▉| 194/200 [00:22<00:00,  9.08round/s, val_excess=0.0

w2 window rolling_3:  97%|▉| 194/200 [00:22<00:00,  9.08round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 195/200 [00:22<00:00,  9.10round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 195/200 [00:22<00:00,  9.10round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 196/200 [00:22<00:00,  9.07round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 196/200 [00:22<00:00,  9.07round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 197/200 [00:22<00:00,  9.09round/s, val_excess=0.0

w2 window rolling_3:  98%|▉| 197/200 [00:22<00:00,  9.09round/s, val_excess=0.0

w2 window rolling_3:  99%|▉| 198/200 [00:22<00:00,  9.13round/s, val_excess=0.0

w2 window rolling_3:  99%|▉| 198/200 [00:22<00:00,  9.13round/s, val_excess=0.0

w2 window rolling_3: 100%|▉| 199/200 [00:22<00:00,  9.20round/s, val_excess=0.0

w2 window rolling_3: 100%|▉| 199/200 [00:22<00:00,  9.20round/s, val_excess=0.0

w2 window rolling_3: 100%|█| 200/200 [00:23<00:00,  9.20round/s, val_excess=0.0

w2 window rolling_3: 100%|█| 200/200 [00:23<00:00,  9.20round/s, val_excess=0.0

w2 window rolling_3: 100%|█| 200/200 [00:23<00:00,  8.68round/s, val_excess=0.0

2026-07-06 17:27:17 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=2 feature_type=window fold=rolling_4

2026-07-06 17:27:37 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=2 feature_type=window fold=rolling_4 features=69

w2 window rolling_4:   0%|                          | 0/200 [00:00<?, ?round/s]

w2 window rolling_4:   0%|                  | 1/200 [00:00<00:21,  9.28round/s]

w2 window rolling_4:   0%| | 1/200 [00:00<00:21,  9.28round/s, val_excess=0.021

w2 window rolling_4:   1%| | 2/200 [00:00<00:21,  9.28round/s, val_excess=0.012

w2 window rolling_4:   2%| | 3/200 [00:00<00:18, 10.57round/s, val_excess=0.012

w2 window rolling_4:   2%| | 3/200 [00:00<00:18, 10.57round/s, val_excess=-0.00

w2 window rolling_4:   2%| | 4/200 [00:00<00:18, 10.57round/s, val_excess=0.020

w2 window rolling_4:   2%| | 5/200 [00:00<00:18, 10.44round/s, val_excess=0.020

w2 window rolling_4:   2%| | 5/200 [00:00<00:18, 10.44round/s, val_excess=0.011

w2 window rolling_4:   3%| | 6/200 [00:00<00:18, 10.44round/s, val_excess=0.032

w2 window rolling_4:   4%| | 7/200 [00:00<00:18, 10.18round/s, val_excess=0.032

w2 window rolling_4:   4%| | 7/200 [00:00<00:18, 10.18round/s, val_excess=0.025

w2 window rolling_4:   4%| | 8/200 [00:00<00:18, 10.18round/s, val_excess=0.020

w2 window rolling_4:   4%| | 9/200 [00:00<00:19,  9.88round/s, val_excess=0.020

w2 window rolling_4:   4%| | 9/200 [00:00<00:19,  9.88round/s, val_excess=0.025

w2 window rolling_4:   5%| | 10/200 [00:00<00:19,  9.85round/s, val_excess=0.02

w2 window rolling_4:   5%| | 10/200 [00:01<00:19,  9.85round/s, val_excess=0.01

w2 window rolling_4:   6%| | 11/200 [00:01<00:19,  9.77round/s, val_excess=0.01

w2 window rolling_4:   6%| | 11/200 [00:01<00:19,  9.77round/s, val_excess=0.02

w2 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.69round/s, val_excess=0.02

w2 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.69round/s, val_excess=0.01

w2 window rolling_4:   6%| | 13/200 [00:01<00:20,  8.97round/s, val_excess=0.01

w2 window rolling_4:   6%| | 13/200 [00:01<00:20,  8.97round/s, val_excess=0.01

w2 window rolling_4:   7%| | 14/200 [00:01<00:21,  8.80round/s, val_excess=0.01

w2 window rolling_4:   7%| | 14/200 [00:01<00:21,  8.80round/s, val_excess=0.02

w2 window rolling_4:   8%| | 15/200 [00:01<00:20,  8.98round/s, val_excess=0.02

w2 window rolling_4:   8%| | 15/200 [00:01<00:20,  8.98round/s, val_excess=0.01

w2 window rolling_4:   8%| | 16/200 [00:01<00:20,  9.05round/s, val_excess=0.01

w2 window rolling_4:   8%| | 16/200 [00:01<00:20,  9.05round/s, val_excess=0.01

w2 window rolling_4:   8%| | 17/200 [00:01<00:20,  8.97round/s, val_excess=0.01

w2 window rolling_4:   8%| | 17/200 [00:01<00:20,  8.97round/s, val_excess=0.02

w2 window rolling_4:   9%| | 18/200 [00:01<00:20,  9.05round/s, val_excess=0.02

w2 window rolling_4:   9%| | 18/200 [00:01<00:20,  9.05round/s, val_excess=0.02

w2 window rolling_4:  10%| | 19/200 [00:02<00:19,  9.13round/s, val_excess=0.02

w2 window rolling_4:  10%| | 19/200 [00:02<00:19,  9.13round/s, val_excess=0.02

w2 window rolling_4:  10%| | 20/200 [00:02<00:20,  8.79round/s, val_excess=0.02

w2 window rolling_4:  10%| | 20/200 [00:02<00:20,  8.79round/s, val_excess=0.02

w2 window rolling_4:  10%| | 21/200 [00:02<00:21,  8.52round/s, val_excess=0.02

w2 window rolling_4:  10%| | 21/200 [00:02<00:21,  8.52round/s, val_excess=0.02

w2 window rolling_4:  11%| | 22/200 [00:02<00:21,  8.28round/s, val_excess=0.02

w2 window rolling_4:  11%| | 22/200 [00:02<00:21,  8.28round/s, val_excess=0.02

w2 window rolling_4:  12%| | 23/200 [00:02<00:21,  8.24round/s, val_excess=0.02

w2 window rolling_4:  12%| | 23/200 [00:02<00:21,  8.24round/s, val_excess=0.02

w2 window rolling_4:  12%| | 24/200 [00:02<00:21,  8.16round/s, val_excess=0.02

w2 window rolling_4:  12%| | 24/200 [00:02<00:21,  8.16round/s, val_excess=0.02

w2 window rolling_4:  12%|▏| 25/200 [00:02<00:21,  8.11round/s, val_excess=0.02

w2 window rolling_4:  12%|▏| 25/200 [00:02<00:21,  8.11round/s, val_excess=0.02

w2 window rolling_4:  13%|▏| 26/200 [00:02<00:21,  8.09round/s, val_excess=0.02

w2 window rolling_4:  13%|▏| 26/200 [00:02<00:21,  8.09round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 27/200 [00:03<00:21,  8.05round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 27/200 [00:03<00:21,  8.05round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 28/200 [00:03<00:21,  8.03round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 28/200 [00:03<00:21,  8.03round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 29/200 [00:03<00:21,  7.87round/s, val_excess=0.01

w2 window rolling_4:  14%|▏| 29/200 [00:03<00:21,  7.87round/s, val_excess=0.00

w2 window rolling_4:  15%|▏| 30/200 [00:03<00:23,  7.10round/s, val_excess=0.00

w2 window rolling_4:  15%|▏| 30/200 [00:03<00:23,  7.10round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 31/200 [00:03<00:22,  7.61round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 31/200 [00:03<00:22,  7.61round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 32/200 [00:03<00:21,  7.95round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 32/200 [00:03<00:21,  7.95round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 33/200 [00:03<00:20,  8.24round/s, val_excess=0.01

w2 window rolling_4:  16%|▏| 33/200 [00:03<00:20,  8.24round/s, val_excess=0.00

w2 window rolling_4:  17%|▏| 34/200 [00:03<00:19,  8.47round/s, val_excess=0.00

w2 window rolling_4:  17%|▏| 34/200 [00:03<00:19,  8.47round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 35/200 [00:03<00:19,  8.64round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 35/200 [00:03<00:19,  8.64round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 36/200 [00:04<00:18,  8.74round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 36/200 [00:04<00:18,  8.74round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 37/200 [00:04<00:18,  8.80round/s, val_excess=0.00

w2 window rolling_4:  18%|▏| 37/200 [00:04<00:18,  8.80round/s, val_excess=0.00

w2 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.85round/s, val_excess=0.00

w2 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.85round/s, val_excess=0.01

w2 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.90round/s, val_excess=0.01

w2 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.90round/s, val_excess=0.00

w2 window rolling_4:  20%|▏| 40/200 [00:04<00:17,  8.94round/s, val_excess=0.00

w2 window rolling_4:  20%|▏| 40/200 [00:04<00:17,  8.94round/s, val_excess=0.00

w2 window rolling_4:  20%|▏| 41/200 [00:04<00:17,  8.89round/s, val_excess=0.00

w2 window rolling_4:  20%|▏| 41/200 [00:04<00:17,  8.89round/s, val_excess=0.00

w2 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  8.91round/s, val_excess=0.00

w2 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  8.91round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  8.91round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  8.91round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 44/200 [00:04<00:17,  8.93round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 44/200 [00:05<00:17,  8.93round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 45/200 [00:05<00:17,  8.71round/s, val_excess=0.01

w2 window rolling_4:  22%|▏| 45/200 [00:05<00:17,  8.71round/s, val_excess=0.01

w2 window rolling_4:  23%|▏| 46/200 [00:05<00:17,  8.81round/s, val_excess=0.01

w2 window rolling_4:  23%|▏| 46/200 [00:05<00:17,  8.81round/s, val_excess=0.00

w2 window rolling_4:  24%|▏| 47/200 [00:05<00:17,  8.87round/s, val_excess=0.00

w2 window rolling_4:  24%|▏| 47/200 [00:05<00:17,  8.87round/s, val_excess=0.01

w2 window rolling_4:  24%|▏| 48/200 [00:05<00:17,  8.89round/s, val_excess=0.01

w2 window rolling_4:  24%|▏| 48/200 [00:05<00:17,  8.89round/s, val_excess=0.01

w2 window rolling_4:  24%|▏| 49/200 [00:05<00:17,  8.77round/s, val_excess=0.01

w2 window rolling_4:  24%|▏| 49/200 [00:05<00:17,  8.77round/s, val_excess=0.02

w2 window rolling_4:  25%|▎| 50/200 [00:05<00:17,  8.44round/s, val_excess=0.02

w2 window rolling_4:  25%|▎| 50/200 [00:05<00:17,  8.44round/s, val_excess=0.02

w2 window rolling_4:  26%|▎| 51/200 [00:05<00:18,  8.28round/s, val_excess=0.02

w2 window rolling_4:  26%|▎| 51/200 [00:05<00:18,  8.28round/s, val_excess=0.01

w2 window rolling_4:  26%|▎| 52/200 [00:05<00:18,  8.17round/s, val_excess=0.01

w2 window rolling_4:  26%|▎| 52/200 [00:05<00:18,  8.17round/s, val_excess=0.01

w2 window rolling_4:  26%|▎| 53/200 [00:06<00:18,  8.08round/s, val_excess=0.01

w2 window rolling_4:  26%|▎| 53/200 [00:06<00:18,  8.08round/s, val_excess=0.02

w2 window rolling_4:  27%|▎| 54/200 [00:06<00:18,  8.00round/s, val_excess=0.02

w2 window rolling_4:  27%|▎| 54/200 [00:06<00:18,  8.00round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 55/200 [00:06<00:18,  8.03round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 55/200 [00:06<00:18,  8.03round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 56/200 [00:06<00:18,  7.89round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 56/200 [00:06<00:18,  7.89round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 57/200 [00:06<00:18,  7.94round/s, val_excess=0.02

w2 window rolling_4:  28%|▎| 57/200 [00:06<00:18,  7.94round/s, val_excess=0.01

w2 window rolling_4:  29%|▎| 58/200 [00:06<00:17,  8.23round/s, val_excess=0.01

w2 window rolling_4:  29%|▎| 58/200 [00:06<00:17,  8.23round/s, val_excess=0.00

w2 window rolling_4:  30%|▎| 59/200 [00:06<00:16,  8.38round/s, val_excess=0.00

w2 window rolling_4:  30%|▎| 59/200 [00:06<00:16,  8.38round/s, val_excess=0.01

w2 window rolling_4:  30%|▎| 60/200 [00:06<00:17,  8.07round/s, val_excess=0.01

w2 window rolling_4:  30%|▎| 60/200 [00:06<00:17,  8.07round/s, val_excess=-0.0

w2 window rolling_4:  30%|▎| 61/200 [00:07<00:16,  8.21round/s, val_excess=-0.0

w2 window rolling_4:  30%|▎| 61/200 [00:07<00:16,  8.21round/s, val_excess=-0.0

w2 window rolling_4:  31%|▎| 62/200 [00:07<00:16,  8.37round/s, val_excess=-0.0

w2 window rolling_4:  31%|▎| 62/200 [00:07<00:16,  8.37round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 63/200 [00:07<00:16,  8.39round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 63/200 [00:07<00:16,  8.39round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 64/200 [00:07<00:15,  8.52round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 64/200 [00:07<00:15,  8.52round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 65/200 [00:07<00:15,  8.63round/s, val_excess=0.00

w2 window rolling_4:  32%|▎| 65/200 [00:07<00:15,  8.63round/s, val_excess=0.00

w2 window rolling_4:  33%|▎| 66/200 [00:07<00:15,  8.72round/s, val_excess=0.00

w2 window rolling_4:  33%|▎| 66/200 [00:07<00:15,  8.72round/s, val_excess=0.01

w2 window rolling_4:  34%|▎| 67/200 [00:07<00:15,  8.76round/s, val_excess=0.01

w2 window rolling_4:  34%|▎| 67/200 [00:07<00:15,  8.76round/s, val_excess=0.02

w2 window rolling_4:  34%|▎| 68/200 [00:07<00:14,  8.82round/s, val_excess=0.02

w2 window rolling_4:  34%|▎| 68/200 [00:07<00:14,  8.82round/s, val_excess=0.01

w2 window rolling_4:  34%|▎| 69/200 [00:07<00:14,  8.89round/s, val_excess=0.01

w2 window rolling_4:  34%|▎| 69/200 [00:07<00:14,  8.89round/s, val_excess=0.02

w2 window rolling_4:  35%|▎| 70/200 [00:08<00:14,  8.81round/s, val_excess=0.02

w2 window rolling_4:  35%|▎| 70/200 [00:08<00:14,  8.81round/s, val_excess=0.02

w2 window rolling_4:  36%|▎| 71/200 [00:08<00:14,  8.87round/s, val_excess=0.02

w2 window rolling_4:  36%|▎| 71/200 [00:08<00:14,  8.87round/s, val_excess=0.02

w2 window rolling_4:  36%|▎| 72/200 [00:08<00:14,  8.78round/s, val_excess=0.02

w2 window rolling_4:  36%|▎| 72/200 [00:08<00:14,  8.78round/s, val_excess=0.03

w2 window rolling_4:  36%|▎| 73/200 [00:08<00:14,  8.71round/s, val_excess=0.03

w2 window rolling_4:  36%|▎| 73/200 [00:08<00:14,  8.71round/s, val_excess=0.01

w2 window rolling_4:  37%|▎| 74/200 [00:08<00:14,  8.74round/s, val_excess=0.01

w2 window rolling_4:  37%|▎| 74/200 [00:08<00:14,  8.74round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 75/200 [00:08<00:14,  8.77round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 75/200 [00:08<00:14,  8.77round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 76/200 [00:08<00:14,  8.85round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 76/200 [00:08<00:14,  8.85round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 77/200 [00:08<00:13,  8.89round/s, val_excess=0.00

w2 window rolling_4:  38%|▍| 77/200 [00:08<00:13,  8.89round/s, val_excess=0.01

w2 window rolling_4:  39%|▍| 78/200 [00:08<00:13,  8.90round/s, val_excess=0.01

w2 window rolling_4:  39%|▍| 78/200 [00:08<00:13,  8.90round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 79/200 [00:09<00:13,  8.72round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 79/200 [00:09<00:13,  8.72round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 80/200 [00:09<00:13,  8.75round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 80/200 [00:09<00:13,  8.75round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 81/200 [00:09<00:13,  8.74round/s, val_excess=0.01

w2 window rolling_4:  40%|▍| 81/200 [00:09<00:13,  8.74round/s, val_excess=0.01

w2 window rolling_4:  41%|▍| 82/200 [00:09<00:13,  8.54round/s, val_excess=0.01

w2 window rolling_4:  41%|▍| 82/200 [00:09<00:13,  8.54round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 83/200 [00:09<00:14,  8.14round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 83/200 [00:09<00:14,  8.14round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 84/200 [00:09<00:14,  7.87round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 84/200 [00:09<00:14,  7.87round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 85/200 [00:09<00:14,  7.74round/s, val_excess=0.01

w2 window rolling_4:  42%|▍| 85/200 [00:09<00:14,  7.74round/s, val_excess=0.01

w2 window rolling_4:  43%|▍| 86/200 [00:10<00:14,  7.69round/s, val_excess=0.01

w2 window rolling_4:  43%|▍| 86/200 [00:10<00:14,  7.69round/s, val_excess=0.01

w2 window rolling_4:  44%|▍| 87/200 [00:10<00:14,  7.67round/s, val_excess=0.01

w2 window rolling_4:  44%|▍| 87/200 [00:10<00:14,  7.67round/s, val_excess=0.01

w2 window rolling_4:  44%|▍| 88/200 [00:10<00:14,  7.69round/s, val_excess=0.01

w2 window rolling_4:  44%|▍| 88/200 [00:10<00:14,  7.69round/s, val_excess=0.00

w2 window rolling_4:  44%|▍| 89/200 [00:10<00:13,  7.99round/s, val_excess=0.00

w2 window rolling_4:  44%|▍| 89/200 [00:10<00:13,  7.99round/s, val_excess=0.00

w2 window rolling_4:  45%|▍| 90/200 [00:10<00:13,  8.26round/s, val_excess=0.00

w2 window rolling_4:  45%|▍| 90/200 [00:10<00:13,  8.26round/s, val_excess=0.00

w2 window rolling_4:  46%|▍| 91/200 [00:10<00:12,  8.52round/s, val_excess=0.00

w2 window rolling_4:  46%|▍| 91/200 [00:10<00:12,  8.52round/s, val_excess=0.01

w2 window rolling_4:  46%|▍| 92/200 [00:10<00:12,  8.68round/s, val_excess=0.01

w2 window rolling_4:  46%|▍| 92/200 [00:10<00:12,  8.68round/s, val_excess=0.01

w2 window rolling_4:  46%|▍| 93/200 [00:10<00:12,  8.73round/s, val_excess=0.01

w2 window rolling_4:  46%|▍| 93/200 [00:10<00:12,  8.73round/s, val_excess=0.01

w2 window rolling_4:  47%|▍| 94/200 [00:10<00:12,  8.79round/s, val_excess=0.01

w2 window rolling_4:  47%|▍| 94/200 [00:10<00:12,  8.79round/s, val_excess=0.01

w2 window rolling_4:  48%|▍| 95/200 [00:11<00:11,  8.89round/s, val_excess=0.01

w2 window rolling_4:  48%|▍| 95/200 [00:11<00:11,  8.89round/s, val_excess=0.00

w2 window rolling_4:  48%|▍| 96/200 [00:11<00:11,  8.90round/s, val_excess=0.00

w2 window rolling_4:  48%|▍| 96/200 [00:11<00:11,  8.90round/s, val_excess=0.00

w2 window rolling_4:  48%|▍| 97/200 [00:11<00:11,  8.93round/s, val_excess=0.00

w2 window rolling_4:  48%|▍| 97/200 [00:11<00:11,  8.93round/s, val_excess=0.01

w2 window rolling_4:  49%|▍| 98/200 [00:11<00:11,  8.91round/s, val_excess=0.01

w2 window rolling_4:  49%|▍| 98/200 [00:11<00:11,  8.91round/s, val_excess=0.02

w2 window rolling_4:  50%|▍| 99/200 [00:11<00:11,  8.89round/s, val_excess=0.02

w2 window rolling_4:  50%|▍| 99/200 [00:11<00:11,  8.89round/s, val_excess=0.01

w2 window rolling_4:  50%|▌| 100/200 [00:11<00:11,  8.91round/s, val_excess=0.0

w2 window rolling_4:  50%|▌| 100/200 [00:11<00:11,  8.91round/s, val_excess=0.0

w2 window rolling_4:  50%|▌| 101/200 [00:11<00:11,  8.92round/s, val_excess=0.0

w2 window rolling_4:  50%|▌| 101/200 [00:11<00:11,  8.92round/s, val_excess=0.0

w2 window rolling_4:  51%|▌| 102/200 [00:11<00:10,  8.93round/s, val_excess=0.0

w2 window rolling_4:  51%|▌| 102/200 [00:11<00:10,  8.93round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  8.97round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  8.97round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 104/200 [00:12<00:10,  9.04round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 104/200 [00:12<00:10,  9.04round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 105/200 [00:12<00:10,  8.99round/s, val_excess=0.0

w2 window rolling_4:  52%|▌| 105/200 [00:12<00:10,  8.99round/s, val_excess=0.0

w2 window rolling_4:  53%|▌| 106/200 [00:12<00:10,  8.98round/s, val_excess=0.0

w2 window rolling_4:  53%|▌| 106/200 [00:12<00:10,  8.98round/s, val_excess=0.0

w2 window rolling_4:  54%|▌| 107/200 [00:12<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_4:  54%|▌| 107/200 [00:12<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_4:  54%|▌| 108/200 [00:12<00:10,  8.87round/s, val_excess=0.0

w2 window rolling_4:  54%|▌| 108/200 [00:12<00:10,  8.87round/s, val_excess=0.0

w2 window rolling_4:  55%|▌| 109/200 [00:12<00:10,  8.89round/s, val_excess=0.0

w2 window rolling_4:  55%|▌| 109/200 [00:12<00:10,  8.89round/s, val_excess=0.0

w2 window rolling_4:  55%|▌| 110/200 [00:12<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_4:  55%|▌| 110/200 [00:12<00:10,  8.92round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 111/200 [00:12<00:09,  8.96round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 111/200 [00:12<00:09,  8.96round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.07round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.07round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 113/200 [00:13<00:09,  9.13round/s, val_excess=0.0

w2 window rolling_4:  56%|▌| 113/200 [00:13<00:09,  9.13round/s, val_excess=0.0

w2 window rolling_4:  57%|▌| 114/200 [00:13<00:09,  9.16round/s, val_excess=0.0

w2 window rolling_4:  57%|▌| 114/200 [00:13<00:09,  9.16round/s, val_excess=0.0

w2 window rolling_4:  57%|▌| 115/200 [00:13<00:09,  9.18round/s, val_excess=0.0

w2 window rolling_4:  57%|▌| 115/200 [00:13<00:09,  9.18round/s, val_excess=0.0

w2 window rolling_4:  58%|▌| 116/200 [00:13<00:09,  9.15round/s, val_excess=0.0

w2 window rolling_4:  58%|▌| 116/200 [00:13<00:09,  9.15round/s, val_excess=0.0

w2 window rolling_4:  58%|▌| 117/200 [00:13<00:09,  9.15round/s, val_excess=0.0

w2 window rolling_4:  58%|▌| 117/200 [00:13<00:09,  9.15round/s, val_excess=0.0

w2 window rolling_4:  59%|▌| 118/200 [00:13<00:08,  9.15round/s, val_excess=0.0

w2 window rolling_4:  59%|▌| 118/200 [00:13<00:08,  9.15round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 119/200 [00:13<00:08,  9.20round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 119/200 [00:13<00:08,  9.20round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 120/200 [00:13<00:08,  9.25round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 120/200 [00:13<00:08,  9.25round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 121/200 [00:13<00:08,  9.19round/s, val_excess=0.0

w2 window rolling_4:  60%|▌| 121/200 [00:13<00:08,  9.19round/s, val_excess=0.0

w2 window rolling_4:  61%|▌| 122/200 [00:14<00:08,  9.23round/s, val_excess=0.0

w2 window rolling_4:  61%|▌| 122/200 [00:14<00:08,  9.23round/s, val_excess=0.0

w2 window rolling_4:  62%|▌| 123/200 [00:14<00:08,  9.26round/s, val_excess=0.0

w2 window rolling_4:  62%|▌| 123/200 [00:14<00:08,  9.26round/s, val_excess=0.0

w2 window rolling_4:  62%|▌| 124/200 [00:14<00:08,  9.34round/s, val_excess=0.0

w2 window rolling_4:  62%|▌| 124/200 [00:14<00:08,  9.34round/s, val_excess=0.0

w2 window rolling_4:  62%|▋| 125/200 [00:14<00:08,  9.34round/s, val_excess=0.0

w2 window rolling_4:  62%|▋| 125/200 [00:14<00:08,  9.34round/s, val_excess=0.0

w2 window rolling_4:  63%|▋| 126/200 [00:14<00:08,  9.23round/s, val_excess=0.0

w2 window rolling_4:  63%|▋| 126/200 [00:14<00:08,  9.23round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 127/200 [00:14<00:07,  9.15round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 127/200 [00:14<00:07,  9.15round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 128/200 [00:14<00:07,  9.10round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 128/200 [00:14<00:07,  9.10round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 129/200 [00:14<00:07,  9.15round/s, val_excess=0.0

w2 window rolling_4:  64%|▋| 129/200 [00:14<00:07,  9.15round/s, val_excess=0.0

w2 window rolling_4:  65%|▋| 130/200 [00:14<00:07,  9.17round/s, val_excess=0.0

w2 window rolling_4:  65%|▋| 130/200 [00:14<00:07,  9.17round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 131/200 [00:14<00:07,  9.18round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 131/200 [00:15<00:07,  9.18round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 132/200 [00:15<00:07,  9.17round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 132/200 [00:15<00:07,  9.17round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 133/200 [00:15<00:07,  9.24round/s, val_excess=0.0

w2 window rolling_4:  66%|▋| 133/200 [00:15<00:07,  9.24round/s, val_excess=0.0

w2 window rolling_4:  67%|▋| 134/200 [00:15<00:07,  9.21round/s, val_excess=0.0

w2 window rolling_4:  67%|▋| 134/200 [00:15<00:07,  9.21round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 135/200 [00:15<00:07,  9.14round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 135/200 [00:15<00:07,  9.14round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 136/200 [00:15<00:06,  9.17round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 136/200 [00:15<00:06,  9.17round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 137/200 [00:15<00:06,  9.19round/s, val_excess=0.0

w2 window rolling_4:  68%|▋| 137/200 [00:15<00:06,  9.19round/s, val_excess=0.0

w2 window rolling_4:  69%|▋| 138/200 [00:15<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  69%|▋| 138/200 [00:15<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 139/200 [00:15<00:06,  9.08round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 139/200 [00:15<00:06,  9.08round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 140/200 [00:15<00:06,  9.10round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 140/200 [00:15<00:06,  9.10round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 141/200 [00:16<00:06,  9.09round/s, val_excess=0.0

w2 window rolling_4:  70%|▋| 141/200 [00:16<00:06,  9.09round/s, val_excess=0.0

w2 window rolling_4:  71%|▋| 142/200 [00:16<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  71%|▋| 142/200 [00:16<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 143/200 [00:16<00:06,  9.15round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 143/200 [00:16<00:06,  9.15round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 144/200 [00:16<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 144/200 [00:16<00:06,  9.16round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 145/200 [00:16<00:06,  9.08round/s, val_excess=0.0

w2 window rolling_4:  72%|▋| 145/200 [00:16<00:06,  9.08round/s, val_excess=0.0

w2 window rolling_4:  73%|▋| 146/200 [00:16<00:05,  9.12round/s, val_excess=0.0

w2 window rolling_4:  73%|▋| 146/200 [00:16<00:05,  9.12round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 147/200 [00:16<00:05,  9.13round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 147/200 [00:16<00:05,  9.13round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 148/200 [00:16<00:05,  9.08round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 148/200 [00:16<00:05,  9.08round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 149/200 [00:16<00:05,  9.09round/s, val_excess=0.0

w2 window rolling_4:  74%|▋| 149/200 [00:16<00:05,  9.09round/s, val_excess=0.0

w2 window rolling_4:  75%|▊| 150/200 [00:17<00:05,  9.07round/s, val_excess=0.0

w2 window rolling_4:  75%|▊| 150/200 [00:17<00:05,  9.07round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 151/200 [00:17<00:05,  9.04round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 151/200 [00:17<00:05,  9.04round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 152/200 [00:17<00:05,  9.01round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 152/200 [00:17<00:05,  9.01round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 153/200 [00:17<00:05,  8.99round/s, val_excess=0.0

w2 window rolling_4:  76%|▊| 153/200 [00:17<00:05,  8.99round/s, val_excess=0.0

w2 window rolling_4:  77%|▊| 154/200 [00:17<00:05,  8.96round/s, val_excess=0.0

w2 window rolling_4:  77%|▊| 154/200 [00:17<00:05,  8.96round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 155/200 [00:17<00:05,  8.90round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 155/200 [00:17<00:05,  8.90round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 156/200 [00:17<00:04,  9.04round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 156/200 [00:17<00:04,  9.04round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 157/200 [00:17<00:04,  9.05round/s, val_excess=0.0

w2 window rolling_4:  78%|▊| 157/200 [00:17<00:04,  9.05round/s, val_excess=0.0

w2 window rolling_4:  79%|▊| 158/200 [00:17<00:04,  9.14round/s, val_excess=0.0

w2 window rolling_4:  79%|▊| 158/200 [00:17<00:04,  9.14round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 159/200 [00:18<00:04,  9.12round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 159/200 [00:18<00:04,  9.12round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 160/200 [00:18<00:04,  9.06round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 160/200 [00:18<00:04,  9.06round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 161/200 [00:18<00:04,  8.96round/s, val_excess=0.0

w2 window rolling_4:  80%|▊| 161/200 [00:18<00:04,  8.96round/s, val_excess=0.0

w2 window rolling_4:  81%|▊| 162/200 [00:18<00:04,  8.94round/s, val_excess=0.0

w2 window rolling_4:  81%|▊| 162/200 [00:18<00:04,  8.94round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 163/200 [00:18<00:04,  8.97round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 163/200 [00:18<00:04,  8.97round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 164/200 [00:18<00:03,  9.02round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 164/200 [00:18<00:03,  9.02round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 165/200 [00:18<00:03,  9.12round/s, val_excess=0.0

w2 window rolling_4:  82%|▊| 165/200 [00:18<00:03,  9.12round/s, val_excess=0.0

w2 window rolling_4:  83%|▊| 166/200 [00:18<00:03,  9.00round/s, val_excess=0.0

w2 window rolling_4:  83%|▊| 166/200 [00:18<00:03,  9.00round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 167/200 [00:18<00:03,  9.04round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 167/200 [00:18<00:03,  9.04round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 168/200 [00:19<00:03,  9.00round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 168/200 [00:19<00:03,  9.00round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 169/200 [00:19<00:03,  8.99round/s, val_excess=0.0

w2 window rolling_4:  84%|▊| 169/200 [00:19<00:03,  8.99round/s, val_excess=0.0

w2 window rolling_4:  85%|▊| 170/200 [00:19<00:03,  8.98round/s, val_excess=0.0

w2 window rolling_4:  85%|▊| 170/200 [00:19<00:03,  8.98round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 171/200 [00:19<00:03,  8.95round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 171/200 [00:19<00:03,  8.95round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 172/200 [00:19<00:03,  8.94round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 172/200 [00:19<00:03,  8.94round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 173/200 [00:19<00:03,  8.97round/s, val_excess=0.0

w2 window rolling_4:  86%|▊| 173/200 [00:19<00:03,  8.97round/s, val_excess=0.0

w2 window rolling_4:  87%|▊| 174/200 [00:19<00:02,  9.03round/s, val_excess=0.0

w2 window rolling_4:  87%|▊| 174/200 [00:19<00:02,  9.03round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 175/200 [00:19<00:02,  8.98round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 175/200 [00:19<00:02,  8.98round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 176/200 [00:19<00:02,  9.06round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 176/200 [00:19<00:02,  9.06round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 177/200 [00:20<00:02,  9.05round/s, val_excess=0.0

w2 window rolling_4:  88%|▉| 177/200 [00:20<00:02,  9.05round/s, val_excess=0.0

w2 window rolling_4:  89%|▉| 178/200 [00:20<00:02,  9.06round/s, val_excess=0.0

w2 window rolling_4:  89%|▉| 178/200 [00:20<00:02,  9.06round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 179/200 [00:20<00:02,  9.08round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 179/200 [00:20<00:02,  9.08round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 180/200 [00:20<00:02,  9.03round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 180/200 [00:20<00:02,  9.03round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 181/200 [00:20<00:02,  9.01round/s, val_excess=0.0

w2 window rolling_4:  90%|▉| 181/200 [00:20<00:02,  9.01round/s, val_excess=0.0

w2 window rolling_4:  91%|▉| 182/200 [00:20<00:02,  8.96round/s, val_excess=0.0

w2 window rolling_4:  91%|▉| 182/200 [00:20<00:02,  8.96round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 183/200 [00:20<00:01,  9.00round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 183/200 [00:20<00:01,  9.00round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 184/200 [00:20<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 184/200 [00:20<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 185/200 [00:20<00:01,  9.10round/s, val_excess=0.0

w2 window rolling_4:  92%|▉| 185/200 [00:20<00:01,  9.10round/s, val_excess=0.0

w2 window rolling_4:  93%|▉| 186/200 [00:21<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_4:  93%|▉| 186/200 [00:21<00:01,  9.06round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 187/200 [00:21<00:01,  9.07round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 187/200 [00:21<00:01,  9.07round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 188/200 [00:21<00:01,  8.99round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 188/200 [00:21<00:01,  8.99round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 189/200 [00:21<00:01,  8.97round/s, val_excess=0.0

w2 window rolling_4:  94%|▉| 189/200 [00:21<00:01,  8.97round/s, val_excess=0.0

w2 window rolling_4:  95%|▉| 190/200 [00:21<00:01,  9.01round/s, val_excess=0.0

w2 window rolling_4:  95%|▉| 190/200 [00:21<00:01,  9.01round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 191/200 [00:21<00:01,  8.97round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 191/200 [00:21<00:01,  8.97round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 192/200 [00:21<00:00,  8.97round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 192/200 [00:21<00:00,  8.97round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 193/200 [00:21<00:00,  9.02round/s, val_excess=0.0

w2 window rolling_4:  96%|▉| 193/200 [00:21<00:00,  9.02round/s, val_excess=0.0

w2 window rolling_4:  97%|▉| 194/200 [00:21<00:00,  8.98round/s, val_excess=0.0

w2 window rolling_4:  97%|▉| 194/200 [00:21<00:00,  8.98round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 195/200 [00:22<00:00,  8.96round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 195/200 [00:22<00:00,  8.96round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 196/200 [00:22<00:00,  8.88round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 196/200 [00:22<00:00,  8.88round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 197/200 [00:22<00:00,  8.76round/s, val_excess=0.0

w2 window rolling_4:  98%|▉| 197/200 [00:22<00:00,  8.76round/s, val_excess=0.0

w2 window rolling_4:  99%|▉| 198/200 [00:22<00:00,  8.66round/s, val_excess=0.0

w2 window rolling_4:  99%|▉| 198/200 [00:22<00:00,  8.66round/s, val_excess=0.0

w2 window rolling_4: 100%|▉| 199/200 [00:22<00:00,  8.68round/s, val_excess=0.0

w2 window rolling_4: 100%|▉| 199/200 [00:22<00:00,  8.68round/s, val_excess=0.0

w2 window rolling_4: 100%|█| 200/200 [00:22<00:00,  8.68round/s, val_excess=0.0

w2 window rolling_4: 100%|█| 200/200 [00:22<00:00,  8.68round/s, val_excess=0.0

w2 window rolling_4: 100%|█| 200/200 [00:22<00:00,  8.83round/s, val_excess=0.0

2026-07-06 17:28:00 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=4 feature_type=window fold=rolling_1

2026-07-06 17:28:20 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=4 feature_type=window fold=rolling_1 features=69

w4 window rolling_1:   0%|                          | 0/200 [00:00<?, ?round/s]

w4 window rolling_1:   0%|                  | 1/200 [00:00<00:20,  9.55round/s]

w4 window rolling_1:   0%| | 1/200 [00:00<00:20,  9.55round/s, val_excess=-0.00

w4 window rolling_1:   1%| | 2/200 [00:00<00:20,  9.55round/s, val_excess=0.014

w4 window rolling_1:   2%| | 3/200 [00:00<00:17, 11.44round/s, val_excess=0.014

w4 window rolling_1:   2%| | 3/200 [00:00<00:17, 11.44round/s, val_excess=0.013

w4 window rolling_1:   2%| | 4/200 [00:00<00:17, 11.44round/s, val_excess=-0.00

w4 window rolling_1:   2%| | 5/200 [00:00<00:17, 11.21round/s, val_excess=-0.00

w4 window rolling_1:   2%| | 5/200 [00:00<00:17, 11.21round/s, val_excess=0.008

w4 window rolling_1:   3%| | 6/200 [00:00<00:17, 11.21round/s, val_excess=0.016

w4 window rolling_1:   4%| | 7/200 [00:00<00:18, 10.72round/s, val_excess=0.016

w4 window rolling_1:   4%| | 7/200 [00:00<00:18, 10.72round/s, val_excess=0.003

w4 window rolling_1:   4%| | 8/200 [00:00<00:17, 10.72round/s, val_excess=0.004

w4 window rolling_1:   4%| | 9/200 [00:00<00:17, 10.62round/s, val_excess=0.004

w4 window rolling_1:   4%| | 9/200 [00:00<00:17, 10.62round/s, val_excess=0.003

w4 window rolling_1:   5%| | 10/200 [00:00<00:17, 10.62round/s, val_excess=0.01

w4 window rolling_1:   6%| | 11/200 [00:01<00:17, 10.52round/s, val_excess=0.01

w4 window rolling_1:   6%| | 11/200 [00:01<00:17, 10.52round/s, val_excess=0.00

w4 window rolling_1:   6%| | 12/200 [00:01<00:17, 10.52round/s, val_excess=0.00

w4 window rolling_1:   6%| | 13/200 [00:01<00:17, 10.40round/s, val_excess=0.00

w4 window rolling_1:   6%| | 13/200 [00:01<00:17, 10.40round/s, val_excess=0.00

w4 window rolling_1:   7%| | 14/200 [00:01<00:17, 10.40round/s, val_excess=0.01

w4 window rolling_1:   8%| | 15/200 [00:01<00:17, 10.31round/s, val_excess=0.01

w4 window rolling_1:   8%| | 15/200 [00:01<00:17, 10.31round/s, val_excess=0.01

w4 window rolling_1:   8%| | 16/200 [00:01<00:17, 10.31round/s, val_excess=0.01

w4 window rolling_1:   8%| | 17/200 [00:01<00:17, 10.18round/s, val_excess=0.01

w4 window rolling_1:   8%| | 17/200 [00:01<00:17, 10.18round/s, val_excess=0.01

w4 window rolling_1:   9%| | 18/200 [00:01<00:17, 10.18round/s, val_excess=0.01

w4 window rolling_1:  10%| | 19/200 [00:01<00:17, 10.22round/s, val_excess=0.01

w4 window rolling_1:  10%| | 19/200 [00:01<00:17, 10.22round/s, val_excess=0.01

w4 window rolling_1:  10%| | 20/200 [00:01<00:17, 10.22round/s, val_excess=0.01

w4 window rolling_1:  10%| | 21/200 [00:02<00:17, 10.28round/s, val_excess=0.01

w4 window rolling_1:  10%| | 21/200 [00:02<00:17, 10.28round/s, val_excess=0.02

w4 window rolling_1:  11%| | 22/200 [00:02<00:17, 10.28round/s, val_excess=0.02

w4 window rolling_1:  12%| | 23/200 [00:02<00:17, 10.26round/s, val_excess=0.02

w4 window rolling_1:  12%| | 23/200 [00:02<00:17, 10.26round/s, val_excess=0.01

w4 window rolling_1:  12%| | 24/200 [00:02<00:17, 10.26round/s, val_excess=0.01

w4 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w4 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.30round/s, val_excess=0.01

w4 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.30round/s, val_excess=0.00

w4 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.21round/s, val_excess=0.00

w4 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.21round/s, val_excess=0.01

w4 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.21round/s, val_excess=0.02

w4 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.12round/s, val_excess=0.02

w4 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.12round/s, val_excess=0.02

w4 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.12round/s, val_excess=0.02

w4 window rolling_1:  16%|▏| 31/200 [00:03<00:16, 10.08round/s, val_excess=0.02

w4 window rolling_1:  16%|▏| 31/200 [00:03<00:16, 10.08round/s, val_excess=0.03

w4 window rolling_1:  16%|▏| 32/200 [00:03<00:16, 10.08round/s, val_excess=0.03

w4 window rolling_1:  16%|▏| 33/200 [00:03<00:16, 10.07round/s, val_excess=0.03

w4 window rolling_1:  16%|▏| 33/200 [00:03<00:16, 10.07round/s, val_excess=0.02

w4 window rolling_1:  17%|▏| 34/200 [00:03<00:16, 10.07round/s, val_excess=0.03

w4 window rolling_1:  18%|▏| 35/200 [00:03<00:16, 10.17round/s, val_excess=0.03

w4 window rolling_1:  18%|▏| 35/200 [00:03<00:16, 10.17round/s, val_excess=0.03

w4 window rolling_1:  18%|▏| 36/200 [00:03<00:16, 10.17round/s, val_excess=0.03

w4 window rolling_1:  18%|▏| 37/200 [00:03<00:16, 10.12round/s, val_excess=0.03

w4 window rolling_1:  18%|▏| 37/200 [00:03<00:16, 10.12round/s, val_excess=0.02

w4 window rolling_1:  19%|▏| 38/200 [00:03<00:16, 10.12round/s, val_excess=0.02

w4 window rolling_1:  20%|▏| 39/200 [00:03<00:15, 10.12round/s, val_excess=0.02

w4 window rolling_1:  20%|▏| 39/200 [00:03<00:15, 10.12round/s, val_excess=0.02

w4 window rolling_1:  20%|▏| 40/200 [00:03<00:15, 10.12round/s, val_excess=0.02

w4 window rolling_1:  20%|▏| 41/200 [00:03<00:15, 10.13round/s, val_excess=0.02

w4 window rolling_1:  20%|▏| 41/200 [00:03<00:15, 10.13round/s, val_excess=0.02

w4 window rolling_1:  21%|▏| 42/200 [00:04<00:15, 10.13round/s, val_excess=0.02

w4 window rolling_1:  22%|▏| 43/200 [00:04<00:15, 10.21round/s, val_excess=0.02

w4 window rolling_1:  22%|▏| 43/200 [00:04<00:15, 10.21round/s, val_excess=0.02

w4 window rolling_1:  22%|▏| 44/200 [00:04<00:15, 10.21round/s, val_excess=0.00

w4 window rolling_1:  22%|▏| 45/200 [00:04<00:15, 10.17round/s, val_excess=0.00

w4 window rolling_1:  22%|▏| 45/200 [00:04<00:15, 10.17round/s, val_excess=0.00

w4 window rolling_1:  23%|▏| 46/200 [00:04<00:15, 10.17round/s, val_excess=0.00

w4 window rolling_1:  24%|▏| 47/200 [00:04<00:15, 10.07round/s, val_excess=0.00

w4 window rolling_1:  24%|▏| 47/200 [00:04<00:15, 10.07round/s, val_excess=0.01

w4 window rolling_1:  24%|▏| 48/200 [00:04<00:15, 10.07round/s, val_excess=0.01

w4 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.10round/s, val_excess=0.01

w4 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.10round/s, val_excess=0.01

w4 window rolling_1:  25%|▎| 50/200 [00:04<00:14, 10.10round/s, val_excess=0.01

w4 window rolling_1:  26%|▎| 51/200 [00:04<00:14, 10.11round/s, val_excess=0.01

w4 window rolling_1:  26%|▎| 51/200 [00:04<00:14, 10.11round/s, val_excess=0.01

w4 window rolling_1:  26%|▎| 52/200 [00:05<00:14, 10.11round/s, val_excess=0.01

w4 window rolling_1:  26%|▎| 53/200 [00:05<00:14, 10.03round/s, val_excess=0.01

w4 window rolling_1:  26%|▎| 53/200 [00:05<00:14, 10.03round/s, val_excess=0.01

w4 window rolling_1:  27%|▎| 54/200 [00:05<00:14, 10.03round/s, val_excess=0.00

w4 window rolling_1:  28%|▎| 55/200 [00:05<00:14, 10.05round/s, val_excess=0.00

w4 window rolling_1:  28%|▎| 55/200 [00:05<00:14, 10.05round/s, val_excess=0.01

w4 window rolling_1:  28%|▎| 56/200 [00:05<00:14, 10.05round/s, val_excess=0.00

w4 window rolling_1:  28%|▎| 57/200 [00:05<00:14, 10.00round/s, val_excess=0.00

w4 window rolling_1:  28%|▎| 57/200 [00:05<00:14, 10.00round/s, val_excess=0.00

w4 window rolling_1:  29%|▎| 58/200 [00:05<00:14, 10.00round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 59/200 [00:05<00:14,  9.94round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 59/200 [00:05<00:14,  9.94round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 60/200 [00:05<00:15,  9.30round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 60/200 [00:05<00:15,  9.30round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 61/200 [00:06<00:14,  9.43round/s, val_excess=0.00

w4 window rolling_1:  30%|▎| 61/200 [00:06<00:14,  9.43round/s, val_excess=0.00

w4 window rolling_1:  31%|▎| 62/200 [00:06<00:14,  9.50round/s, val_excess=0.00

w4 window rolling_1:  31%|▎| 62/200 [00:06<00:14,  9.50round/s, val_excess=0.00

w4 window rolling_1:  32%|▎| 63/200 [00:06<00:14,  9.50round/s, val_excess=0.01

w4 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.17round/s, val_excess=0.01

w4 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.17round/s, val_excess=0.01

w4 window rolling_1:  32%|▎| 65/200 [00:06<00:15,  8.84round/s, val_excess=0.01

w4 window rolling_1:  32%|▎| 65/200 [00:06<00:15,  8.84round/s, val_excess=0.01

w4 window rolling_1:  33%|▎| 66/200 [00:06<00:15,  8.84round/s, val_excess=0.01

w4 window rolling_1:  34%|▎| 67/200 [00:06<00:14,  9.20round/s, val_excess=0.01

w4 window rolling_1:  34%|▎| 67/200 [00:06<00:14,  9.20round/s, val_excess=0.01

w4 window rolling_1:  34%|▎| 68/200 [00:06<00:14,  9.20round/s, val_excess=0.01

w4 window rolling_1:  34%|▎| 69/200 [00:06<00:13,  9.51round/s, val_excess=0.01

w4 window rolling_1:  34%|▎| 69/200 [00:06<00:13,  9.51round/s, val_excess=0.01

w4 window rolling_1:  35%|▎| 70/200 [00:06<00:13,  9.58round/s, val_excess=0.01

w4 window rolling_1:  35%|▎| 70/200 [00:06<00:13,  9.58round/s, val_excess=0.00

w4 window rolling_1:  36%|▎| 71/200 [00:07<00:13,  9.64round/s, val_excess=0.00

w4 window rolling_1:  36%|▎| 71/200 [00:07<00:13,  9.64round/s, val_excess=0.00

w4 window rolling_1:  36%|▎| 72/200 [00:07<00:13,  9.64round/s, val_excess=0.00

w4 window rolling_1:  36%|▎| 73/200 [00:07<00:12,  9.83round/s, val_excess=0.00

w4 window rolling_1:  36%|▎| 73/200 [00:07<00:12,  9.83round/s, val_excess=0.01

w4 window rolling_1:  37%|▎| 74/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w4 window rolling_1:  37%|▎| 74/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 75/200 [00:07<00:12,  9.86round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 75/200 [00:07<00:12,  9.86round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 76/200 [00:07<00:12,  9.86round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 76/200 [00:07<00:12,  9.86round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 77/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w4 window rolling_1:  38%|▍| 77/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w4 window rolling_1:  39%|▍| 78/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w4 window rolling_1:  40%|▍| 79/200 [00:07<00:12,  9.88round/s, val_excess=0.01

w4 window rolling_1:  40%|▍| 79/200 [00:07<00:12,  9.88round/s, val_excess=0.01

w4 window rolling_1:  40%|▍| 80/200 [00:07<00:12,  9.88round/s, val_excess=0.01

w4 window rolling_1:  40%|▍| 81/200 [00:08<00:11,  9.98round/s, val_excess=0.01

w4 window rolling_1:  40%|▍| 81/200 [00:08<00:11,  9.98round/s, val_excess=0.01

w4 window rolling_1:  41%|▍| 82/200 [00:08<00:11,  9.96round/s, val_excess=0.01

w4 window rolling_1:  41%|▍| 82/200 [00:08<00:11,  9.96round/s, val_excess=0.02

w4 window rolling_1:  42%|▍| 83/200 [00:08<00:11,  9.96round/s, val_excess=0.02

w4 window rolling_1:  42%|▍| 84/200 [00:08<00:11, 10.08round/s, val_excess=0.02

w4 window rolling_1:  42%|▍| 84/200 [00:08<00:11, 10.08round/s, val_excess=0.01

w4 window rolling_1:  42%|▍| 85/200 [00:08<00:11, 10.08round/s, val_excess=0.01

w4 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.04round/s, val_excess=0.01

w4 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.04round/s, val_excess=0.01

w4 window rolling_1:  44%|▍| 87/200 [00:08<00:11, 10.04round/s, val_excess=0.02

w4 window rolling_1:  44%|▍| 88/200 [00:08<00:11, 10.02round/s, val_excess=0.02

w4 window rolling_1:  44%|▍| 88/200 [00:08<00:11, 10.02round/s, val_excess=0.01

w4 window rolling_1:  44%|▍| 89/200 [00:08<00:11, 10.02round/s, val_excess=0.01

w4 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.00round/s, val_excess=0.01

w4 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.00round/s, val_excess=0.01

w4 window rolling_1:  46%|▍| 91/200 [00:09<00:10, 10.00round/s, val_excess=0.01

w4 window rolling_1:  46%|▍| 92/200 [00:09<00:10, 10.07round/s, val_excess=0.01

w4 window rolling_1:  46%|▍| 92/200 [00:09<00:10, 10.07round/s, val_excess=0.01

w4 window rolling_1:  46%|▍| 93/200 [00:09<00:10, 10.07round/s, val_excess=0.01

w4 window rolling_1:  47%|▍| 94/200 [00:09<00:10, 10.03round/s, val_excess=0.01

w4 window rolling_1:  47%|▍| 94/200 [00:09<00:10, 10.03round/s, val_excess=0.01

w4 window rolling_1:  48%|▍| 95/200 [00:09<00:10, 10.03round/s, val_excess=0.01

w4 window rolling_1:  48%|▍| 96/200 [00:09<00:10,  9.95round/s, val_excess=0.01

w4 window rolling_1:  48%|▍| 96/200 [00:09<00:10,  9.95round/s, val_excess=0.01

w4 window rolling_1:  48%|▍| 97/200 [00:09<00:10,  9.92round/s, val_excess=0.01

w4 window rolling_1:  48%|▍| 97/200 [00:09<00:10,  9.92round/s, val_excess=0.01

w4 window rolling_1:  49%|▍| 98/200 [00:09<00:10,  9.88round/s, val_excess=0.01

w4 window rolling_1:  49%|▍| 98/200 [00:09<00:10,  9.88round/s, val_excess=0.01

w4 window rolling_1:  50%|▍| 99/200 [00:09<00:10,  9.88round/s, val_excess=0.01

w4 window rolling_1:  50%|▌| 100/200 [00:09<00:10,  9.94round/s, val_excess=0.0

w4 window rolling_1:  50%|▌| 100/200 [00:09<00:10,  9.94round/s, val_excess=0.0

w4 window rolling_1:  50%|▌| 101/200 [00:10<00:09,  9.93round/s, val_excess=0.0

w4 window rolling_1:  50%|▌| 101/200 [00:10<00:09,  9.93round/s, val_excess=0.0

w4 window rolling_1:  51%|▌| 102/200 [00:10<00:09,  9.91round/s, val_excess=0.0

w4 window rolling_1:  51%|▌| 102/200 [00:10<00:09,  9.91round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 103/200 [00:10<00:09,  9.81round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 103/200 [00:10<00:09,  9.81round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 104/200 [00:10<00:09,  9.82round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 104/200 [00:10<00:09,  9.82round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 105/200 [00:10<00:09,  9.77round/s, val_excess=0.0

w4 window rolling_1:  52%|▌| 105/200 [00:10<00:09,  9.77round/s, val_excess=0.0

w4 window rolling_1:  53%|▌| 106/200 [00:10<00:09,  9.80round/s, val_excess=0.0

w4 window rolling_1:  53%|▌| 106/200 [00:10<00:09,  9.80round/s, val_excess=0.0

w4 window rolling_1:  54%|▌| 107/200 [00:10<00:09,  9.77round/s, val_excess=0.0

w4 window rolling_1:  54%|▌| 107/200 [00:10<00:09,  9.77round/s, val_excess=0.0

w4 window rolling_1:  54%|▌| 108/200 [00:10<00:09,  9.74round/s, val_excess=0.0

w4 window rolling_1:  54%|▌| 108/200 [00:10<00:09,  9.74round/s, val_excess=0.0

w4 window rolling_1:  55%|▌| 109/200 [00:10<00:09,  9.74round/s, val_excess=0.0

w4 window rolling_1:  55%|▌| 110/200 [00:11<00:09,  9.96round/s, val_excess=0.0

w4 window rolling_1:  55%|▌| 110/200 [00:11<00:09,  9.96round/s, val_excess=0.0

w4 window rolling_1:  56%|▌| 111/200 [00:11<00:08,  9.97round/s, val_excess=0.0

w4 window rolling_1:  56%|▌| 111/200 [00:11<00:08,  9.97round/s, val_excess=0.0

w4 window rolling_1:  56%|▌| 112/200 [00:11<00:08,  9.97round/s, val_excess=0.0

w4 window rolling_1:  56%|▌| 113/200 [00:11<00:08,  9.98round/s, val_excess=0.0

w4 window rolling_1:  56%|▌| 113/200 [00:11<00:08,  9.98round/s, val_excess=0.0

w4 window rolling_1:  57%|▌| 114/200 [00:11<00:08,  9.97round/s, val_excess=0.0

w4 window rolling_1:  57%|▌| 114/200 [00:11<00:08,  9.97round/s, val_excess=0.0

w4 window rolling_1:  57%|▌| 115/200 [00:11<00:08,  9.92round/s, val_excess=0.0

w4 window rolling_1:  57%|▌| 115/200 [00:11<00:08,  9.92round/s, val_excess=0.0

w4 window rolling_1:  58%|▌| 116/200 [00:11<00:08,  9.71round/s, val_excess=0.0

w4 window rolling_1:  58%|▌| 116/200 [00:11<00:08,  9.71round/s, val_excess=0.0

w4 window rolling_1:  58%|▌| 117/200 [00:11<00:08,  9.60round/s, val_excess=0.0

w4 window rolling_1:  58%|▌| 117/200 [00:11<00:08,  9.60round/s, val_excess=0.0

w4 window rolling_1:  59%|▌| 118/200 [00:11<00:08,  9.51round/s, val_excess=0.0

w4 window rolling_1:  59%|▌| 118/200 [00:11<00:08,  9.51round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 119/200 [00:11<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 119/200 [00:11<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 120/200 [00:12<00:08,  9.37round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 120/200 [00:12<00:08,  9.37round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 121/200 [00:12<00:08,  9.39round/s, val_excess=0.0

w4 window rolling_1:  60%|▌| 121/200 [00:12<00:08,  9.39round/s, val_excess=0.0

w4 window rolling_1:  61%|▌| 122/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_1:  61%|▌| 122/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_1:  62%|▌| 123/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_1:  62%|▌| 124/200 [00:12<00:07,  9.68round/s, val_excess=0.0

w4 window rolling_1:  62%|▌| 124/200 [00:12<00:07,  9.68round/s, val_excess=0.0

w4 window rolling_1:  62%|▋| 125/200 [00:12<00:07,  9.75round/s, val_excess=0.0

w4 window rolling_1:  62%|▋| 125/200 [00:12<00:07,  9.75round/s, val_excess=0.0

w4 window rolling_1:  63%|▋| 126/200 [00:12<00:07,  9.76round/s, val_excess=0.0

w4 window rolling_1:  63%|▋| 126/200 [00:12<00:07,  9.76round/s, val_excess=0.0

w4 window rolling_1:  64%|▋| 127/200 [00:12<00:07,  9.77round/s, val_excess=0.0

w4 window rolling_1:  64%|▋| 127/200 [00:12<00:07,  9.77round/s, val_excess=0.0

w4 window rolling_1:  64%|▋| 128/200 [00:12<00:07,  9.71round/s, val_excess=0.0

w4 window rolling_1:  64%|▋| 128/200 [00:12<00:07,  9.71round/s, val_excess=0.0

w4 window rolling_1:  64%|▋| 129/200 [00:12<00:07,  9.71round/s, val_excess=0.0

w4 window rolling_1:  65%|▋| 130/200 [00:13<00:07,  9.82round/s, val_excess=0.0

w4 window rolling_1:  65%|▋| 130/200 [00:13<00:07,  9.82round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 131/200 [00:13<00:07,  9.78round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 131/200 [00:13<00:07,  9.78round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 132/200 [00:13<00:07,  9.66round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 132/200 [00:13<00:07,  9.66round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 133/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w4 window rolling_1:  66%|▋| 133/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w4 window rolling_1:  67%|▋| 134/200 [00:13<00:06,  9.81round/s, val_excess=0.0

w4 window rolling_1:  67%|▋| 134/200 [00:13<00:06,  9.81round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 135/200 [00:13<00:06,  9.80round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 135/200 [00:13<00:06,  9.80round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 136/200 [00:13<00:07,  8.84round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 136/200 [00:13<00:07,  8.84round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 137/200 [00:13<00:07,  8.23round/s, val_excess=0.0

w4 window rolling_1:  68%|▋| 137/200 [00:13<00:07,  8.23round/s, val_excess=0.0

w4 window rolling_1:  69%|▋| 138/200 [00:14<00:07,  7.78round/s, val_excess=0.0

w4 window rolling_1:  69%|▋| 138/200 [00:14<00:07,  7.78round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 139/200 [00:14<00:07,  7.88round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 139/200 [00:14<00:07,  7.88round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 140/200 [00:14<00:07,  8.12round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 140/200 [00:14<00:07,  8.12round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 141/200 [00:14<00:07,  8.31round/s, val_excess=0.0

w4 window rolling_1:  70%|▋| 141/200 [00:14<00:07,  8.31round/s, val_excess=0.0

w4 window rolling_1:  71%|▋| 142/200 [00:14<00:06,  8.52round/s, val_excess=0.0

w4 window rolling_1:  71%|▋| 142/200 [00:14<00:06,  8.52round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 143/200 [00:14<00:06,  8.59round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 143/200 [00:14<00:06,  8.59round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 144/200 [00:14<00:06,  8.65round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 144/200 [00:14<00:06,  8.65round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 145/200 [00:14<00:06,  8.92round/s, val_excess=0.0

w4 window rolling_1:  72%|▋| 145/200 [00:14<00:06,  8.92round/s, val_excess=0.0

w4 window rolling_1:  73%|▋| 146/200 [00:14<00:05,  9.18round/s, val_excess=0.0

w4 window rolling_1:  73%|▋| 146/200 [00:14<00:05,  9.18round/s, val_excess=0.0

w4 window rolling_1:  74%|▋| 147/200 [00:15<00:05,  9.36round/s, val_excess=0.0

w4 window rolling_1:  74%|▋| 147/200 [00:15<00:05,  9.36round/s, val_excess=0.0

w4 window rolling_1:  74%|▋| 148/200 [00:15<00:05,  9.36round/s, val_excess=0.0

w4 window rolling_1:  74%|▋| 149/200 [00:15<00:05,  9.74round/s, val_excess=0.0

w4 window rolling_1:  74%|▋| 149/200 [00:15<00:05,  9.74round/s, val_excess=0.0

w4 window rolling_1:  75%|▊| 150/200 [00:15<00:05,  9.79round/s, val_excess=0.0

w4 window rolling_1:  75%|▊| 150/200 [00:15<00:05,  9.79round/s, val_excess=0.0

w4 window rolling_1:  76%|▊| 151/200 [00:15<00:05,  9.79round/s, val_excess=0.0

w4 window rolling_1:  76%|▊| 152/200 [00:15<00:04,  9.91round/s, val_excess=0.0

w4 window rolling_1:  76%|▊| 152/200 [00:15<00:04,  9.91round/s, val_excess=0.0

w4 window rolling_1:  76%|▊| 153/200 [00:15<00:04,  9.92round/s, val_excess=0.0

w4 window rolling_1:  76%|▊| 153/200 [00:15<00:04,  9.92round/s, val_excess=0.0

w4 window rolling_1:  77%|▊| 154/200 [00:15<00:04,  9.92round/s, val_excess=0.0

w4 window rolling_1:  78%|▊| 155/200 [00:15<00:04,  9.96round/s, val_excess=0.0

w4 window rolling_1:  78%|▊| 155/200 [00:15<00:04,  9.96round/s, val_excess=0.0

w4 window rolling_1:  78%|▊| 156/200 [00:15<00:04,  9.94round/s, val_excess=0.0

w4 window rolling_1:  78%|▊| 156/200 [00:15<00:04,  9.94round/s, val_excess=0.0

w4 window rolling_1:  78%|▊| 157/200 [00:16<00:04,  9.94round/s, val_excess=0.0

w4 window rolling_1:  79%|▊| 158/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w4 window rolling_1:  79%|▊| 158/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w4 window rolling_1:  80%|▊| 159/200 [00:16<00:04, 10.05round/s, val_excess=0.0

w4 window rolling_1:  80%|▊| 160/200 [00:16<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  80%|▊| 160/200 [00:16<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  80%|▊| 161/200 [00:16<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  81%|▊| 162/200 [00:16<00:03, 10.10round/s, val_excess=0.0

w4 window rolling_1:  81%|▊| 162/200 [00:16<00:03, 10.10round/s, val_excess=0.0

w4 window rolling_1:  82%|▊| 163/200 [00:16<00:03, 10.10round/s, val_excess=0.0

w4 window rolling_1:  82%|▊| 164/200 [00:16<00:03, 10.07round/s, val_excess=0.0

w4 window rolling_1:  82%|▊| 164/200 [00:16<00:03, 10.07round/s, val_excess=0.0

w4 window rolling_1:  82%|▊| 165/200 [00:16<00:03, 10.07round/s, val_excess=0.0

w4 window rolling_1:  83%|▊| 166/200 [00:16<00:03, 10.12round/s, val_excess=0.0

w4 window rolling_1:  83%|▊| 166/200 [00:16<00:03, 10.12round/s, val_excess=0.0

w4 window rolling_1:  84%|▊| 167/200 [00:16<00:03, 10.12round/s, val_excess=0.0

w4 window rolling_1:  84%|▊| 168/200 [00:17<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  84%|▊| 168/200 [00:17<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  84%|▊| 169/200 [00:17<00:03, 10.03round/s, val_excess=0.0

w4 window rolling_1:  85%|▊| 170/200 [00:17<00:03,  9.96round/s, val_excess=0.0

w4 window rolling_1:  85%|▊| 170/200 [00:17<00:03,  9.96round/s, val_excess=0.0

w4 window rolling_1:  86%|▊| 171/200 [00:17<00:02,  9.95round/s, val_excess=0.0

w4 window rolling_1:  86%|▊| 171/200 [00:17<00:02,  9.95round/s, val_excess=0.0

w4 window rolling_1:  86%|▊| 172/200 [00:17<00:02,  9.95round/s, val_excess=0.0

w4 window rolling_1:  86%|▊| 173/200 [00:17<00:02, 10.04round/s, val_excess=0.0

w4 window rolling_1:  86%|▊| 173/200 [00:17<00:02, 10.04round/s, val_excess=0.0

w4 window rolling_1:  87%|▊| 174/200 [00:17<00:02, 10.04round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 175/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 175/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 176/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 176/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 177/200 [00:18<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_1:  88%|▉| 177/200 [00:18<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_1:  89%|▉| 178/200 [00:18<00:02,  9.86round/s, val_excess=0.0

w4 window rolling_1:  89%|▉| 178/200 [00:18<00:02,  9.86round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 179/200 [00:18<00:02,  9.88round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 179/200 [00:18<00:02,  9.88round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 180/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 180/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 181/200 [00:18<00:01,  9.89round/s, val_excess=0.0

w4 window rolling_1:  90%|▉| 181/200 [00:18<00:01,  9.89round/s, val_excess=0.0

w4 window rolling_1:  91%|▉| 182/200 [00:18<00:01,  9.88round/s, val_excess=0.0

w4 window rolling_1:  91%|▉| 182/200 [00:18<00:01,  9.88round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 183/200 [00:18<00:01,  9.58round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 183/200 [00:18<00:01,  9.58round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 184/200 [00:18<00:01,  9.35round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 184/200 [00:18<00:01,  9.35round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 185/200 [00:18<00:01,  9.44round/s, val_excess=0.0

w4 window rolling_1:  92%|▉| 185/200 [00:18<00:01,  9.44round/s, val_excess=0.0

w4 window rolling_1:  93%|▉| 186/200 [00:18<00:01,  9.60round/s, val_excess=0.0

w4 window rolling_1:  93%|▉| 186/200 [00:18<00:01,  9.60round/s, val_excess=0.0

w4 window rolling_1:  94%|▉| 187/200 [00:19<00:01,  9.65round/s, val_excess=0.0

w4 window rolling_1:  94%|▉| 187/200 [00:19<00:01,  9.65round/s, val_excess=0.0

w4 window rolling_1:  94%|▉| 188/200 [00:19<00:01,  9.65round/s, val_excess=0.0

w4 window rolling_1:  94%|▉| 189/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w4 window rolling_1:  94%|▉| 189/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w4 window rolling_1:  95%|▉| 190/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w4 window rolling_1:  95%|▉| 190/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 191/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 191/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 192/200 [00:19<00:00,  9.74round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 192/200 [00:19<00:00,  9.74round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 193/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w4 window rolling_1:  96%|▉| 193/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w4 window rolling_1:  97%|▉| 194/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 195/200 [00:19<00:00,  9.92round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 195/200 [00:19<00:00,  9.92round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 196/200 [00:19<00:00,  9.88round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 196/200 [00:19<00:00,  9.88round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 197/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w4 window rolling_1:  98%|▉| 197/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w4 window rolling_1:  99%|▉| 198/200 [00:20<00:00,  9.82round/s, val_excess=0.0

w4 window rolling_1:  99%|▉| 198/200 [00:20<00:00,  9.82round/s, val_excess=0.0

w4 window rolling_1: 100%|▉| 199/200 [00:20<00:00,  9.82round/s, val_excess=0.0

w4 window rolling_1: 100%|▉| 199/200 [00:20<00:00,  9.82round/s, val_excess=0.0

w4 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w4 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w4 window rolling_1: 100%|█| 200/200 [00:20<00:00,  9.82round/s, val_excess=0.0

2026-07-06 17:28:40 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=4 feature_type=window fold=rolling_2

2026-07-06 17:29:00 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=4 feature_type=window fold=rolling_2 features=69

w4 window rolling_2:   0%|                          | 0/200 [00:00<?, ?round/s]

w4 window rolling_2:   0%|                  | 1/200 [00:00<00:20,  9.53round/s]

w4 window rolling_2:   0%| | 1/200 [00:00<00:20,  9.53round/s, val_excess=0.013

w4 window rolling_2:   1%| | 2/200 [00:00<00:20,  9.53round/s, val_excess=0.025

w4 window rolling_2:   2%| | 3/200 [00:00<00:18, 10.91round/s, val_excess=0.025

w4 window rolling_2:   2%| | 3/200 [00:00<00:18, 10.91round/s, val_excess=0.015

w4 window rolling_2:   2%| | 4/200 [00:00<00:17, 10.91round/s, val_excess=0.016

w4 window rolling_2:   2%| | 5/200 [00:00<00:18, 10.62round/s, val_excess=0.016

w4 window rolling_2:   2%| | 5/200 [00:00<00:18, 10.62round/s, val_excess=0.012

w4 window rolling_2:   3%| | 6/200 [00:00<00:18, 10.62round/s, val_excess=0.015

w4 window rolling_2:   4%| | 7/200 [00:00<00:18, 10.19round/s, val_excess=0.015

w4 window rolling_2:   4%| | 7/200 [00:00<00:18, 10.19round/s, val_excess=0.015

w4 window rolling_2:   4%| | 8/200 [00:00<00:18, 10.19round/s, val_excess=0.014

w4 window rolling_2:   4%| | 9/200 [00:00<00:19,  9.95round/s, val_excess=0.014

w4 window rolling_2:   4%| | 9/200 [00:00<00:19,  9.95round/s, val_excess=0.013

w4 window rolling_2:   5%| | 10/200 [00:00<00:19,  9.92round/s, val_excess=0.01

w4 window rolling_2:   5%| | 10/200 [00:00<00:19,  9.92round/s, val_excess=0.02

w4 window rolling_2:   6%| | 11/200 [00:01<00:19,  9.86round/s, val_excess=0.02

w4 window rolling_2:   6%| | 11/200 [00:01<00:19,  9.86round/s, val_excess=0.02

w4 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.61round/s, val_excess=0.02

w4 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.61round/s, val_excess=0.02

w4 window rolling_2:   6%| | 13/200 [00:01<00:19,  9.68round/s, val_excess=0.02

w4 window rolling_2:   6%| | 13/200 [00:01<00:19,  9.68round/s, val_excess=0.02

w4 window rolling_2:   7%| | 14/200 [00:01<00:19,  9.59round/s, val_excess=0.02

w4 window rolling_2:   7%| | 14/200 [00:01<00:19,  9.59round/s, val_excess=0.02

w4 window rolling_2:   8%| | 15/200 [00:01<00:19,  9.58round/s, val_excess=0.02

w4 window rolling_2:   8%| | 15/200 [00:01<00:19,  9.58round/s, val_excess=0.01

w4 window rolling_2:   8%| | 16/200 [00:01<00:19,  9.46round/s, val_excess=0.01

w4 window rolling_2:   8%| | 16/200 [00:01<00:19,  9.46round/s, val_excess=0.01

w4 window rolling_2:   8%| | 17/200 [00:01<00:19,  9.50round/s, val_excess=0.01

w4 window rolling_2:   8%| | 17/200 [00:01<00:19,  9.50round/s, val_excess=0.01

w4 window rolling_2:   9%| | 18/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w4 window rolling_2:   9%| | 18/200 [00:01<00:19,  9.51round/s, val_excess=0.02

w4 window rolling_2:  10%| | 19/200 [00:01<00:19,  9.39round/s, val_excess=0.02

w4 window rolling_2:  10%| | 19/200 [00:01<00:19,  9.39round/s, val_excess=0.01

w4 window rolling_2:  10%| | 20/200 [00:02<00:18,  9.48round/s, val_excess=0.01

w4 window rolling_2:  10%| | 20/200 [00:02<00:18,  9.48round/s, val_excess=0.01

w4 window rolling_2:  10%| | 21/200 [00:02<00:18,  9.56round/s, val_excess=0.01

w4 window rolling_2:  10%| | 21/200 [00:02<00:18,  9.56round/s, val_excess=0.01

w4 window rolling_2:  11%| | 22/200 [00:02<00:18,  9.45round/s, val_excess=0.01

w4 window rolling_2:  11%| | 22/200 [00:02<00:18,  9.45round/s, val_excess=0.02

w4 window rolling_2:  12%| | 23/200 [00:02<00:18,  9.53round/s, val_excess=0.02

w4 window rolling_2:  12%| | 23/200 [00:02<00:18,  9.53round/s, val_excess=0.02

w4 window rolling_2:  12%| | 24/200 [00:02<00:18,  9.56round/s, val_excess=0.02

w4 window rolling_2:  12%| | 24/200 [00:02<00:18,  9.56round/s, val_excess=0.02

w4 window rolling_2:  12%|▏| 25/200 [00:02<00:18,  9.39round/s, val_excess=0.02

w4 window rolling_2:  12%|▏| 25/200 [00:02<00:18,  9.39round/s, val_excess=0.01

w4 window rolling_2:  13%|▏| 26/200 [00:02<00:18,  9.36round/s, val_excess=0.01

w4 window rolling_2:  13%|▏| 26/200 [00:02<00:18,  9.36round/s, val_excess=0.01

w4 window rolling_2:  14%|▏| 27/200 [00:02<00:18,  9.29round/s, val_excess=0.01

w4 window rolling_2:  14%|▏| 27/200 [00:02<00:18,  9.29round/s, val_excess=0.02

w4 window rolling_2:  14%|▏| 28/200 [00:02<00:18,  9.11round/s, val_excess=0.02

w4 window rolling_2:  14%|▏| 28/200 [00:02<00:18,  9.11round/s, val_excess=0.02

w4 window rolling_2:  14%|▏| 29/200 [00:03<00:18,  9.10round/s, val_excess=0.02

w4 window rolling_2:  14%|▏| 29/200 [00:03<00:18,  9.10round/s, val_excess=0.01

w4 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.05round/s, val_excess=0.01

w4 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.05round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 31/200 [00:03<00:18,  8.93round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 31/200 [00:03<00:18,  8.93round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.03round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.03round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 33/200 [00:03<00:18,  9.07round/s, val_excess=0.01

w4 window rolling_2:  16%|▏| 33/200 [00:03<00:18,  9.07round/s, val_excess=0.01

w4 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  9.10round/s, val_excess=0.01

w4 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  9.10round/s, val_excess=0.01

w4 window rolling_2:  18%|▏| 35/200 [00:03<00:19,  8.54round/s, val_excess=0.01

w4 window rolling_2:  18%|▏| 35/200 [00:03<00:19,  8.54round/s, val_excess=0.02

w4 window rolling_2:  18%|▏| 36/200 [00:03<00:18,  8.67round/s, val_excess=0.02

w4 window rolling_2:  18%|▏| 36/200 [00:03<00:18,  8.67round/s, val_excess=0.02

w4 window rolling_2:  18%|▏| 37/200 [00:03<00:18,  8.74round/s, val_excess=0.02

w4 window rolling_2:  18%|▏| 37/200 [00:03<00:18,  8.74round/s, val_excess=0.02

w4 window rolling_2:  19%|▏| 38/200 [00:04<00:18,  8.87round/s, val_excess=0.02

w4 window rolling_2:  19%|▏| 38/200 [00:04<00:18,  8.87round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 39/200 [00:04<00:18,  8.93round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 39/200 [00:04<00:18,  8.93round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 40/200 [00:04<00:17,  8.96round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 40/200 [00:04<00:17,  8.96round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 41/200 [00:04<00:17,  9.04round/s, val_excess=0.02

w4 window rolling_2:  20%|▏| 41/200 [00:04<00:17,  9.04round/s, val_excess=0.01

w4 window rolling_2:  21%|▏| 42/200 [00:04<00:17,  9.06round/s, val_excess=0.01

w4 window rolling_2:  21%|▏| 42/200 [00:04<00:17,  9.06round/s, val_excess=0.02

w4 window rolling_2:  22%|▏| 43/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w4 window rolling_2:  22%|▏| 43/200 [00:04<00:17,  9.02round/s, val_excess=0.01

w4 window rolling_2:  22%|▏| 44/200 [00:04<00:17,  9.02round/s, val_excess=0.01

w4 window rolling_2:  22%|▏| 44/200 [00:04<00:17,  9.02round/s, val_excess=0.02

w4 window rolling_2:  22%|▏| 45/200 [00:04<00:17,  9.04round/s, val_excess=0.02

w4 window rolling_2:  22%|▏| 45/200 [00:04<00:17,  9.04round/s, val_excess=0.01

w4 window rolling_2:  23%|▏| 46/200 [00:04<00:17,  9.03round/s, val_excess=0.01

w4 window rolling_2:  23%|▏| 46/200 [00:04<00:17,  9.03round/s, val_excess=0.02

w4 window rolling_2:  24%|▏| 47/200 [00:05<00:16,  9.04round/s, val_excess=0.02

w4 window rolling_2:  24%|▏| 47/200 [00:05<00:16,  9.04round/s, val_excess=0.01

w4 window rolling_2:  24%|▏| 48/200 [00:05<00:16,  9.01round/s, val_excess=0.01

w4 window rolling_2:  24%|▏| 48/200 [00:05<00:16,  9.01round/s, val_excess=0.02

w4 window rolling_2:  24%|▏| 49/200 [00:05<00:16,  9.09round/s, val_excess=0.02

w4 window rolling_2:  24%|▏| 49/200 [00:05<00:16,  9.09round/s, val_excess=0.03

w4 window rolling_2:  25%|▎| 50/200 [00:05<00:16,  9.08round/s, val_excess=0.03

w4 window rolling_2:  25%|▎| 50/200 [00:05<00:16,  9.08round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 51/200 [00:05<00:16,  9.03round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 51/200 [00:05<00:16,  9.03round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 52/200 [00:05<00:16,  8.99round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 52/200 [00:05<00:16,  8.99round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 53/200 [00:05<00:16,  9.04round/s, val_excess=0.02

w4 window rolling_2:  26%|▎| 53/200 [00:05<00:16,  9.04round/s, val_excess=0.02

w4 window rolling_2:  27%|▎| 54/200 [00:05<00:16,  9.05round/s, val_excess=0.02

w4 window rolling_2:  27%|▎| 54/200 [00:05<00:16,  9.05round/s, val_excess=0.01

w4 window rolling_2:  28%|▎| 55/200 [00:05<00:16,  9.05round/s, val_excess=0.01

w4 window rolling_2:  28%|▎| 55/200 [00:05<00:16,  9.05round/s, val_excess=0.02

w4 window rolling_2:  28%|▎| 56/200 [00:06<00:15,  9.04round/s, val_excess=0.02

w4 window rolling_2:  28%|▎| 56/200 [00:06<00:15,  9.04round/s, val_excess=0.02

w4 window rolling_2:  28%|▎| 57/200 [00:06<00:15,  9.02round/s, val_excess=0.02

w4 window rolling_2:  28%|▎| 57/200 [00:06<00:15,  9.02round/s, val_excess=0.01

w4 window rolling_2:  29%|▎| 58/200 [00:06<00:15,  9.08round/s, val_excess=0.01

w4 window rolling_2:  29%|▎| 58/200 [00:06<00:15,  9.08round/s, val_excess=0.01

w4 window rolling_2:  30%|▎| 59/200 [00:06<00:15,  9.09round/s, val_excess=0.01

w4 window rolling_2:  30%|▎| 59/200 [00:06<00:15,  9.09round/s, val_excess=0.02

w4 window rolling_2:  30%|▎| 60/200 [00:06<00:15,  9.00round/s, val_excess=0.02

w4 window rolling_2:  30%|▎| 60/200 [00:06<00:15,  9.00round/s, val_excess=0.02

w4 window rolling_2:  30%|▎| 61/200 [00:06<00:17,  8.05round/s, val_excess=0.02

w4 window rolling_2:  30%|▎| 61/200 [00:06<00:17,  8.05round/s, val_excess=0.02

w4 window rolling_2:  31%|▎| 62/200 [00:06<00:17,  7.99round/s, val_excess=0.02

w4 window rolling_2:  31%|▎| 62/200 [00:06<00:17,  7.99round/s, val_excess=0.03

w4 window rolling_2:  32%|▎| 63/200 [00:06<00:16,  8.30round/s, val_excess=0.03

w4 window rolling_2:  32%|▎| 63/200 [00:06<00:16,  8.30round/s, val_excess=0.02

w4 window rolling_2:  32%|▎| 64/200 [00:06<00:16,  8.47round/s, val_excess=0.02

w4 window rolling_2:  32%|▎| 64/200 [00:06<00:16,  8.47round/s, val_excess=0.02

w4 window rolling_2:  32%|▎| 65/200 [00:07<00:15,  8.57round/s, val_excess=0.02

w4 window rolling_2:  32%|▎| 65/200 [00:07<00:15,  8.57round/s, val_excess=0.03

w4 window rolling_2:  33%|▎| 66/200 [00:07<00:15,  8.70round/s, val_excess=0.03

w4 window rolling_2:  33%|▎| 66/200 [00:07<00:15,  8.70round/s, val_excess=0.02

w4 window rolling_2:  34%|▎| 67/200 [00:07<00:15,  8.81round/s, val_excess=0.02

w4 window rolling_2:  34%|▎| 67/200 [00:07<00:15,  8.81round/s, val_excess=0.02

w4 window rolling_2:  34%|▎| 68/200 [00:07<00:14,  8.86round/s, val_excess=0.02

w4 window rolling_2:  34%|▎| 68/200 [00:07<00:14,  8.86round/s, val_excess=0.03

w4 window rolling_2:  34%|▎| 69/200 [00:07<00:14,  8.86round/s, val_excess=0.03

w4 window rolling_2:  34%|▎| 69/200 [00:07<00:14,  8.86round/s, val_excess=0.03

w4 window rolling_2:  35%|▎| 70/200 [00:07<00:14,  8.93round/s, val_excess=0.03

w4 window rolling_2:  35%|▎| 70/200 [00:07<00:14,  8.93round/s, val_excess=0.03

w4 window rolling_2:  36%|▎| 71/200 [00:07<00:14,  8.92round/s, val_excess=0.03

w4 window rolling_2:  36%|▎| 71/200 [00:07<00:14,  8.92round/s, val_excess=0.02

w4 window rolling_2:  36%|▎| 72/200 [00:07<00:14,  8.90round/s, val_excess=0.02

w4 window rolling_2:  36%|▎| 72/200 [00:07<00:14,  8.90round/s, val_excess=0.03

w4 window rolling_2:  36%|▎| 73/200 [00:07<00:14,  8.93round/s, val_excess=0.03

w4 window rolling_2:  36%|▎| 73/200 [00:07<00:14,  8.93round/s, val_excess=0.03

w4 window rolling_2:  37%|▎| 74/200 [00:08<00:14,  8.90round/s, val_excess=0.03

w4 window rolling_2:  37%|▎| 74/200 [00:08<00:14,  8.90round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 75/200 [00:08<00:14,  8.87round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 75/200 [00:08<00:14,  8.87round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 76/200 [00:08<00:13,  8.88round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 76/200 [00:08<00:13,  8.88round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 77/200 [00:08<00:13,  9.08round/s, val_excess=0.03

w4 window rolling_2:  38%|▍| 77/200 [00:08<00:13,  9.08round/s, val_excess=0.03

w4 window rolling_2:  39%|▍| 78/200 [00:08<00:13,  9.25round/s, val_excess=0.03

w4 window rolling_2:  39%|▍| 78/200 [00:08<00:13,  9.25round/s, val_excess=0.03

w4 window rolling_2:  40%|▍| 79/200 [00:08<00:13,  9.29round/s, val_excess=0.03

w4 window rolling_2:  40%|▍| 79/200 [00:08<00:13,  9.29round/s, val_excess=0.02

w4 window rolling_2:  40%|▍| 80/200 [00:08<00:12,  9.35round/s, val_excess=0.02

w4 window rolling_2:  40%|▍| 80/200 [00:08<00:12,  9.35round/s, val_excess=0.03

w4 window rolling_2:  40%|▍| 81/200 [00:08<00:12,  9.34round/s, val_excess=0.03

w4 window rolling_2:  40%|▍| 81/200 [00:08<00:12,  9.34round/s, val_excess=0.03

w4 window rolling_2:  41%|▍| 82/200 [00:08<00:12,  9.42round/s, val_excess=0.03

w4 window rolling_2:  41%|▍| 82/200 [00:08<00:12,  9.42round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 83/200 [00:09<00:12,  9.41round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 83/200 [00:09<00:12,  9.41round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 84/200 [00:09<00:12,  9.39round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 84/200 [00:09<00:12,  9.39round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 85/200 [00:09<00:12,  8.97round/s, val_excess=0.03

w4 window rolling_2:  42%|▍| 85/200 [00:09<00:12,  8.97round/s, val_excess=0.03

w4 window rolling_2:  43%|▍| 86/200 [00:09<00:12,  9.06round/s, val_excess=0.03

w4 window rolling_2:  43%|▍| 86/200 [00:09<00:12,  9.06round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 87/200 [00:09<00:12,  9.19round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 87/200 [00:09<00:12,  9.19round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 88/200 [00:09<00:12,  9.22round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 88/200 [00:09<00:12,  9.22round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 89/200 [00:09<00:11,  9.35round/s, val_excess=0.03

w4 window rolling_2:  44%|▍| 89/200 [00:09<00:11,  9.35round/s, val_excess=0.03

w4 window rolling_2:  45%|▍| 90/200 [00:09<00:11,  9.37round/s, val_excess=0.03

w4 window rolling_2:  45%|▍| 90/200 [00:09<00:11,  9.37round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 91/200 [00:09<00:11,  9.46round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 91/200 [00:09<00:11,  9.46round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 92/200 [00:10<00:11,  9.51round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 92/200 [00:10<00:11,  9.51round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 93/200 [00:10<00:11,  9.61round/s, val_excess=0.03

w4 window rolling_2:  46%|▍| 93/200 [00:10<00:11,  9.61round/s, val_excess=0.03

w4 window rolling_2:  47%|▍| 94/200 [00:10<00:10,  9.69round/s, val_excess=0.03

w4 window rolling_2:  47%|▍| 94/200 [00:10<00:10,  9.69round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 95/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 95/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 96/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 96/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 97/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  48%|▍| 97/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  49%|▍| 98/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  49%|▍| 98/200 [00:10<00:10,  9.73round/s, val_excess=0.03

w4 window rolling_2:  50%|▍| 99/200 [00:10<00:10,  9.74round/s, val_excess=0.03

w4 window rolling_2:  50%|▍| 99/200 [00:10<00:10,  9.74round/s, val_excess=0.02

w4 window rolling_2:  50%|▌| 100/200 [00:10<00:10,  9.71round/s, val_excess=0.0

w4 window rolling_2:  50%|▌| 100/200 [00:10<00:10,  9.71round/s, val_excess=0.0

w4 window rolling_2:  50%|▌| 101/200 [00:10<00:10,  9.66round/s, val_excess=0.0

w4 window rolling_2:  50%|▌| 101/200 [00:10<00:10,  9.66round/s, val_excess=0.0

w4 window rolling_2:  51%|▌| 102/200 [00:11<00:10,  9.60round/s, val_excess=0.0

w4 window rolling_2:  51%|▌| 102/200 [00:11<00:10,  9.60round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 103/200 [00:11<00:10,  9.61round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 103/200 [00:11<00:10,  9.61round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 104/200 [00:11<00:10,  9.21round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 104/200 [00:11<00:10,  9.21round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 105/200 [00:11<00:10,  9.29round/s, val_excess=0.0

w4 window rolling_2:  52%|▌| 105/200 [00:11<00:10,  9.29round/s, val_excess=0.0

w4 window rolling_2:  53%|▌| 106/200 [00:11<00:10,  9.35round/s, val_excess=0.0

w4 window rolling_2:  53%|▌| 106/200 [00:11<00:10,  9.35round/s, val_excess=0.0

w4 window rolling_2:  54%|▌| 107/200 [00:11<00:09,  9.39round/s, val_excess=0.0

w4 window rolling_2:  54%|▌| 107/200 [00:11<00:09,  9.39round/s, val_excess=0.0

w4 window rolling_2:  54%|▌| 108/200 [00:11<00:09,  9.36round/s, val_excess=0.0

w4 window rolling_2:  54%|▌| 108/200 [00:11<00:09,  9.36round/s, val_excess=0.0

w4 window rolling_2:  55%|▌| 109/200 [00:11<00:09,  9.50round/s, val_excess=0.0

w4 window rolling_2:  55%|▌| 109/200 [00:11<00:09,  9.50round/s, val_excess=0.0

w4 window rolling_2:  55%|▌| 110/200 [00:11<00:09,  9.54round/s, val_excess=0.0

w4 window rolling_2:  55%|▌| 110/200 [00:11<00:09,  9.54round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 111/200 [00:12<00:09,  9.47round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 111/200 [00:12<00:09,  9.47round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 112/200 [00:12<00:09,  9.50round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 112/200 [00:12<00:09,  9.50round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 113/200 [00:12<00:09,  9.41round/s, val_excess=0.0

w4 window rolling_2:  56%|▌| 113/200 [00:12<00:09,  9.41round/s, val_excess=0.0

w4 window rolling_2:  57%|▌| 114/200 [00:12<00:09,  9.51round/s, val_excess=0.0

w4 window rolling_2:  57%|▌| 114/200 [00:12<00:09,  9.51round/s, val_excess=0.0

w4 window rolling_2:  57%|▌| 115/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_2:  57%|▌| 115/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_2:  58%|▌| 116/200 [00:12<00:08,  9.59round/s, val_excess=0.0

w4 window rolling_2:  58%|▌| 116/200 [00:12<00:08,  9.59round/s, val_excess=0.0

w4 window rolling_2:  58%|▌| 117/200 [00:12<00:08,  9.56round/s, val_excess=0.0

w4 window rolling_2:  58%|▌| 117/200 [00:12<00:08,  9.56round/s, val_excess=0.0

w4 window rolling_2:  59%|▌| 118/200 [00:12<00:08,  9.53round/s, val_excess=0.0

w4 window rolling_2:  59%|▌| 118/200 [00:12<00:08,  9.53round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 119/200 [00:12<00:08,  9.42round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 119/200 [00:12<00:08,  9.42round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 120/200 [00:12<00:08,  9.43round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 120/200 [00:12<00:08,  9.43round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 121/200 [00:13<00:08,  9.45round/s, val_excess=0.0

w4 window rolling_2:  60%|▌| 121/200 [00:13<00:08,  9.45round/s, val_excess=0.0

w4 window rolling_2:  61%|▌| 122/200 [00:13<00:08,  9.51round/s, val_excess=0.0

w4 window rolling_2:  61%|▌| 122/200 [00:13<00:08,  9.51round/s, val_excess=0.0

w4 window rolling_2:  62%|▌| 123/200 [00:13<00:08,  8.93round/s, val_excess=0.0

w4 window rolling_2:  62%|▌| 123/200 [00:13<00:08,  8.93round/s, val_excess=0.0

w4 window rolling_2:  62%|▌| 124/200 [00:13<00:08,  9.12round/s, val_excess=0.0

w4 window rolling_2:  62%|▌| 124/200 [00:13<00:08,  9.12round/s, val_excess=0.0

w4 window rolling_2:  62%|▋| 125/200 [00:13<00:08,  9.23round/s, val_excess=0.0

w4 window rolling_2:  62%|▋| 125/200 [00:13<00:08,  9.23round/s, val_excess=0.0

w4 window rolling_2:  63%|▋| 126/200 [00:13<00:07,  9.26round/s, val_excess=0.0

w4 window rolling_2:  63%|▋| 126/200 [00:13<00:07,  9.26round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 127/200 [00:13<00:07,  9.42round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 127/200 [00:13<00:07,  9.42round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 128/200 [00:13<00:07,  9.48round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 128/200 [00:13<00:07,  9.48round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 129/200 [00:13<00:07,  9.53round/s, val_excess=0.0

w4 window rolling_2:  64%|▋| 129/200 [00:13<00:07,  9.53round/s, val_excess=0.0

w4 window rolling_2:  65%|▋| 130/200 [00:14<00:07,  9.59round/s, val_excess=0.0

w4 window rolling_2:  65%|▋| 130/200 [00:14<00:07,  9.59round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 131/200 [00:14<00:07,  9.61round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 131/200 [00:14<00:07,  9.61round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 132/200 [00:14<00:07,  9.55round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 132/200 [00:14<00:07,  9.55round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 133/200 [00:14<00:07,  9.53round/s, val_excess=0.0

w4 window rolling_2:  66%|▋| 133/200 [00:14<00:07,  9.53round/s, val_excess=0.0

w4 window rolling_2:  67%|▋| 134/200 [00:14<00:06,  9.57round/s, val_excess=0.0

w4 window rolling_2:  67%|▋| 134/200 [00:14<00:06,  9.57round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 135/200 [00:14<00:06,  9.54round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 135/200 [00:14<00:06,  9.54round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 136/200 [00:14<00:06,  9.47round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 136/200 [00:14<00:06,  9.47round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 137/200 [00:14<00:06,  9.49round/s, val_excess=0.0

w4 window rolling_2:  68%|▋| 137/200 [00:14<00:06,  9.49round/s, val_excess=0.0

w4 window rolling_2:  69%|▋| 138/200 [00:14<00:06,  9.52round/s, val_excess=0.0

w4 window rolling_2:  69%|▋| 138/200 [00:14<00:06,  9.52round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 139/200 [00:14<00:06,  9.61round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 139/200 [00:14<00:06,  9.61round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 140/200 [00:15<00:06,  9.50round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 140/200 [00:15<00:06,  9.50round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 141/200 [00:15<00:06,  9.52round/s, val_excess=0.0

w4 window rolling_2:  70%|▋| 141/200 [00:15<00:06,  9.52round/s, val_excess=0.0

w4 window rolling_2:  71%|▋| 142/200 [00:15<00:06,  9.04round/s, val_excess=0.0

w4 window rolling_2:  71%|▋| 142/200 [00:15<00:06,  9.04round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 143/200 [00:15<00:06,  9.28round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 143/200 [00:15<00:06,  9.28round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 144/200 [00:15<00:05,  9.35round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 144/200 [00:15<00:05,  9.35round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 145/200 [00:15<00:05,  9.41round/s, val_excess=0.0

w4 window rolling_2:  72%|▋| 145/200 [00:15<00:05,  9.41round/s, val_excess=0.0

w4 window rolling_2:  73%|▋| 146/200 [00:15<00:05,  9.46round/s, val_excess=0.0

w4 window rolling_2:  73%|▋| 146/200 [00:15<00:05,  9.46round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 147/200 [00:15<00:05,  9.44round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 147/200 [00:15<00:05,  9.44round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 148/200 [00:15<00:05,  9.52round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 148/200 [00:15<00:05,  9.52round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 149/200 [00:16<00:05,  9.59round/s, val_excess=0.0

w4 window rolling_2:  74%|▋| 149/200 [00:16<00:05,  9.59round/s, val_excess=0.0

w4 window rolling_2:  75%|▊| 150/200 [00:16<00:05,  9.61round/s, val_excess=0.0

w4 window rolling_2:  75%|▊| 150/200 [00:16<00:05,  9.61round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 151/200 [00:16<00:05,  9.72round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 151/200 [00:16<00:05,  9.72round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 152/200 [00:16<00:04,  9.76round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 152/200 [00:16<00:04,  9.76round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 153/200 [00:16<00:04,  9.72round/s, val_excess=0.0

w4 window rolling_2:  76%|▊| 153/200 [00:16<00:04,  9.72round/s, val_excess=0.0

w4 window rolling_2:  77%|▊| 154/200 [00:16<00:04,  9.68round/s, val_excess=0.0

w4 window rolling_2:  77%|▊| 154/200 [00:16<00:04,  9.68round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 155/200 [00:16<00:04,  9.70round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 155/200 [00:16<00:04,  9.70round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 156/200 [00:16<00:04,  9.66round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 156/200 [00:16<00:04,  9.66round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 157/200 [00:16<00:04,  9.62round/s, val_excess=0.0

w4 window rolling_2:  78%|▊| 157/200 [00:16<00:04,  9.62round/s, val_excess=0.0

w4 window rolling_2:  79%|▊| 158/200 [00:16<00:04,  9.68round/s, val_excess=0.0

w4 window rolling_2:  79%|▊| 158/200 [00:16<00:04,  9.68round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 159/200 [00:17<00:04,  9.74round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 159/200 [00:17<00:04,  9.74round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 160/200 [00:17<00:04,  9.71round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 160/200 [00:17<00:04,  9.71round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 161/200 [00:17<00:04,  9.08round/s, val_excess=0.0

w4 window rolling_2:  80%|▊| 161/200 [00:17<00:04,  9.08round/s, val_excess=0.0

w4 window rolling_2:  81%|▊| 162/200 [00:17<00:04,  9.26round/s, val_excess=0.0

w4 window rolling_2:  81%|▊| 162/200 [00:17<00:04,  9.26round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 163/200 [00:17<00:03,  9.36round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 163/200 [00:17<00:03,  9.36round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 164/200 [00:17<00:03,  9.40round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 164/200 [00:17<00:03,  9.40round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 165/200 [00:17<00:03,  9.54round/s, val_excess=0.0

w4 window rolling_2:  82%|▊| 165/200 [00:17<00:03,  9.54round/s, val_excess=0.0

w4 window rolling_2:  83%|▊| 166/200 [00:17<00:03,  9.64round/s, val_excess=0.0

w4 window rolling_2:  83%|▊| 166/200 [00:17<00:03,  9.64round/s, val_excess=0.0

w4 window rolling_2:  84%|▊| 167/200 [00:17<00:03,  9.70round/s, val_excess=0.0

w4 window rolling_2:  84%|▊| 167/200 [00:17<00:03,  9.70round/s, val_excess=0.0

w4 window rolling_2:  84%|▊| 168/200 [00:18<00:03,  9.70round/s, val_excess=0.0

w4 window rolling_2:  84%|▊| 169/200 [00:18<00:03,  9.81round/s, val_excess=0.0

w4 window rolling_2:  84%|▊| 169/200 [00:18<00:03,  9.81round/s, val_excess=0.0

w4 window rolling_2:  85%|▊| 170/200 [00:18<00:03,  9.73round/s, val_excess=0.0

w4 window rolling_2:  85%|▊| 170/200 [00:18<00:03,  9.73round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 171/200 [00:18<00:02,  9.78round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 171/200 [00:18<00:02,  9.78round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 172/200 [00:18<00:02,  9.81round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 172/200 [00:18<00:02,  9.81round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 173/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w4 window rolling_2:  86%|▊| 173/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w4 window rolling_2:  87%|▊| 174/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_2:  87%|▊| 174/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 175/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 175/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 176/200 [00:18<00:02,  9.87round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 176/200 [00:18<00:02,  9.87round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 177/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_2:  88%|▉| 177/200 [00:18<00:02,  9.85round/s, val_excess=0.0

w4 window rolling_2:  89%|▉| 178/200 [00:19<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_2:  89%|▉| 178/200 [00:19<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 179/200 [00:19<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 179/200 [00:19<00:02,  9.90round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 180/200 [00:19<00:02,  9.82round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 180/200 [00:19<00:02,  9.82round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 181/200 [00:19<00:02,  9.31round/s, val_excess=0.0

w4 window rolling_2:  90%|▉| 181/200 [00:19<00:02,  9.31round/s, val_excess=0.0

w4 window rolling_2:  91%|▉| 182/200 [00:19<00:01,  9.31round/s, val_excess=0.0

w4 window rolling_2:  92%|▉| 183/200 [00:19<00:01,  9.71round/s, val_excess=0.0

w4 window rolling_2:  92%|▉| 183/200 [00:19<00:01,  9.71round/s, val_excess=0.0

w4 window rolling_2:  92%|▉| 184/200 [00:19<00:01,  9.76round/s, val_excess=0.0

w4 window rolling_2:  92%|▉| 184/200 [00:19<00:01,  9.76round/s, val_excess=0.0

w4 window rolling_2:  92%|▉| 185/200 [00:19<00:01,  9.76round/s, val_excess=0.0

w4 window rolling_2:  93%|▉| 186/200 [00:19<00:01,  9.91round/s, val_excess=0.0

w4 window rolling_2:  93%|▉| 186/200 [00:19<00:01,  9.91round/s, val_excess=0.0

w4 window rolling_2:  94%|▉| 187/200 [00:19<00:01,  9.91round/s, val_excess=0.0

w4 window rolling_2:  94%|▉| 188/200 [00:20<00:01,  9.97round/s, val_excess=0.0

w4 window rolling_2:  94%|▉| 188/200 [00:20<00:01,  9.97round/s, val_excess=0.0

w4 window rolling_2:  94%|▉| 189/200 [00:20<00:01,  9.97round/s, val_excess=0.0

w4 window rolling_2:  95%|▉| 190/200 [00:20<00:01, 10.00round/s, val_excess=0.0

w4 window rolling_2:  95%|▉| 190/200 [00:20<00:01, 10.00round/s, val_excess=0.0

w4 window rolling_2:  96%|▉| 191/200 [00:20<00:00, 10.00round/s, val_excess=0.0

w4 window rolling_2:  96%|▉| 192/200 [00:20<00:00, 10.01round/s, val_excess=0.0

w4 window rolling_2:  96%|▉| 192/200 [00:20<00:00, 10.01round/s, val_excess=0.0

w4 window rolling_2:  96%|▉| 193/200 [00:20<00:00,  9.99round/s, val_excess=0.0

w4 window rolling_2:  96%|▉| 193/200 [00:20<00:00,  9.99round/s, val_excess=0.0

w4 window rolling_2:  97%|▉| 194/200 [00:20<00:00,  9.93round/s, val_excess=0.0

w4 window rolling_2:  97%|▉| 194/200 [00:20<00:00,  9.93round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 195/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 195/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 196/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 196/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 197/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  98%|▉| 197/200 [00:20<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2:  99%|▉| 198/200 [00:21<00:00,  9.91round/s, val_excess=0.0

w4 window rolling_2: 100%|▉| 199/200 [00:21<00:00, 10.02round/s, val_excess=0.0

w4 window rolling_2: 100%|▉| 199/200 [00:21<00:00, 10.02round/s, val_excess=0.0

w4 window rolling_2: 100%|█| 200/200 [00:21<00:00,  9.85round/s, val_excess=0.0

w4 window rolling_2: 100%|█| 200/200 [00:21<00:00,  9.85round/s, val_excess=0.0

w4 window rolling_2: 100%|█| 200/200 [00:21<00:00,  9.41round/s, val_excess=0.0

2026-07-06 17:29:21 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=4 feature_type=window fold=rolling_3

2026-07-06 17:29:42 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=4 feature_type=window fold=rolling_3 features=69

w4 window rolling_3:   0%|                          | 0/200 [00:00<?, ?round/s]

w4 window rolling_3:   0%|                  | 1/200 [00:00<00:21,  9.12round/s]

w4 window rolling_3:   0%| | 1/200 [00:00<00:21,  9.12round/s, val_excess=0.001

w4 window rolling_3:   1%| | 2/200 [00:00<00:21,  9.12round/s, val_excess=-0.00

w4 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.69round/s, val_excess=-0.00

w4 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.69round/s, val_excess=-0.00

w4 window rolling_3:   2%| | 4/200 [00:00<00:18, 10.69round/s, val_excess=-0.01

w4 window rolling_3:   2%| | 5/200 [00:00<00:18, 10.67round/s, val_excess=-0.01

w4 window rolling_3:   2%| | 5/200 [00:00<00:18, 10.67round/s, val_excess=-0.00

w4 window rolling_3:   3%| | 6/200 [00:00<00:18, 10.67round/s, val_excess=-0.01

w4 window rolling_3:   4%| | 7/200 [00:00<00:18, 10.42round/s, val_excess=-0.01

w4 window rolling_3:   4%| | 7/200 [00:00<00:18, 10.42round/s, val_excess=-0.01

w4 window rolling_3:   4%| | 8/200 [00:00<00:18, 10.42round/s, val_excess=-0.00

w4 window rolling_3:   4%| | 9/200 [00:00<00:18, 10.34round/s, val_excess=-0.00

w4 window rolling_3:   4%| | 9/200 [00:00<00:18, 10.34round/s, val_excess=-0.00

w4 window rolling_3:   5%| | 10/200 [00:00<00:18, 10.34round/s, val_excess=-0.0

w4 window rolling_3:   6%| | 11/200 [00:01<00:18, 10.19round/s, val_excess=-0.0

w4 window rolling_3:   6%| | 11/200 [00:01<00:18, 10.19round/s, val_excess=0.01

w4 window rolling_3:   6%| | 12/200 [00:01<00:18, 10.19round/s, val_excess=0.00

w4 window rolling_3:   6%| | 13/200 [00:01<00:18, 10.07round/s, val_excess=0.00

w4 window rolling_3:   6%| | 13/200 [00:01<00:18, 10.07round/s, val_excess=-0.0

w4 window rolling_3:   7%| | 14/200 [00:01<00:18, 10.07round/s, val_excess=0.00

w4 window rolling_3:   8%| | 15/200 [00:01<00:18,  9.93round/s, val_excess=0.00

w4 window rolling_3:   8%| | 15/200 [00:01<00:18,  9.93round/s, val_excess=0.00

w4 window rolling_3:   8%| | 16/200 [00:01<00:18,  9.88round/s, val_excess=0.00

w4 window rolling_3:   8%| | 16/200 [00:01<00:18,  9.88round/s, val_excess=0.00

w4 window rolling_3:   8%| | 17/200 [00:01<00:18,  9.81round/s, val_excess=0.00

w4 window rolling_3:   8%| | 17/200 [00:01<00:18,  9.81round/s, val_excess=0.00

w4 window rolling_3:   9%| | 18/200 [00:01<00:18,  9.72round/s, val_excess=0.00

w4 window rolling_3:   9%| | 18/200 [00:01<00:18,  9.72round/s, val_excess=0.00

w4 window rolling_3:  10%| | 19/200 [00:01<00:18,  9.62round/s, val_excess=0.00

w4 window rolling_3:  10%| | 19/200 [00:01<00:18,  9.62round/s, val_excess=0.00

w4 window rolling_3:  10%| | 20/200 [00:02<00:18,  9.57round/s, val_excess=0.00

w4 window rolling_3:  10%| | 20/200 [00:02<00:18,  9.57round/s, val_excess=0.00

w4 window rolling_3:  10%| | 21/200 [00:02<00:18,  9.56round/s, val_excess=0.00

w4 window rolling_3:  10%| | 21/200 [00:02<00:18,  9.56round/s, val_excess=0.00

w4 window rolling_3:  11%| | 22/200 [00:02<00:18,  9.51round/s, val_excess=0.00

w4 window rolling_3:  11%| | 22/200 [00:02<00:18,  9.51round/s, val_excess=0.00

w4 window rolling_3:  12%| | 23/200 [00:02<00:18,  9.41round/s, val_excess=0.00

w4 window rolling_3:  12%| | 23/200 [00:02<00:18,  9.41round/s, val_excess=0.00

w4 window rolling_3:  12%| | 24/200 [00:02<00:18,  9.43round/s, val_excess=0.00

w4 window rolling_3:  12%| | 24/200 [00:02<00:18,  9.43round/s, val_excess=-0.0

w4 window rolling_3:  12%|▏| 25/200 [00:02<00:19,  8.91round/s, val_excess=-0.0

w4 window rolling_3:  12%|▏| 25/200 [00:02<00:19,  8.91round/s, val_excess=-0.0

w4 window rolling_3:  13%|▏| 26/200 [00:02<00:19,  9.02round/s, val_excess=-0.0

w4 window rolling_3:  13%|▏| 26/200 [00:02<00:19,  9.02round/s, val_excess=-0.0

w4 window rolling_3:  14%|▏| 27/200 [00:02<00:18,  9.12round/s, val_excess=-0.0

w4 window rolling_3:  14%|▏| 27/200 [00:02<00:18,  9.12round/s, val_excess=0.00

w4 window rolling_3:  14%|▏| 28/200 [00:02<00:18,  9.15round/s, val_excess=0.00

w4 window rolling_3:  14%|▏| 28/200 [00:02<00:18,  9.15round/s, val_excess=0.00

w4 window rolling_3:  14%|▏| 29/200 [00:02<00:18,  9.23round/s, val_excess=0.00

w4 window rolling_3:  14%|▏| 29/200 [00:02<00:18,  9.23round/s, val_excess=-0.0

w4 window rolling_3:  15%|▏| 30/200 [00:03<00:18,  9.28round/s, val_excess=-0.0

w4 window rolling_3:  15%|▏| 30/200 [00:03<00:18,  9.28round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 31/200 [00:03<00:19,  8.89round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 31/200 [00:03<00:19,  8.89round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 32/200 [00:03<00:19,  8.72round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 32/200 [00:03<00:19,  8.72round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 33/200 [00:03<00:19,  8.52round/s, val_excess=-0.0

w4 window rolling_3:  16%|▏| 33/200 [00:03<00:19,  8.52round/s, val_excess=-0.0

w4 window rolling_3:  17%|▏| 34/200 [00:03<00:19,  8.39round/s, val_excess=-0.0

w4 window rolling_3:  17%|▏| 34/200 [00:03<00:19,  8.39round/s, val_excess=-0.0

w4 window rolling_3:  18%|▏| 35/200 [00:03<00:19,  8.38round/s, val_excess=-0.0

w4 window rolling_3:  18%|▏| 35/200 [00:03<00:19,  8.38round/s, val_excess=0.00

w4 window rolling_3:  18%|▏| 36/200 [00:03<00:19,  8.44round/s, val_excess=0.00

w4 window rolling_3:  18%|▏| 36/200 [00:03<00:19,  8.44round/s, val_excess=-0.0

w4 window rolling_3:  18%|▏| 37/200 [00:03<00:19,  8.34round/s, val_excess=-0.0

w4 window rolling_3:  18%|▏| 37/200 [00:03<00:19,  8.34round/s, val_excess=0.00

w4 window rolling_3:  19%|▏| 38/200 [00:04<00:19,  8.29round/s, val_excess=0.00

w4 window rolling_3:  19%|▏| 38/200 [00:04<00:19,  8.29round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 39/200 [00:04<00:19,  8.18round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 39/200 [00:04<00:19,  8.18round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 40/200 [00:04<00:19,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 40/200 [00:04<00:19,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 41/200 [00:04<00:19,  8.22round/s, val_excess=-0.0

w4 window rolling_3:  20%|▏| 41/200 [00:04<00:19,  8.22round/s, val_excess=-0.0

w4 window rolling_3:  21%|▏| 42/200 [00:04<00:19,  8.28round/s, val_excess=-0.0

w4 window rolling_3:  21%|▏| 42/200 [00:04<00:19,  8.28round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 43/200 [00:04<00:18,  8.36round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 43/200 [00:04<00:18,  8.36round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 44/200 [00:04<00:18,  8.41round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 44/200 [00:04<00:18,  8.41round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 45/200 [00:04<00:18,  8.32round/s, val_excess=-0.0

w4 window rolling_3:  22%|▏| 45/200 [00:04<00:18,  8.32round/s, val_excess=-0.0

w4 window rolling_3:  23%|▏| 46/200 [00:05<00:18,  8.28round/s, val_excess=-0.0

w4 window rolling_3:  23%|▏| 46/200 [00:05<00:18,  8.28round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 47/200 [00:05<00:18,  8.31round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 47/200 [00:05<00:18,  8.31round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 48/200 [00:05<00:18,  8.29round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 48/200 [00:05<00:18,  8.29round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 49/200 [00:05<00:18,  8.29round/s, val_excess=-0.0

w4 window rolling_3:  24%|▏| 49/200 [00:05<00:18,  8.29round/s, val_excess=-0.0

w4 window rolling_3:  25%|▎| 50/200 [00:05<00:18,  8.07round/s, val_excess=-0.0

w4 window rolling_3:  25%|▎| 50/200 [00:05<00:18,  8.07round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 51/200 [00:05<00:18,  8.16round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 51/200 [00:05<00:18,  8.16round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 52/200 [00:05<00:18,  8.04round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 52/200 [00:05<00:18,  8.04round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 53/200 [00:05<00:18,  8.08round/s, val_excess=-0.0

w4 window rolling_3:  26%|▎| 53/200 [00:05<00:18,  8.08round/s, val_excess=-0.0

w4 window rolling_3:  27%|▎| 54/200 [00:06<00:17,  8.14round/s, val_excess=-0.0

w4 window rolling_3:  27%|▎| 54/200 [00:06<00:17,  8.14round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 55/200 [00:06<00:18,  8.03round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 55/200 [00:06<00:18,  8.03round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 56/200 [00:06<00:17,  8.11round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 56/200 [00:06<00:17,  8.11round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 57/200 [00:06<00:17,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  28%|▎| 57/200 [00:06<00:17,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  29%|▎| 58/200 [00:06<00:17,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  29%|▎| 58/200 [00:06<00:17,  8.20round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 59/200 [00:06<00:17,  8.17round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 59/200 [00:06<00:17,  8.17round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 60/200 [00:06<00:17,  8.15round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 60/200 [00:06<00:17,  8.15round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 61/200 [00:06<00:16,  8.39round/s, val_excess=-0.0

w4 window rolling_3:  30%|▎| 61/200 [00:06<00:16,  8.39round/s, val_excess=-0.0

w4 window rolling_3:  31%|▎| 62/200 [00:06<00:16,  8.56round/s, val_excess=-0.0

w4 window rolling_3:  31%|▎| 62/200 [00:06<00:16,  8.56round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 63/200 [00:07<00:15,  8.65round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 63/200 [00:07<00:15,  8.65round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 64/200 [00:07<00:15,  8.83round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 64/200 [00:07<00:15,  8.83round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 65/200 [00:07<00:15,  8.84round/s, val_excess=-0.0

w4 window rolling_3:  32%|▎| 65/200 [00:07<00:15,  8.84round/s, val_excess=-0.0

w4 window rolling_3:  33%|▎| 66/200 [00:07<00:15,  8.91round/s, val_excess=-0.0

w4 window rolling_3:  33%|▎| 66/200 [00:07<00:15,  8.91round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 67/200 [00:07<00:14,  9.00round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 67/200 [00:07<00:14,  9.00round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 68/200 [00:07<00:14,  8.99round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 68/200 [00:07<00:14,  8.99round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 69/200 [00:07<00:14,  9.03round/s, val_excess=-0.0

w4 window rolling_3:  34%|▎| 69/200 [00:07<00:14,  9.03round/s, val_excess=-0.0

w4 window rolling_3:  35%|▎| 70/200 [00:07<00:14,  9.04round/s, val_excess=-0.0

w4 window rolling_3:  35%|▎| 70/200 [00:07<00:14,  9.04round/s, val_excess=0.00

w4 window rolling_3:  36%|▎| 71/200 [00:07<00:14,  9.02round/s, val_excess=0.00

w4 window rolling_3:  36%|▎| 71/200 [00:07<00:14,  9.02round/s, val_excess=-0.0

w4 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  9.08round/s, val_excess=-0.0

w4 window rolling_3:  36%|▎| 72/200 [00:08<00:14,  9.08round/s, val_excess=-0.0

w4 window rolling_3:  36%|▎| 73/200 [00:08<00:13,  9.19round/s, val_excess=-0.0

w4 window rolling_3:  36%|▎| 73/200 [00:08<00:13,  9.19round/s, val_excess=-0.0

w4 window rolling_3:  37%|▎| 74/200 [00:08<00:13,  9.07round/s, val_excess=-0.0

w4 window rolling_3:  37%|▎| 74/200 [00:08<00:13,  9.07round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 75/200 [00:08<00:13,  9.11round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 75/200 [00:08<00:13,  9.11round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 76/200 [00:08<00:13,  9.06round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 76/200 [00:08<00:13,  9.06round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 77/200 [00:08<00:13,  9.09round/s, val_excess=-0.0

w4 window rolling_3:  38%|▍| 77/200 [00:08<00:13,  9.09round/s, val_excess=-0.0

w4 window rolling_3:  39%|▍| 78/200 [00:08<00:13,  9.08round/s, val_excess=-0.0

w4 window rolling_3:  39%|▍| 78/200 [00:08<00:13,  9.08round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 79/200 [00:08<00:13,  9.11round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 79/200 [00:08<00:13,  9.11round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 80/200 [00:08<00:13,  9.07round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 80/200 [00:08<00:13,  9.07round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 81/200 [00:09<00:13,  9.10round/s, val_excess=-0.0

w4 window rolling_3:  40%|▍| 81/200 [00:09<00:13,  9.10round/s, val_excess=-0.0

w4 window rolling_3:  41%|▍| 82/200 [00:09<00:12,  9.17round/s, val_excess=-0.0

w4 window rolling_3:  41%|▍| 82/200 [00:09<00:12,  9.17round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 83/200 [00:09<00:12,  9.13round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 83/200 [00:09<00:12,  9.13round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.24round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 84/200 [00:09<00:12,  9.24round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.17round/s, val_excess=-0.0

w4 window rolling_3:  42%|▍| 85/200 [00:09<00:12,  9.17round/s, val_excess=-0.0

w4 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.21round/s, val_excess=-0.0

w4 window rolling_3:  43%|▍| 86/200 [00:09<00:12,  9.21round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 87/200 [00:09<00:12,  9.22round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 87/200 [00:09<00:12,  9.22round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 88/200 [00:09<00:12,  9.22round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 88/200 [00:09<00:12,  9.22round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  9.15round/s, val_excess=-0.0

w4 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  9.15round/s, val_excess=-0.0

w4 window rolling_3:  45%|▍| 90/200 [00:10<00:11,  9.21round/s, val_excess=-0.0

w4 window rolling_3:  45%|▍| 90/200 [00:10<00:11,  9.21round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.23round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 91/200 [00:10<00:11,  9.23round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.23round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 92/200 [00:10<00:11,  9.23round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 93/200 [00:10<00:11,  9.20round/s, val_excess=-0.0

w4 window rolling_3:  46%|▍| 93/200 [00:10<00:11,  9.20round/s, val_excess=-0.0

w4 window rolling_3:  47%|▍| 94/200 [00:10<00:11,  9.24round/s, val_excess=-0.0

w4 window rolling_3:  47%|▍| 94/200 [00:10<00:11,  9.24round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  9.26round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 95/200 [00:10<00:11,  9.26round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 96/200 [00:10<00:11,  9.31round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 96/200 [00:10<00:11,  9.31round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 97/200 [00:10<00:11,  9.26round/s, val_excess=-0.0

w4 window rolling_3:  48%|▍| 97/200 [00:10<00:11,  9.26round/s, val_excess=-0.0

w4 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  9.22round/s, val_excess=-0.0

w4 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  9.22round/s, val_excess=0.00

w4 window rolling_3:  50%|▍| 99/200 [00:11<00:10,  9.37round/s, val_excess=0.00

w4 window rolling_3:  50%|▍| 99/200 [00:11<00:10,  9.37round/s, val_excess=0.00

w4 window rolling_3:  50%|▌| 100/200 [00:11<00:10,  9.50round/s, val_excess=0.0

w4 window rolling_3:  50%|▌| 100/200 [00:11<00:10,  9.50round/s, val_excess=0.0

w4 window rolling_3:  50%|▌| 101/200 [00:11<00:10,  9.61round/s, val_excess=0.0

w4 window rolling_3:  50%|▌| 101/200 [00:11<00:10,  9.61round/s, val_excess=0.0

w4 window rolling_3:  51%|▌| 102/200 [00:11<00:10,  9.49round/s, val_excess=0.0

w4 window rolling_3:  51%|▌| 102/200 [00:11<00:10,  9.49round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 103/200 [00:11<00:10,  9.50round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 103/200 [00:11<00:10,  9.50round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 104/200 [00:11<00:10,  9.52round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 104/200 [00:11<00:10,  9.52round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 105/200 [00:11<00:10,  9.39round/s, val_excess=0.0

w4 window rolling_3:  52%|▌| 105/200 [00:11<00:10,  9.39round/s, val_excess=0.0

w4 window rolling_3:  53%|▌| 106/200 [00:11<00:10,  9.37round/s, val_excess=0.0

w4 window rolling_3:  53%|▌| 106/200 [00:11<00:10,  9.37round/s, val_excess=0.0

w4 window rolling_3:  54%|▌| 107/200 [00:11<00:09,  9.38round/s, val_excess=0.0

w4 window rolling_3:  54%|▌| 107/200 [00:11<00:09,  9.38round/s, val_excess=0.0

w4 window rolling_3:  54%|▌| 108/200 [00:11<00:09,  9.41round/s, val_excess=0.0

w4 window rolling_3:  54%|▌| 108/200 [00:11<00:09,  9.41round/s, val_excess=0.0

w4 window rolling_3:  55%|▌| 109/200 [00:12<00:09,  9.46round/s, val_excess=0.0

w4 window rolling_3:  55%|▌| 109/200 [00:12<00:09,  9.46round/s, val_excess=-0.

w4 window rolling_3:  55%|▌| 110/200 [00:12<00:09,  9.46round/s, val_excess=-0.

w4 window rolling_3:  55%|▌| 110/200 [00:12<00:09,  9.46round/s, val_excess=0.0

w4 window rolling_3:  56%|▌| 111/200 [00:12<00:09,  9.38round/s, val_excess=0.0

w4 window rolling_3:  56%|▌| 111/200 [00:12<00:09,  9.38round/s, val_excess=-0.

w4 window rolling_3:  56%|▌| 112/200 [00:12<00:09,  9.44round/s, val_excess=-0.

w4 window rolling_3:  56%|▌| 112/200 [00:12<00:09,  9.44round/s, val_excess=-0.

w4 window rolling_3:  56%|▌| 113/200 [00:12<00:09,  9.42round/s, val_excess=-0.

w4 window rolling_3:  56%|▌| 113/200 [00:12<00:09,  9.42round/s, val_excess=-0.

w4 window rolling_3:  57%|▌| 114/200 [00:12<00:09,  9.49round/s, val_excess=-0.

w4 window rolling_3:  57%|▌| 114/200 [00:12<00:09,  9.49round/s, val_excess=-0.

w4 window rolling_3:  57%|▌| 115/200 [00:12<00:08,  9.52round/s, val_excess=-0.

w4 window rolling_3:  57%|▌| 115/200 [00:12<00:08,  9.52round/s, val_excess=-0.

w4 window rolling_3:  58%|▌| 116/200 [00:12<00:08,  9.49round/s, val_excess=-0.

w4 window rolling_3:  58%|▌| 116/200 [00:12<00:08,  9.49round/s, val_excess=0.0

w4 window rolling_3:  58%|▌| 117/200 [00:12<00:08,  9.48round/s, val_excess=0.0

w4 window rolling_3:  58%|▌| 117/200 [00:12<00:08,  9.48round/s, val_excess=0.0

w4 window rolling_3:  59%|▌| 118/200 [00:13<00:08,  9.50round/s, val_excess=0.0

w4 window rolling_3:  59%|▌| 118/200 [00:13<00:08,  9.50round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 119/200 [00:13<00:08,  9.54round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 119/200 [00:13<00:08,  9.54round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 120/200 [00:13<00:08,  9.58round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 120/200 [00:13<00:08,  9.58round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 121/200 [00:13<00:08,  9.24round/s, val_excess=0.0

w4 window rolling_3:  60%|▌| 121/200 [00:13<00:08,  9.24round/s, val_excess=0.0

w4 window rolling_3:  61%|▌| 122/200 [00:13<00:08,  9.28round/s, val_excess=0.0

w4 window rolling_3:  61%|▌| 122/200 [00:13<00:08,  9.28round/s, val_excess=0.0

w4 window rolling_3:  62%|▌| 123/200 [00:13<00:08,  9.33round/s, val_excess=0.0

w4 window rolling_3:  62%|▌| 123/200 [00:13<00:08,  9.33round/s, val_excess=0.0

w4 window rolling_3:  62%|▌| 124/200 [00:13<00:08,  9.39round/s, val_excess=0.0

w4 window rolling_3:  62%|▌| 124/200 [00:13<00:08,  9.39round/s, val_excess=0.0

w4 window rolling_3:  62%|▋| 125/200 [00:13<00:07,  9.47round/s, val_excess=0.0

w4 window rolling_3:  62%|▋| 125/200 [00:13<00:07,  9.47round/s, val_excess=0.0

w4 window rolling_3:  63%|▋| 126/200 [00:13<00:07,  9.29round/s, val_excess=0.0

w4 window rolling_3:  63%|▋| 126/200 [00:13<00:07,  9.29round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 127/200 [00:13<00:07,  9.39round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 127/200 [00:13<00:07,  9.39round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 128/200 [00:14<00:07,  9.42round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 128/200 [00:14<00:07,  9.42round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 129/200 [00:14<00:07,  9.50round/s, val_excess=0.0

w4 window rolling_3:  64%|▋| 129/200 [00:14<00:07,  9.50round/s, val_excess=0.0

w4 window rolling_3:  65%|▋| 130/200 [00:14<00:07,  9.59round/s, val_excess=0.0

w4 window rolling_3:  65%|▋| 130/200 [00:14<00:07,  9.59round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 131/200 [00:14<00:07,  9.48round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 131/200 [00:14<00:07,  9.48round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 132/200 [00:14<00:07,  9.48round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 132/200 [00:14<00:07,  9.48round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 133/200 [00:14<00:07,  9.54round/s, val_excess=-0.

w4 window rolling_3:  66%|▋| 133/200 [00:14<00:07,  9.54round/s, val_excess=-0.

w4 window rolling_3:  67%|▋| 134/200 [00:14<00:06,  9.49round/s, val_excess=-0.

w4 window rolling_3:  67%|▋| 134/200 [00:14<00:06,  9.49round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 135/200 [00:14<00:06,  9.47round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 135/200 [00:14<00:06,  9.47round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 136/200 [00:14<00:06,  9.50round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 136/200 [00:14<00:06,  9.50round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 137/200 [00:15<00:06,  9.47round/s, val_excess=-0.

w4 window rolling_3:  68%|▋| 137/200 [00:15<00:06,  9.47round/s, val_excess=0.0

w4 window rolling_3:  69%|▋| 138/200 [00:15<00:06,  9.55round/s, val_excess=0.0

w4 window rolling_3:  69%|▋| 138/200 [00:15<00:06,  9.55round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 139/200 [00:15<00:06,  9.58round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 139/200 [00:15<00:06,  9.58round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 140/200 [00:15<00:06,  9.65round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 140/200 [00:15<00:06,  9.65round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 141/200 [00:15<00:06,  9.65round/s, val_excess=-0.

w4 window rolling_3:  70%|▋| 141/200 [00:15<00:06,  9.65round/s, val_excess=-0.

w4 window rolling_3:  71%|▋| 142/200 [00:15<00:06,  8.99round/s, val_excess=-0.

w4 window rolling_3:  71%|▋| 142/200 [00:15<00:06,  8.99round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 143/200 [00:15<00:06,  9.13round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 143/200 [00:15<00:06,  9.13round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 144/200 [00:15<00:06,  9.14round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 144/200 [00:15<00:06,  9.14round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 145/200 [00:15<00:06,  9.16round/s, val_excess=-0.

w4 window rolling_3:  72%|▋| 145/200 [00:15<00:06,  9.16round/s, val_excess=-0.

w4 window rolling_3:  73%|▋| 146/200 [00:16<00:05,  9.19round/s, val_excess=-0.

w4 window rolling_3:  73%|▋| 146/200 [00:16<00:05,  9.19round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 147/200 [00:16<00:05,  9.31round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 147/200 [00:16<00:05,  9.31round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 148/200 [00:16<00:05,  9.42round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 148/200 [00:16<00:05,  9.42round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 149/200 [00:16<00:05,  9.55round/s, val_excess=-0.

w4 window rolling_3:  74%|▋| 149/200 [00:16<00:05,  9.55round/s, val_excess=-0.

w4 window rolling_3:  75%|▊| 150/200 [00:16<00:05,  9.48round/s, val_excess=-0.

w4 window rolling_3:  75%|▊| 150/200 [00:16<00:05,  9.48round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 151/200 [00:16<00:05,  9.53round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 151/200 [00:16<00:05,  9.53round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 152/200 [00:16<00:05,  9.42round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 152/200 [00:16<00:05,  9.42round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 153/200 [00:16<00:04,  9.48round/s, val_excess=-0.

w4 window rolling_3:  76%|▊| 153/200 [00:16<00:04,  9.48round/s, val_excess=-0.

w4 window rolling_3:  77%|▊| 154/200 [00:16<00:04,  9.45round/s, val_excess=-0.

w4 window rolling_3:  77%|▊| 154/200 [00:16<00:04,  9.45round/s, val_excess=-0.

w4 window rolling_3:  78%|▊| 155/200 [00:16<00:04,  9.31round/s, val_excess=-0.

w4 window rolling_3:  78%|▊| 155/200 [00:16<00:04,  9.31round/s, val_excess=0.0

w4 window rolling_3:  78%|▊| 156/200 [00:17<00:04,  9.31round/s, val_excess=0.0

w4 window rolling_3:  78%|▊| 156/200 [00:17<00:04,  9.31round/s, val_excess=0.0

w4 window rolling_3:  78%|▊| 157/200 [00:17<00:04,  9.26round/s, val_excess=0.0

w4 window rolling_3:  78%|▊| 157/200 [00:17<00:04,  9.26round/s, val_excess=0.0

w4 window rolling_3:  79%|▊| 158/200 [00:17<00:04,  9.30round/s, val_excess=0.0

w4 window rolling_3:  79%|▊| 158/200 [00:17<00:04,  9.30round/s, val_excess=0.0

w4 window rolling_3:  80%|▊| 159/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_3:  80%|▊| 159/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_3:  80%|▊| 160/200 [00:17<00:04,  9.51round/s, val_excess=0.0

w4 window rolling_3:  80%|▊| 160/200 [00:17<00:04,  9.51round/s, val_excess=-0.

w4 window rolling_3:  80%|▊| 161/200 [00:17<00:04,  9.47round/s, val_excess=-0.

w4 window rolling_3:  80%|▊| 161/200 [00:17<00:04,  9.47round/s, val_excess=-0.

w4 window rolling_3:  81%|▊| 162/200 [00:17<00:04,  9.39round/s, val_excess=-0.

w4 window rolling_3:  81%|▊| 162/200 [00:17<00:04,  9.39round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 163/200 [00:17<00:03,  9.35round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 163/200 [00:17<00:03,  9.35round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 164/200 [00:17<00:03,  9.16round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 164/200 [00:17<00:03,  9.16round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 165/200 [00:18<00:03,  9.21round/s, val_excess=-0.

w4 window rolling_3:  82%|▊| 165/200 [00:18<00:03,  9.21round/s, val_excess=-0.

w4 window rolling_3:  83%|▊| 166/200 [00:18<00:03,  9.28round/s, val_excess=-0.

w4 window rolling_3:  83%|▊| 166/200 [00:18<00:03,  9.28round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 167/200 [00:18<00:03,  9.34round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 167/200 [00:18<00:03,  9.34round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 168/200 [00:18<00:03,  9.43round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 168/200 [00:18<00:03,  9.43round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 169/200 [00:18<00:03,  9.29round/s, val_excess=-0.

w4 window rolling_3:  84%|▊| 169/200 [00:18<00:03,  9.29round/s, val_excess=-0.

w4 window rolling_3:  85%|▊| 170/200 [00:18<00:03,  9.30round/s, val_excess=-0.

w4 window rolling_3:  85%|▊| 170/200 [00:18<00:03,  9.30round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 171/200 [00:18<00:03,  9.30round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 171/200 [00:18<00:03,  9.30round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 172/200 [00:18<00:02,  9.48round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 172/200 [00:18<00:02,  9.48round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 173/200 [00:18<00:02,  9.46round/s, val_excess=-0.

w4 window rolling_3:  86%|▊| 173/200 [00:18<00:02,  9.46round/s, val_excess=-0.

w4 window rolling_3:  87%|▊| 174/200 [00:18<00:02,  9.35round/s, val_excess=-0.

w4 window rolling_3:  87%|▊| 174/200 [00:18<00:02,  9.35round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 175/200 [00:19<00:02,  9.39round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 175/200 [00:19<00:02,  9.39round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 176/200 [00:19<00:02,  9.38round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 176/200 [00:19<00:02,  9.38round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 177/200 [00:19<00:02,  9.41round/s, val_excess=-0.

w4 window rolling_3:  88%|▉| 177/200 [00:19<00:02,  9.41round/s, val_excess=-0.

w4 window rolling_3:  89%|▉| 178/200 [00:19<00:02,  9.34round/s, val_excess=-0.

w4 window rolling_3:  89%|▉| 178/200 [00:19<00:02,  9.34round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 179/200 [00:19<00:02,  9.40round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 179/200 [00:19<00:02,  9.40round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 180/200 [00:19<00:02,  9.46round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 180/200 [00:19<00:02,  9.46round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 181/200 [00:19<00:01,  9.60round/s, val_excess=-0.

w4 window rolling_3:  90%|▉| 181/200 [00:19<00:01,  9.60round/s, val_excess=-0.

w4 window rolling_3:  91%|▉| 182/200 [00:19<00:01,  9.58round/s, val_excess=-0.

w4 window rolling_3:  91%|▉| 182/200 [00:19<00:01,  9.58round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 183/200 [00:19<00:01,  9.57round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 183/200 [00:19<00:01,  9.57round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 184/200 [00:20<00:01,  9.47round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 184/200 [00:20<00:01,  9.47round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 185/200 [00:20<00:01,  9.54round/s, val_excess=-0.

w4 window rolling_3:  92%|▉| 185/200 [00:20<00:01,  9.54round/s, val_excess=-0.

w4 window rolling_3:  93%|▉| 186/200 [00:20<00:01,  9.65round/s, val_excess=-0.

w4 window rolling_3:  93%|▉| 186/200 [00:20<00:01,  9.65round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 187/200 [00:20<00:01,  9.61round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 187/200 [00:20<00:01,  9.61round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 188/200 [00:20<00:01,  9.61round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 188/200 [00:20<00:01,  9.61round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 189/200 [00:20<00:01,  9.63round/s, val_excess=-0.

w4 window rolling_3:  94%|▉| 189/200 [00:20<00:01,  9.63round/s, val_excess=-0.

w4 window rolling_3:  95%|▉| 190/200 [00:20<00:01,  9.65round/s, val_excess=-0.

w4 window rolling_3:  95%|▉| 190/200 [00:20<00:01,  9.65round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 191/200 [00:20<00:00,  9.69round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 191/200 [00:20<00:00,  9.69round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 192/200 [00:20<00:00,  9.71round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 192/200 [00:20<00:00,  9.71round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 193/200 [00:20<00:00,  9.72round/s, val_excess=-0.

w4 window rolling_3:  96%|▉| 193/200 [00:20<00:00,  9.72round/s, val_excess=-0.

w4 window rolling_3:  97%|▉| 194/200 [00:21<00:00,  9.68round/s, val_excess=-0.

w4 window rolling_3:  97%|▉| 194/200 [00:21<00:00,  9.68round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 195/200 [00:21<00:00,  9.68round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 195/200 [00:21<00:00,  9.68round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 196/200 [00:21<00:00,  9.73round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 196/200 [00:21<00:00,  9.73round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 197/200 [00:21<00:00,  9.65round/s, val_excess=-0.

w4 window rolling_3:  98%|▉| 197/200 [00:21<00:00,  9.65round/s, val_excess=-0.

w4 window rolling_3:  99%|▉| 198/200 [00:21<00:00,  9.54round/s, val_excess=-0.

w4 window rolling_3:  99%|▉| 198/200 [00:21<00:00,  9.54round/s, val_excess=-0.

w4 window rolling_3: 100%|▉| 199/200 [00:21<00:00,  9.59round/s, val_excess=-0.

w4 window rolling_3: 100%|▉| 199/200 [00:21<00:00,  9.59round/s, val_excess=-0.

w4 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.63round/s, val_excess=-0.

w4 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.63round/s, val_excess=-0.

w4 window rolling_3: 100%|█| 200/200 [00:21<00:00,  9.22round/s, val_excess=-0.

2026-07-06 17:30:04 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=4 feature_type=window fold=rolling_4

2026-07-06 17:30:25 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=4 feature_type=window fold=rolling_4 features=69

w4 window rolling_4:   0%|                          | 0/200 [00:00<?, ?round/s]

w4 window rolling_4:   0%|                  | 1/200 [00:00<00:23,  8.38round/s]

w4 window rolling_4:   0%| | 1/200 [00:00<00:23,  8.38round/s, val_excess=0.001

w4 window rolling_4:   1%| | 2/200 [00:00<00:23,  8.38round/s, val_excess=0.007

w4 window rolling_4:   2%| | 3/200 [00:00<00:20,  9.57round/s, val_excess=0.007

w4 window rolling_4:   2%| | 3/200 [00:00<00:20,  9.57round/s, val_excess=0.007

w4 window rolling_4:   2%| | 4/200 [00:00<00:20,  9.57round/s, val_excess=-0.00

w4 window rolling_4:   2%| | 5/200 [00:00<00:19, 10.06round/s, val_excess=-0.00

w4 window rolling_4:   2%| | 5/200 [00:00<00:19, 10.06round/s, val_excess=0.018

w4 window rolling_4:   3%| | 6/200 [00:00<00:19, 10.06round/s, val_excess=0.009

w4 window rolling_4:   4%| | 7/200 [00:00<00:19,  9.98round/s, val_excess=0.009

w4 window rolling_4:   4%| | 7/200 [00:00<00:19,  9.98round/s, val_excess=0.024

w4 window rolling_4:   4%| | 8/200 [00:00<00:19,  9.92round/s, val_excess=0.024

w4 window rolling_4:   4%| | 8/200 [00:00<00:19,  9.92round/s, val_excess=0.016

w4 window rolling_4:   4%| | 9/200 [00:00<00:19,  9.88round/s, val_excess=0.016

w4 window rolling_4:   4%| | 9/200 [00:00<00:19,  9.88round/s, val_excess=0.023

w4 window rolling_4:   5%| | 10/200 [00:01<00:19,  9.82round/s, val_excess=0.02

w4 window rolling_4:   5%| | 10/200 [00:01<00:19,  9.82round/s, val_excess=0.02

w4 window rolling_4:   6%| | 11/200 [00:01<00:19,  9.82round/s, val_excess=0.02

w4 window rolling_4:   6%| | 11/200 [00:01<00:19,  9.82round/s, val_excess=0.01

w4 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.81round/s, val_excess=0.01

w4 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.81round/s, val_excess=0.02

w4 window rolling_4:   6%| | 13/200 [00:01<00:19,  9.77round/s, val_excess=0.02

w4 window rolling_4:   6%| | 13/200 [00:01<00:19,  9.77round/s, val_excess=0.02

w4 window rolling_4:   7%| | 14/200 [00:01<00:19,  9.74round/s, val_excess=0.02

w4 window rolling_4:   7%| | 14/200 [00:01<00:19,  9.74round/s, val_excess=0.02

w4 window rolling_4:   8%| | 15/200 [00:01<00:19,  9.70round/s, val_excess=0.02

w4 window rolling_4:   8%| | 15/200 [00:01<00:19,  9.70round/s, val_excess=0.02

w4 window rolling_4:   8%| | 16/200 [00:01<00:19,  9.64round/s, val_excess=0.02

w4 window rolling_4:   8%| | 16/200 [00:01<00:19,  9.64round/s, val_excess=0.01

w4 window rolling_4:   8%| | 17/200 [00:01<00:19,  9.53round/s, val_excess=0.01

w4 window rolling_4:   8%| | 17/200 [00:01<00:19,  9.53round/s, val_excess=0.01

w4 window rolling_4:   9%| | 18/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w4 window rolling_4:   9%| | 18/200 [00:01<00:19,  9.51round/s, val_excess=0.01

w4 window rolling_4:  10%| | 19/200 [00:01<00:19,  9.43round/s, val_excess=0.01

w4 window rolling_4:  10%| | 19/200 [00:01<00:19,  9.43round/s, val_excess=0.01

w4 window rolling_4:  10%| | 20/200 [00:02<00:19,  9.43round/s, val_excess=0.01

w4 window rolling_4:  10%| | 20/200 [00:02<00:19,  9.43round/s, val_excess=0.01

w4 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.49round/s, val_excess=0.01

w4 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.49round/s, val_excess=0.01

w4 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.47round/s, val_excess=0.01

w4 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.47round/s, val_excess=0.01

w4 window rolling_4:  12%| | 23/200 [00:02<00:18,  9.46round/s, val_excess=0.01

w4 window rolling_4:  12%| | 23/200 [00:02<00:18,  9.46round/s, val_excess=0.02

w4 window rolling_4:  12%| | 24/200 [00:02<00:18,  9.52round/s, val_excess=0.02

w4 window rolling_4:  12%| | 24/200 [00:02<00:18,  9.52round/s, val_excess=0.01

w4 window rolling_4:  12%|▏| 25/200 [00:02<00:18,  9.57round/s, val_excess=0.01

w4 window rolling_4:  12%|▏| 25/200 [00:02<00:18,  9.57round/s, val_excess=0.01

w4 window rolling_4:  13%|▏| 26/200 [00:02<00:18,  9.50round/s, val_excess=0.01

w4 window rolling_4:  13%|▏| 26/200 [00:02<00:18,  9.50round/s, val_excess=0.03

w4 window rolling_4:  14%|▏| 27/200 [00:02<00:18,  9.50round/s, val_excess=0.03

w4 window rolling_4:  14%|▏| 27/200 [00:02<00:18,  9.50round/s, val_excess=0.03

w4 window rolling_4:  14%|▏| 28/200 [00:02<00:20,  8.45round/s, val_excess=0.03

w4 window rolling_4:  14%|▏| 28/200 [00:02<00:20,  8.45round/s, val_excess=0.04

w4 window rolling_4:  14%|▏| 29/200 [00:03<00:21,  8.13round/s, val_excess=0.04

w4 window rolling_4:  14%|▏| 29/200 [00:03<00:21,  8.13round/s, val_excess=0.04

w4 window rolling_4:  15%|▏| 30/200 [00:03<00:20,  8.21round/s, val_excess=0.04

w4 window rolling_4:  15%|▏| 30/200 [00:03<00:20,  8.21round/s, val_excess=0.04

w4 window rolling_4:  16%|▏| 31/200 [00:03<00:20,  8.31round/s, val_excess=0.04

w4 window rolling_4:  16%|▏| 31/200 [00:03<00:20,  8.31round/s, val_excess=0.03

w4 window rolling_4:  16%|▏| 32/200 [00:03<00:19,  8.43round/s, val_excess=0.03

w4 window rolling_4:  16%|▏| 32/200 [00:03<00:19,  8.43round/s, val_excess=0.03

w4 window rolling_4:  16%|▏| 33/200 [00:03<00:19,  8.49round/s, val_excess=0.03

w4 window rolling_4:  16%|▏| 33/200 [00:03<00:19,  8.49round/s, val_excess=0.03

w4 window rolling_4:  17%|▏| 34/200 [00:03<00:19,  8.50round/s, val_excess=0.03

w4 window rolling_4:  17%|▏| 34/200 [00:03<00:19,  8.50round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 35/200 [00:03<00:19,  8.44round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 35/200 [00:03<00:19,  8.44round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 36/200 [00:03<00:19,  8.31round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 36/200 [00:03<00:19,  8.31round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 37/200 [00:04<00:19,  8.43round/s, val_excess=0.03

w4 window rolling_4:  18%|▏| 37/200 [00:04<00:19,  8.43round/s, val_excess=0.03

w4 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.65round/s, val_excess=0.03

w4 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.65round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.90round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.90round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 40/200 [00:04<00:17,  8.92round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 40/200 [00:04<00:17,  8.92round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 41/200 [00:04<00:17,  9.04round/s, val_excess=0.03

w4 window rolling_4:  20%|▏| 41/200 [00:04<00:17,  9.04round/s, val_excess=0.03

w4 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  9.09round/s, val_excess=0.03

w4 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  9.09round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  9.10round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  9.10round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 44/200 [00:04<00:17,  9.12round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 44/200 [00:04<00:17,  9.12round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 45/200 [00:04<00:16,  9.13round/s, val_excess=0.03

w4 window rolling_4:  22%|▏| 45/200 [00:04<00:16,  9.13round/s, val_excess=0.03

w4 window rolling_4:  23%|▏| 46/200 [00:05<00:16,  9.17round/s, val_excess=0.03

w4 window rolling_4:  23%|▏| 46/200 [00:05<00:16,  9.17round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 47/200 [00:05<00:16,  9.21round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 47/200 [00:05<00:16,  9.21round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 48/200 [00:05<00:16,  9.24round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 48/200 [00:05<00:16,  9.24round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 49/200 [00:05<00:16,  9.28round/s, val_excess=0.03

w4 window rolling_4:  24%|▏| 49/200 [00:05<00:16,  9.28round/s, val_excess=0.03

w4 window rolling_4:  25%|▎| 50/200 [00:05<00:16,  9.33round/s, val_excess=0.03

w4 window rolling_4:  25%|▎| 50/200 [00:05<00:16,  9.33round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 51/200 [00:05<00:16,  9.21round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 51/200 [00:05<00:16,  9.21round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.34round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.34round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.36round/s, val_excess=0.03

w4 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.36round/s, val_excess=0.03

w4 window rolling_4:  27%|▎| 54/200 [00:05<00:15,  9.30round/s, val_excess=0.03

w4 window rolling_4:  27%|▎| 54/200 [00:05<00:15,  9.30round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 55/200 [00:05<00:15,  9.29round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 55/200 [00:05<00:15,  9.29round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 56/200 [00:06<00:15,  9.28round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 56/200 [00:06<00:15,  9.28round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 57/200 [00:06<00:15,  9.34round/s, val_excess=0.03

w4 window rolling_4:  28%|▎| 57/200 [00:06<00:15,  9.34round/s, val_excess=0.03

w4 window rolling_4:  29%|▎| 58/200 [00:06<00:15,  9.33round/s, val_excess=0.03

w4 window rolling_4:  29%|▎| 58/200 [00:06<00:15,  9.33round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 59/200 [00:06<00:15,  9.37round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 59/200 [00:06<00:15,  9.37round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 60/200 [00:06<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 60/200 [00:06<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.40round/s, val_excess=0.03

w4 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.40round/s, val_excess=0.03

w4 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.41round/s, val_excess=0.03

w4 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.41round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 63/200 [00:06<00:14,  9.31round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 63/200 [00:06<00:14,  9.31round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 64/200 [00:06<00:14,  9.37round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 64/200 [00:06<00:14,  9.37round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 65/200 [00:07<00:14,  9.41round/s, val_excess=0.03

w4 window rolling_4:  32%|▎| 65/200 [00:07<00:14,  9.41round/s, val_excess=0.03

w4 window rolling_4:  33%|▎| 66/200 [00:07<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  33%|▎| 66/200 [00:07<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 67/200 [00:07<00:14,  9.37round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 67/200 [00:07<00:14,  9.37round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 68/200 [00:07<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 68/200 [00:07<00:14,  9.36round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 69/200 [00:07<00:14,  9.33round/s, val_excess=0.03

w4 window rolling_4:  34%|▎| 69/200 [00:07<00:14,  9.33round/s, val_excess=0.03

w4 window rolling_4:  35%|▎| 70/200 [00:07<00:14,  9.16round/s, val_excess=0.03

w4 window rolling_4:  35%|▎| 70/200 [00:07<00:14,  9.16round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.30round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.30round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.39round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.39round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 73/200 [00:07<00:13,  9.35round/s, val_excess=0.03

w4 window rolling_4:  36%|▎| 73/200 [00:07<00:13,  9.35round/s, val_excess=0.03

w4 window rolling_4:  37%|▎| 74/200 [00:08<00:13,  9.37round/s, val_excess=0.03

w4 window rolling_4:  37%|▎| 74/200 [00:08<00:13,  9.37round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 75/200 [00:08<00:13,  9.41round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 75/200 [00:08<00:13,  9.41round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 76/200 [00:08<00:13,  9.49round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 76/200 [00:08<00:13,  9.49round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 77/200 [00:08<00:12,  9.48round/s, val_excess=0.03

w4 window rolling_4:  38%|▍| 77/200 [00:08<00:12,  9.48round/s, val_excess=0.04

w4 window rolling_4:  39%|▍| 78/200 [00:08<00:12,  9.45round/s, val_excess=0.04

w4 window rolling_4:  39%|▍| 78/200 [00:08<00:12,  9.45round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 79/200 [00:08<00:12,  9.53round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 79/200 [00:08<00:12,  9.53round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.55round/s, val_excess=0.04

w4 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.55round/s, val_excess=0.04

w4 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.52round/s, val_excess=0.04

w4 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.52round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.47round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.47round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 84/200 [00:09<00:12,  9.49round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 84/200 [00:09<00:12,  9.49round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 85/200 [00:09<00:12,  9.48round/s, val_excess=0.04

w4 window rolling_4:  42%|▍| 85/200 [00:09<00:12,  9.48round/s, val_excess=0.04

w4 window rolling_4:  43%|▍| 86/200 [00:09<00:12,  9.45round/s, val_excess=0.04

w4 window rolling_4:  43%|▍| 86/200 [00:09<00:12,  9.45round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 87/200 [00:09<00:11,  9.46round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 87/200 [00:09<00:11,  9.46round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 88/200 [00:09<00:11,  9.54round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 88/200 [00:09<00:11,  9.54round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.34round/s, val_excess=0.04

w4 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.34round/s, val_excess=0.04

w4 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.27round/s, val_excess=0.04

w4 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.27round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.30round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.30round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.35round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.35round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 93/200 [00:10<00:11,  9.36round/s, val_excess=0.04

w4 window rolling_4:  46%|▍| 93/200 [00:10<00:11,  9.36round/s, val_excess=0.04

w4 window rolling_4:  47%|▍| 94/200 [00:10<00:11,  8.87round/s, val_excess=0.04

w4 window rolling_4:  47%|▍| 94/200 [00:10<00:11,  8.87round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 95/200 [00:10<00:12,  8.40round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 95/200 [00:10<00:12,  8.40round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 96/200 [00:10<00:12,  8.13round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 96/200 [00:10<00:12,  8.13round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 97/200 [00:10<00:13,  7.90round/s, val_excess=0.04

w4 window rolling_4:  48%|▍| 97/200 [00:10<00:13,  7.90round/s, val_excess=0.04

w4 window rolling_4:  49%|▍| 98/200 [00:10<00:12,  8.21round/s, val_excess=0.04

w4 window rolling_4:  49%|▍| 98/200 [00:10<00:12,  8.21round/s, val_excess=0.04

w4 window rolling_4:  50%|▍| 99/200 [00:10<00:12,  8.35round/s, val_excess=0.04

w4 window rolling_4:  50%|▍| 99/200 [00:10<00:12,  8.35round/s, val_excess=0.04

w4 window rolling_4:  50%|▌| 100/200 [00:10<00:11,  8.59round/s, val_excess=0.0

w4 window rolling_4:  50%|▌| 100/200 [00:10<00:11,  8.59round/s, val_excess=0.0

w4 window rolling_4:  50%|▌| 101/200 [00:10<00:11,  8.70round/s, val_excess=0.0

w4 window rolling_4:  50%|▌| 101/200 [00:10<00:11,  8.70round/s, val_excess=0.0

w4 window rolling_4:  51%|▌| 102/200 [00:11<00:11,  8.84round/s, val_excess=0.0

w4 window rolling_4:  51%|▌| 102/200 [00:11<00:11,  8.84round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  8.87round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  8.87round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 104/200 [00:11<00:10,  8.95round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 104/200 [00:11<00:10,  8.95round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 105/200 [00:11<00:10,  9.08round/s, val_excess=0.0

w4 window rolling_4:  52%|▌| 105/200 [00:11<00:10,  9.08round/s, val_excess=0.0

w4 window rolling_4:  53%|▌| 106/200 [00:11<00:10,  9.16round/s, val_excess=0.0

w4 window rolling_4:  53%|▌| 106/200 [00:11<00:10,  9.16round/s, val_excess=0.0

w4 window rolling_4:  54%|▌| 107/200 [00:11<00:10,  9.18round/s, val_excess=0.0

w4 window rolling_4:  54%|▌| 107/200 [00:11<00:10,  9.18round/s, val_excess=0.0

w4 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.26round/s, val_excess=0.0

w4 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.26round/s, val_excess=0.0

w4 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.11round/s, val_excess=0.0

w4 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.11round/s, val_excess=0.0

w4 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.11round/s, val_excess=0.0

w4 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.11round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 111/200 [00:12<00:09,  9.13round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 111/200 [00:12<00:09,  9.13round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.02round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.02round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 113/200 [00:12<00:09,  9.15round/s, val_excess=0.0

w4 window rolling_4:  56%|▌| 113/200 [00:12<00:09,  9.15round/s, val_excess=0.0

w4 window rolling_4:  57%|▌| 114/200 [00:12<00:09,  9.22round/s, val_excess=0.0

w4 window rolling_4:  57%|▌| 114/200 [00:12<00:09,  9.22round/s, val_excess=0.0

w4 window rolling_4:  57%|▌| 115/200 [00:12<00:09,  9.25round/s, val_excess=0.0

w4 window rolling_4:  57%|▌| 115/200 [00:12<00:09,  9.25round/s, val_excess=0.0

w4 window rolling_4:  58%|▌| 116/200 [00:12<00:09,  9.31round/s, val_excess=0.0

w4 window rolling_4:  58%|▌| 116/200 [00:12<00:09,  9.31round/s, val_excess=0.0

w4 window rolling_4:  58%|▌| 117/200 [00:12<00:09,  9.14round/s, val_excess=0.0

w4 window rolling_4:  58%|▌| 117/200 [00:12<00:09,  9.14round/s, val_excess=0.0

w4 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.18round/s, val_excess=0.0

w4 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.18round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.25round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.25round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 120/200 [00:13<00:08,  9.25round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 120/200 [00:13<00:08,  9.25round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 121/200 [00:13<00:08,  9.30round/s, val_excess=0.0

w4 window rolling_4:  60%|▌| 121/200 [00:13<00:08,  9.30round/s, val_excess=0.0

w4 window rolling_4:  61%|▌| 122/200 [00:13<00:08,  9.31round/s, val_excess=0.0

w4 window rolling_4:  61%|▌| 122/200 [00:13<00:08,  9.31round/s, val_excess=0.0

w4 window rolling_4:  62%|▌| 123/200 [00:13<00:08,  9.26round/s, val_excess=0.0

w4 window rolling_4:  62%|▌| 123/200 [00:13<00:08,  9.26round/s, val_excess=0.0

w4 window rolling_4:  62%|▌| 124/200 [00:13<00:08,  9.24round/s, val_excess=0.0

w4 window rolling_4:  62%|▌| 124/200 [00:13<00:08,  9.24round/s, val_excess=0.0

w4 window rolling_4:  62%|▋| 125/200 [00:13<00:08,  9.28round/s, val_excess=0.0

w4 window rolling_4:  62%|▋| 125/200 [00:13<00:08,  9.28round/s, val_excess=0.0

w4 window rolling_4:  63%|▋| 126/200 [00:13<00:07,  9.33round/s, val_excess=0.0

w4 window rolling_4:  63%|▋| 126/200 [00:13<00:07,  9.33round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.18round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.18round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 128/200 [00:13<00:09,  7.74round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 128/200 [00:13<00:09,  7.74round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 129/200 [00:14<00:08,  7.95round/s, val_excess=0.0

w4 window rolling_4:  64%|▋| 129/200 [00:14<00:08,  7.95round/s, val_excess=0.0

w4 window rolling_4:  65%|▋| 130/200 [00:14<00:08,  8.30round/s, val_excess=0.0

w4 window rolling_4:  65%|▋| 130/200 [00:14<00:08,  8.30round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 131/200 [00:14<00:08,  8.17round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 131/200 [00:14<00:08,  8.17round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 132/200 [00:14<00:08,  8.49round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 132/200 [00:14<00:08,  8.49round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 133/200 [00:14<00:07,  8.73round/s, val_excess=0.0

w4 window rolling_4:  66%|▋| 133/200 [00:14<00:07,  8.73round/s, val_excess=0.0

w4 window rolling_4:  67%|▋| 134/200 [00:14<00:07,  8.90round/s, val_excess=0.0

w4 window rolling_4:  67%|▋| 134/200 [00:14<00:07,  8.90round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 135/200 [00:14<00:07,  8.98round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 135/200 [00:14<00:07,  8.98round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 136/200 [00:14<00:07,  8.99round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 136/200 [00:14<00:07,  8.99round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.14round/s, val_excess=0.0

w4 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.14round/s, val_excess=0.0

w4 window rolling_4:  69%|▋| 138/200 [00:15<00:06,  9.18round/s, val_excess=0.0

w4 window rolling_4:  69%|▋| 138/200 [00:15<00:06,  9.18round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 139/200 [00:15<00:06,  9.26round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 139/200 [00:15<00:06,  9.26round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 140/200 [00:15<00:06,  9.34round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 140/200 [00:15<00:06,  9.34round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 141/200 [00:15<00:06,  9.39round/s, val_excess=0.0

w4 window rolling_4:  70%|▋| 141/200 [00:15<00:06,  9.39round/s, val_excess=0.0

w4 window rolling_4:  71%|▋| 142/200 [00:15<00:06,  9.34round/s, val_excess=0.0

w4 window rolling_4:  71%|▋| 142/200 [00:15<00:06,  9.34round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 143/200 [00:15<00:06,  9.33round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 143/200 [00:15<00:06,  9.33round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 144/200 [00:15<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 144/200 [00:15<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 145/200 [00:15<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  72%|▋| 145/200 [00:15<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.30round/s, val_excess=0.0

w4 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.30round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 147/200 [00:16<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 147/200 [00:16<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 148/200 [00:16<00:05,  9.32round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 148/200 [00:16<00:05,  9.32round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 149/200 [00:16<00:05,  9.34round/s, val_excess=0.0

w4 window rolling_4:  74%|▋| 149/200 [00:16<00:05,  9.34round/s, val_excess=0.0

w4 window rolling_4:  75%|▊| 150/200 [00:16<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  75%|▊| 150/200 [00:16<00:05,  9.38round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 151/200 [00:16<00:05,  9.45round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 151/200 [00:16<00:05,  9.45round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 152/200 [00:16<00:05,  9.43round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 152/200 [00:16<00:05,  9.43round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 153/200 [00:16<00:05,  9.40round/s, val_excess=0.0

w4 window rolling_4:  76%|▊| 153/200 [00:16<00:05,  9.40round/s, val_excess=0.0

w4 window rolling_4:  77%|▊| 154/200 [00:16<00:04,  9.40round/s, val_excess=0.0

w4 window rolling_4:  77%|▊| 154/200 [00:16<00:04,  9.40round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 155/200 [00:16<00:04,  9.40round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 155/200 [00:16<00:04,  9.40round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 156/200 [00:17<00:04,  9.43round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 156/200 [00:17<00:04,  9.43round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 157/200 [00:17<00:04,  9.43round/s, val_excess=0.0

w4 window rolling_4:  78%|▊| 157/200 [00:17<00:04,  9.43round/s, val_excess=0.0

w4 window rolling_4:  79%|▊| 158/200 [00:17<00:04,  9.33round/s, val_excess=0.0

w4 window rolling_4:  79%|▊| 158/200 [00:17<00:04,  9.33round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 159/200 [00:17<00:04,  9.18round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 159/200 [00:17<00:04,  9.18round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 160/200 [00:17<00:04,  9.32round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 160/200 [00:17<00:04,  9.32round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 161/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_4:  80%|▊| 161/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_4:  81%|▊| 162/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_4:  81%|▊| 162/200 [00:17<00:04,  9.34round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 163/200 [00:17<00:03,  9.40round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 163/200 [00:17<00:03,  9.40round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 164/200 [00:17<00:03,  9.38round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 164/200 [00:17<00:03,  9.38round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 165/200 [00:17<00:03,  9.39round/s, val_excess=0.0

w4 window rolling_4:  82%|▊| 165/200 [00:17<00:03,  9.39round/s, val_excess=0.0

w4 window rolling_4:  83%|▊| 166/200 [00:18<00:03,  9.41round/s, val_excess=0.0

w4 window rolling_4:  83%|▊| 166/200 [00:18<00:03,  9.41round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 167/200 [00:18<00:03,  9.39round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 167/200 [00:18<00:03,  9.39round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 168/200 [00:18<00:03,  9.38round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 168/200 [00:18<00:03,  9.38round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 169/200 [00:18<00:03,  9.34round/s, val_excess=0.0

w4 window rolling_4:  84%|▊| 169/200 [00:18<00:03,  9.34round/s, val_excess=0.0

w4 window rolling_4:  85%|▊| 170/200 [00:18<00:03,  9.35round/s, val_excess=0.0

w4 window rolling_4:  85%|▊| 170/200 [00:18<00:03,  9.35round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 171/200 [00:18<00:03,  9.35round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 171/200 [00:18<00:03,  9.35round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 172/200 [00:18<00:02,  9.38round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 172/200 [00:18<00:02,  9.38round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 173/200 [00:18<00:02,  9.38round/s, val_excess=0.0

w4 window rolling_4:  86%|▊| 173/200 [00:18<00:02,  9.38round/s, val_excess=0.0

w4 window rolling_4:  87%|▊| 174/200 [00:18<00:02,  9.36round/s, val_excess=0.0

w4 window rolling_4:  87%|▊| 174/200 [00:18<00:02,  9.36round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 175/200 [00:19<00:02,  9.42round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 175/200 [00:19<00:02,  9.42round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 176/200 [00:19<00:02,  9.39round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 176/200 [00:19<00:02,  9.39round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 177/200 [00:19<00:02,  9.21round/s, val_excess=0.0

w4 window rolling_4:  88%|▉| 177/200 [00:19<00:02,  9.21round/s, val_excess=0.0

w4 window rolling_4:  89%|▉| 178/200 [00:19<00:02,  9.11round/s, val_excess=0.0

w4 window rolling_4:  89%|▉| 178/200 [00:19<00:02,  9.11round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 179/200 [00:19<00:02,  9.14round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 179/200 [00:19<00:02,  9.14round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 180/200 [00:19<00:02,  9.09round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 180/200 [00:19<00:02,  9.09round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 181/200 [00:19<00:02,  9.08round/s, val_excess=0.0

w4 window rolling_4:  90%|▉| 181/200 [00:19<00:02,  9.08round/s, val_excess=0.0

w4 window rolling_4:  91%|▉| 182/200 [00:19<00:01,  9.13round/s, val_excess=0.0

w4 window rolling_4:  91%|▉| 182/200 [00:19<00:01,  9.13round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 183/200 [00:19<00:01,  9.16round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 183/200 [00:19<00:01,  9.16round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 184/200 [00:20<00:01,  9.23round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 184/200 [00:20<00:01,  9.23round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 185/200 [00:20<00:01,  9.30round/s, val_excess=0.0

w4 window rolling_4:  92%|▉| 185/200 [00:20<00:01,  9.30round/s, val_excess=0.0

w4 window rolling_4:  93%|▉| 186/200 [00:20<00:01,  9.31round/s, val_excess=0.0

w4 window rolling_4:  93%|▉| 186/200 [00:20<00:01,  9.31round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 187/200 [00:20<00:01,  9.25round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 187/200 [00:20<00:01,  9.25round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 188/200 [00:20<00:01,  9.32round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 188/200 [00:20<00:01,  9.32round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 189/200 [00:20<00:01,  9.34round/s, val_excess=0.0

w4 window rolling_4:  94%|▉| 189/200 [00:20<00:01,  9.34round/s, val_excess=0.0

w4 window rolling_4:  95%|▉| 190/200 [00:20<00:01,  9.32round/s, val_excess=0.0

w4 window rolling_4:  95%|▉| 190/200 [00:20<00:01,  9.32round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 191/200 [00:20<00:00,  9.33round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 191/200 [00:20<00:00,  9.33round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 192/200 [00:20<00:00,  9.27round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 192/200 [00:20<00:00,  9.27round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.22round/s, val_excess=0.0

w4 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.22round/s, val_excess=0.0

w4 window rolling_4:  97%|▉| 194/200 [00:21<00:00,  9.31round/s, val_excess=0.0

w4 window rolling_4:  97%|▉| 194/200 [00:21<00:00,  9.31round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 195/200 [00:21<00:00,  9.29round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 195/200 [00:21<00:00,  9.29round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 196/200 [00:21<00:00,  8.79round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 196/200 [00:21<00:00,  8.79round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 197/200 [00:21<00:00,  9.03round/s, val_excess=0.0

w4 window rolling_4:  98%|▉| 197/200 [00:21<00:00,  9.03round/s, val_excess=0.0

w4 window rolling_4:  99%|▉| 198/200 [00:21<00:00,  9.16round/s, val_excess=0.0

w4 window rolling_4:  99%|▉| 198/200 [00:21<00:00,  9.16round/s, val_excess=0.0

w4 window rolling_4: 100%|▉| 199/200 [00:21<00:00,  9.17round/s, val_excess=0.0

w4 window rolling_4: 100%|▉| 199/200 [00:21<00:00,  9.17round/s, val_excess=0.0

w4 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.24round/s, val_excess=0.0

w4 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.24round/s, val_excess=0.0

w4 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.19round/s, val_excess=0.0

2026-07-06 17:30:47 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=8 feature_type=window fold=rolling_1

2026-07-06 17:31:06 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=8 feature_type=window fold=rolling_1 features=69

w8 window rolling_1:   0%|                          | 0/200 [00:00<?, ?round/s]

w8 window rolling_1:   0%| | 1/200 [00:00<00:19, 10.02round/s, val_excess=0.012

w8 window rolling_1:   1%| | 2/200 [00:00<00:16, 11.76round/s, val_excess=0.012

w8 window rolling_1:   1%| | 2/200 [00:00<00:16, 11.76round/s, val_excess=-0.01

w8 window rolling_1:   2%| | 3/200 [00:00<00:16, 11.76round/s, val_excess=0.017

w8 window rolling_1:   2%| | 4/200 [00:00<00:15, 12.33round/s, val_excess=0.017

w8 window rolling_1:   2%| | 4/200 [00:00<00:15, 12.33round/s, val_excess=-0.00

w8 window rolling_1:   2%| | 5/200 [00:00<00:15, 12.33round/s, val_excess=0.006

w8 window rolling_1:   3%| | 6/200 [00:00<00:15, 12.27round/s, val_excess=0.006

w8 window rolling_1:   3%| | 6/200 [00:00<00:15, 12.27round/s, val_excess=-0.00

w8 window rolling_1:   4%| | 7/200 [00:00<00:15, 12.27round/s, val_excess=-0.00

w8 window rolling_1:   4%| | 8/200 [00:00<00:15, 12.05round/s, val_excess=-0.00

w8 window rolling_1:   4%| | 8/200 [00:00<00:15, 12.05round/s, val_excess=-0.01

w8 window rolling_1:   4%| | 9/200 [00:00<00:15, 12.05round/s, val_excess=-0.01

w8 window rolling_1:   5%| | 10/200 [00:00<00:16, 11.51round/s, val_excess=-0.0

w8 window rolling_1:   5%| | 10/200 [00:00<00:16, 11.51round/s, val_excess=-0.0

w8 window rolling_1:   6%| | 11/200 [00:00<00:16, 11.51round/s, val_excess=-0.0

w8 window rolling_1:   6%| | 12/200 [00:01<00:16, 11.34round/s, val_excess=-0.0

w8 window rolling_1:   6%| | 12/200 [00:01<00:16, 11.34round/s, val_excess=-0.0

w8 window rolling_1:   6%| | 13/200 [00:01<00:16, 11.34round/s, val_excess=-0.0

w8 window rolling_1:   7%| | 14/200 [00:01<00:16, 11.05round/s, val_excess=-0.0

w8 window rolling_1:   7%| | 14/200 [00:01<00:16, 11.05round/s, val_excess=-0.0

w8 window rolling_1:   8%| | 15/200 [00:01<00:16, 11.05round/s, val_excess=-0.0

w8 window rolling_1:   8%| | 16/200 [00:01<00:16, 10.92round/s, val_excess=-0.0

w8 window rolling_1:   8%| | 16/200 [00:01<00:16, 10.92round/s, val_excess=-0.0

w8 window rolling_1:   8%| | 17/200 [00:01<00:16, 10.92round/s, val_excess=-0.0

w8 window rolling_1:   9%| | 18/200 [00:01<00:16, 10.84round/s, val_excess=-0.0

w8 window rolling_1:   9%| | 18/200 [00:01<00:16, 10.84round/s, val_excess=-0.0

w8 window rolling_1:  10%| | 19/200 [00:01<00:16, 10.84round/s, val_excess=-0.0

w8 window rolling_1:  10%| | 20/200 [00:01<00:16, 10.72round/s, val_excess=-0.0

w8 window rolling_1:  10%| | 20/200 [00:01<00:16, 10.72round/s, val_excess=-0.0

w8 window rolling_1:  10%| | 21/200 [00:01<00:16, 10.72round/s, val_excess=-0.0

w8 window rolling_1:  11%| | 22/200 [00:01<00:16, 10.65round/s, val_excess=-0.0

w8 window rolling_1:  11%| | 22/200 [00:01<00:16, 10.65round/s, val_excess=-0.0

w8 window rolling_1:  12%| | 23/200 [00:02<00:16, 10.65round/s, val_excess=-0.0

w8 window rolling_1:  12%| | 24/200 [00:02<00:16, 10.63round/s, val_excess=-0.0

w8 window rolling_1:  12%| | 24/200 [00:02<00:16, 10.63round/s, val_excess=-0.0

w8 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.63round/s, val_excess=-0.0

w8 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.61round/s, val_excess=-0.0

w8 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.61round/s, val_excess=-0.0

w8 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.61round/s, val_excess=-0.0

w8 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.57round/s, val_excess=-0.0

w8 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.57round/s, val_excess=-0.0

w8 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.57round/s, val_excess=-0.0

w8 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.48round/s, val_excess=-0.0

w8 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.48round/s, val_excess=-0.0

w8 window rolling_1:  16%|▏| 31/200 [00:02<00:16, 10.48round/s, val_excess=-0.0

w8 window rolling_1:  16%|▏| 32/200 [00:02<00:16, 10.44round/s, val_excess=-0.0

w8 window rolling_1:  16%|▏| 32/200 [00:02<00:16, 10.44round/s, val_excess=-0.0

w8 window rolling_1:  16%|▏| 33/200 [00:03<00:15, 10.44round/s, val_excess=-0.0

w8 window rolling_1:  17%|▏| 34/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  17%|▏| 34/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  18%|▏| 35/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  18%|▏| 36/200 [00:03<00:15, 10.42round/s, val_excess=-0.0

w8 window rolling_1:  18%|▏| 36/200 [00:03<00:15, 10.42round/s, val_excess=-0.0

w8 window rolling_1:  18%|▏| 37/200 [00:03<00:15, 10.42round/s, val_excess=-0.0

w8 window rolling_1:  19%|▏| 38/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  19%|▏| 38/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  20%|▏| 39/200 [00:03<00:15, 10.40round/s, val_excess=-0.0

w8 window rolling_1:  20%|▏| 40/200 [00:03<00:15, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  20%|▏| 40/200 [00:03<00:15, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  20%|▏| 41/200 [00:03<00:15, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  21%|▏| 42/200 [00:03<00:15, 10.33round/s, val_excess=-0.0

w8 window rolling_1:  21%|▏| 42/200 [00:03<00:15, 10.33round/s, val_excess=-0.0

w8 window rolling_1:  22%|▏| 43/200 [00:03<00:15, 10.33round/s, val_excess=-0.0

w8 window rolling_1:  22%|▏| 44/200 [00:04<00:15, 10.34round/s, val_excess=-0.0

w8 window rolling_1:  22%|▏| 44/200 [00:04<00:15, 10.34round/s, val_excess=-0.0

w8 window rolling_1:  22%|▏| 45/200 [00:04<00:14, 10.34round/s, val_excess=-0.0

w8 window rolling_1:  23%|▏| 46/200 [00:04<00:15, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  23%|▏| 46/200 [00:04<00:15, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  24%|▏| 47/200 [00:04<00:14, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  24%|▏| 48/200 [00:04<00:14, 10.29round/s, val_excess=-0.0

w8 window rolling_1:  24%|▏| 48/200 [00:04<00:14, 10.29round/s, val_excess=-0.0

w8 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.29round/s, val_excess=-0.0

w8 window rolling_1:  25%|▎| 50/200 [00:04<00:14, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  25%|▎| 50/200 [00:04<00:14, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  26%|▎| 51/200 [00:04<00:14, 10.36round/s, val_excess=-0.0

w8 window rolling_1:  26%|▎| 52/200 [00:04<00:15,  9.83round/s, val_excess=-0.0

w8 window rolling_1:  26%|▎| 52/200 [00:04<00:15,  9.83round/s, val_excess=-0.0

w8 window rolling_1:  26%|▎| 53/200 [00:05<00:15,  9.64round/s, val_excess=-0.0

w8 window rolling_1:  26%|▎| 53/200 [00:05<00:15,  9.64round/s, val_excess=-0.0

w8 window rolling_1:  27%|▎| 54/200 [00:05<00:15,  9.48round/s, val_excess=-0.0

w8 window rolling_1:  27%|▎| 54/200 [00:05<00:15,  9.48round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 55/200 [00:05<00:15,  9.36round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 55/200 [00:05<00:15,  9.36round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 56/200 [00:05<00:15,  9.48round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 56/200 [00:05<00:15,  9.48round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 57/200 [00:05<00:15,  9.30round/s, val_excess=-0.0

w8 window rolling_1:  28%|▎| 57/200 [00:05<00:15,  9.30round/s, val_excess=-0.0

w8 window rolling_1:  29%|▎| 58/200 [00:05<00:15,  9.18round/s, val_excess=-0.0

w8 window rolling_1:  29%|▎| 58/200 [00:05<00:15,  9.18round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 59/200 [00:05<00:15,  9.07round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 59/200 [00:05<00:15,  9.07round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 60/200 [00:05<00:15,  8.99round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 60/200 [00:05<00:15,  8.99round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 61/200 [00:05<00:15,  8.97round/s, val_excess=-0.0

w8 window rolling_1:  30%|▎| 61/200 [00:05<00:15,  8.97round/s, val_excess=-0.0

w8 window rolling_1:  31%|▎| 62/200 [00:06<00:15,  8.92round/s, val_excess=-0.0

w8 window rolling_1:  31%|▎| 62/200 [00:06<00:15,  8.92round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 63/200 [00:06<00:15,  9.12round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 63/200 [00:06<00:15,  9.12round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.16round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 64/200 [00:06<00:14,  9.16round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 65/200 [00:06<00:14,  9.20round/s, val_excess=-0.0

w8 window rolling_1:  32%|▎| 65/200 [00:06<00:14,  9.20round/s, val_excess=-0.0

w8 window rolling_1:  33%|▎| 66/200 [00:06<00:14,  9.11round/s, val_excess=-0.0

w8 window rolling_1:  33%|▎| 66/200 [00:06<00:14,  9.11round/s, val_excess=-0.0

w8 window rolling_1:  34%|▎| 67/200 [00:06<00:14,  9.10round/s, val_excess=-0.0

w8 window rolling_1:  34%|▎| 67/200 [00:06<00:14,  9.10round/s, val_excess=-0.0

w8 window rolling_1:  34%|▎| 68/200 [00:06<00:14,  9.10round/s, val_excess=-0.0

w8 window rolling_1:  34%|▎| 69/200 [00:06<00:13,  9.41round/s, val_excess=-0.0

w8 window rolling_1:  34%|▎| 69/200 [00:06<00:13,  9.41round/s, val_excess=-0.0

w8 window rolling_1:  35%|▎| 70/200 [00:06<00:13,  9.41round/s, val_excess=-0.0

w8 window rolling_1:  36%|▎| 71/200 [00:06<00:13,  9.68round/s, val_excess=-0.0

w8 window rolling_1:  36%|▎| 71/200 [00:06<00:13,  9.68round/s, val_excess=-0.0

w8 window rolling_1:  36%|▎| 72/200 [00:07<00:13,  9.74round/s, val_excess=-0.0

w8 window rolling_1:  36%|▎| 72/200 [00:07<00:13,  9.74round/s, val_excess=-0.0

w8 window rolling_1:  36%|▎| 73/200 [00:07<00:13,  9.74round/s, val_excess=-0.0

w8 window rolling_1:  37%|▎| 74/200 [00:07<00:12,  9.99round/s, val_excess=-0.0

w8 window rolling_1:  37%|▎| 74/200 [00:07<00:12,  9.99round/s, val_excess=-0.0

w8 window rolling_1:  38%|▍| 75/200 [00:07<00:12,  9.99round/s, val_excess=-0.0

w8 window rolling_1:  38%|▍| 76/200 [00:07<00:12, 10.00round/s, val_excess=-0.0

w8 window rolling_1:  38%|▍| 76/200 [00:07<00:12, 10.00round/s, val_excess=-0.0

w8 window rolling_1:  38%|▍| 77/200 [00:07<00:12, 10.00round/s, val_excess=-0.0

w8 window rolling_1:  39%|▍| 78/200 [00:07<00:12, 10.15round/s, val_excess=-0.0

w8 window rolling_1:  39%|▍| 78/200 [00:07<00:12, 10.15round/s, val_excess=-0.0

w8 window rolling_1:  40%|▍| 79/200 [00:07<00:11, 10.15round/s, val_excess=-0.0

w8 window rolling_1:  40%|▍| 80/200 [00:07<00:11, 10.24round/s, val_excess=-0.0

w8 window rolling_1:  40%|▍| 80/200 [00:07<00:11, 10.24round/s, val_excess=-0.0

w8 window rolling_1:  40%|▍| 81/200 [00:07<00:11, 10.24round/s, val_excess=-0.0

w8 window rolling_1:  41%|▍| 82/200 [00:08<00:11, 10.21round/s, val_excess=-0.0

w8 window rolling_1:  41%|▍| 82/200 [00:08<00:11, 10.21round/s, val_excess=-0.0

w8 window rolling_1:  42%|▍| 83/200 [00:08<00:11, 10.21round/s, val_excess=-0.0

w8 window rolling_1:  42%|▍| 84/200 [00:08<00:11, 10.20round/s, val_excess=-0.0

w8 window rolling_1:  42%|▍| 84/200 [00:08<00:11, 10.20round/s, val_excess=-0.0

w8 window rolling_1:  42%|▍| 85/200 [00:08<00:11, 10.20round/s, val_excess=-0.0

w8 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.16round/s, val_excess=-0.0

w8 window rolling_1:  43%|▍| 86/200 [00:08<00:11, 10.16round/s, val_excess=-0.0

w8 window rolling_1:  44%|▍| 87/200 [00:08<00:11, 10.16round/s, val_excess=-0.0

w8 window rolling_1:  44%|▍| 88/200 [00:08<00:10, 10.28round/s, val_excess=-0.0

w8 window rolling_1:  44%|▍| 88/200 [00:08<00:10, 10.28round/s, val_excess=-0.0

w8 window rolling_1:  44%|▍| 89/200 [00:08<00:10, 10.28round/s, val_excess=-0.0

w8 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  46%|▍| 91/200 [00:08<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  46%|▍| 92/200 [00:09<00:10, 10.30round/s, val_excess=-0.0

w8 window rolling_1:  46%|▍| 92/200 [00:09<00:10, 10.30round/s, val_excess=-0.0

w8 window rolling_1:  46%|▍| 93/200 [00:09<00:10, 10.30round/s, val_excess=-0.0

w8 window rolling_1:  47%|▍| 94/200 [00:09<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  47%|▍| 94/200 [00:09<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  48%|▍| 95/200 [00:09<00:10, 10.27round/s, val_excess=-0.0

w8 window rolling_1:  48%|▍| 96/200 [00:09<00:10, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  48%|▍| 96/200 [00:09<00:10, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  48%|▍| 97/200 [00:09<00:10, 10.25round/s, val_excess=-0.0

w8 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.32round/s, val_excess=-0.0

w8 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.32round/s, val_excess=-0.0

w8 window rolling_1:  50%|▍| 99/200 [00:09<00:09, 10.32round/s, val_excess=-0.0

w8 window rolling_1:  50%|▌| 100/200 [00:09<00:09, 10.32round/s, val_excess=-0.

w8 window rolling_1:  50%|▌| 100/200 [00:09<00:09, 10.32round/s, val_excess=-0.

w8 window rolling_1:  50%|▌| 101/200 [00:09<00:09, 10.32round/s, val_excess=-0.

w8 window rolling_1:  51%|▌| 102/200 [00:09<00:09, 10.29round/s, val_excess=-0.

w8 window rolling_1:  51%|▌| 102/200 [00:09<00:09, 10.29round/s, val_excess=-0.

w8 window rolling_1:  52%|▌| 103/200 [00:10<00:09, 10.29round/s, val_excess=-0.

w8 window rolling_1:  52%|▌| 104/200 [00:10<00:09, 10.27round/s, val_excess=-0.

w8 window rolling_1:  52%|▌| 104/200 [00:10<00:09, 10.27round/s, val_excess=-0.

w8 window rolling_1:  52%|▌| 105/200 [00:10<00:09, 10.27round/s, val_excess=-0.

w8 window rolling_1:  53%|▌| 106/200 [00:10<00:09, 10.25round/s, val_excess=-0.

w8 window rolling_1:  53%|▌| 106/200 [00:10<00:09, 10.25round/s, val_excess=-0.

w8 window rolling_1:  54%|▌| 107/200 [00:10<00:09, 10.25round/s, val_excess=-0.

w8 window rolling_1:  54%|▌| 108/200 [00:10<00:09, 10.19round/s, val_excess=-0.

w8 window rolling_1:  54%|▌| 108/200 [00:10<00:09, 10.19round/s, val_excess=-0.

w8 window rolling_1:  55%|▌| 109/200 [00:10<00:08, 10.19round/s, val_excess=-0.

w8 window rolling_1:  55%|▌| 110/200 [00:10<00:08, 10.23round/s, val_excess=-0.

w8 window rolling_1:  55%|▌| 110/200 [00:10<00:08, 10.23round/s, val_excess=-0.

w8 window rolling_1:  56%|▌| 111/200 [00:10<00:08, 10.23round/s, val_excess=-0.

w8 window rolling_1:  56%|▌| 112/200 [00:10<00:08, 10.24round/s, val_excess=-0.

w8 window rolling_1:  56%|▌| 112/200 [00:10<00:08, 10.24round/s, val_excess=-0.

w8 window rolling_1:  56%|▌| 113/200 [00:11<00:08, 10.24round/s, val_excess=-0.

w8 window rolling_1:  57%|▌| 114/200 [00:11<00:08, 10.21round/s, val_excess=-0.

w8 window rolling_1:  57%|▌| 114/200 [00:11<00:08, 10.21round/s, val_excess=-0.

w8 window rolling_1:  57%|▌| 115/200 [00:11<00:08, 10.21round/s, val_excess=-0.

w8 window rolling_1:  58%|▌| 116/200 [00:11<00:08,  9.67round/s, val_excess=-0.

w8 window rolling_1:  58%|▌| 116/200 [00:11<00:08,  9.67round/s, val_excess=-0.

w8 window rolling_1:  58%|▌| 117/200 [00:11<00:08,  9.43round/s, val_excess=-0.

w8 window rolling_1:  58%|▌| 117/200 [00:11<00:08,  9.43round/s, val_excess=-0.

w8 window rolling_1:  59%|▌| 118/200 [00:11<00:08,  9.25round/s, val_excess=-0.

w8 window rolling_1:  59%|▌| 118/200 [00:11<00:08,  9.25round/s, val_excess=-0.

w8 window rolling_1:  60%|▌| 119/200 [00:11<00:08,  9.25round/s, val_excess=-0.

w8 window rolling_1:  60%|▌| 120/200 [00:11<00:08,  9.66round/s, val_excess=-0.

w8 window rolling_1:  60%|▌| 120/200 [00:11<00:08,  9.66round/s, val_excess=-0.

w8 window rolling_1:  60%|▌| 121/200 [00:11<00:08,  9.66round/s, val_excess=-0.

w8 window rolling_1:  61%|▌| 122/200 [00:12<00:07,  9.89round/s, val_excess=-0.

w8 window rolling_1:  61%|▌| 122/200 [00:12<00:07,  9.89round/s, val_excess=-0.

w8 window rolling_1:  62%|▌| 123/200 [00:12<00:07,  9.89round/s, val_excess=-0.

w8 window rolling_1:  62%|▌| 124/200 [00:12<00:07, 10.11round/s, val_excess=-0.

w8 window rolling_1:  62%|▌| 124/200 [00:12<00:07, 10.11round/s, val_excess=-0.

w8 window rolling_1:  62%|▋| 125/200 [00:12<00:07, 10.11round/s, val_excess=-0.

w8 window rolling_1:  63%|▋| 126/200 [00:12<00:07, 10.22round/s, val_excess=-0.

w8 window rolling_1:  63%|▋| 126/200 [00:12<00:07, 10.22round/s, val_excess=-0.

w8 window rolling_1:  64%|▋| 127/200 [00:12<00:07, 10.22round/s, val_excess=-0.

w8 window rolling_1:  64%|▋| 128/200 [00:12<00:07, 10.25round/s, val_excess=-0.

w8 window rolling_1:  64%|▋| 128/200 [00:12<00:07, 10.25round/s, val_excess=-0.

w8 window rolling_1:  64%|▋| 129/200 [00:12<00:06, 10.25round/s, val_excess=-0.

w8 window rolling_1:  65%|▋| 130/200 [00:12<00:07,  9.91round/s, val_excess=-0.

w8 window rolling_1:  65%|▋| 130/200 [00:12<00:07,  9.91round/s, val_excess=-0.

w8 window rolling_1:  66%|▋| 131/200 [00:12<00:06,  9.91round/s, val_excess=-0.

w8 window rolling_1:  66%|▋| 132/200 [00:12<00:06, 10.03round/s, val_excess=-0.

w8 window rolling_1:  66%|▋| 132/200 [00:12<00:06, 10.03round/s, val_excess=-0.

w8 window rolling_1:  66%|▋| 133/200 [00:13<00:06, 10.03round/s, val_excess=-0.

w8 window rolling_1:  67%|▋| 134/200 [00:13<00:06, 10.16round/s, val_excess=-0.

w8 window rolling_1:  67%|▋| 134/200 [00:13<00:06, 10.16round/s, val_excess=-0.

w8 window rolling_1:  68%|▋| 135/200 [00:13<00:06, 10.16round/s, val_excess=-0.

w8 window rolling_1:  68%|▋| 136/200 [00:13<00:06, 10.19round/s, val_excess=-0.

w8 window rolling_1:  68%|▋| 136/200 [00:13<00:06, 10.19round/s, val_excess=-0.

w8 window rolling_1:  68%|▋| 137/200 [00:13<00:06, 10.19round/s, val_excess=-0.

w8 window rolling_1:  69%|▋| 138/200 [00:13<00:06, 10.19round/s, val_excess=-0.

w8 window rolling_1:  69%|▋| 138/200 [00:13<00:06, 10.19round/s, val_excess=-0.

w8 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.19round/s, val_excess=-0.

w8 window rolling_1:  70%|▋| 140/200 [00:13<00:05, 10.17round/s, val_excess=-0.

w8 window rolling_1:  70%|▋| 140/200 [00:13<00:05, 10.17round/s, val_excess=-0.

w8 window rolling_1:  70%|▋| 141/200 [00:13<00:05, 10.17round/s, val_excess=-0.

w8 window rolling_1:  71%|▋| 142/200 [00:13<00:05, 10.21round/s, val_excess=-0.

w8 window rolling_1:  71%|▋| 142/200 [00:13<00:05, 10.21round/s, val_excess=-0.

w8 window rolling_1:  72%|▋| 143/200 [00:14<00:05, 10.21round/s, val_excess=-0.

w8 window rolling_1:  72%|▋| 144/200 [00:14<00:05, 10.19round/s, val_excess=-0.

w8 window rolling_1:  72%|▋| 144/200 [00:14<00:05, 10.19round/s, val_excess=-0.

w8 window rolling_1:  72%|▋| 145/200 [00:14<00:05, 10.19round/s, val_excess=-0.

w8 window rolling_1:  73%|▋| 146/200 [00:14<00:05, 10.28round/s, val_excess=-0.

w8 window rolling_1:  73%|▋| 146/200 [00:14<00:05, 10.28round/s, val_excess=-0.

w8 window rolling_1:  74%|▋| 147/200 [00:14<00:05, 10.28round/s, val_excess=-0.

w8 window rolling_1:  74%|▋| 148/200 [00:14<00:05, 10.35round/s, val_excess=-0.

w8 window rolling_1:  74%|▋| 148/200 [00:14<00:05, 10.35round/s, val_excess=-0.

w8 window rolling_1:  74%|▋| 149/200 [00:14<00:04, 10.35round/s, val_excess=-0.

w8 window rolling_1:  75%|▊| 150/200 [00:14<00:04, 10.37round/s, val_excess=-0.

w8 window rolling_1:  75%|▊| 150/200 [00:14<00:04, 10.37round/s, val_excess=-0.

w8 window rolling_1:  76%|▊| 151/200 [00:14<00:04, 10.37round/s, val_excess=-0.

w8 window rolling_1:  76%|▊| 152/200 [00:14<00:04, 10.34round/s, val_excess=-0.

w8 window rolling_1:  76%|▊| 152/200 [00:14<00:04, 10.34round/s, val_excess=-0.

w8 window rolling_1:  76%|▊| 153/200 [00:15<00:04, 10.34round/s, val_excess=-0.

w8 window rolling_1:  77%|▊| 154/200 [00:15<00:04, 10.30round/s, val_excess=-0.

w8 window rolling_1:  77%|▊| 154/200 [00:15<00:04, 10.30round/s, val_excess=-0.

w8 window rolling_1:  78%|▊| 155/200 [00:15<00:04, 10.30round/s, val_excess=-0.

w8 window rolling_1:  78%|▊| 156/200 [00:15<00:04, 10.31round/s, val_excess=-0.

w8 window rolling_1:  78%|▊| 156/200 [00:15<00:04, 10.31round/s, val_excess=-0.

w8 window rolling_1:  78%|▊| 157/200 [00:15<00:04, 10.31round/s, val_excess=-0.

w8 window rolling_1:  79%|▊| 158/200 [00:15<00:04, 10.34round/s, val_excess=-0.

w8 window rolling_1:  79%|▊| 158/200 [00:15<00:04, 10.34round/s, val_excess=-0.

w8 window rolling_1:  80%|▊| 159/200 [00:15<00:03, 10.34round/s, val_excess=-0.

w8 window rolling_1:  80%|▊| 160/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  80%|▊| 160/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  80%|▊| 161/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  81%|▊| 162/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  81%|▊| 162/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  82%|▊| 163/200 [00:15<00:03, 10.31round/s, val_excess=-0.

w8 window rolling_1:  82%|▊| 164/200 [00:16<00:03, 10.35round/s, val_excess=-0.

w8 window rolling_1:  82%|▊| 164/200 [00:16<00:03, 10.35round/s, val_excess=-0.

w8 window rolling_1:  82%|▊| 165/200 [00:16<00:03, 10.35round/s, val_excess=-0.

w8 window rolling_1:  83%|▊| 166/200 [00:16<00:03, 10.32round/s, val_excess=-0.

w8 window rolling_1:  83%|▊| 166/200 [00:16<00:03, 10.32round/s, val_excess=-0.

w8 window rolling_1:  84%|▊| 167/200 [00:16<00:03, 10.32round/s, val_excess=-0.

w8 window rolling_1:  84%|▊| 168/200 [00:16<00:03, 10.37round/s, val_excess=-0.

w8 window rolling_1:  84%|▊| 168/200 [00:16<00:03, 10.37round/s, val_excess=-0.

w8 window rolling_1:  84%|▊| 169/200 [00:16<00:02, 10.37round/s, val_excess=-0.

w8 window rolling_1:  85%|▊| 170/200 [00:16<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  85%|▊| 170/200 [00:16<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  86%|▊| 171/200 [00:16<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  86%|▊| 172/200 [00:16<00:02, 10.30round/s, val_excess=-0.

w8 window rolling_1:  86%|▊| 172/200 [00:16<00:02, 10.30round/s, val_excess=-0.

w8 window rolling_1:  86%|▊| 173/200 [00:16<00:02, 10.30round/s, val_excess=-0.

w8 window rolling_1:  87%|▊| 174/200 [00:17<00:02, 10.31round/s, val_excess=-0.

w8 window rolling_1:  87%|▊| 174/200 [00:17<00:02, 10.31round/s, val_excess=-0.

w8 window rolling_1:  88%|▉| 175/200 [00:17<00:02, 10.31round/s, val_excess=-0.

w8 window rolling_1:  88%|▉| 176/200 [00:17<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  88%|▉| 176/200 [00:17<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  88%|▉| 177/200 [00:17<00:02, 10.33round/s, val_excess=-0.

w8 window rolling_1:  89%|▉| 178/200 [00:17<00:02, 10.35round/s, val_excess=-0.

w8 window rolling_1:  89%|▉| 178/200 [00:17<00:02, 10.35round/s, val_excess=-0.

w8 window rolling_1:  90%|▉| 179/200 [00:17<00:02, 10.35round/s, val_excess=-0.

w8 window rolling_1:  90%|▉| 180/200 [00:17<00:01, 10.29round/s, val_excess=-0.

w8 window rolling_1:  90%|▉| 180/200 [00:17<00:01, 10.29round/s, val_excess=-0.

w8 window rolling_1:  90%|▉| 181/200 [00:17<00:01, 10.29round/s, val_excess=-0.

w8 window rolling_1:  91%|▉| 182/200 [00:17<00:01, 10.34round/s, val_excess=-0.

w8 window rolling_1:  91%|▉| 182/200 [00:17<00:01, 10.34round/s, val_excess=-0.

w8 window rolling_1:  92%|▉| 183/200 [00:17<00:01, 10.34round/s, val_excess=-0.

w8 window rolling_1:  92%|▉| 184/200 [00:18<00:01, 10.37round/s, val_excess=-0.

w8 window rolling_1:  92%|▉| 184/200 [00:18<00:01, 10.37round/s, val_excess=-0.

w8 window rolling_1:  92%|▉| 185/200 [00:18<00:01, 10.37round/s, val_excess=-0.

w8 window rolling_1:  93%|▉| 186/200 [00:18<00:01, 10.21round/s, val_excess=-0.

w8 window rolling_1:  93%|▉| 186/200 [00:18<00:01, 10.21round/s, val_excess=-0.

w8 window rolling_1:  94%|▉| 187/200 [00:18<00:01, 10.21round/s, val_excess=-0.

w8 window rolling_1:  94%|▉| 188/200 [00:18<00:01, 10.06round/s, val_excess=-0.

w8 window rolling_1:  94%|▉| 188/200 [00:18<00:01, 10.06round/s, val_excess=-0.

w8 window rolling_1:  94%|▉| 189/200 [00:18<00:01, 10.06round/s, val_excess=-0.

w8 window rolling_1:  95%|▉| 190/200 [00:18<00:00, 10.08round/s, val_excess=-0.

w8 window rolling_1:  95%|▉| 190/200 [00:18<00:00, 10.08round/s, val_excess=-0.

w8 window rolling_1:  96%|▉| 191/200 [00:18<00:00, 10.08round/s, val_excess=-0.

w8 window rolling_1:  96%|▉| 192/200 [00:18<00:00, 10.04round/s, val_excess=-0.

w8 window rolling_1:  96%|▉| 192/200 [00:18<00:00, 10.04round/s, val_excess=-0.

w8 window rolling_1:  96%|▉| 193/200 [00:18<00:00, 10.04round/s, val_excess=-0.

w8 window rolling_1:  97%|▉| 194/200 [00:19<00:00, 10.22round/s, val_excess=-0.

w8 window rolling_1:  97%|▉| 194/200 [00:19<00:00, 10.22round/s, val_excess=-0.

w8 window rolling_1:  98%|▉| 195/200 [00:19<00:00, 10.22round/s, val_excess=-0.

w8 window rolling_1:  98%|▉| 196/200 [00:19<00:00, 10.09round/s, val_excess=-0.

w8 window rolling_1:  98%|▉| 196/200 [00:19<00:00, 10.09round/s, val_excess=-0.

w8 window rolling_1:  98%|▉| 197/200 [00:19<00:00, 10.09round/s, val_excess=-0.

w8 window rolling_1:  99%|▉| 198/200 [00:19<00:00, 10.16round/s, val_excess=-0.

w8 window rolling_1:  99%|▉| 198/200 [00:19<00:00, 10.16round/s, val_excess=-0.

w8 window rolling_1: 100%|▉| 199/200 [00:19<00:00, 10.16round/s, val_excess=-0.

w8 window rolling_1: 100%|█| 200/200 [00:19<00:00, 10.13round/s, val_excess=-0.

w8 window rolling_1: 100%|█| 200/200 [00:19<00:00, 10.13round/s, val_excess=-0.

w8 window rolling_1: 100%|█| 200/200 [00:19<00:00, 10.19round/s, val_excess=-0.

2026-07-06 17:31:26 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=8 feature_type=window fold=rolling_2

2026-07-06 17:31:46 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=8 feature_type=window fold=rolling_2 features=69

w8 window rolling_2:   0%|                          | 0/200 [00:00<?, ?round/s]

w8 window rolling_2:   0%|                  | 1/200 [00:00<00:21,  9.10round/s]

w8 window rolling_2:   0%| | 1/200 [00:00<00:21,  9.10round/s, val_excess=0.003

w8 window rolling_2:   1%| | 2/200 [00:00<00:21,  9.10round/s, val_excess=0.014

w8 window rolling_2:   2%| | 3/200 [00:00<00:17, 11.36round/s, val_excess=0.014

w8 window rolling_2:   2%| | 3/200 [00:00<00:17, 11.36round/s, val_excess=-0.00

w8 window rolling_2:   2%| | 4/200 [00:00<00:17, 11.36round/s, val_excess=-0.00

w8 window rolling_2:   2%| | 5/200 [00:00<00:17, 11.32round/s, val_excess=-0.00

w8 window rolling_2:   2%| | 5/200 [00:00<00:17, 11.32round/s, val_excess=0.000

w8 window rolling_2:   3%| | 6/200 [00:00<00:17, 11.32round/s, val_excess=0.011

w8 window rolling_2:   4%| | 7/200 [00:00<00:17, 11.27round/s, val_excess=0.011

w8 window rolling_2:   4%| | 7/200 [00:00<00:17, 11.27round/s, val_excess=0.013

w8 window rolling_2:   4%| | 8/200 [00:00<00:17, 11.27round/s, val_excess=0.009

w8 window rolling_2:   4%| | 9/200 [00:00<00:17, 11.07round/s, val_excess=0.009

w8 window rolling_2:   4%| | 9/200 [00:00<00:17, 11.07round/s, val_excess=0.008

w8 window rolling_2:   5%| | 10/200 [00:00<00:17, 11.07round/s, val_excess=0.01

w8 window rolling_2:   6%| | 11/200 [00:01<00:17, 10.92round/s, val_excess=0.01

w8 window rolling_2:   6%| | 11/200 [00:01<00:17, 10.92round/s, val_excess=0.01

w8 window rolling_2:   6%| | 12/200 [00:01<00:17, 10.92round/s, val_excess=0.01

w8 window rolling_2:   6%| | 13/200 [00:01<00:17, 10.72round/s, val_excess=0.01

w8 window rolling_2:   6%| | 13/200 [00:01<00:17, 10.72round/s, val_excess=0.01

w8 window rolling_2:   7%| | 14/200 [00:01<00:17, 10.72round/s, val_excess=0.01

w8 window rolling_2:   8%| | 15/200 [00:01<00:17, 10.55round/s, val_excess=0.01

w8 window rolling_2:   8%| | 15/200 [00:01<00:17, 10.55round/s, val_excess=0.01

w8 window rolling_2:   8%| | 16/200 [00:01<00:17, 10.55round/s, val_excess=0.01

w8 window rolling_2:   8%| | 17/200 [00:01<00:17, 10.50round/s, val_excess=0.01

w8 window rolling_2:   8%| | 17/200 [00:01<00:17, 10.50round/s, val_excess=0.01

w8 window rolling_2:   9%| | 18/200 [00:01<00:17, 10.50round/s, val_excess=0.01

w8 window rolling_2:  10%| | 19/200 [00:01<00:17, 10.44round/s, val_excess=0.01

w8 window rolling_2:  10%| | 19/200 [00:01<00:17, 10.44round/s, val_excess=0.01

w8 window rolling_2:  10%| | 20/200 [00:01<00:17, 10.44round/s, val_excess=0.01

w8 window rolling_2:  10%| | 21/200 [00:01<00:17, 10.36round/s, val_excess=0.01

w8 window rolling_2:  10%| | 21/200 [00:01<00:17, 10.36round/s, val_excess=0.01

w8 window rolling_2:  11%| | 22/200 [00:02<00:17, 10.36round/s, val_excess=0.01

w8 window rolling_2:  12%| | 23/200 [00:02<00:17, 10.23round/s, val_excess=0.01

w8 window rolling_2:  12%| | 23/200 [00:02<00:17, 10.23round/s, val_excess=0.01

w8 window rolling_2:  12%| | 24/200 [00:02<00:17, 10.23round/s, val_excess=0.01

w8 window rolling_2:  12%|▏| 25/200 [00:02<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_2:  12%|▏| 25/200 [00:02<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_2:  13%|▏| 26/200 [00:02<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_2:  14%|▏| 27/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_2:  14%|▏| 27/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_2:  14%|▏| 28/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_2:  14%|▏| 29/200 [00:02<00:17,  9.95round/s, val_excess=0.01

w8 window rolling_2:  14%|▏| 29/200 [00:02<00:17,  9.95round/s, val_excess=0.01

w8 window rolling_2:  15%|▏| 30/200 [00:02<00:17,  9.95round/s, val_excess=0.02

w8 window rolling_2:  16%|▏| 31/200 [00:02<00:16,  9.97round/s, val_excess=0.02

w8 window rolling_2:  16%|▏| 31/200 [00:02<00:16,  9.97round/s, val_excess=0.01

w8 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.22round/s, val_excess=0.01

w8 window rolling_2:  16%|▏| 32/200 [00:03<00:18,  9.22round/s, val_excess=0.01

w8 window rolling_2:  16%|▏| 33/200 [00:03<00:18,  9.22round/s, val_excess=0.02

w8 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  8.85round/s, val_excess=0.02

w8 window rolling_2:  17%|▏| 34/200 [00:03<00:18,  8.85round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 35/200 [00:03<00:18,  9.00round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 35/200 [00:03<00:18,  9.00round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 36/200 [00:03<00:19,  8.42round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 36/200 [00:03<00:19,  8.42round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 37/200 [00:03<00:19,  8.40round/s, val_excess=0.02

w8 window rolling_2:  18%|▏| 37/200 [00:03<00:19,  8.40round/s, val_excess=0.02

w8 window rolling_2:  19%|▏| 38/200 [00:03<00:18,  8.63round/s, val_excess=0.02

w8 window rolling_2:  19%|▏| 38/200 [00:03<00:18,  8.63round/s, val_excess=0.02

w8 window rolling_2:  20%|▏| 39/200 [00:03<00:18,  8.89round/s, val_excess=0.02

w8 window rolling_2:  20%|▏| 39/200 [00:03<00:18,  8.89round/s, val_excess=0.01

w8 window rolling_2:  20%|▏| 40/200 [00:04<00:17,  9.15round/s, val_excess=0.01

w8 window rolling_2:  20%|▏| 40/200 [00:04<00:17,  9.15round/s, val_excess=0.02

w8 window rolling_2:  20%|▏| 41/200 [00:04<00:17,  9.15round/s, val_excess=0.01

w8 window rolling_2:  21%|▏| 42/200 [00:04<00:16,  9.57round/s, val_excess=0.01

w8 window rolling_2:  21%|▏| 42/200 [00:04<00:16,  9.57round/s, val_excess=0.01

w8 window rolling_2:  22%|▏| 43/200 [00:04<00:16,  9.65round/s, val_excess=0.01

w8 window rolling_2:  22%|▏| 43/200 [00:04<00:16,  9.65round/s, val_excess=0.01

w8 window rolling_2:  22%|▏| 44/200 [00:04<00:16,  9.65round/s, val_excess=0.02

w8 window rolling_2:  22%|▏| 45/200 [00:04<00:15,  9.86round/s, val_excess=0.02

w8 window rolling_2:  22%|▏| 45/200 [00:04<00:15,  9.86round/s, val_excess=0.02

w8 window rolling_2:  23%|▏| 46/200 [00:04<00:15,  9.87round/s, val_excess=0.02

w8 window rolling_2:  23%|▏| 46/200 [00:04<00:15,  9.87round/s, val_excess=0.02

w8 window rolling_2:  24%|▏| 47/200 [00:04<00:15,  9.87round/s, val_excess=0.02

w8 window rolling_2:  24%|▏| 48/200 [00:04<00:15,  9.99round/s, val_excess=0.02

w8 window rolling_2:  24%|▏| 48/200 [00:04<00:15,  9.99round/s, val_excess=0.02

w8 window rolling_2:  24%|▏| 49/200 [00:04<00:15,  9.93round/s, val_excess=0.02

w8 window rolling_2:  24%|▏| 49/200 [00:04<00:15,  9.93round/s, val_excess=0.02

w8 window rolling_2:  25%|▎| 50/200 [00:05<00:15,  9.93round/s, val_excess=0.02

w8 window rolling_2:  26%|▎| 51/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_2:  26%|▎| 51/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_2:  26%|▎| 52/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_2:  26%|▎| 53/200 [00:05<00:14, 10.00round/s, val_excess=0.02

w8 window rolling_2:  26%|▎| 53/200 [00:05<00:14, 10.00round/s, val_excess=0.02

w8 window rolling_2:  27%|▎| 54/200 [00:05<00:14, 10.00round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 55/200 [00:05<00:14, 10.00round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 55/200 [00:05<00:14, 10.00round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 56/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 56/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 57/200 [00:05<00:14,  9.96round/s, val_excess=0.02

w8 window rolling_2:  28%|▎| 57/200 [00:05<00:14,  9.96round/s, val_excess=0.02

w8 window rolling_2:  29%|▎| 58/200 [00:05<00:14,  9.96round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 59/200 [00:05<00:14,  9.96round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 59/200 [00:05<00:14,  9.96round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 60/200 [00:06<00:14,  9.90round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 60/200 [00:06<00:14,  9.90round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 61/200 [00:06<00:14,  9.91round/s, val_excess=0.02

w8 window rolling_2:  30%|▎| 61/200 [00:06<00:14,  9.91round/s, val_excess=0.01

w8 window rolling_2:  31%|▎| 62/200 [00:06<00:13,  9.91round/s, val_excess=0.01

w8 window rolling_2:  32%|▎| 63/200 [00:06<00:13,  9.95round/s, val_excess=0.01

w8 window rolling_2:  32%|▎| 63/200 [00:06<00:13,  9.95round/s, val_excess=0.01

w8 window rolling_2:  32%|▎| 64/200 [00:06<00:13,  9.95round/s, val_excess=0.01

w8 window rolling_2:  32%|▎| 65/200 [00:06<00:13, 10.11round/s, val_excess=0.01

w8 window rolling_2:  32%|▎| 65/200 [00:06<00:13, 10.11round/s, val_excess=0.01

w8 window rolling_2:  33%|▎| 66/200 [00:06<00:13, 10.11round/s, val_excess=0.02

w8 window rolling_2:  34%|▎| 67/200 [00:06<00:13, 10.17round/s, val_excess=0.02

w8 window rolling_2:  34%|▎| 67/200 [00:06<00:13, 10.17round/s, val_excess=0.01

w8 window rolling_2:  34%|▎| 68/200 [00:06<00:12, 10.17round/s, val_excess=0.02

w8 window rolling_2:  34%|▎| 69/200 [00:06<00:12, 10.21round/s, val_excess=0.02

w8 window rolling_2:  34%|▎| 69/200 [00:06<00:12, 10.21round/s, val_excess=0.02

w8 window rolling_2:  35%|▎| 70/200 [00:07<00:12, 10.21round/s, val_excess=0.01

w8 window rolling_2:  36%|▎| 71/200 [00:07<00:12, 10.16round/s, val_excess=0.01

w8 window rolling_2:  36%|▎| 71/200 [00:07<00:12, 10.16round/s, val_excess=0.01

w8 window rolling_2:  36%|▎| 72/200 [00:07<00:12, 10.16round/s, val_excess=0.02

w8 window rolling_2:  36%|▎| 73/200 [00:07<00:12, 10.16round/s, val_excess=0.02

w8 window rolling_2:  36%|▎| 73/200 [00:07<00:12, 10.16round/s, val_excess=0.01

w8 window rolling_2:  37%|▎| 74/200 [00:07<00:12, 10.16round/s, val_excess=0.01

w8 window rolling_2:  38%|▍| 75/200 [00:07<00:12, 10.17round/s, val_excess=0.01

w8 window rolling_2:  38%|▍| 75/200 [00:07<00:12, 10.17round/s, val_excess=0.02

w8 window rolling_2:  38%|▍| 76/200 [00:07<00:12, 10.17round/s, val_excess=0.02

w8 window rolling_2:  38%|▍| 77/200 [00:07<00:12, 10.13round/s, val_excess=0.02

w8 window rolling_2:  38%|▍| 77/200 [00:07<00:12, 10.13round/s, val_excess=0.01

w8 window rolling_2:  39%|▍| 78/200 [00:07<00:12, 10.13round/s, val_excess=0.01

w8 window rolling_2:  40%|▍| 79/200 [00:07<00:12, 10.01round/s, val_excess=0.01

w8 window rolling_2:  40%|▍| 79/200 [00:07<00:12, 10.01round/s, val_excess=0.01

w8 window rolling_2:  40%|▍| 80/200 [00:08<00:11, 10.01round/s, val_excess=0.01

w8 window rolling_2:  40%|▍| 81/200 [00:08<00:11, 10.12round/s, val_excess=0.01

w8 window rolling_2:  40%|▍| 81/200 [00:08<00:11, 10.12round/s, val_excess=0.01

w8 window rolling_2:  41%|▍| 82/200 [00:08<00:11, 10.12round/s, val_excess=0.01

w8 window rolling_2:  42%|▍| 83/200 [00:08<00:11, 10.14round/s, val_excess=0.01

w8 window rolling_2:  42%|▍| 83/200 [00:08<00:11, 10.14round/s, val_excess=0.01

w8 window rolling_2:  42%|▍| 84/200 [00:08<00:11, 10.14round/s, val_excess=0.01

w8 window rolling_2:  42%|▍| 85/200 [00:08<00:11, 10.09round/s, val_excess=0.01

w8 window rolling_2:  42%|▍| 85/200 [00:08<00:11, 10.09round/s, val_excess=0.01

w8 window rolling_2:  43%|▍| 86/200 [00:08<00:11, 10.09round/s, val_excess=0.01

w8 window rolling_2:  44%|▍| 87/200 [00:08<00:11, 10.11round/s, val_excess=0.01

w8 window rolling_2:  44%|▍| 87/200 [00:08<00:11, 10.11round/s, val_excess=0.01

w8 window rolling_2:  44%|▍| 88/200 [00:08<00:11, 10.11round/s, val_excess=0.01

w8 window rolling_2:  44%|▍| 89/200 [00:08<00:10, 10.16round/s, val_excess=0.01

w8 window rolling_2:  44%|▍| 89/200 [00:08<00:10, 10.16round/s, val_excess=0.02

w8 window rolling_2:  45%|▍| 90/200 [00:09<00:10, 10.16round/s, val_excess=0.02

w8 window rolling_2:  46%|▍| 91/200 [00:09<00:10, 10.19round/s, val_excess=0.02

w8 window rolling_2:  46%|▍| 91/200 [00:09<00:10, 10.19round/s, val_excess=0.01

w8 window rolling_2:  46%|▍| 92/200 [00:09<00:10, 10.19round/s, val_excess=0.02

w8 window rolling_2:  46%|▍| 93/200 [00:09<00:10, 10.15round/s, val_excess=0.02

w8 window rolling_2:  46%|▍| 93/200 [00:09<00:10, 10.15round/s, val_excess=0.02

w8 window rolling_2:  47%|▍| 94/200 [00:09<00:10, 10.15round/s, val_excess=0.02

w8 window rolling_2:  48%|▍| 95/200 [00:09<00:10, 10.15round/s, val_excess=0.02

w8 window rolling_2:  48%|▍| 95/200 [00:09<00:10, 10.15round/s, val_excess=0.02

w8 window rolling_2:  48%|▍| 96/200 [00:09<00:10, 10.15round/s, val_excess=0.01

w8 window rolling_2:  48%|▍| 97/200 [00:09<00:10, 10.13round/s, val_excess=0.01

w8 window rolling_2:  48%|▍| 97/200 [00:09<00:10, 10.13round/s, val_excess=0.01

w8 window rolling_2:  49%|▍| 98/200 [00:09<00:10, 10.13round/s, val_excess=0.01

w8 window rolling_2:  50%|▍| 99/200 [00:09<00:09, 10.15round/s, val_excess=0.01

w8 window rolling_2:  50%|▍| 99/200 [00:09<00:09, 10.15round/s, val_excess=0.01

w8 window rolling_2:  50%|▌| 100/200 [00:09<00:09, 10.15round/s, val_excess=0.0

w8 window rolling_2:  50%|▌| 101/200 [00:10<00:09, 10.14round/s, val_excess=0.0

w8 window rolling_2:  50%|▌| 101/200 [00:10<00:09, 10.14round/s, val_excess=0.0

w8 window rolling_2:  51%|▌| 102/200 [00:10<00:09, 10.14round/s, val_excess=0.0

w8 window rolling_2:  52%|▌| 103/200 [00:10<00:09, 10.18round/s, val_excess=0.0

w8 window rolling_2:  52%|▌| 103/200 [00:10<00:09, 10.18round/s, val_excess=0.0

w8 window rolling_2:  52%|▌| 104/200 [00:10<00:09, 10.18round/s, val_excess=0.0

w8 window rolling_2:  52%|▌| 105/200 [00:10<00:09, 10.05round/s, val_excess=0.0

w8 window rolling_2:  52%|▌| 105/200 [00:10<00:09, 10.05round/s, val_excess=0.0

w8 window rolling_2:  53%|▌| 106/200 [00:10<00:09, 10.05round/s, val_excess=0.0

w8 window rolling_2:  54%|▌| 107/200 [00:10<00:09,  9.96round/s, val_excess=0.0

w8 window rolling_2:  54%|▌| 107/200 [00:10<00:09,  9.96round/s, val_excess=0.0

w8 window rolling_2:  54%|▌| 108/200 [00:10<00:09,  9.93round/s, val_excess=0.0

w8 window rolling_2:  54%|▌| 108/200 [00:10<00:09,  9.93round/s, val_excess=0.0

w8 window rolling_2:  55%|▌| 109/200 [00:10<00:09,  9.88round/s, val_excess=0.0

w8 window rolling_2:  55%|▌| 109/200 [00:10<00:09,  9.88round/s, val_excess=0.0

w8 window rolling_2:  55%|▌| 110/200 [00:11<00:09,  9.86round/s, val_excess=0.0

w8 window rolling_2:  55%|▌| 110/200 [00:11<00:09,  9.86round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 111/200 [00:11<00:09,  9.83round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 111/200 [00:11<00:09,  9.83round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 112/200 [00:11<00:08,  9.79round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 112/200 [00:11<00:08,  9.79round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 113/200 [00:11<00:08,  9.78round/s, val_excess=0.0

w8 window rolling_2:  56%|▌| 113/200 [00:11<00:08,  9.78round/s, val_excess=0.0

w8 window rolling_2:  57%|▌| 114/200 [00:11<00:08,  9.78round/s, val_excess=0.0

w8 window rolling_2:  57%|▌| 115/200 [00:11<00:08,  9.80round/s, val_excess=0.0

w8 window rolling_2:  57%|▌| 115/200 [00:11<00:08,  9.80round/s, val_excess=0.0

w8 window rolling_2:  58%|▌| 116/200 [00:11<00:08,  9.78round/s, val_excess=0.0

w8 window rolling_2:  58%|▌| 116/200 [00:11<00:08,  9.78round/s, val_excess=0.0

w8 window rolling_2:  58%|▌| 117/200 [00:11<00:08,  9.82round/s, val_excess=0.0

w8 window rolling_2:  58%|▌| 117/200 [00:11<00:08,  9.82round/s, val_excess=0.0

w8 window rolling_2:  59%|▌| 118/200 [00:11<00:08,  9.85round/s, val_excess=0.0

w8 window rolling_2:  59%|▌| 118/200 [00:11<00:08,  9.85round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 119/200 [00:11<00:08,  9.84round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 119/200 [00:11<00:08,  9.84round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 120/200 [00:12<00:08,  9.85round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 120/200 [00:12<00:08,  9.85round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 121/200 [00:12<00:08,  9.81round/s, val_excess=0.0

w8 window rolling_2:  60%|▌| 121/200 [00:12<00:08,  9.81round/s, val_excess=0.0

w8 window rolling_2:  61%|▌| 122/200 [00:12<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  61%|▌| 122/200 [00:12<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  62%|▌| 123/200 [00:12<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  62%|▌| 123/200 [00:12<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  62%|▌| 124/200 [00:12<00:07,  9.78round/s, val_excess=0.0

w8 window rolling_2:  62%|▌| 124/200 [00:12<00:07,  9.78round/s, val_excess=0.0

w8 window rolling_2:  62%|▋| 125/200 [00:12<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  62%|▋| 125/200 [00:12<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  63%|▋| 126/200 [00:12<00:07,  9.76round/s, val_excess=0.0

w8 window rolling_2:  63%|▋| 126/200 [00:12<00:07,  9.76round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 127/200 [00:12<00:07,  9.78round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 127/200 [00:12<00:07,  9.78round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 128/200 [00:12<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 128/200 [00:12<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 129/200 [00:12<00:07,  9.84round/s, val_excess=0.0

w8 window rolling_2:  64%|▋| 129/200 [00:12<00:07,  9.84round/s, val_excess=0.0

w8 window rolling_2:  65%|▋| 130/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  65%|▋| 130/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 131/200 [00:13<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 131/200 [00:13<00:07,  9.81round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 132/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 132/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 133/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  66%|▋| 133/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  67%|▋| 134/200 [00:13<00:06,  9.60round/s, val_excess=0.0

w8 window rolling_2:  67%|▋| 134/200 [00:13<00:06,  9.60round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 135/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 135/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 136/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 136/200 [00:13<00:06,  9.68round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 137/200 [00:13<00:06,  9.75round/s, val_excess=0.0

w8 window rolling_2:  68%|▋| 137/200 [00:13<00:06,  9.75round/s, val_excess=0.0

w8 window rolling_2:  69%|▋| 138/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w8 window rolling_2:  69%|▋| 138/200 [00:13<00:06,  9.74round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 139/200 [00:13<00:06,  9.69round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 139/200 [00:13<00:06,  9.69round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 140/200 [00:14<00:06,  9.64round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 140/200 [00:14<00:06,  9.64round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 141/200 [00:14<00:06,  9.65round/s, val_excess=0.0

w8 window rolling_2:  70%|▋| 141/200 [00:14<00:06,  9.65round/s, val_excess=0.0

w8 window rolling_2:  71%|▋| 142/200 [00:14<00:06,  9.59round/s, val_excess=0.0

w8 window rolling_2:  71%|▋| 142/200 [00:14<00:06,  9.59round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 143/200 [00:14<00:05,  9.60round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 143/200 [00:14<00:05,  9.60round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 144/200 [00:14<00:05,  9.53round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 144/200 [00:14<00:05,  9.53round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 145/200 [00:14<00:05,  9.53round/s, val_excess=0.0

w8 window rolling_2:  72%|▋| 145/200 [00:14<00:05,  9.53round/s, val_excess=0.0

w8 window rolling_2:  73%|▋| 146/200 [00:14<00:05,  9.54round/s, val_excess=0.0

w8 window rolling_2:  73%|▋| 146/200 [00:14<00:05,  9.54round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 147/200 [00:14<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 147/200 [00:14<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 148/200 [00:14<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 148/200 [00:14<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 149/200 [00:15<00:05,  9.55round/s, val_excess=0.0

w8 window rolling_2:  74%|▋| 149/200 [00:15<00:05,  9.55round/s, val_excess=0.0

w8 window rolling_2:  75%|▊| 150/200 [00:15<00:05,  9.56round/s, val_excess=0.0

w8 window rolling_2:  75%|▊| 150/200 [00:15<00:05,  9.56round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 151/200 [00:15<00:05,  9.44round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 151/200 [00:15<00:05,  9.44round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 152/200 [00:15<00:05,  9.42round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 152/200 [00:15<00:05,  9.42round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 153/200 [00:15<00:04,  9.44round/s, val_excess=0.0

w8 window rolling_2:  76%|▊| 153/200 [00:15<00:04,  9.44round/s, val_excess=0.0

w8 window rolling_2:  77%|▊| 154/200 [00:15<00:04,  9.45round/s, val_excess=0.0

w8 window rolling_2:  77%|▊| 154/200 [00:15<00:04,  9.45round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 155/200 [00:15<00:04,  9.49round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 155/200 [00:15<00:04,  9.49round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 156/200 [00:15<00:04,  9.48round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 156/200 [00:15<00:04,  9.48round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 157/200 [00:15<00:04,  9.46round/s, val_excess=0.0

w8 window rolling_2:  78%|▊| 157/200 [00:15<00:04,  9.46round/s, val_excess=0.0

w8 window rolling_2:  79%|▊| 158/200 [00:15<00:04,  9.48round/s, val_excess=0.0

w8 window rolling_2:  79%|▊| 158/200 [00:15<00:04,  9.48round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 159/200 [00:16<00:04,  9.52round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 159/200 [00:16<00:04,  9.52round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 160/200 [00:16<00:04,  9.49round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 160/200 [00:16<00:04,  9.49round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 161/200 [00:16<00:04,  9.55round/s, val_excess=0.0

w8 window rolling_2:  80%|▊| 161/200 [00:16<00:04,  9.55round/s, val_excess=0.0

w8 window rolling_2:  81%|▊| 162/200 [00:16<00:03,  9.55round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 163/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 163/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 164/200 [00:16<00:03,  9.83round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 164/200 [00:16<00:03,  9.83round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 165/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  82%|▊| 165/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  83%|▊| 166/200 [00:16<00:03,  9.87round/s, val_excess=0.0

w8 window rolling_2:  83%|▊| 166/200 [00:16<00:03,  9.87round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 167/200 [00:16<00:03,  9.82round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 167/200 [00:16<00:03,  9.82round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 168/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 168/200 [00:16<00:03,  9.85round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 169/200 [00:17<00:03,  9.83round/s, val_excess=0.0

w8 window rolling_2:  84%|▊| 169/200 [00:17<00:03,  9.83round/s, val_excess=0.0

w8 window rolling_2:  85%|▊| 170/200 [00:17<00:03,  9.83round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 171/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 171/200 [00:17<00:02,  9.94round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 172/200 [00:17<00:02,  9.92round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 172/200 [00:17<00:02,  9.92round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 173/200 [00:17<00:02,  9.93round/s, val_excess=0.0

w8 window rolling_2:  86%|▊| 173/200 [00:17<00:02,  9.93round/s, val_excess=0.0

w8 window rolling_2:  87%|▊| 174/200 [00:17<00:02,  9.90round/s, val_excess=0.0

w8 window rolling_2:  87%|▊| 174/200 [00:17<00:02,  9.90round/s, val_excess=0.0

w8 window rolling_2:  88%|▉| 175/200 [00:17<00:02,  9.90round/s, val_excess=0.0

w8 window rolling_2:  88%|▉| 176/200 [00:17<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  88%|▉| 176/200 [00:17<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  88%|▉| 177/200 [00:17<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  88%|▉| 177/200 [00:17<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  89%|▉| 178/200 [00:17<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 179/200 [00:18<00:02, 10.03round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 179/200 [00:18<00:02, 10.03round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 180/200 [00:18<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 180/200 [00:18<00:02,  9.99round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 181/200 [00:18<00:01,  9.97round/s, val_excess=0.0

w8 window rolling_2:  90%|▉| 181/200 [00:18<00:01,  9.97round/s, val_excess=0.0

w8 window rolling_2:  91%|▉| 182/200 [00:18<00:01,  9.94round/s, val_excess=0.0

w8 window rolling_2:  91%|▉| 182/200 [00:18<00:01,  9.94round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 183/200 [00:18<00:01,  9.86round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 183/200 [00:18<00:01,  9.86round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 184/200 [00:18<00:01,  9.85round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 184/200 [00:18<00:01,  9.85round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 185/200 [00:18<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_2:  92%|▉| 185/200 [00:18<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_2:  93%|▉| 186/200 [00:18<00:01,  9.80round/s, val_excess=0.0

w8 window rolling_2:  93%|▉| 186/200 [00:18<00:01,  9.80round/s, val_excess=0.0

w8 window rolling_2:  94%|▉| 187/200 [00:18<00:01,  9.80round/s, val_excess=0.0

w8 window rolling_2:  94%|▉| 187/200 [00:18<00:01,  9.80round/s, val_excess=0.0

w8 window rolling_2:  94%|▉| 188/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_2:  94%|▉| 188/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_2:  94%|▉| 189/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_2:  95%|▉| 190/200 [00:19<00:01,  9.88round/s, val_excess=0.0

w8 window rolling_2:  95%|▉| 190/200 [00:19<00:01,  9.88round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 191/200 [00:19<00:00,  9.87round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 191/200 [00:19<00:00,  9.87round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 192/200 [00:19<00:00,  9.88round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 192/200 [00:19<00:00,  9.88round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 193/200 [00:19<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2:  96%|▉| 193/200 [00:19<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2:  97%|▉| 194/200 [00:19<00:00,  9.79round/s, val_excess=0.0

w8 window rolling_2:  97%|▉| 194/200 [00:19<00:00,  9.79round/s, val_excess=0.0

w8 window rolling_2:  98%|▉| 195/200 [00:19<00:00,  9.82round/s, val_excess=0.0

w8 window rolling_2:  98%|▉| 195/200 [00:19<00:00,  9.82round/s, val_excess=0.0

w8 window rolling_2:  98%|▉| 196/200 [00:19<00:00,  9.82round/s, val_excess=0.0

w8 window rolling_2:  98%|▉| 197/200 [00:19<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2:  98%|▉| 197/200 [00:19<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2:  99%|▉| 198/200 [00:20<00:00,  9.87round/s, val_excess=0.0

w8 window rolling_2:  99%|▉| 198/200 [00:20<00:00,  9.87round/s, val_excess=0.0

w8 window rolling_2: 100%|▉| 199/200 [00:20<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2: 100%|▉| 199/200 [00:20<00:00,  9.83round/s, val_excess=0.0

w8 window rolling_2: 100%|█| 200/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w8 window rolling_2: 100%|█| 200/200 [00:20<00:00,  9.81round/s, val_excess=0.0

w8 window rolling_2: 100%|█| 200/200 [00:20<00:00,  9.88round/s, val_excess=0.0

2026-07-06 17:32:06 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=8 feature_type=window fold=rolling_3

2026-07-06 17:32:27 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=8 feature_type=window fold=rolling_3 features=69

w8 window rolling_3:   0%|                          | 0/200 [00:00<?, ?round/s]

w8 window rolling_3:   0%|                  | 1/200 [00:00<00:20,  9.71round/s]

w8 window rolling_3:   0%| | 1/200 [00:00<00:20,  9.71round/s, val_excess=-0.01

w8 window rolling_3:   1%| | 2/200 [00:00<00:20,  9.71round/s, val_excess=-0.00

w8 window rolling_3:   2%| | 3/200 [00:00<00:17, 11.36round/s, val_excess=-0.00

w8 window rolling_3:   2%| | 3/200 [00:00<00:17, 11.36round/s, val_excess=0.002

w8 window rolling_3:   2%| | 4/200 [00:00<00:17, 11.36round/s, val_excess=0.017

w8 window rolling_3:   2%| | 5/200 [00:00<00:17, 11.22round/s, val_excess=0.017

w8 window rolling_3:   2%| | 5/200 [00:00<00:17, 11.22round/s, val_excess=0.003

w8 window rolling_3:   3%| | 6/200 [00:00<00:17, 11.22round/s, val_excess=0.007

w8 window rolling_3:   4%| | 7/200 [00:00<00:17, 10.86round/s, val_excess=0.007

w8 window rolling_3:   4%| | 7/200 [00:00<00:17, 10.86round/s, val_excess=0.021

w8 window rolling_3:   4%| | 8/200 [00:00<00:17, 10.86round/s, val_excess=0.011

w8 window rolling_3:   4%| | 9/200 [00:00<00:17, 10.75round/s, val_excess=0.011

w8 window rolling_3:   4%| | 9/200 [00:00<00:17, 10.75round/s, val_excess=0.006

w8 window rolling_3:   5%| | 10/200 [00:00<00:17, 10.75round/s, val_excess=0.00

w8 window rolling_3:   6%| | 11/200 [00:01<00:17, 10.51round/s, val_excess=0.00

w8 window rolling_3:   6%| | 11/200 [00:01<00:17, 10.51round/s, val_excess=0.01

w8 window rolling_3:   6%| | 12/200 [00:01<00:17, 10.51round/s, val_excess=0.02

w8 window rolling_3:   6%| | 13/200 [00:01<00:17, 10.49round/s, val_excess=0.02

w8 window rolling_3:   6%| | 13/200 [00:01<00:17, 10.49round/s, val_excess=0.01

w8 window rolling_3:   7%| | 14/200 [00:01<00:17, 10.49round/s, val_excess=0.01

w8 window rolling_3:   8%| | 15/200 [00:01<00:18, 10.20round/s, val_excess=0.01

w8 window rolling_3:   8%| | 15/200 [00:01<00:18, 10.20round/s, val_excess=0.01

w8 window rolling_3:   8%| | 16/200 [00:01<00:18, 10.20round/s, val_excess=0.01

w8 window rolling_3:   8%| | 17/200 [00:01<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_3:   8%| | 17/200 [00:01<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_3:   9%| | 18/200 [00:01<00:17, 10.17round/s, val_excess=0.01

w8 window rolling_3:  10%| | 19/200 [00:01<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  10%| | 19/200 [00:01<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  10%| | 20/200 [00:01<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  10%| | 21/200 [00:02<00:17, 10.18round/s, val_excess=0.01

w8 window rolling_3:  10%| | 21/200 [00:02<00:17, 10.18round/s, val_excess=0.01

w8 window rolling_3:  11%| | 22/200 [00:02<00:17, 10.18round/s, val_excess=0.01

w8 window rolling_3:  12%| | 23/200 [00:02<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  12%| | 23/200 [00:02<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  12%| | 24/200 [00:02<00:17, 10.14round/s, val_excess=0.01

w8 window rolling_3:  12%|▏| 25/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_3:  12%|▏| 25/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_3:  13%|▏| 26/200 [00:02<00:17, 10.04round/s, val_excess=0.01

w8 window rolling_3:  14%|▏| 27/200 [00:02<00:17,  9.97round/s, val_excess=0.01

w8 window rolling_3:  14%|▏| 27/200 [00:02<00:17,  9.97round/s, val_excess=0.01

w8 window rolling_3:  14%|▏| 28/200 [00:02<00:17,  9.97round/s, val_excess=0.01

w8 window rolling_3:  14%|▏| 28/200 [00:02<00:17,  9.97round/s, val_excess=0.01

w8 window rolling_3:  14%|▏| 29/200 [00:02<00:17,  9.97round/s, val_excess=0.01

w8 window rolling_3:  15%|▏| 30/200 [00:02<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  15%|▏| 30/200 [00:02<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  16%|▏| 31/200 [00:03<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  16%|▏| 32/200 [00:03<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  16%|▏| 32/200 [00:03<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  16%|▏| 33/200 [00:03<00:16, 10.02round/s, val_excess=0.01

w8 window rolling_3:  17%|▏| 34/200 [00:03<00:16,  9.91round/s, val_excess=0.01

w8 window rolling_3:  17%|▏| 34/200 [00:03<00:16,  9.91round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 35/200 [00:03<00:16,  9.92round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 35/200 [00:03<00:16,  9.92round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 36/200 [00:03<00:16,  9.87round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 36/200 [00:03<00:16,  9.87round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 37/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  18%|▏| 37/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  19%|▏| 38/200 [00:03<00:16,  9.85round/s, val_excess=0.01

w8 window rolling_3:  19%|▏| 38/200 [00:03<00:16,  9.85round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 39/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 39/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 40/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 40/200 [00:03<00:16,  9.83round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 41/200 [00:04<00:16,  9.85round/s, val_excess=0.01

w8 window rolling_3:  20%|▏| 41/200 [00:04<00:16,  9.85round/s, val_excess=0.02

w8 window rolling_3:  21%|▏| 42/200 [00:04<00:16,  9.79round/s, val_excess=0.02

w8 window rolling_3:  21%|▏| 42/200 [00:04<00:16,  9.79round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 43/200 [00:04<00:16,  9.81round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 43/200 [00:04<00:16,  9.81round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 44/200 [00:04<00:15,  9.78round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 44/200 [00:04<00:15,  9.78round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 45/200 [00:04<00:15,  9.80round/s, val_excess=0.01

w8 window rolling_3:  22%|▏| 45/200 [00:04<00:15,  9.80round/s, val_excess=0.01

w8 window rolling_3:  23%|▏| 46/200 [00:04<00:15,  9.79round/s, val_excess=0.01

w8 window rolling_3:  23%|▏| 46/200 [00:04<00:15,  9.79round/s, val_excess=0.01

w8 window rolling_3:  24%|▏| 47/200 [00:04<00:15,  9.80round/s, val_excess=0.01

w8 window rolling_3:  24%|▏| 47/200 [00:04<00:15,  9.80round/s, val_excess=0.01

w8 window rolling_3:  24%|▏| 48/200 [00:04<00:15,  9.84round/s, val_excess=0.01

w8 window rolling_3:  24%|▏| 48/200 [00:04<00:15,  9.84round/s, val_excess=0.01

w8 window rolling_3:  24%|▏| 49/200 [00:04<00:15,  9.84round/s, val_excess=0.01

w8 window rolling_3:  25%|▎| 50/200 [00:04<00:15,  9.92round/s, val_excess=0.01

w8 window rolling_3:  25%|▎| 50/200 [00:04<00:15,  9.92round/s, val_excess=0.01

w8 window rolling_3:  26%|▎| 51/200 [00:05<00:15,  9.86round/s, val_excess=0.01

w8 window rolling_3:  26%|▎| 51/200 [00:05<00:15,  9.86round/s, val_excess=0.01

w8 window rolling_3:  26%|▎| 52/200 [00:05<00:15,  9.86round/s, val_excess=0.01

w8 window rolling_3:  26%|▎| 53/200 [00:05<00:14,  9.98round/s, val_excess=0.01

w8 window rolling_3:  26%|▎| 53/200 [00:05<00:14,  9.98round/s, val_excess=0.02

w8 window rolling_3:  27%|▎| 54/200 [00:05<00:14,  9.86round/s, val_excess=0.02

w8 window rolling_3:  27%|▎| 54/200 [00:05<00:14,  9.86round/s, val_excess=0.02

w8 window rolling_3:  28%|▎| 55/200 [00:05<00:14,  9.85round/s, val_excess=0.02

w8 window rolling_3:  28%|▎| 55/200 [00:05<00:14,  9.85round/s, val_excess=0.01

w8 window rolling_3:  28%|▎| 56/200 [00:05<00:14,  9.85round/s, val_excess=0.01

w8 window rolling_3:  28%|▎| 57/200 [00:05<00:14,  9.88round/s, val_excess=0.01

w8 window rolling_3:  28%|▎| 57/200 [00:05<00:14,  9.88round/s, val_excess=0.01

w8 window rolling_3:  29%|▎| 58/200 [00:05<00:14,  9.89round/s, val_excess=0.01

w8 window rolling_3:  29%|▎| 58/200 [00:05<00:14,  9.89round/s, val_excess=0.01

w8 window rolling_3:  30%|▎| 59/200 [00:05<00:14,  9.89round/s, val_excess=0.01

w8 window rolling_3:  30%|▎| 60/200 [00:05<00:13, 10.01round/s, val_excess=0.01

w8 window rolling_3:  30%|▎| 60/200 [00:05<00:13, 10.01round/s, val_excess=0.01

w8 window rolling_3:  30%|▎| 61/200 [00:06<00:13, 10.01round/s, val_excess=0.01

w8 window rolling_3:  31%|▎| 62/200 [00:06<00:13,  9.99round/s, val_excess=0.01

w8 window rolling_3:  31%|▎| 62/200 [00:06<00:13,  9.99round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 63/200 [00:06<00:13,  9.97round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 63/200 [00:06<00:13,  9.97round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 64/200 [00:06<00:13,  9.89round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 64/200 [00:06<00:13,  9.89round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 65/200 [00:06<00:14,  9.62round/s, val_excess=0.01

w8 window rolling_3:  32%|▎| 65/200 [00:06<00:14,  9.62round/s, val_excess=0.01

w8 window rolling_3:  33%|▎| 66/200 [00:06<00:13,  9.63round/s, val_excess=0.01

w8 window rolling_3:  33%|▎| 66/200 [00:06<00:13,  9.63round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 67/200 [00:06<00:13,  9.63round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 67/200 [00:06<00:13,  9.63round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 68/200 [00:06<00:13,  9.68round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 68/200 [00:06<00:13,  9.68round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 69/200 [00:06<00:13,  9.60round/s, val_excess=0.01

w8 window rolling_3:  34%|▎| 69/200 [00:06<00:13,  9.60round/s, val_excess=0.01

w8 window rolling_3:  35%|▎| 70/200 [00:06<00:13,  9.65round/s, val_excess=0.01

w8 window rolling_3:  35%|▎| 70/200 [00:06<00:13,  9.65round/s, val_excess=0.01

w8 window rolling_3:  36%|▎| 71/200 [00:07<00:13,  9.69round/s, val_excess=0.01

w8 window rolling_3:  36%|▎| 71/200 [00:07<00:13,  9.69round/s, val_excess=0.01

w8 window rolling_3:  36%|▎| 72/200 [00:07<00:13,  9.69round/s, val_excess=0.01

w8 window rolling_3:  36%|▎| 73/200 [00:07<00:12,  9.91round/s, val_excess=0.01

w8 window rolling_3:  36%|▎| 73/200 [00:07<00:12,  9.91round/s, val_excess=0.01

w8 window rolling_3:  37%|▎| 74/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w8 window rolling_3:  37%|▎| 74/200 [00:07<00:12,  9.85round/s, val_excess=0.01

w8 window rolling_3:  38%|▍| 75/200 [00:07<00:12,  9.84round/s, val_excess=0.01

w8 window rolling_3:  38%|▍| 75/200 [00:07<00:12,  9.84round/s, val_excess=0.01

w8 window rolling_3:  38%|▍| 76/200 [00:07<00:12,  9.84round/s, val_excess=0.01

w8 window rolling_3:  38%|▍| 77/200 [00:07<00:12,  9.92round/s, val_excess=0.01

w8 window rolling_3:  38%|▍| 77/200 [00:07<00:12,  9.92round/s, val_excess=0.01

w8 window rolling_3:  39%|▍| 78/200 [00:07<00:12,  9.89round/s, val_excess=0.01

w8 window rolling_3:  39%|▍| 78/200 [00:07<00:12,  9.89round/s, val_excess=0.01

w8 window rolling_3:  40%|▍| 79/200 [00:07<00:12,  9.89round/s, val_excess=0.01

w8 window rolling_3:  40%|▍| 80/200 [00:08<00:12, 10.00round/s, val_excess=0.01

w8 window rolling_3:  40%|▍| 80/200 [00:08<00:12, 10.00round/s, val_excess=0.01

w8 window rolling_3:  40%|▍| 81/200 [00:08<00:11, 10.00round/s, val_excess=0.01

w8 window rolling_3:  41%|▍| 82/200 [00:08<00:11, 10.01round/s, val_excess=0.01

w8 window rolling_3:  41%|▍| 82/200 [00:08<00:11, 10.01round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 83/200 [00:08<00:12,  9.29round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 83/200 [00:08<00:12,  9.29round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 84/200 [00:08<00:12,  9.24round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 84/200 [00:08<00:12,  9.24round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 85/200 [00:08<00:12,  9.19round/s, val_excess=0.01

w8 window rolling_3:  42%|▍| 85/200 [00:08<00:12,  9.19round/s, val_excess=0.01

w8 window rolling_3:  43%|▍| 86/200 [00:08<00:12,  9.08round/s, val_excess=0.01

w8 window rolling_3:  43%|▍| 86/200 [00:08<00:12,  9.08round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 87/200 [00:08<00:12,  8.96round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 87/200 [00:08<00:12,  8.96round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 88/200 [00:08<00:12,  8.93round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 88/200 [00:08<00:12,  8.93round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  8.82round/s, val_excess=0.01

w8 window rolling_3:  44%|▍| 89/200 [00:09<00:12,  8.82round/s, val_excess=0.01

w8 window rolling_3:  45%|▍| 90/200 [00:09<00:12,  8.67round/s, val_excess=0.01

w8 window rolling_3:  45%|▍| 90/200 [00:09<00:12,  8.67round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 91/200 [00:09<00:12,  8.65round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 91/200 [00:09<00:12,  8.65round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 92/200 [00:09<00:12,  8.69round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 92/200 [00:09<00:12,  8.69round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 93/200 [00:09<00:12,  8.88round/s, val_excess=0.01

w8 window rolling_3:  46%|▍| 93/200 [00:09<00:12,  8.88round/s, val_excess=0.01

w8 window rolling_3:  47%|▍| 94/200 [00:09<00:11,  8.94round/s, val_excess=0.01

w8 window rolling_3:  47%|▍| 94/200 [00:09<00:11,  8.94round/s, val_excess=0.01

w8 window rolling_3:  48%|▍| 95/200 [00:09<00:11,  8.92round/s, val_excess=0.01

w8 window rolling_3:  48%|▍| 95/200 [00:09<00:11,  8.92round/s, val_excess=0.02

w8 window rolling_3:  48%|▍| 96/200 [00:09<00:11,  8.89round/s, val_excess=0.02

w8 window rolling_3:  48%|▍| 96/200 [00:09<00:11,  8.89round/s, val_excess=0.02

w8 window rolling_3:  48%|▍| 97/200 [00:09<00:11,  8.93round/s, val_excess=0.02

w8 window rolling_3:  48%|▍| 97/200 [00:09<00:11,  8.93round/s, val_excess=0.02

w8 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  8.85round/s, val_excess=0.02

w8 window rolling_3:  49%|▍| 98/200 [00:10<00:11,  8.85round/s, val_excess=0.02

w8 window rolling_3:  50%|▍| 99/200 [00:10<00:11,  8.77round/s, val_excess=0.02

w8 window rolling_3:  50%|▍| 99/200 [00:10<00:11,  8.77round/s, val_excess=0.02

w8 window rolling_3:  50%|▌| 100/200 [00:10<00:11,  9.00round/s, val_excess=0.0

w8 window rolling_3:  50%|▌| 100/200 [00:10<00:11,  9.00round/s, val_excess=0.0

w8 window rolling_3:  50%|▌| 101/200 [00:10<00:11,  8.93round/s, val_excess=0.0

w8 window rolling_3:  50%|▌| 101/200 [00:10<00:11,  8.93round/s, val_excess=0.0

w8 window rolling_3:  51%|▌| 102/200 [00:10<00:11,  8.85round/s, val_excess=0.0

w8 window rolling_3:  51%|▌| 102/200 [00:10<00:11,  8.85round/s, val_excess=0.0

w8 window rolling_3:  52%|▌| 103/200 [00:10<00:10,  8.85round/s, val_excess=0.0

w8 window rolling_3:  52%|▌| 104/200 [00:10<00:10,  9.29round/s, val_excess=0.0

w8 window rolling_3:  52%|▌| 104/200 [00:10<00:10,  9.29round/s, val_excess=0.0

w8 window rolling_3:  52%|▌| 105/200 [00:10<00:10,  9.39round/s, val_excess=0.0

w8 window rolling_3:  52%|▌| 105/200 [00:10<00:10,  9.39round/s, val_excess=0.0

w8 window rolling_3:  53%|▌| 106/200 [00:10<00:09,  9.51round/s, val_excess=0.0

w8 window rolling_3:  53%|▌| 106/200 [00:10<00:09,  9.51round/s, val_excess=0.0

w8 window rolling_3:  54%|▌| 107/200 [00:10<00:09,  9.53round/s, val_excess=0.0

w8 window rolling_3:  54%|▌| 107/200 [00:10<00:09,  9.53round/s, val_excess=0.0

w8 window rolling_3:  54%|▌| 108/200 [00:11<00:09,  9.60round/s, val_excess=0.0

w8 window rolling_3:  54%|▌| 108/200 [00:11<00:09,  9.60round/s, val_excess=0.0

w8 window rolling_3:  55%|▌| 109/200 [00:11<00:09,  9.60round/s, val_excess=0.0

w8 window rolling_3:  55%|▌| 109/200 [00:11<00:09,  9.60round/s, val_excess=0.0

w8 window rolling_3:  55%|▌| 110/200 [00:11<00:09,  9.71round/s, val_excess=0.0

w8 window rolling_3:  55%|▌| 110/200 [00:11<00:09,  9.71round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 111/200 [00:11<00:09,  9.38round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 111/200 [00:11<00:09,  9.38round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 112/200 [00:11<00:09,  9.54round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 112/200 [00:11<00:09,  9.54round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 113/200 [00:11<00:09,  9.44round/s, val_excess=0.0

w8 window rolling_3:  56%|▌| 113/200 [00:11<00:09,  9.44round/s, val_excess=0.0

w8 window rolling_3:  57%|▌| 114/200 [00:11<00:08,  9.56round/s, val_excess=0.0

w8 window rolling_3:  57%|▌| 114/200 [00:11<00:08,  9.56round/s, val_excess=0.0

w8 window rolling_3:  57%|▌| 115/200 [00:11<00:08,  9.56round/s, val_excess=0.0

w8 window rolling_3:  58%|▌| 116/200 [00:11<00:08,  9.77round/s, val_excess=0.0

w8 window rolling_3:  58%|▌| 116/200 [00:11<00:08,  9.77round/s, val_excess=0.0

w8 window rolling_3:  58%|▌| 117/200 [00:12<00:08,  9.83round/s, val_excess=0.0

w8 window rolling_3:  58%|▌| 117/200 [00:12<00:08,  9.83round/s, val_excess=0.0

w8 window rolling_3:  59%|▌| 118/200 [00:12<00:08,  9.82round/s, val_excess=0.0

w8 window rolling_3:  59%|▌| 118/200 [00:12<00:08,  9.82round/s, val_excess=0.0

w8 window rolling_3:  60%|▌| 119/200 [00:12<00:08,  9.82round/s, val_excess=0.0

w8 window rolling_3:  60%|▌| 120/200 [00:12<00:08,  9.87round/s, val_excess=0.0

w8 window rolling_3:  60%|▌| 120/200 [00:12<00:08,  9.87round/s, val_excess=0.0

w8 window rolling_3:  60%|▌| 121/200 [00:12<00:08,  9.71round/s, val_excess=0.0

w8 window rolling_3:  60%|▌| 121/200 [00:12<00:08,  9.71round/s, val_excess=0.0

w8 window rolling_3:  61%|▌| 122/200 [00:12<00:08,  9.60round/s, val_excess=0.0

w8 window rolling_3:  61%|▌| 122/200 [00:12<00:08,  9.60round/s, val_excess=0.0

w8 window rolling_3:  62%|▌| 123/200 [00:12<00:07,  9.69round/s, val_excess=0.0

w8 window rolling_3:  62%|▌| 123/200 [00:12<00:07,  9.69round/s, val_excess=0.0

w8 window rolling_3:  62%|▌| 124/200 [00:12<00:07,  9.67round/s, val_excess=0.0

w8 window rolling_3:  62%|▌| 124/200 [00:12<00:07,  9.67round/s, val_excess=0.0

w8 window rolling_3:  62%|▋| 125/200 [00:12<00:07,  9.73round/s, val_excess=0.0

w8 window rolling_3:  62%|▋| 125/200 [00:12<00:07,  9.73round/s, val_excess=0.0

w8 window rolling_3:  63%|▋| 126/200 [00:12<00:07,  9.73round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 127/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 127/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 128/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 128/200 [00:13<00:07,  9.79round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 129/200 [00:13<00:07,  9.62round/s, val_excess=0.0

w8 window rolling_3:  64%|▋| 129/200 [00:13<00:07,  9.62round/s, val_excess=0.0

w8 window rolling_3:  65%|▋| 130/200 [00:13<00:07,  9.52round/s, val_excess=0.0

w8 window rolling_3:  65%|▋| 130/200 [00:13<00:07,  9.52round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 131/200 [00:13<00:07,  9.57round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 131/200 [00:13<00:07,  9.57round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 132/200 [00:13<00:07,  9.64round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 132/200 [00:13<00:07,  9.64round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 133/200 [00:13<00:07,  9.55round/s, val_excess=0.0

w8 window rolling_3:  66%|▋| 133/200 [00:13<00:07,  9.55round/s, val_excess=0.0

w8 window rolling_3:  67%|▋| 134/200 [00:13<00:06,  9.62round/s, val_excess=0.0

w8 window rolling_3:  67%|▋| 134/200 [00:13<00:06,  9.62round/s, val_excess=0.0

w8 window rolling_3:  68%|▋| 135/200 [00:13<00:06,  9.62round/s, val_excess=0.0

w8 window rolling_3:  68%|▋| 136/200 [00:13<00:06,  9.71round/s, val_excess=0.0

w8 window rolling_3:  68%|▋| 136/200 [00:13<00:06,  9.71round/s, val_excess=0.0

w8 window rolling_3:  68%|▋| 137/200 [00:14<00:06,  9.71round/s, val_excess=0.0

w8 window rolling_3:  69%|▋| 138/200 [00:14<00:06,  9.81round/s, val_excess=0.0

w8 window rolling_3:  69%|▋| 138/200 [00:14<00:06,  9.81round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 139/200 [00:14<00:06,  9.85round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 139/200 [00:14<00:06,  9.85round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 140/200 [00:14<00:06,  9.85round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 140/200 [00:14<00:06,  9.85round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 141/200 [00:14<00:06,  9.81round/s, val_excess=0.0

w8 window rolling_3:  70%|▋| 141/200 [00:14<00:06,  9.81round/s, val_excess=0.0

w8 window rolling_3:  71%|▋| 142/200 [00:14<00:05,  9.83round/s, val_excess=0.0

w8 window rolling_3:  71%|▋| 142/200 [00:14<00:05,  9.83round/s, val_excess=0.0

w8 window rolling_3:  72%|▋| 143/200 [00:14<00:05,  9.83round/s, val_excess=0.0

w8 window rolling_3:  72%|▋| 144/200 [00:14<00:05,  9.90round/s, val_excess=0.0

w8 window rolling_3:  72%|▋| 144/200 [00:14<00:05,  9.90round/s, val_excess=0.0

w8 window rolling_3:  72%|▋| 145/200 [00:14<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  72%|▋| 145/200 [00:14<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  73%|▋| 146/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  73%|▋| 146/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 147/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 147/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 148/200 [00:15<00:05,  9.79round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 148/200 [00:15<00:05,  9.79round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 149/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  74%|▋| 149/200 [00:15<00:05,  9.84round/s, val_excess=0.0

w8 window rolling_3:  75%|▊| 150/200 [00:15<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_3:  75%|▊| 150/200 [00:15<00:05,  9.64round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 151/200 [00:15<00:05,  9.74round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 151/200 [00:15<00:05,  9.74round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 152/200 [00:15<00:05,  9.40round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 152/200 [00:15<00:05,  9.40round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 153/200 [00:15<00:04,  9.54round/s, val_excess=0.0

w8 window rolling_3:  76%|▊| 153/200 [00:15<00:04,  9.54round/s, val_excess=0.0

w8 window rolling_3:  77%|▊| 154/200 [00:15<00:04,  9.65round/s, val_excess=0.0

w8 window rolling_3:  77%|▊| 154/200 [00:15<00:04,  9.65round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 155/200 [00:15<00:04,  9.72round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 155/200 [00:15<00:04,  9.72round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 156/200 [00:16<00:04,  9.74round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 156/200 [00:16<00:04,  9.74round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 157/200 [00:16<00:04,  9.82round/s, val_excess=0.0

w8 window rolling_3:  78%|▊| 157/200 [00:16<00:04,  9.82round/s, val_excess=0.0

w8 window rolling_3:  79%|▊| 158/200 [00:16<00:04,  9.82round/s, val_excess=0.0

w8 window rolling_3:  79%|▊| 158/200 [00:16<00:04,  9.82round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 159/200 [00:16<00:04,  9.85round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 159/200 [00:16<00:04,  9.85round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 160/200 [00:16<00:04,  9.57round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 160/200 [00:16<00:04,  9.57round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 161/200 [00:16<00:04,  9.65round/s, val_excess=0.0

w8 window rolling_3:  80%|▊| 161/200 [00:16<00:04,  9.65round/s, val_excess=0.0

w8 window rolling_3:  81%|▊| 162/200 [00:16<00:03,  9.69round/s, val_excess=0.0

w8 window rolling_3:  81%|▊| 162/200 [00:16<00:03,  9.69round/s, val_excess=0.0

w8 window rolling_3:  82%|▊| 163/200 [00:16<00:03,  9.67round/s, val_excess=0.0

w8 window rolling_3:  82%|▊| 163/200 [00:16<00:03,  9.67round/s, val_excess=0.0

w8 window rolling_3:  82%|▊| 164/200 [00:16<00:03,  9.74round/s, val_excess=0.0

w8 window rolling_3:  82%|▊| 164/200 [00:16<00:03,  9.74round/s, val_excess=0.0

w8 window rolling_3:  82%|▊| 165/200 [00:16<00:03,  9.74round/s, val_excess=0.0

w8 window rolling_3:  83%|▊| 166/200 [00:17<00:03,  9.59round/s, val_excess=0.0

w8 window rolling_3:  83%|▊| 166/200 [00:17<00:03,  9.59round/s, val_excess=0.0

w8 window rolling_3:  84%|▊| 167/200 [00:17<00:03,  9.59round/s, val_excess=0.0

w8 window rolling_3:  84%|▊| 168/200 [00:17<00:03,  9.78round/s, val_excess=0.0

w8 window rolling_3:  84%|▊| 168/200 [00:17<00:03,  9.78round/s, val_excess=0.0

w8 window rolling_3:  84%|▊| 169/200 [00:17<00:03,  9.78round/s, val_excess=0.0

w8 window rolling_3:  85%|▊| 170/200 [00:17<00:03,  9.73round/s, val_excess=0.0

w8 window rolling_3:  85%|▊| 170/200 [00:17<00:03,  9.73round/s, val_excess=0.0

w8 window rolling_3:  86%|▊| 171/200 [00:17<00:02,  9.72round/s, val_excess=0.0

w8 window rolling_3:  86%|▊| 171/200 [00:17<00:02,  9.72round/s, val_excess=0.0

w8 window rolling_3:  86%|▊| 172/200 [00:17<00:02,  9.60round/s, val_excess=0.0

w8 window rolling_3:  86%|▊| 172/200 [00:17<00:02,  9.60round/s, val_excess=0.0

w8 window rolling_3:  86%|▊| 173/200 [00:17<00:02,  9.60round/s, val_excess=0.0

w8 window rolling_3:  87%|▊| 174/200 [00:17<00:02,  9.79round/s, val_excess=0.0

w8 window rolling_3:  87%|▊| 174/200 [00:17<00:02,  9.79round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 175/200 [00:17<00:02,  9.80round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 175/200 [00:17<00:02,  9.80round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 176/200 [00:18<00:02,  9.82round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 176/200 [00:18<00:02,  9.82round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 177/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w8 window rolling_3:  88%|▉| 177/200 [00:18<00:02,  9.83round/s, val_excess=0.0

w8 window rolling_3:  89%|▉| 178/200 [00:18<00:02,  9.80round/s, val_excess=0.0

w8 window rolling_3:  89%|▉| 178/200 [00:18<00:02,  9.80round/s, val_excess=0.0

w8 window rolling_3:  90%|▉| 179/200 [00:18<00:02,  9.80round/s, val_excess=0.0

w8 window rolling_3:  90%|▉| 180/200 [00:18<00:02,  9.88round/s, val_excess=0.0

w8 window rolling_3:  90%|▉| 180/200 [00:18<00:02,  9.88round/s, val_excess=0.0

w8 window rolling_3:  90%|▉| 181/200 [00:18<00:01,  9.85round/s, val_excess=0.0

w8 window rolling_3:  90%|▉| 181/200 [00:18<00:01,  9.85round/s, val_excess=0.0

w8 window rolling_3:  91%|▉| 182/200 [00:18<00:01,  9.83round/s, val_excess=0.0

w8 window rolling_3:  91%|▉| 182/200 [00:18<00:01,  9.83round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 183/200 [00:18<00:01,  9.79round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 183/200 [00:18<00:01,  9.79round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 184/200 [00:18<00:01,  9.77round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 184/200 [00:18<00:01,  9.77round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 185/200 [00:19<00:01,  9.81round/s, val_excess=0.0

w8 window rolling_3:  92%|▉| 185/200 [00:19<00:01,  9.81round/s, val_excess=0.0

w8 window rolling_3:  93%|▉| 186/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_3:  93%|▉| 186/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_3:  94%|▉| 187/200 [00:19<00:01,  9.82round/s, val_excess=0.0

w8 window rolling_3:  94%|▉| 188/200 [00:19<00:01,  9.96round/s, val_excess=0.0

w8 window rolling_3:  94%|▉| 188/200 [00:19<00:01,  9.96round/s, val_excess=0.0

w8 window rolling_3:  94%|▉| 189/200 [00:19<00:01,  9.96round/s, val_excess=0.0

w8 window rolling_3:  95%|▉| 190/200 [00:19<00:01,  9.97round/s, val_excess=0.0

w8 window rolling_3:  95%|▉| 190/200 [00:19<00:01,  9.97round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 191/200 [00:19<00:00,  9.75round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 191/200 [00:19<00:00,  9.75round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 192/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 192/200 [00:19<00:00,  9.76round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 193/200 [00:19<00:00,  9.72round/s, val_excess=0.0

w8 window rolling_3:  96%|▉| 193/200 [00:19<00:00,  9.72round/s, val_excess=0.0

w8 window rolling_3:  97%|▉| 194/200 [00:19<00:00,  9.51round/s, val_excess=0.0

w8 window rolling_3:  97%|▉| 194/200 [00:19<00:00,  9.51round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 195/200 [00:20<00:00,  9.49round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 195/200 [00:20<00:00,  9.49round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 196/200 [00:20<00:00,  9.52round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 196/200 [00:20<00:00,  9.52round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 197/200 [00:20<00:00,  9.51round/s, val_excess=0.0

w8 window rolling_3:  98%|▉| 197/200 [00:20<00:00,  9.51round/s, val_excess=0.0

w8 window rolling_3:  99%|▉| 198/200 [00:20<00:00,  9.62round/s, val_excess=0.0

w8 window rolling_3:  99%|▉| 198/200 [00:20<00:00,  9.62round/s, val_excess=0.0

w8 window rolling_3: 100%|▉| 199/200 [00:20<00:00,  9.64round/s, val_excess=0.0

w8 window rolling_3: 100%|▉| 199/200 [00:20<00:00,  9.64round/s, val_excess=0.0

w8 window rolling_3: 100%|█| 200/200 [00:20<00:00,  9.73round/s, val_excess=0.0

w8 window rolling_3: 100%|█| 200/200 [00:20<00:00,  9.73round/s, val_excess=0.0

w8 window rolling_3: 100%|█| 200/200 [00:20<00:00,  9.73round/s, val_excess=0.0

2026-07-06 17:32:48 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=8 feature_type=window fold=rolling_4

2026-07-06 17:33:09 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=8 feature_type=window fold=rolling_4 features=69

w8 window rolling_4:   0%|                          | 0/200 [00:00<?, ?round/s]

w8 window rolling_4:   0%|                  | 1/200 [00:00<00:21,  9.15round/s]

w8 window rolling_4:   0%| | 1/200 [00:00<00:21,  9.15round/s, val_excess=0.000

w8 window rolling_4:   1%| | 2/200 [00:00<00:21,  9.15round/s, val_excess=-0.02

w8 window rolling_4:   2%| | 3/200 [00:00<00:19,  9.91round/s, val_excess=-0.02

w8 window rolling_4:   2%| | 3/200 [00:00<00:19,  9.91round/s, val_excess=-0.00

w8 window rolling_4:   2%| | 4/200 [00:00<00:20,  9.69round/s, val_excess=-0.00

w8 window rolling_4:   2%| | 4/200 [00:00<00:20,  9.69round/s, val_excess=-0.02

w8 window rolling_4:   2%| | 5/200 [00:00<00:20,  9.57round/s, val_excess=-0.02

w8 window rolling_4:   2%| | 5/200 [00:00<00:20,  9.57round/s, val_excess=-0.02

w8 window rolling_4:   3%| | 6/200 [00:00<00:20,  9.35round/s, val_excess=-0.02

w8 window rolling_4:   3%| | 6/200 [00:00<00:20,  9.35round/s, val_excess=-0.01

w8 window rolling_4:   4%| | 7/200 [00:00<00:20,  9.25round/s, val_excess=-0.01

w8 window rolling_4:   4%| | 7/200 [00:00<00:20,  9.25round/s, val_excess=-0.01

w8 window rolling_4:   4%| | 8/200 [00:00<00:20,  9.35round/s, val_excess=-0.01

w8 window rolling_4:   4%| | 8/200 [00:00<00:20,  9.35round/s, val_excess=-0.01

w8 window rolling_4:   4%| | 9/200 [00:00<00:20,  9.35round/s, val_excess=-0.00

w8 window rolling_4:   5%| | 10/200 [00:01<00:19,  9.73round/s, val_excess=-0.0

w8 window rolling_4:   5%| | 10/200 [00:01<00:19,  9.73round/s, val_excess=-0.0

w8 window rolling_4:   6%| | 11/200 [00:01<00:19,  9.73round/s, val_excess=-0.0

w8 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.88round/s, val_excess=-0.0

w8 window rolling_4:   6%| | 12/200 [00:01<00:19,  9.88round/s, val_excess=-0.0

w8 window rolling_4:   6%| | 13/200 [00:01<00:18,  9.90round/s, val_excess=-0.0

w8 window rolling_4:   6%| | 13/200 [00:01<00:18,  9.90round/s, val_excess=-0.0

w8 window rolling_4:   7%| | 14/200 [00:01<00:18,  9.89round/s, val_excess=-0.0

w8 window rolling_4:   7%| | 14/200 [00:01<00:18,  9.89round/s, val_excess=-0.0

w8 window rolling_4:   8%| | 15/200 [00:01<00:18,  9.92round/s, val_excess=-0.0

w8 window rolling_4:   8%| | 15/200 [00:01<00:18,  9.92round/s, val_excess=-0.0

w8 window rolling_4:   8%| | 16/200 [00:01<00:18,  9.92round/s, val_excess=-0.0

w8 window rolling_4:   8%| | 17/200 [00:01<00:18,  9.90round/s, val_excess=-0.0

w8 window rolling_4:   8%| | 17/200 [00:01<00:18,  9.90round/s, val_excess=-0.0

w8 window rolling_4:   9%| | 18/200 [00:01<00:18,  9.85round/s, val_excess=-0.0

w8 window rolling_4:   9%| | 18/200 [00:01<00:18,  9.85round/s, val_excess=0.00

w8 window rolling_4:  10%| | 19/200 [00:01<00:18,  9.72round/s, val_excess=0.00

w8 window rolling_4:  10%| | 19/200 [00:01<00:18,  9.72round/s, val_excess=-0.0

w8 window rolling_4:  10%| | 20/200 [00:02<00:18,  9.77round/s, val_excess=-0.0

w8 window rolling_4:  10%| | 20/200 [00:02<00:18,  9.77round/s, val_excess=-0.0

w8 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.70round/s, val_excess=-0.0

w8 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.70round/s, val_excess=-0.0

w8 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.66round/s, val_excess=-0.0

w8 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.66round/s, val_excess=-0.0

w8 window rolling_4:  12%| | 23/200 [00:02<00:18,  9.66round/s, val_excess=-0.0

w8 window rolling_4:  12%| | 24/200 [00:02<00:18,  9.67round/s, val_excess=-0.0

w8 window rolling_4:  12%| | 24/200 [00:02<00:18,  9.67round/s, val_excess=-0.0

w8 window rolling_4:  12%|▏| 25/200 [00:02<00:18,  9.67round/s, val_excess=-0.0

w8 window rolling_4:  12%|▏| 25/200 [00:02<00:18,  9.67round/s, val_excess=-0.0

w8 window rolling_4:  13%|▏| 26/200 [00:02<00:17,  9.70round/s, val_excess=-0.0

w8 window rolling_4:  13%|▏| 26/200 [00:02<00:17,  9.70round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 27/200 [00:02<00:17,  9.72round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 27/200 [00:02<00:17,  9.72round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 28/200 [00:02<00:17,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 28/200 [00:02<00:17,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 29/200 [00:02<00:17,  9.57round/s, val_excess=-0.0

w8 window rolling_4:  14%|▏| 29/200 [00:02<00:17,  9.57round/s, val_excess=-0.0

w8 window rolling_4:  15%|▏| 30/200 [00:03<00:17,  9.60round/s, val_excess=-0.0

w8 window rolling_4:  15%|▏| 30/200 [00:03<00:17,  9.60round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 31/200 [00:03<00:17,  9.52round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 31/200 [00:03<00:17,  9.52round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 32/200 [00:03<00:17,  9.52round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 32/200 [00:03<00:17,  9.52round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 33/200 [00:03<00:17,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  16%|▏| 33/200 [00:03<00:17,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  17%|▏| 34/200 [00:03<00:18,  9.15round/s, val_excess=-0.0

w8 window rolling_4:  17%|▏| 34/200 [00:03<00:18,  9.15round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 35/200 [00:03<00:18,  9.07round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 35/200 [00:03<00:18,  9.07round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 36/200 [00:03<00:18,  8.88round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 36/200 [00:03<00:18,  8.88round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 37/200 [00:03<00:18,  8.77round/s, val_excess=-0.0

w8 window rolling_4:  18%|▏| 37/200 [00:03<00:18,  8.77round/s, val_excess=-0.0

w8 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.62round/s, val_excess=-0.0

w8 window rolling_4:  19%|▏| 38/200 [00:04<00:18,  8.62round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.54round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 39/200 [00:04<00:18,  8.54round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 40/200 [00:04<00:18,  8.51round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 40/200 [00:04<00:18,  8.51round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 41/200 [00:04<00:18,  8.72round/s, val_excess=-0.0

w8 window rolling_4:  20%|▏| 41/200 [00:04<00:18,  8.72round/s, val_excess=-0.0

w8 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  9.02round/s, val_excess=-0.0

w8 window rolling_4:  21%|▏| 42/200 [00:04<00:17,  9.02round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  9.17round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 43/200 [00:04<00:17,  9.17round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 44/200 [00:04<00:16,  9.20round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 44/200 [00:04<00:16,  9.20round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 45/200 [00:04<00:16,  9.24round/s, val_excess=-0.0

w8 window rolling_4:  22%|▏| 45/200 [00:04<00:16,  9.24round/s, val_excess=-0.0

w8 window rolling_4:  23%|▏| 46/200 [00:04<00:16,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  23%|▏| 46/200 [00:04<00:16,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 47/200 [00:04<00:16,  9.38round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 47/200 [00:04<00:16,  9.38round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 48/200 [00:05<00:16,  9.39round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 48/200 [00:05<00:16,  9.39round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 49/200 [00:05<00:15,  9.44round/s, val_excess=-0.0

w8 window rolling_4:  24%|▏| 49/200 [00:05<00:15,  9.44round/s, val_excess=-0.0

w8 window rolling_4:  25%|▎| 50/200 [00:05<00:15,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  25%|▎| 50/200 [00:05<00:15,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 51/200 [00:05<00:15,  9.45round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 51/200 [00:05<00:15,  9.45round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.41round/s, val_excess=-0.0

w8 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.41round/s, val_excess=-0.0

w8 window rolling_4:  27%|▎| 54/200 [00:05<00:15,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  27%|▎| 54/200 [00:05<00:15,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 55/200 [00:05<00:15,  9.58round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 55/200 [00:05<00:15,  9.58round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 56/200 [00:05<00:15,  9.57round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 56/200 [00:05<00:15,  9.57round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 57/200 [00:06<00:14,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  28%|▎| 57/200 [00:06<00:14,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  29%|▎| 58/200 [00:06<00:14,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  29%|▎| 58/200 [00:06<00:14,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 59/200 [00:06<00:14,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 59/200 [00:06<00:14,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 60/200 [00:06<00:14,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 60/200 [00:06<00:14,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.59round/s, val_excess=-0.0

w8 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.63round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 63/200 [00:06<00:14,  9.60round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 63/200 [00:06<00:14,  9.60round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 64/200 [00:06<00:14,  9.48round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 64/200 [00:06<00:14,  9.48round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 65/200 [00:06<00:14,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  32%|▎| 65/200 [00:06<00:14,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  33%|▎| 66/200 [00:06<00:14,  9.49round/s, val_excess=-0.0

w8 window rolling_4:  33%|▎| 66/200 [00:06<00:14,  9.49round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 67/200 [00:07<00:13,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 67/200 [00:07<00:13,  9.51round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 68/200 [00:07<00:13,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 68/200 [00:07<00:13,  9.50round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 69/200 [00:07<00:13,  9.49round/s, val_excess=-0.0

w8 window rolling_4:  34%|▎| 69/200 [00:07<00:13,  9.49round/s, val_excess=-0.0

w8 window rolling_4:  35%|▎| 70/200 [00:07<00:13,  9.54round/s, val_excess=-0.0

w8 window rolling_4:  35%|▎| 70/200 [00:07<00:13,  9.54round/s, val_excess=-0.0

w8 window rolling_4:  36%|▎| 71/200 [00:07<00:14,  8.96round/s, val_excess=-0.0

w8 window rolling_4:  36%|▎| 71/200 [00:07<00:14,  8.96round/s, val_excess=-0.0

w8 window rolling_4:  36%|▎| 72/200 [00:07<00:14,  8.62round/s, val_excess=-0.0

w8 window rolling_4:  36%|▎| 72/200 [00:07<00:14,  8.62round/s, val_excess=0.00

w8 window rolling_4:  36%|▎| 73/200 [00:07<00:15,  8.38round/s, val_excess=0.00

w8 window rolling_4:  36%|▎| 73/200 [00:07<00:15,  8.38round/s, val_excess=0.00

w8 window rolling_4:  37%|▎| 74/200 [00:07<00:15,  8.23round/s, val_excess=0.00

w8 window rolling_4:  37%|▎| 74/200 [00:07<00:15,  8.23round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 75/200 [00:08<00:15,  8.12round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 75/200 [00:08<00:15,  8.12round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 76/200 [00:08<00:15,  8.05round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 76/200 [00:08<00:15,  8.05round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 77/200 [00:08<00:14,  8.40round/s, val_excess=0.00

w8 window rolling_4:  38%|▍| 77/200 [00:08<00:14,  8.40round/s, val_excess=-0.0

w8 window rolling_4:  39%|▍| 78/200 [00:08<00:14,  8.70round/s, val_excess=-0.0

w8 window rolling_4:  39%|▍| 78/200 [00:08<00:14,  8.70round/s, val_excess=-0.0

w8 window rolling_4:  40%|▍| 79/200 [00:08<00:13,  8.87round/s, val_excess=-0.0

w8 window rolling_4:  40%|▍| 79/200 [00:08<00:13,  8.87round/s, val_excess=0.00

w8 window rolling_4:  40%|▍| 80/200 [00:08<00:13,  9.06round/s, val_excess=0.00

w8 window rolling_4:  40%|▍| 80/200 [00:08<00:13,  9.06round/s, val_excess=-0.0

w8 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.20round/s, val_excess=-0.0

w8 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.20round/s, val_excess=-0.0

w8 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.29round/s, val_excess=-0.0

w8 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.29round/s, val_excess=0.00

w8 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.34round/s, val_excess=0.00

w8 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  42%|▍| 84/200 [00:09<00:12,  9.32round/s, val_excess=-0.0

w8 window rolling_4:  42%|▍| 84/200 [00:09<00:12,  9.32round/s, val_excess=-0.0

w8 window rolling_4:  42%|▍| 85/200 [00:09<00:12,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  42%|▍| 85/200 [00:09<00:12,  9.43round/s, val_excess=-0.0

w8 window rolling_4:  43%|▍| 86/200 [00:09<00:12,  9.41round/s, val_excess=-0.0

w8 window rolling_4:  43%|▍| 86/200 [00:09<00:12,  9.41round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 87/200 [00:09<00:12,  9.40round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 87/200 [00:09<00:12,  9.40round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 88/200 [00:09<00:11,  9.44round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 88/200 [00:09<00:11,  9.44round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.55round/s, val_excess=-0.0

w8 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.55round/s, val_excess=-0.0

w8 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.55round/s, val_excess=-0.0

w8 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.55round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.42round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.42round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.38round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.38round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 93/200 [00:09<00:11,  9.30round/s, val_excess=-0.0

w8 window rolling_4:  46%|▍| 93/200 [00:09<00:11,  9.30round/s, val_excess=-0.0

w8 window rolling_4:  47%|▍| 94/200 [00:10<00:11,  9.36round/s, val_excess=-0.0

w8 window rolling_4:  47%|▍| 94/200 [00:10<00:11,  9.36round/s, val_excess=-0.0

w8 window rolling_4:  48%|▍| 95/200 [00:10<00:11,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  48%|▍| 95/200 [00:10<00:11,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  48%|▍| 96/200 [00:10<00:11,  9.34round/s, val_excess=-0.0

w8 window rolling_4:  48%|▍| 96/200 [00:10<00:11,  9.34round/s, val_excess=0.00

w8 window rolling_4:  48%|▍| 97/200 [00:10<00:11,  9.36round/s, val_excess=0.00

w8 window rolling_4:  48%|▍| 97/200 [00:10<00:11,  9.36round/s, val_excess=0.00

w8 window rolling_4:  49%|▍| 98/200 [00:10<00:11,  9.26round/s, val_excess=0.00

w8 window rolling_4:  49%|▍| 98/200 [00:10<00:11,  9.26round/s, val_excess=0.00

w8 window rolling_4:  50%|▍| 99/200 [00:10<00:10,  9.28round/s, val_excess=0.00

w8 window rolling_4:  50%|▍| 99/200 [00:10<00:10,  9.28round/s, val_excess=0.00

w8 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.23round/s, val_excess=0.0

w8 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.23round/s, val_excess=0.0

w8 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.22round/s, val_excess=0.0

w8 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.22round/s, val_excess=-0.

w8 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.23round/s, val_excess=-0.

w8 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.23round/s, val_excess=-0.

w8 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  9.20round/s, val_excess=-0.

w8 window rolling_4:  52%|▌| 103/200 [00:11<00:10,  9.20round/s, val_excess=0.0

w8 window rolling_4:  52%|▌| 104/200 [00:11<00:10,  9.15round/s, val_excess=0.0

w8 window rolling_4:  52%|▌| 104/200 [00:11<00:10,  9.15round/s, val_excess=0.0

w8 window rolling_4:  52%|▌| 105/200 [00:11<00:10,  9.20round/s, val_excess=0.0

w8 window rolling_4:  52%|▌| 105/200 [00:11<00:10,  9.20round/s, val_excess=0.0

w8 window rolling_4:  53%|▌| 106/200 [00:11<00:10,  9.19round/s, val_excess=0.0

w8 window rolling_4:  53%|▌| 106/200 [00:11<00:10,  9.19round/s, val_excess=0.0

w8 window rolling_4:  54%|▌| 107/200 [00:11<00:10,  9.17round/s, val_excess=0.0

w8 window rolling_4:  54%|▌| 107/200 [00:11<00:10,  9.17round/s, val_excess=0.0

w8 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.28round/s, val_excess=0.0

w8 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.24round/s, val_excess=-0.

w8 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.24round/s, val_excess=-0.

w8 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.33round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.33round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.35round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 112/200 [00:12<00:09,  9.35round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 113/200 [00:12<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  56%|▌| 113/200 [00:12<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  57%|▌| 114/200 [00:12<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  57%|▌| 114/200 [00:12<00:09,  9.28round/s, val_excess=-0.

w8 window rolling_4:  57%|▌| 115/200 [00:12<00:09,  9.33round/s, val_excess=-0.

w8 window rolling_4:  57%|▌| 115/200 [00:12<00:09,  9.33round/s, val_excess=-0.

w8 window rolling_4:  58%|▌| 116/200 [00:12<00:08,  9.40round/s, val_excess=-0.

w8 window rolling_4:  58%|▌| 116/200 [00:12<00:08,  9.40round/s, val_excess=-0.

w8 window rolling_4:  58%|▌| 117/200 [00:12<00:08,  9.41round/s, val_excess=-0.

w8 window rolling_4:  58%|▌| 117/200 [00:12<00:08,  9.41round/s, val_excess=-0.

w8 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.53round/s, val_excess=-0.

w8 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.53round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.49round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.49round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.53round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.53round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.49round/s, val_excess=-0.

w8 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.49round/s, val_excess=-0.

w8 window rolling_4:  61%|▌| 122/200 [00:13<00:08,  9.48round/s, val_excess=-0.

w8 window rolling_4:  61%|▌| 122/200 [00:13<00:08,  9.48round/s, val_excess=-0.

w8 window rolling_4:  62%|▌| 123/200 [00:13<00:08,  9.47round/s, val_excess=-0.

w8 window rolling_4:  62%|▌| 123/200 [00:13<00:08,  9.47round/s, val_excess=-0.

w8 window rolling_4:  62%|▌| 124/200 [00:13<00:08,  9.47round/s, val_excess=-0.

w8 window rolling_4:  62%|▌| 124/200 [00:13<00:08,  9.47round/s, val_excess=-0.

w8 window rolling_4:  62%|▋| 125/200 [00:13<00:07,  9.55round/s, val_excess=-0.

w8 window rolling_4:  62%|▋| 125/200 [00:13<00:07,  9.55round/s, val_excess=-0.

w8 window rolling_4:  63%|▋| 126/200 [00:13<00:07,  9.57round/s, val_excess=-0.

w8 window rolling_4:  63%|▋| 126/200 [00:13<00:07,  9.57round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.54round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.54round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.56round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.56round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.58round/s, val_excess=-0.

w8 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.58round/s, val_excess=-0.

w8 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.59round/s, val_excess=-0.

w8 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.59round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 131/200 [00:14<00:07,  9.55round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 131/200 [00:14<00:07,  9.55round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 132/200 [00:14<00:07,  9.60round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 132/200 [00:14<00:07,  9.60round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 133/200 [00:14<00:07,  9.56round/s, val_excess=-0.

w8 window rolling_4:  66%|▋| 133/200 [00:14<00:07,  9.56round/s, val_excess=-0.

w8 window rolling_4:  67%|▋| 134/200 [00:14<00:06,  9.53round/s, val_excess=-0.

w8 window rolling_4:  67%|▋| 134/200 [00:14<00:06,  9.53round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 135/200 [00:14<00:06,  9.56round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 135/200 [00:14<00:06,  9.56round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 136/200 [00:14<00:06,  9.60round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 136/200 [00:14<00:06,  9.60round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.62round/s, val_excess=-0.

w8 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.62round/s, val_excess=-0.

w8 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.54round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.54round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 141/200 [00:15<00:06,  9.53round/s, val_excess=-0.

w8 window rolling_4:  70%|▋| 141/200 [00:15<00:06,  9.53round/s, val_excess=-0.

w8 window rolling_4:  71%|▋| 142/200 [00:15<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  71%|▋| 142/200 [00:15<00:06,  9.52round/s, val_excess=-0.

w8 window rolling_4:  72%|▋| 143/200 [00:15<00:05,  9.52round/s, val_excess=-0.

w8 window rolling_4:  72%|▋| 144/200 [00:15<00:05,  9.60round/s, val_excess=-0.

w8 window rolling_4:  72%|▋| 144/200 [00:15<00:05,  9.60round/s, val_excess=-0.

w8 window rolling_4:  72%|▋| 145/200 [00:15<00:05,  9.59round/s, val_excess=-0.

w8 window rolling_4:  72%|▋| 145/200 [00:15<00:05,  9.59round/s, val_excess=-0.

w8 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.63round/s, val_excess=-0.

w8 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.63round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.48round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.48round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.45round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.45round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.52round/s, val_excess=-0.

w8 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.52round/s, val_excess=-0.

w8 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.61round/s, val_excess=-0.

w8 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.61round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 151/200 [00:16<00:05,  9.62round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 151/200 [00:16<00:05,  9.62round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 152/200 [00:16<00:04,  9.61round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 152/200 [00:16<00:04,  9.61round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 153/200 [00:16<00:04,  9.60round/s, val_excess=-0.

w8 window rolling_4:  76%|▊| 153/200 [00:16<00:04,  9.60round/s, val_excess=-0.

w8 window rolling_4:  77%|▊| 154/200 [00:16<00:04,  9.54round/s, val_excess=-0.

w8 window rolling_4:  77%|▊| 154/200 [00:16<00:04,  9.54round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 155/200 [00:16<00:04,  9.51round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 155/200 [00:16<00:04,  9.51round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.52round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.52round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.38round/s, val_excess=-0.

w8 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.38round/s, val_excess=-0.

w8 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.43round/s, val_excess=-0.

w8 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.43round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.37round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.37round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 160/200 [00:17<00:04,  9.38round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 160/200 [00:17<00:04,  9.38round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 161/200 [00:17<00:04,  9.48round/s, val_excess=-0.

w8 window rolling_4:  80%|▊| 161/200 [00:17<00:04,  9.48round/s, val_excess=-0.

w8 window rolling_4:  81%|▊| 162/200 [00:17<00:04,  9.49round/s, val_excess=-0.

w8 window rolling_4:  81%|▊| 162/200 [00:17<00:04,  9.49round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 163/200 [00:17<00:03,  9.49round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 163/200 [00:17<00:03,  9.49round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 164/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 164/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 165/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w8 window rolling_4:  82%|▊| 165/200 [00:17<00:03,  9.54round/s, val_excess=-0.

w8 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.55round/s, val_excess=-0.

w8 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.55round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.49round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.49round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.51round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.51round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.47round/s, val_excess=-0.

w8 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.47round/s, val_excess=-0.

w8 window rolling_4:  85%|▊| 170/200 [00:18<00:03,  9.51round/s, val_excess=-0.

w8 window rolling_4:  85%|▊| 170/200 [00:18<00:03,  9.51round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 171/200 [00:18<00:03,  9.52round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 171/200 [00:18<00:03,  9.52round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 172/200 [00:18<00:02,  9.60round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 172/200 [00:18<00:02,  9.60round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 173/200 [00:18<00:02,  9.59round/s, val_excess=-0.

w8 window rolling_4:  86%|▊| 173/200 [00:18<00:02,  9.59round/s, val_excess=-0.

w8 window rolling_4:  87%|▊| 174/200 [00:18<00:02,  9.56round/s, val_excess=-0.

w8 window rolling_4:  87%|▊| 174/200 [00:18<00:02,  9.56round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  9.51round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  9.51round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  9.46round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  9.46round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  8.48round/s, val_excess=-0.

w8 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  8.48round/s, val_excess=-0.

w8 window rolling_4:  89%|▉| 178/200 [00:19<00:02,  8.10round/s, val_excess=-0.

w8 window rolling_4:  89%|▉| 178/200 [00:19<00:02,  8.10round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 179/200 [00:19<00:02,  8.48round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 179/200 [00:19<00:02,  8.48round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 180/200 [00:19<00:02,  8.67round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 180/200 [00:19<00:02,  8.67round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 181/200 [00:19<00:02,  8.80round/s, val_excess=-0.

w8 window rolling_4:  90%|▉| 181/200 [00:19<00:02,  8.80round/s, val_excess=-0.

w8 window rolling_4:  91%|▉| 182/200 [00:19<00:02,  8.93round/s, val_excess=-0.

w8 window rolling_4:  91%|▉| 182/200 [00:19<00:02,  8.93round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 183/200 [00:19<00:01,  9.12round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 183/200 [00:19<00:01,  9.12round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 184/200 [00:19<00:01,  9.35round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 184/200 [00:19<00:01,  9.35round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.36round/s, val_excess=-0.

w8 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.36round/s, val_excess=-0.

w8 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.37round/s, val_excess=-0.

w8 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.37round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.42round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.42round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 188/200 [00:20<00:01,  9.55round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 188/200 [00:20<00:01,  9.55round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 189/200 [00:20<00:01,  9.52round/s, val_excess=-0.

w8 window rolling_4:  94%|▉| 189/200 [00:20<00:01,  9.52round/s, val_excess=-0.

w8 window rolling_4:  95%|▉| 190/200 [00:20<00:01,  9.53round/s, val_excess=-0.

w8 window rolling_4:  95%|▉| 190/200 [00:20<00:01,  9.53round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 191/200 [00:20<00:00,  9.57round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 191/200 [00:20<00:00,  9.57round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 192/200 [00:20<00:00,  9.62round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 192/200 [00:20<00:00,  9.62round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.51round/s, val_excess=-0.

w8 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.51round/s, val_excess=-0.

w8 window rolling_4:  97%|▉| 194/200 [00:20<00:00,  9.55round/s, val_excess=-0.

w8 window rolling_4:  97%|▉| 194/200 [00:20<00:00,  9.55round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.58round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.58round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  9.70round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  9.70round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 197/200 [00:21<00:00,  9.63round/s, val_excess=-0.

w8 window rolling_4:  98%|▉| 197/200 [00:21<00:00,  9.63round/s, val_excess=-0.

w8 window rolling_4:  99%|▉| 198/200 [00:21<00:00,  9.66round/s, val_excess=-0.

w8 window rolling_4:  99%|▉| 198/200 [00:21<00:00,  9.66round/s, val_excess=-0.

w8 window rolling_4: 100%|▉| 199/200 [00:21<00:00,  9.62round/s, val_excess=-0.

w8 window rolling_4: 100%|▉| 199/200 [00:21<00:00,  9.62round/s, val_excess=-0.

w8 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.61round/s, val_excess=-0.

w8 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.61round/s, val_excess=-0.

w8 window rolling_4: 100%|█| 200/200 [00:21<00:00,  9.38round/s, val_excess=-0.

2026-07-06 17:33:30 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=12 feature_type=window fold=rolling_1

2026-07-06 17:33:50 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=12 feature_type=window fold=rolling_1 features=69

w12 window rolling_1:   0%|                         | 0/200 [00:00<?, ?round/s]

w12 window rolling_1:   0%|                 | 1/200 [00:00<00:22,  8.87round/s]

w12 window rolling_1:   0%| | 1/200 [00:00<00:22,  8.87round/s, val_excess=0.00

w12 window rolling_1:   1%| | 2/200 [00:00<00:22,  8.87round/s, val_excess=-0.0

w12 window rolling_1:   2%| | 3/200 [00:00<00:17, 11.49round/s, val_excess=-0.0

w12 window rolling_1:   2%| | 3/200 [00:00<00:17, 11.49round/s, val_excess=0.00

w12 window rolling_1:   2%| | 4/200 [00:00<00:17, 11.49round/s, val_excess=-0.0

w12 window rolling_1:   2%| | 5/200 [00:00<00:16, 11.63round/s, val_excess=-0.0

w12 window rolling_1:   2%| | 5/200 [00:00<00:16, 11.63round/s, val_excess=0.00

w12 window rolling_1:   3%| | 6/200 [00:00<00:16, 11.63round/s, val_excess=0.00

w12 window rolling_1:   4%| | 7/200 [00:00<00:16, 11.42round/s, val_excess=0.00

w12 window rolling_1:   4%| | 7/200 [00:00<00:16, 11.42round/s, val_excess=0.02

w12 window rolling_1:   4%| | 8/200 [00:00<00:16, 11.42round/s, val_excess=0.03

w12 window rolling_1:   4%| | 9/200 [00:00<00:17, 11.18round/s, val_excess=0.03

w12 window rolling_1:   4%| | 9/200 [00:00<00:17, 11.18round/s, val_excess=0.02

w12 window rolling_1:   5%| | 10/200 [00:00<00:16, 11.18round/s, val_excess=0.0

w12 window rolling_1:   6%| | 11/200 [00:00<00:17, 10.89round/s, val_excess=0.0

w12 window rolling_1:   6%| | 11/200 [00:00<00:17, 10.89round/s, val_excess=0.0

w12 window rolling_1:   6%| | 12/200 [00:01<00:17, 10.89round/s, val_excess=0.0

w12 window rolling_1:   6%| | 13/200 [00:01<00:17, 10.84round/s, val_excess=0.0

w12 window rolling_1:   6%| | 13/200 [00:01<00:17, 10.84round/s, val_excess=0.0

w12 window rolling_1:   7%| | 14/200 [00:01<00:17, 10.84round/s, val_excess=0.0

w12 window rolling_1:   8%| | 15/200 [00:01<00:17, 10.82round/s, val_excess=0.0

w12 window rolling_1:   8%| | 15/200 [00:01<00:17, 10.82round/s, val_excess=0.0

w12 window rolling_1:   8%| | 16/200 [00:01<00:17, 10.82round/s, val_excess=0.0

w12 window rolling_1:   8%| | 17/200 [00:01<00:16, 10.81round/s, val_excess=0.0

w12 window rolling_1:   8%| | 17/200 [00:01<00:16, 10.81round/s, val_excess=0.0

w12 window rolling_1:   9%| | 18/200 [00:01<00:16, 10.81round/s, val_excess=0.0

w12 window rolling_1:  10%| | 19/200 [00:01<00:16, 10.73round/s, val_excess=0.0

w12 window rolling_1:  10%| | 19/200 [00:01<00:16, 10.73round/s, val_excess=0.0

w12 window rolling_1:  10%| | 20/200 [00:01<00:16, 10.73round/s, val_excess=0.0

w12 window rolling_1:  10%| | 21/200 [00:01<00:16, 10.68round/s, val_excess=0.0

w12 window rolling_1:  10%| | 21/200 [00:01<00:16, 10.68round/s, val_excess=0.0

w12 window rolling_1:  11%| | 22/200 [00:02<00:16, 10.68round/s, val_excess=0.0

w12 window rolling_1:  12%| | 23/200 [00:02<00:16, 10.59round/s, val_excess=0.0

w12 window rolling_1:  12%| | 23/200 [00:02<00:16, 10.59round/s, val_excess=0.0

w12 window rolling_1:  12%| | 24/200 [00:02<00:16, 10.59round/s, val_excess=0.0

w12 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.53round/s, val_excess=0.0

w12 window rolling_1:  12%|▏| 25/200 [00:02<00:16, 10.53round/s, val_excess=0.0

w12 window rolling_1:  13%|▏| 26/200 [00:02<00:16, 10.53round/s, val_excess=0.0

w12 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.54round/s, val_excess=0.0

w12 window rolling_1:  14%|▏| 27/200 [00:02<00:16, 10.54round/s, val_excess=0.0

w12 window rolling_1:  14%|▏| 28/200 [00:02<00:16, 10.54round/s, val_excess=0.0

w12 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.55round/s, val_excess=0.0

w12 window rolling_1:  14%|▏| 29/200 [00:02<00:16, 10.55round/s, val_excess=0.0

w12 window rolling_1:  15%|▏| 30/200 [00:02<00:16, 10.55round/s, val_excess=0.0

w12 window rolling_1:  16%|▏| 31/200 [00:02<00:15, 10.61round/s, val_excess=0.0

w12 window rolling_1:  16%|▏| 31/200 [00:02<00:15, 10.61round/s, val_excess=0.0

w12 window rolling_1:  16%|▏| 32/200 [00:02<00:15, 10.61round/s, val_excess=0.0

w12 window rolling_1:  16%|▏| 33/200 [00:03<00:15, 10.62round/s, val_excess=0.0

w12 window rolling_1:  16%|▏| 33/200 [00:03<00:15, 10.62round/s, val_excess=0.0

w12 window rolling_1:  17%|▏| 34/200 [00:03<00:15, 10.62round/s, val_excess=0.0

w12 window rolling_1:  18%|▏| 35/200 [00:03<00:15, 10.66round/s, val_excess=0.0

w12 window rolling_1:  18%|▏| 35/200 [00:03<00:15, 10.66round/s, val_excess=0.0

w12 window rolling_1:  18%|▏| 36/200 [00:03<00:15, 10.66round/s, val_excess=0.0

w12 window rolling_1:  18%|▏| 37/200 [00:03<00:15, 10.67round/s, val_excess=0.0

w12 window rolling_1:  18%|▏| 37/200 [00:03<00:15, 10.67round/s, val_excess=-0.

w12 window rolling_1:  19%|▏| 38/200 [00:03<00:15, 10.67round/s, val_excess=0.0

w12 window rolling_1:  20%|▏| 39/200 [00:03<00:15, 10.69round/s, val_excess=0.0

w12 window rolling_1:  20%|▏| 39/200 [00:03<00:15, 10.69round/s, val_excess=-0.

w12 window rolling_1:  20%|▏| 40/200 [00:03<00:14, 10.69round/s, val_excess=0.0

w12 window rolling_1:  20%|▏| 41/200 [00:03<00:14, 10.68round/s, val_excess=0.0

w12 window rolling_1:  20%|▏| 41/200 [00:03<00:14, 10.68round/s, val_excess=-0.

w12 window rolling_1:  21%|▏| 42/200 [00:03<00:14, 10.68round/s, val_excess=-0.

w12 window rolling_1:  22%|▏| 43/200 [00:04<00:14, 10.65round/s, val_excess=-0.

w12 window rolling_1:  22%|▏| 43/200 [00:04<00:14, 10.65round/s, val_excess=-0.

w12 window rolling_1:  22%|▏| 44/200 [00:04<00:14, 10.65round/s, val_excess=-0.

w12 window rolling_1:  22%|▏| 45/200 [00:04<00:14, 10.66round/s, val_excess=-0.

w12 window rolling_1:  22%|▏| 45/200 [00:04<00:14, 10.66round/s, val_excess=-0.

w12 window rolling_1:  23%|▏| 46/200 [00:04<00:14, 10.66round/s, val_excess=-0.

w12 window rolling_1:  24%|▏| 47/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  24%|▏| 47/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  24%|▏| 48/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  24%|▏| 49/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  25%|▎| 50/200 [00:04<00:14, 10.58round/s, val_excess=-0.

w12 window rolling_1:  26%|▎| 51/200 [00:04<00:14, 10.60round/s, val_excess=-0.

w12 window rolling_1:  26%|▎| 51/200 [00:04<00:14, 10.60round/s, val_excess=-0.

w12 window rolling_1:  26%|▎| 52/200 [00:04<00:13, 10.60round/s, val_excess=-0.

w12 window rolling_1:  26%|▎| 53/200 [00:04<00:13, 10.54round/s, val_excess=-0.

w12 window rolling_1:  26%|▎| 53/200 [00:04<00:13, 10.54round/s, val_excess=-0.

w12 window rolling_1:  27%|▎| 54/200 [00:05<00:13, 10.54round/s, val_excess=0.0

w12 window rolling_1:  28%|▎| 55/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  28%|▎| 55/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  28%|▎| 56/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  28%|▎| 57/200 [00:05<00:13, 10.48round/s, val_excess=0.0

w12 window rolling_1:  28%|▎| 57/200 [00:05<00:13, 10.48round/s, val_excess=0.0

w12 window rolling_1:  29%|▎| 58/200 [00:05<00:13, 10.48round/s, val_excess=0.0

w12 window rolling_1:  30%|▎| 59/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  30%|▎| 59/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  30%|▎| 60/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  30%|▎| 61/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  30%|▎| 61/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  31%|▎| 62/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  32%|▎| 63/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  32%|▎| 63/200 [00:05<00:13, 10.52round/s, val_excess=0.0

w12 window rolling_1:  32%|▎| 64/200 [00:06<00:12, 10.52round/s, val_excess=0.0

w12 window rolling_1:  32%|▎| 65/200 [00:06<00:12, 10.48round/s, val_excess=0.0

w12 window rolling_1:  32%|▎| 65/200 [00:06<00:12, 10.48round/s, val_excess=0.0

w12 window rolling_1:  33%|▎| 66/200 [00:06<00:12, 10.48round/s, val_excess=0.0

w12 window rolling_1:  34%|▎| 67/200 [00:06<00:12, 10.51round/s, val_excess=0.0

w12 window rolling_1:  34%|▎| 67/200 [00:06<00:12, 10.51round/s, val_excess=-0.

w12 window rolling_1:  34%|▎| 68/200 [00:06<00:12, 10.51round/s, val_excess=-0.

w12 window rolling_1:  34%|▎| 69/200 [00:06<00:12, 10.55round/s, val_excess=-0.

w12 window rolling_1:  34%|▎| 69/200 [00:06<00:12, 10.55round/s, val_excess=-0.

w12 window rolling_1:  35%|▎| 70/200 [00:06<00:12, 10.55round/s, val_excess=-0.

w12 window rolling_1:  36%|▎| 71/200 [00:06<00:12, 10.54round/s, val_excess=-0.

w12 window rolling_1:  36%|▎| 71/200 [00:06<00:12, 10.54round/s, val_excess=-0.

w12 window rolling_1:  36%|▎| 72/200 [00:06<00:12, 10.54round/s, val_excess=-0.

w12 window rolling_1:  36%|▎| 73/200 [00:06<00:12, 10.56round/s, val_excess=-0.

w12 window rolling_1:  36%|▎| 73/200 [00:06<00:12, 10.56round/s, val_excess=-0.

w12 window rolling_1:  37%|▎| 74/200 [00:06<00:11, 10.56round/s, val_excess=-0.

w12 window rolling_1:  38%|▍| 75/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  38%|▍| 75/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  38%|▍| 76/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  38%|▍| 77/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  38%|▍| 77/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  39%|▍| 78/200 [00:07<00:11, 10.51round/s, val_excess=-0.

w12 window rolling_1:  40%|▍| 79/200 [00:07<00:11, 10.47round/s, val_excess=-0.

w12 window rolling_1:  40%|▍| 79/200 [00:07<00:11, 10.47round/s, val_excess=-0.

w12 window rolling_1:  40%|▍| 80/200 [00:07<00:11, 10.47round/s, val_excess=-0.

w12 window rolling_1:  40%|▍| 81/200 [00:07<00:11, 10.46round/s, val_excess=-0.

w12 window rolling_1:  40%|▍| 81/200 [00:07<00:11, 10.46round/s, val_excess=-0.

w12 window rolling_1:  41%|▍| 82/200 [00:07<00:11, 10.46round/s, val_excess=-0.

w12 window rolling_1:  42%|▍| 83/200 [00:07<00:11, 10.53round/s, val_excess=-0.

w12 window rolling_1:  42%|▍| 83/200 [00:07<00:11, 10.53round/s, val_excess=-0.

w12 window rolling_1:  42%|▍| 84/200 [00:07<00:11, 10.53round/s, val_excess=-0.

w12 window rolling_1:  42%|▍| 85/200 [00:07<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  42%|▍| 85/200 [00:07<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  43%|▍| 86/200 [00:08<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  44%|▍| 87/200 [00:08<00:10, 10.42round/s, val_excess=-0.

w12 window rolling_1:  44%|▍| 87/200 [00:08<00:10, 10.42round/s, val_excess=-0.

w12 window rolling_1:  44%|▍| 88/200 [00:08<00:10, 10.42round/s, val_excess=-0.

w12 window rolling_1:  44%|▍| 89/200 [00:08<00:10, 10.39round/s, val_excess=-0.

w12 window rolling_1:  44%|▍| 89/200 [00:08<00:10, 10.39round/s, val_excess=-0.

w12 window rolling_1:  45%|▍| 90/200 [00:08<00:10, 10.39round/s, val_excess=-0.

w12 window rolling_1:  46%|▍| 91/200 [00:08<00:10, 10.45round/s, val_excess=-0.

w12 window rolling_1:  46%|▍| 91/200 [00:08<00:10, 10.45round/s, val_excess=-0.

w12 window rolling_1:  46%|▍| 92/200 [00:08<00:10, 10.45round/s, val_excess=-0.

w12 window rolling_1:  46%|▍| 93/200 [00:08<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  46%|▍| 93/200 [00:08<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  47%|▍| 94/200 [00:08<00:10, 10.51round/s, val_excess=-0.

w12 window rolling_1:  48%|▍| 95/200 [00:08<00:09, 10.55round/s, val_excess=-0.

w12 window rolling_1:  48%|▍| 95/200 [00:08<00:09, 10.55round/s, val_excess=-0.

w12 window rolling_1:  48%|▍| 96/200 [00:09<00:09, 10.55round/s, val_excess=-0.

w12 window rolling_1:  48%|▍| 97/200 [00:09<00:09, 10.54round/s, val_excess=-0.

w12 window rolling_1:  48%|▍| 97/200 [00:09<00:09, 10.54round/s, val_excess=-0.

w12 window rolling_1:  49%|▍| 98/200 [00:09<00:09, 10.54round/s, val_excess=-0.

w12 window rolling_1:  50%|▍| 99/200 [00:09<00:09, 10.52round/s, val_excess=-0.

w12 window rolling_1:  50%|▍| 99/200 [00:09<00:09, 10.52round/s, val_excess=-0.

w12 window rolling_1:  50%|▌| 100/200 [00:09<00:09, 10.52round/s, val_excess=-0

w12 window rolling_1:  50%|▌| 101/200 [00:09<00:09, 10.52round/s, val_excess=-0

w12 window rolling_1:  50%|▌| 101/200 [00:09<00:09, 10.52round/s, val_excess=-0

w12 window rolling_1:  51%|▌| 102/200 [00:09<00:09, 10.52round/s, val_excess=-0

w12 window rolling_1:  52%|▌| 103/200 [00:09<00:09, 10.48round/s, val_excess=-0

w12 window rolling_1:  52%|▌| 103/200 [00:09<00:09, 10.48round/s, val_excess=-0

w12 window rolling_1:  52%|▌| 104/200 [00:09<00:09, 10.48round/s, val_excess=0.

w12 window rolling_1:  52%|▌| 105/200 [00:09<00:09, 10.47round/s, val_excess=0.

w12 window rolling_1:  52%|▌| 105/200 [00:09<00:09, 10.47round/s, val_excess=0.

w12 window rolling_1:  53%|▌| 106/200 [00:10<00:08, 10.47round/s, val_excess=0.

w12 window rolling_1:  54%|▌| 107/200 [00:10<00:08, 10.49round/s, val_excess=0.

w12 window rolling_1:  54%|▌| 107/200 [00:10<00:08, 10.49round/s, val_excess=0.

w12 window rolling_1:  54%|▌| 108/200 [00:10<00:08, 10.49round/s, val_excess=0.

w12 window rolling_1:  55%|▌| 109/200 [00:10<00:08, 10.44round/s, val_excess=0.

w12 window rolling_1:  55%|▌| 109/200 [00:10<00:08, 10.44round/s, val_excess=0.

w12 window rolling_1:  55%|▌| 110/200 [00:10<00:08, 10.44round/s, val_excess=0.

w12 window rolling_1:  56%|▌| 111/200 [00:10<00:08, 10.40round/s, val_excess=0.

w12 window rolling_1:  56%|▌| 111/200 [00:10<00:08, 10.40round/s, val_excess=0.

w12 window rolling_1:  56%|▌| 112/200 [00:10<00:08, 10.40round/s, val_excess=0.

w12 window rolling_1:  56%|▌| 113/200 [00:10<00:08, 10.37round/s, val_excess=0.

w12 window rolling_1:  56%|▌| 113/200 [00:10<00:08, 10.37round/s, val_excess=0.

w12 window rolling_1:  57%|▌| 114/200 [00:10<00:08, 10.37round/s, val_excess=0.

w12 window rolling_1:  57%|▌| 115/200 [00:10<00:08, 10.34round/s, val_excess=0.

w12 window rolling_1:  57%|▌| 115/200 [00:10<00:08, 10.34round/s, val_excess=-0

w12 window rolling_1:  58%|▌| 116/200 [00:10<00:08, 10.34round/s, val_excess=0.

w12 window rolling_1:  58%|▌| 117/200 [00:11<00:08, 10.32round/s, val_excess=0.

w12 window rolling_1:  58%|▌| 117/200 [00:11<00:08, 10.32round/s, val_excess=0.

w12 window rolling_1:  59%|▌| 118/200 [00:11<00:07, 10.32round/s, val_excess=0.

w12 window rolling_1:  60%|▌| 119/200 [00:11<00:07, 10.34round/s, val_excess=0.

w12 window rolling_1:  60%|▌| 119/200 [00:11<00:07, 10.34round/s, val_excess=0.

w12 window rolling_1:  60%|▌| 120/200 [00:11<00:07, 10.34round/s, val_excess=0.

w12 window rolling_1:  60%|▌| 121/200 [00:11<00:07, 10.37round/s, val_excess=0.

w12 window rolling_1:  60%|▌| 121/200 [00:11<00:07, 10.37round/s, val_excess=0.

w12 window rolling_1:  61%|▌| 122/200 [00:11<00:07, 10.37round/s, val_excess=-0

w12 window rolling_1:  62%|▌| 123/200 [00:11<00:07, 10.41round/s, val_excess=-0

w12 window rolling_1:  62%|▌| 123/200 [00:11<00:07, 10.41round/s, val_excess=-0

w12 window rolling_1:  62%|▌| 124/200 [00:11<00:07, 10.41round/s, val_excess=-0

w12 window rolling_1:  62%|▋| 125/200 [00:11<00:07, 10.40round/s, val_excess=-0

w12 window rolling_1:  62%|▋| 125/200 [00:11<00:07, 10.40round/s, val_excess=0.

w12 window rolling_1:  63%|▋| 126/200 [00:11<00:07, 10.40round/s, val_excess=0.

w12 window rolling_1:  64%|▋| 127/200 [00:12<00:07, 10.25round/s, val_excess=0.

w12 window rolling_1:  64%|▋| 127/200 [00:12<00:07, 10.25round/s, val_excess=0.

w12 window rolling_1:  64%|▋| 128/200 [00:12<00:07, 10.25round/s, val_excess=0.

w12 window rolling_1:  64%|▋| 129/200 [00:12<00:06, 10.33round/s, val_excess=0.

w12 window rolling_1:  64%|▋| 129/200 [00:12<00:06, 10.33round/s, val_excess=0.

w12 window rolling_1:  65%|▋| 130/200 [00:12<00:06, 10.33round/s, val_excess=0.

w12 window rolling_1:  66%|▋| 131/200 [00:12<00:06, 10.43round/s, val_excess=0.

w12 window rolling_1:  66%|▋| 131/200 [00:12<00:06, 10.43round/s, val_excess=0.

w12 window rolling_1:  66%|▋| 132/200 [00:12<00:06, 10.43round/s, val_excess=0.

w12 window rolling_1:  66%|▋| 133/200 [00:12<00:06, 10.47round/s, val_excess=0.

w12 window rolling_1:  66%|▋| 133/200 [00:12<00:06, 10.47round/s, val_excess=0.

w12 window rolling_1:  67%|▋| 134/200 [00:12<00:06, 10.47round/s, val_excess=0.

w12 window rolling_1:  68%|▋| 135/200 [00:12<00:06, 10.56round/s, val_excess=0.

w12 window rolling_1:  68%|▋| 135/200 [00:12<00:06, 10.56round/s, val_excess=0.

w12 window rolling_1:  68%|▋| 136/200 [00:12<00:06, 10.56round/s, val_excess=0.

w12 window rolling_1:  68%|▋| 137/200 [00:12<00:05, 10.52round/s, val_excess=0.

w12 window rolling_1:  68%|▋| 137/200 [00:12<00:05, 10.52round/s, val_excess=0.

w12 window rolling_1:  69%|▋| 138/200 [00:13<00:05, 10.52round/s, val_excess=0.

w12 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.65round/s, val_excess=0.

w12 window rolling_1:  70%|▋| 139/200 [00:13<00:05, 10.65round/s, val_excess=0.

w12 window rolling_1:  70%|▋| 140/200 [00:13<00:05, 10.65round/s, val_excess=0.

w12 window rolling_1:  70%|▋| 141/200 [00:13<00:05, 10.66round/s, val_excess=0.

w12 window rolling_1:  70%|▋| 141/200 [00:13<00:05, 10.66round/s, val_excess=0.

w12 window rolling_1:  71%|▋| 142/200 [00:13<00:05, 10.66round/s, val_excess=0.

w12 window rolling_1:  72%|▋| 143/200 [00:13<00:05, 10.60round/s, val_excess=0.

w12 window rolling_1:  72%|▋| 143/200 [00:13<00:05, 10.60round/s, val_excess=0.

w12 window rolling_1:  72%|▋| 144/200 [00:13<00:05, 10.60round/s, val_excess=0.

w12 window rolling_1:  72%|▋| 145/200 [00:13<00:05, 10.69round/s, val_excess=0.

w12 window rolling_1:  72%|▋| 145/200 [00:13<00:05, 10.69round/s, val_excess=0.

w12 window rolling_1:  73%|▋| 146/200 [00:13<00:05, 10.69round/s, val_excess=0.

w12 window rolling_1:  74%|▋| 147/200 [00:13<00:04, 10.62round/s, val_excess=0.

w12 window rolling_1:  74%|▋| 147/200 [00:13<00:04, 10.62round/s, val_excess=0.

w12 window rolling_1:  74%|▋| 148/200 [00:14<00:04, 10.62round/s, val_excess=0.

w12 window rolling_1:  74%|▋| 149/200 [00:14<00:04, 10.67round/s, val_excess=0.

w12 window rolling_1:  74%|▋| 149/200 [00:14<00:04, 10.67round/s, val_excess=0.

w12 window rolling_1:  75%|▊| 150/200 [00:14<00:04, 10.67round/s, val_excess=0.

w12 window rolling_1:  76%|▊| 151/200 [00:14<00:04, 10.59round/s, val_excess=0.

w12 window rolling_1:  76%|▊| 151/200 [00:14<00:04, 10.59round/s, val_excess=0.

w12 window rolling_1:  76%|▊| 152/200 [00:14<00:04, 10.59round/s, val_excess=0.

w12 window rolling_1:  76%|▊| 153/200 [00:14<00:04, 10.53round/s, val_excess=0.

w12 window rolling_1:  76%|▊| 153/200 [00:14<00:04, 10.53round/s, val_excess=0.

w12 window rolling_1:  77%|▊| 154/200 [00:14<00:04, 10.53round/s, val_excess=0.

w12 window rolling_1:  78%|▊| 155/200 [00:14<00:04, 10.60round/s, val_excess=0.

w12 window rolling_1:  78%|▊| 155/200 [00:14<00:04, 10.60round/s, val_excess=0.

w12 window rolling_1:  78%|▊| 156/200 [00:14<00:04, 10.60round/s, val_excess=0.

w12 window rolling_1:  78%|▊| 157/200 [00:14<00:04, 10.60round/s, val_excess=0.

w12 window rolling_1:  78%|▊| 157/200 [00:14<00:04, 10.60round/s, val_excess=0.

w12 window rolling_1:  79%|▊| 158/200 [00:14<00:03, 10.60round/s, val_excess=0.

w12 window rolling_1:  80%|▊| 159/200 [00:15<00:03, 10.65round/s, val_excess=0.

w12 window rolling_1:  80%|▊| 159/200 [00:15<00:03, 10.65round/s, val_excess=0.

w12 window rolling_1:  80%|▊| 160/200 [00:15<00:03, 10.65round/s, val_excess=0.

w12 window rolling_1:  80%|▊| 161/200 [00:15<00:03, 10.70round/s, val_excess=0.

w12 window rolling_1:  80%|▊| 161/200 [00:15<00:03, 10.70round/s, val_excess=0.

w12 window rolling_1:  81%|▊| 162/200 [00:15<00:03, 10.70round/s, val_excess=0.

w12 window rolling_1:  82%|▊| 163/200 [00:15<00:03, 10.62round/s, val_excess=0.

w12 window rolling_1:  82%|▊| 163/200 [00:15<00:03, 10.62round/s, val_excess=0.

w12 window rolling_1:  82%|▊| 164/200 [00:15<00:03, 10.62round/s, val_excess=0.

w12 window rolling_1:  82%|▊| 165/200 [00:15<00:03, 10.55round/s, val_excess=0.

w12 window rolling_1:  82%|▊| 165/200 [00:15<00:03, 10.55round/s, val_excess=0.

w12 window rolling_1:  83%|▊| 166/200 [00:15<00:03, 10.55round/s, val_excess=0.

w12 window rolling_1:  84%|▊| 167/200 [00:15<00:03, 10.57round/s, val_excess=0.

w12 window rolling_1:  84%|▊| 167/200 [00:15<00:03, 10.57round/s, val_excess=0.

w12 window rolling_1:  84%|▊| 168/200 [00:15<00:03, 10.57round/s, val_excess=0.

w12 window rolling_1:  84%|▊| 169/200 [00:15<00:02, 10.55round/s, val_excess=0.

w12 window rolling_1:  84%|▊| 169/200 [00:15<00:02, 10.55round/s, val_excess=0.

w12 window rolling_1:  85%|▊| 170/200 [00:16<00:02, 10.55round/s, val_excess=0.

w12 window rolling_1:  86%|▊| 171/200 [00:16<00:02, 10.56round/s, val_excess=0.

w12 window rolling_1:  86%|▊| 171/200 [00:16<00:02, 10.56round/s, val_excess=0.

w12 window rolling_1:  86%|▊| 172/200 [00:16<00:02, 10.56round/s, val_excess=0.

w12 window rolling_1:  86%|▊| 173/200 [00:16<00:02, 10.60round/s, val_excess=0.

w12 window rolling_1:  86%|▊| 173/200 [00:16<00:02, 10.60round/s, val_excess=0.

w12 window rolling_1:  87%|▊| 174/200 [00:16<00:02, 10.60round/s, val_excess=0.

w12 window rolling_1:  88%|▉| 175/200 [00:16<00:02, 10.58round/s, val_excess=0.

w12 window rolling_1:  88%|▉| 175/200 [00:16<00:02, 10.58round/s, val_excess=0.

w12 window rolling_1:  88%|▉| 176/200 [00:16<00:02, 10.58round/s, val_excess=0.

w12 window rolling_1:  88%|▉| 177/200 [00:16<00:02, 10.65round/s, val_excess=0.

w12 window rolling_1:  88%|▉| 177/200 [00:16<00:02, 10.65round/s, val_excess=0.

w12 window rolling_1:  89%|▉| 178/200 [00:16<00:02, 10.65round/s, val_excess=0.

w12 window rolling_1:  90%|▉| 179/200 [00:16<00:01, 10.59round/s, val_excess=0.

w12 window rolling_1:  90%|▉| 179/200 [00:16<00:01, 10.59round/s, val_excess=0.

w12 window rolling_1:  90%|▉| 180/200 [00:17<00:01, 10.59round/s, val_excess=0.

w12 window rolling_1:  90%|▉| 181/200 [00:17<00:01, 10.48round/s, val_excess=0.

w12 window rolling_1:  90%|▉| 181/200 [00:17<00:01, 10.48round/s, val_excess=0.

w12 window rolling_1:  91%|▉| 182/200 [00:17<00:01, 10.48round/s, val_excess=0.

w12 window rolling_1:  92%|▉| 183/200 [00:17<00:01, 10.49round/s, val_excess=0.

w12 window rolling_1:  92%|▉| 183/200 [00:17<00:01, 10.49round/s, val_excess=0.

w12 window rolling_1:  92%|▉| 184/200 [00:17<00:01, 10.49round/s, val_excess=0.

w12 window rolling_1:  92%|▉| 185/200 [00:17<00:01, 10.52round/s, val_excess=0.

w12 window rolling_1:  92%|▉| 185/200 [00:17<00:01, 10.52round/s, val_excess=0.

w12 window rolling_1:  93%|▉| 186/200 [00:17<00:01, 10.52round/s, val_excess=0.

w12 window rolling_1:  94%|▉| 187/200 [00:17<00:01, 10.45round/s, val_excess=0.

w12 window rolling_1:  94%|▉| 187/200 [00:17<00:01, 10.45round/s, val_excess=0.

w12 window rolling_1:  94%|▉| 188/200 [00:17<00:01, 10.45round/s, val_excess=0.

w12 window rolling_1:  94%|▉| 189/200 [00:17<00:01, 10.53round/s, val_excess=0.

w12 window rolling_1:  94%|▉| 189/200 [00:17<00:01, 10.53round/s, val_excess=0.

w12 window rolling_1:  95%|▉| 190/200 [00:17<00:00, 10.53round/s, val_excess=0.

w12 window rolling_1:  96%|▉| 191/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1:  96%|▉| 191/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1:  96%|▉| 192/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1:  96%|▉| 193/200 [00:18<00:00, 10.46round/s, val_excess=0.

w12 window rolling_1:  96%|▉| 193/200 [00:18<00:00, 10.46round/s, val_excess=0.

w12 window rolling_1:  97%|▉| 194/200 [00:18<00:00, 10.46round/s, val_excess=0.

w12 window rolling_1:  98%|▉| 195/200 [00:18<00:00, 10.39round/s, val_excess=0.

w12 window rolling_1:  98%|▉| 195/200 [00:18<00:00, 10.39round/s, val_excess=0.

w12 window rolling_1:  98%|▉| 196/200 [00:18<00:00, 10.39round/s, val_excess=0.

w12 window rolling_1:  98%|▉| 197/200 [00:18<00:00, 10.43round/s, val_excess=0.

w12 window rolling_1:  98%|▉| 197/200 [00:18<00:00, 10.43round/s, val_excess=0.

w12 window rolling_1:  99%|▉| 198/200 [00:18<00:00, 10.43round/s, val_excess=0.

w12 window rolling_1: 100%|▉| 199/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1: 100%|▉| 199/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1: 100%|█| 200/200 [00:18<00:00, 10.54round/s, val_excess=0.

w12 window rolling_1: 100%|█| 200/200 [00:18<00:00, 10.56round/s, val_excess=0.

2026-07-06 17:34:09 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=12 feature_type=window fold=rolling_2

2026-07-06 17:34:30 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=12 feature_type=window fold=rolling_2 features=69

w12 window rolling_2:   0%|                         | 0/200 [00:00<?, ?round/s]

w12 window rolling_2:   0%| | 1/200 [00:00<00:19, 10.09round/s, val_excess=0.00

w12 window rolling_2:   1%| | 2/200 [00:00<00:17, 11.37round/s, val_excess=0.00

w12 window rolling_2:   1%| | 2/200 [00:00<00:17, 11.37round/s, val_excess=-0.0

w12 window rolling_2:   2%| | 3/200 [00:00<00:17, 11.37round/s, val_excess=-0.0

w12 window rolling_2:   2%| | 4/200 [00:00<00:16, 11.64round/s, val_excess=-0.0

w12 window rolling_2:   2%| | 4/200 [00:00<00:16, 11.64round/s, val_excess=-0.0

w12 window rolling_2:   2%| | 5/200 [00:00<00:16, 11.64round/s, val_excess=0.00

w12 window rolling_2:   3%| | 6/200 [00:00<00:17, 11.26round/s, val_excess=0.00

w12 window rolling_2:   3%| | 6/200 [00:00<00:17, 11.26round/s, val_excess=-0.0

w12 window rolling_2:   4%| | 7/200 [00:00<00:17, 11.26round/s, val_excess=0.00

w12 window rolling_2:   4%| | 8/200 [00:00<00:17, 10.85round/s, val_excess=0.00

w12 window rolling_2:   4%| | 8/200 [00:00<00:17, 10.85round/s, val_excess=0.00

w12 window rolling_2:   4%| | 9/200 [00:00<00:17, 10.85round/s, val_excess=0.00

w12 window rolling_2:   5%| | 10/200 [00:00<00:18, 10.07round/s, val_excess=0.0

w12 window rolling_2:   5%| | 10/200 [00:00<00:18, 10.07round/s, val_excess=0.0

w12 window rolling_2:   6%| | 11/200 [00:01<00:18, 10.07round/s, val_excess=0.0

w12 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.80round/s, val_excess=0.0

w12 window rolling_2:   6%| | 12/200 [00:01<00:19,  9.80round/s, val_excess=0.0

w12 window rolling_2:   6%| | 13/200 [00:01<00:19,  9.80round/s, val_excess=0.0

w12 window rolling_2:   7%| | 14/200 [00:01<00:18,  9.88round/s, val_excess=0.0

w12 window rolling_2:   7%| | 14/200 [00:01<00:18,  9.88round/s, val_excess=0.0

w12 window rolling_2:   8%| | 15/200 [00:01<00:18,  9.88round/s, val_excess=0.0

w12 window rolling_2:   8%| | 16/200 [00:01<00:18,  9.96round/s, val_excess=0.0

w12 window rolling_2:   8%| | 16/200 [00:01<00:18,  9.96round/s, val_excess=0.0

w12 window rolling_2:   8%| | 17/200 [00:01<00:18,  9.95round/s, val_excess=0.0

w12 window rolling_2:   8%| | 17/200 [00:01<00:18,  9.95round/s, val_excess=0.0

w12 window rolling_2:   9%| | 18/200 [00:01<00:18,  9.95round/s, val_excess=0.0

w12 window rolling_2:  10%| | 19/200 [00:01<00:18, 10.03round/s, val_excess=0.0

w12 window rolling_2:  10%| | 19/200 [00:01<00:18, 10.03round/s, val_excess=0.0

w12 window rolling_2:  10%| | 20/200 [00:01<00:17, 10.03round/s, val_excess=0.0

w12 window rolling_2:  10%| | 21/200 [00:02<00:18,  9.93round/s, val_excess=0.0

w12 window rolling_2:  10%| | 21/200 [00:02<00:18,  9.93round/s, val_excess=0.0

w12 window rolling_2:  11%| | 22/200 [00:02<00:17,  9.93round/s, val_excess=0.0

w12 window rolling_2:  12%| | 23/200 [00:02<00:17, 10.02round/s, val_excess=0.0

w12 window rolling_2:  12%| | 23/200 [00:02<00:17, 10.02round/s, val_excess=0.0

w12 window rolling_2:  12%| | 24/200 [00:02<00:17, 10.02round/s, val_excess=0.0

w12 window rolling_2:  12%|▏| 25/200 [00:02<00:17,  9.76round/s, val_excess=0.0

w12 window rolling_2:  12%|▏| 25/200 [00:02<00:17,  9.76round/s, val_excess=0.0

w12 window rolling_2:  13%|▏| 26/200 [00:02<00:18,  9.45round/s, val_excess=0.0

w12 window rolling_2:  13%|▏| 26/200 [00:02<00:18,  9.45round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 27/200 [00:02<00:18,  9.19round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 27/200 [00:02<00:18,  9.19round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 28/200 [00:02<00:19,  8.97round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 28/200 [00:02<00:19,  8.97round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 29/200 [00:02<00:18,  9.12round/s, val_excess=0.0

w12 window rolling_2:  14%|▏| 29/200 [00:02<00:18,  9.12round/s, val_excess=0.0

w12 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.31round/s, val_excess=0.0

w12 window rolling_2:  15%|▏| 30/200 [00:03<00:18,  9.31round/s, val_excess=0.0

w12 window rolling_2:  16%|▏| 31/200 [00:03<00:18,  9.31round/s, val_excess=0.0

w12 window rolling_2:  16%|▏| 32/200 [00:03<00:17,  9.56round/s, val_excess=0.0

w12 window rolling_2:  16%|▏| 32/200 [00:03<00:17,  9.56round/s, val_excess=0.0

w12 window rolling_2:  16%|▏| 33/200 [00:03<00:17,  9.56round/s, val_excess=0.0

w12 window rolling_2:  17%|▏| 34/200 [00:03<00:17,  9.60round/s, val_excess=0.0

w12 window rolling_2:  17%|▏| 34/200 [00:03<00:17,  9.60round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 35/200 [00:03<00:17,  9.66round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 35/200 [00:03<00:17,  9.66round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 36/200 [00:03<00:16,  9.71round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 36/200 [00:03<00:16,  9.71round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 37/200 [00:03<00:16,  9.74round/s, val_excess=0.0

w12 window rolling_2:  18%|▏| 37/200 [00:03<00:16,  9.74round/s, val_excess=0.0

w12 window rolling_2:  19%|▏| 38/200 [00:03<00:16,  9.74round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 39/200 [00:03<00:16,  9.90round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 39/200 [00:03<00:16,  9.90round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 40/200 [00:04<00:16,  9.91round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 40/200 [00:04<00:16,  9.91round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 41/200 [00:04<00:16,  9.92round/s, val_excess=0.0

w12 window rolling_2:  20%|▏| 41/200 [00:04<00:16,  9.92round/s, val_excess=0.0

w12 window rolling_2:  21%|▏| 42/200 [00:04<00:15,  9.92round/s, val_excess=0.0

w12 window rolling_2:  22%|▏| 43/200 [00:04<00:15, 10.01round/s, val_excess=0.0

w12 window rolling_2:  22%|▏| 43/200 [00:04<00:15, 10.01round/s, val_excess=0.0

w12 window rolling_2:  22%|▏| 44/200 [00:04<00:15,  9.99round/s, val_excess=0.0

w12 window rolling_2:  22%|▏| 44/200 [00:04<00:15,  9.99round/s, val_excess=0.0

w12 window rolling_2:  22%|▏| 45/200 [00:04<00:15,  9.99round/s, val_excess=0.0

w12 window rolling_2:  23%|▏| 46/200 [00:04<00:15, 10.11round/s, val_excess=0.0

w12 window rolling_2:  23%|▏| 46/200 [00:04<00:15, 10.11round/s, val_excess=0.0

w12 window rolling_2:  24%|▏| 47/200 [00:04<00:15, 10.11round/s, val_excess=0.0

w12 window rolling_2:  24%|▏| 48/200 [00:04<00:15, 10.11round/s, val_excess=0.0

w12 window rolling_2:  24%|▏| 48/200 [00:04<00:15, 10.11round/s, val_excess=0.0

w12 window rolling_2:  24%|▏| 49/200 [00:04<00:14, 10.11round/s, val_excess=0.0

w12 window rolling_2:  25%|▎| 50/200 [00:05<00:14, 10.11round/s, val_excess=0.0

w12 window rolling_2:  25%|▎| 50/200 [00:05<00:14, 10.11round/s, val_excess=0.0

w12 window rolling_2:  26%|▎| 51/200 [00:05<00:14, 10.11round/s, val_excess=0.0

w12 window rolling_2:  26%|▎| 52/200 [00:05<00:14, 10.13round/s, val_excess=0.0

w12 window rolling_2:  26%|▎| 52/200 [00:05<00:14, 10.13round/s, val_excess=0.0

w12 window rolling_2:  26%|▎| 53/200 [00:05<00:14, 10.13round/s, val_excess=0.0

w12 window rolling_2:  27%|▎| 54/200 [00:05<00:14, 10.19round/s, val_excess=0.0

w12 window rolling_2:  27%|▎| 54/200 [00:05<00:14, 10.19round/s, val_excess=0.0

w12 window rolling_2:  28%|▎| 55/200 [00:05<00:14, 10.19round/s, val_excess=0.0

w12 window rolling_2:  28%|▎| 56/200 [00:05<00:14, 10.23round/s, val_excess=0.0

w12 window rolling_2:  28%|▎| 56/200 [00:05<00:14, 10.23round/s, val_excess=0.0

w12 window rolling_2:  28%|▎| 57/200 [00:05<00:13, 10.23round/s, val_excess=0.0

w12 window rolling_2:  29%|▎| 58/200 [00:05<00:13, 10.21round/s, val_excess=0.0

w12 window rolling_2:  29%|▎| 58/200 [00:05<00:13, 10.21round/s, val_excess=0.0

w12 window rolling_2:  30%|▎| 59/200 [00:05<00:13, 10.21round/s, val_excess=0.0

w12 window rolling_2:  30%|▎| 60/200 [00:06<00:13, 10.19round/s, val_excess=0.0

w12 window rolling_2:  30%|▎| 60/200 [00:06<00:13, 10.19round/s, val_excess=0.0

w12 window rolling_2:  30%|▎| 61/200 [00:06<00:13, 10.19round/s, val_excess=0.0

w12 window rolling_2:  31%|▎| 62/200 [00:06<00:13, 10.20round/s, val_excess=0.0

w12 window rolling_2:  31%|▎| 62/200 [00:06<00:13, 10.20round/s, val_excess=0.0

w12 window rolling_2:  32%|▎| 63/200 [00:06<00:13, 10.20round/s, val_excess=0.0

w12 window rolling_2:  32%|▎| 64/200 [00:06<00:13, 10.23round/s, val_excess=0.0

w12 window rolling_2:  32%|▎| 64/200 [00:06<00:13, 10.23round/s, val_excess=0.0

w12 window rolling_2:  32%|▎| 65/200 [00:06<00:13, 10.23round/s, val_excess=0.0

w12 window rolling_2:  33%|▎| 66/200 [00:06<00:13, 10.11round/s, val_excess=0.0

w12 window rolling_2:  33%|▎| 66/200 [00:06<00:13, 10.11round/s, val_excess=0.0

w12 window rolling_2:  34%|▎| 67/200 [00:06<00:13, 10.11round/s, val_excess=0.0

w12 window rolling_2:  34%|▎| 68/200 [00:06<00:13, 10.15round/s, val_excess=0.0

w12 window rolling_2:  34%|▎| 68/200 [00:06<00:13, 10.15round/s, val_excess=0.0

w12 window rolling_2:  34%|▎| 69/200 [00:06<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_2:  35%|▎| 70/200 [00:07<00:12, 10.17round/s, val_excess=0.0

w12 window rolling_2:  35%|▎| 70/200 [00:07<00:12, 10.17round/s, val_excess=0.0

w12 window rolling_2:  36%|▎| 71/200 [00:07<00:12, 10.17round/s, val_excess=0.0

w12 window rolling_2:  36%|▎| 72/200 [00:07<00:12, 10.12round/s, val_excess=0.0

w12 window rolling_2:  36%|▎| 72/200 [00:07<00:12, 10.12round/s, val_excess=0.0

w12 window rolling_2:  36%|▎| 73/200 [00:07<00:12, 10.12round/s, val_excess=0.0

w12 window rolling_2:  37%|▎| 74/200 [00:07<00:12, 10.13round/s, val_excess=0.0

w12 window rolling_2:  37%|▎| 74/200 [00:07<00:12, 10.13round/s, val_excess=0.0

w12 window rolling_2:  38%|▍| 75/200 [00:07<00:12, 10.13round/s, val_excess=0.0

w12 window rolling_2:  38%|▍| 76/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_2:  38%|▍| 76/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_2:  38%|▍| 77/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_2:  39%|▍| 78/200 [00:07<00:12, 10.14round/s, val_excess=0.0

w12 window rolling_2:  39%|▍| 78/200 [00:07<00:12, 10.14round/s, val_excess=0.0

w12 window rolling_2:  40%|▍| 79/200 [00:07<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  40%|▍| 80/200 [00:07<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_2:  40%|▍| 80/200 [00:07<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_2:  40%|▍| 81/200 [00:08<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_2:  41%|▍| 82/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  41%|▍| 82/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  42%|▍| 83/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  42%|▍| 84/200 [00:08<00:11, 10.13round/s, val_excess=0.0

w12 window rolling_2:  42%|▍| 84/200 [00:08<00:11, 10.13round/s, val_excess=0.0

w12 window rolling_2:  42%|▍| 85/200 [00:08<00:11, 10.13round/s, val_excess=0.0

w12 window rolling_2:  43%|▍| 86/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_2:  43%|▍| 86/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_2:  44%|▍| 87/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_2:  44%|▍| 88/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  44%|▍| 88/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_2:  44%|▍| 89/200 [00:08<00:10, 10.14round/s, val_excess=0.0

w12 window rolling_2:  45%|▍| 90/200 [00:08<00:10, 10.13round/s, val_excess=0.0

w12 window rolling_2:  45%|▍| 90/200 [00:08<00:10, 10.13round/s, val_excess=0.0

w12 window rolling_2:  46%|▍| 91/200 [00:09<00:10, 10.13round/s, val_excess=0.0

w12 window rolling_2:  46%|▍| 92/200 [00:09<00:10, 10.10round/s, val_excess=0.0

w12 window rolling_2:  46%|▍| 92/200 [00:09<00:10, 10.10round/s, val_excess=0.0

w12 window rolling_2:  46%|▍| 93/200 [00:09<00:10, 10.10round/s, val_excess=0.0

w12 window rolling_2:  47%|▍| 94/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  47%|▍| 94/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  48%|▍| 95/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  48%|▍| 96/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  48%|▍| 96/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  48%|▍| 97/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  49%|▍| 98/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  49%|▍| 98/200 [00:09<00:10, 10.16round/s, val_excess=0.0

w12 window rolling_2:  50%|▍| 99/200 [00:09<00:09, 10.16round/s, val_excess=0.0

w12 window rolling_2:  50%|▌| 100/200 [00:09<00:09, 10.15round/s, val_excess=0.

w12 window rolling_2:  50%|▌| 100/200 [00:09<00:09, 10.15round/s, val_excess=0.

w12 window rolling_2:  50%|▌| 101/200 [00:10<00:09, 10.15round/s, val_excess=0.

w12 window rolling_2:  51%|▌| 102/200 [00:10<00:09, 10.12round/s, val_excess=0.

w12 window rolling_2:  51%|▌| 102/200 [00:10<00:09, 10.12round/s, val_excess=0.

w12 window rolling_2:  52%|▌| 103/200 [00:10<00:09, 10.12round/s, val_excess=0.

w12 window rolling_2:  52%|▌| 104/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_2:  52%|▌| 104/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_2:  52%|▌| 105/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_2:  53%|▌| 106/200 [00:10<00:09, 10.07round/s, val_excess=0.

w12 window rolling_2:  53%|▌| 106/200 [00:10<00:09, 10.07round/s, val_excess=0.

w12 window rolling_2:  54%|▌| 107/200 [00:10<00:09, 10.07round/s, val_excess=0.

w12 window rolling_2:  54%|▌| 108/200 [00:10<00:09, 10.11round/s, val_excess=0.

w12 window rolling_2:  54%|▌| 108/200 [00:10<00:09, 10.11round/s, val_excess=0.

w12 window rolling_2:  55%|▌| 109/200 [00:10<00:08, 10.11round/s, val_excess=0.

w12 window rolling_2:  55%|▌| 110/200 [00:10<00:08, 10.17round/s, val_excess=0.

w12 window rolling_2:  55%|▌| 110/200 [00:10<00:08, 10.17round/s, val_excess=0.

w12 window rolling_2:  56%|▌| 111/200 [00:11<00:08, 10.17round/s, val_excess=0.

w12 window rolling_2:  56%|▌| 112/200 [00:11<00:08, 10.11round/s, val_excess=0.

w12 window rolling_2:  56%|▌| 112/200 [00:11<00:08, 10.11round/s, val_excess=0.

w12 window rolling_2:  56%|▌| 113/200 [00:11<00:08, 10.11round/s, val_excess=0.

w12 window rolling_2:  57%|▌| 114/200 [00:11<00:08, 10.15round/s, val_excess=0.

w12 window rolling_2:  57%|▌| 114/200 [00:11<00:08, 10.15round/s, val_excess=0.

w12 window rolling_2:  57%|▌| 115/200 [00:11<00:08, 10.15round/s, val_excess=0.

w12 window rolling_2:  58%|▌| 116/200 [00:11<00:08, 10.21round/s, val_excess=0.

w12 window rolling_2:  58%|▌| 116/200 [00:11<00:08, 10.21round/s, val_excess=0.

w12 window rolling_2:  58%|▌| 117/200 [00:11<00:08, 10.21round/s, val_excess=0.

w12 window rolling_2:  59%|▌| 118/200 [00:11<00:08, 10.22round/s, val_excess=0.

w12 window rolling_2:  59%|▌| 118/200 [00:11<00:08, 10.22round/s, val_excess=0.

w12 window rolling_2:  60%|▌| 119/200 [00:11<00:07, 10.22round/s, val_excess=0.

w12 window rolling_2:  60%|▌| 120/200 [00:11<00:07, 10.19round/s, val_excess=0.

w12 window rolling_2:  60%|▌| 120/200 [00:11<00:07, 10.19round/s, val_excess=0.

w12 window rolling_2:  60%|▌| 121/200 [00:12<00:07, 10.19round/s, val_excess=0.

w12 window rolling_2:  61%|▌| 122/200 [00:12<00:07, 10.17round/s, val_excess=0.

w12 window rolling_2:  61%|▌| 122/200 [00:12<00:07, 10.17round/s, val_excess=0.

w12 window rolling_2:  62%|▌| 123/200 [00:12<00:07, 10.17round/s, val_excess=0.

w12 window rolling_2:  62%|▌| 124/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  62%|▌| 124/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  62%|▋| 125/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  63%|▋| 126/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  63%|▋| 126/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  64%|▋| 127/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_2:  64%|▋| 128/200 [00:12<00:07, 10.22round/s, val_excess=0.

w12 window rolling_2:  64%|▋| 128/200 [00:12<00:07, 10.22round/s, val_excess=0.

w12 window rolling_2:  64%|▋| 129/200 [00:12<00:06, 10.22round/s, val_excess=0.

w12 window rolling_2:  65%|▋| 130/200 [00:12<00:06, 10.26round/s, val_excess=0.

w12 window rolling_2:  65%|▋| 130/200 [00:12<00:06, 10.26round/s, val_excess=0.

w12 window rolling_2:  66%|▋| 131/200 [00:13<00:06, 10.26round/s, val_excess=0.

w12 window rolling_2:  66%|▋| 132/200 [00:13<00:06, 10.20round/s, val_excess=0.

w12 window rolling_2:  66%|▋| 132/200 [00:13<00:06, 10.20round/s, val_excess=0.

w12 window rolling_2:  66%|▋| 133/200 [00:13<00:06, 10.20round/s, val_excess=0.

w12 window rolling_2:  67%|▋| 134/200 [00:13<00:06, 10.16round/s, val_excess=0.

w12 window rolling_2:  67%|▋| 134/200 [00:13<00:06, 10.16round/s, val_excess=0.

w12 window rolling_2:  68%|▋| 135/200 [00:13<00:06, 10.16round/s, val_excess=0.

w12 window rolling_2:  68%|▋| 136/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_2:  68%|▋| 136/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_2:  68%|▋| 137/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_2:  69%|▋| 138/200 [00:13<00:06, 10.23round/s, val_excess=0.

w12 window rolling_2:  69%|▋| 138/200 [00:13<00:06, 10.23round/s, val_excess=0.

w12 window rolling_2:  70%|▋| 139/200 [00:13<00:05, 10.23round/s, val_excess=0.

w12 window rolling_2:  70%|▋| 140/200 [00:13<00:05, 10.22round/s, val_excess=0.

w12 window rolling_2:  70%|▋| 140/200 [00:13<00:05, 10.22round/s, val_excess=0.

w12 window rolling_2:  70%|▋| 141/200 [00:13<00:05, 10.22round/s, val_excess=0.

w12 window rolling_2:  71%|▋| 142/200 [00:14<00:05, 10.23round/s, val_excess=0.

w12 window rolling_2:  71%|▋| 142/200 [00:14<00:05, 10.23round/s, val_excess=0.

w12 window rolling_2:  72%|▋| 143/200 [00:14<00:05, 10.23round/s, val_excess=0.

w12 window rolling_2:  72%|▋| 144/200 [00:14<00:05, 10.15round/s, val_excess=0.

w12 window rolling_2:  72%|▋| 144/200 [00:14<00:05, 10.15round/s, val_excess=0.

w12 window rolling_2:  72%|▋| 145/200 [00:14<00:05, 10.15round/s, val_excess=0.

w12 window rolling_2:  73%|▋| 146/200 [00:14<00:05, 10.19round/s, val_excess=0.

w12 window rolling_2:  73%|▋| 146/200 [00:14<00:05, 10.19round/s, val_excess=0.

w12 window rolling_2:  74%|▋| 147/200 [00:14<00:05, 10.19round/s, val_excess=0.

w12 window rolling_2:  74%|▋| 148/200 [00:14<00:05, 10.12round/s, val_excess=0.

w12 window rolling_2:  74%|▋| 148/200 [00:14<00:05, 10.12round/s, val_excess=0.

w12 window rolling_2:  74%|▋| 149/200 [00:14<00:05, 10.12round/s, val_excess=0.

w12 window rolling_2:  75%|▊| 150/200 [00:14<00:04, 10.22round/s, val_excess=0.

w12 window rolling_2:  75%|▊| 150/200 [00:14<00:04, 10.22round/s, val_excess=0.

w12 window rolling_2:  76%|▊| 151/200 [00:14<00:04, 10.22round/s, val_excess=0.

w12 window rolling_2:  76%|▊| 152/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  76%|▊| 152/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  76%|▊| 153/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  77%|▊| 154/200 [00:15<00:04, 10.17round/s, val_excess=0.

w12 window rolling_2:  77%|▊| 154/200 [00:15<00:04, 10.17round/s, val_excess=0.

w12 window rolling_2:  78%|▊| 155/200 [00:15<00:04, 10.17round/s, val_excess=0.

w12 window rolling_2:  78%|▊| 156/200 [00:15<00:04, 10.20round/s, val_excess=0.

w12 window rolling_2:  78%|▊| 156/200 [00:15<00:04, 10.20round/s, val_excess=0.

w12 window rolling_2:  78%|▊| 157/200 [00:15<00:04, 10.20round/s, val_excess=0.

w12 window rolling_2:  79%|▊| 158/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  79%|▊| 158/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  80%|▊| 159/200 [00:15<00:04, 10.21round/s, val_excess=0.

w12 window rolling_2:  80%|▊| 160/200 [00:15<00:03, 10.20round/s, val_excess=0.

w12 window rolling_2:  80%|▊| 160/200 [00:15<00:03, 10.20round/s, val_excess=0.

w12 window rolling_2:  80%|▊| 161/200 [00:15<00:03, 10.20round/s, val_excess=0.

w12 window rolling_2:  81%|▊| 162/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_2:  81%|▊| 162/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_2:  82%|▊| 163/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_2:  82%|▊| 164/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  82%|▊| 164/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  82%|▊| 165/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  83%|▊| 166/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  83%|▊| 166/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  84%|▊| 167/200 [00:16<00:03, 10.08round/s, val_excess=0.

w12 window rolling_2:  84%|▊| 168/200 [00:16<00:03, 10.17round/s, val_excess=0.

w12 window rolling_2:  84%|▊| 168/200 [00:16<00:03, 10.17round/s, val_excess=0.

w12 window rolling_2:  84%|▊| 169/200 [00:16<00:03, 10.17round/s, val_excess=0.

w12 window rolling_2:  85%|▊| 170/200 [00:16<00:02, 10.24round/s, val_excess=0.

w12 window rolling_2:  85%|▊| 170/200 [00:16<00:02, 10.24round/s, val_excess=0.

w12 window rolling_2:  86%|▊| 171/200 [00:16<00:02, 10.24round/s, val_excess=0.

w12 window rolling_2:  86%|▊| 172/200 [00:17<00:02, 10.19round/s, val_excess=0.

w12 window rolling_2:  86%|▊| 172/200 [00:17<00:02, 10.19round/s, val_excess=0.

w12 window rolling_2:  86%|▊| 173/200 [00:17<00:02, 10.19round/s, val_excess=0.

w12 window rolling_2:  87%|▊| 174/200 [00:17<00:02, 10.21round/s, val_excess=0.

w12 window rolling_2:  87%|▊| 174/200 [00:17<00:02, 10.21round/s, val_excess=0.

w12 window rolling_2:  88%|▉| 175/200 [00:17<00:02, 10.21round/s, val_excess=0.

w12 window rolling_2:  88%|▉| 176/200 [00:17<00:02, 10.29round/s, val_excess=0.

w12 window rolling_2:  88%|▉| 176/200 [00:17<00:02, 10.29round/s, val_excess=0.

w12 window rolling_2:  88%|▉| 177/200 [00:17<00:02, 10.29round/s, val_excess=0.

w12 window rolling_2:  89%|▉| 178/200 [00:17<00:02, 10.27round/s, val_excess=0.

w12 window rolling_2:  89%|▉| 178/200 [00:17<00:02, 10.27round/s, val_excess=0.

w12 window rolling_2:  90%|▉| 179/200 [00:17<00:02, 10.27round/s, val_excess=0.

w12 window rolling_2:  90%|▉| 180/200 [00:17<00:01, 10.24round/s, val_excess=0.

w12 window rolling_2:  90%|▉| 180/200 [00:17<00:01, 10.24round/s, val_excess=0.

w12 window rolling_2:  90%|▉| 181/200 [00:17<00:01, 10.24round/s, val_excess=0.

w12 window rolling_2:  91%|▉| 182/200 [00:18<00:01, 10.18round/s, val_excess=0.

w12 window rolling_2:  91%|▉| 182/200 [00:18<00:01, 10.18round/s, val_excess=0.

w12 window rolling_2:  92%|▉| 183/200 [00:18<00:01, 10.18round/s, val_excess=0.

w12 window rolling_2:  92%|▉| 184/200 [00:18<00:01, 10.19round/s, val_excess=0.

w12 window rolling_2:  92%|▉| 184/200 [00:18<00:01, 10.19round/s, val_excess=0.

w12 window rolling_2:  92%|▉| 185/200 [00:18<00:01, 10.19round/s, val_excess=0.

w12 window rolling_2:  93%|▉| 186/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_2:  93%|▉| 186/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_2:  94%|▉| 187/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_2:  94%|▉| 188/200 [00:18<00:01, 10.27round/s, val_excess=0.

w12 window rolling_2:  94%|▉| 188/200 [00:18<00:01, 10.27round/s, val_excess=0.

w12 window rolling_2:  94%|▉| 189/200 [00:18<00:01, 10.27round/s, val_excess=0.

w12 window rolling_2:  95%|▉| 190/200 [00:18<00:00, 10.26round/s, val_excess=0.

w12 window rolling_2:  95%|▉| 190/200 [00:18<00:00, 10.26round/s, val_excess=0.

w12 window rolling_2:  96%|▉| 191/200 [00:18<00:00, 10.26round/s, val_excess=0.

w12 window rolling_2:  96%|▉| 192/200 [00:18<00:00, 10.18round/s, val_excess=0.

w12 window rolling_2:  96%|▉| 192/200 [00:18<00:00, 10.18round/s, val_excess=0.

w12 window rolling_2:  96%|▉| 193/200 [00:19<00:00, 10.18round/s, val_excess=0.

w12 window rolling_2:  97%|▉| 194/200 [00:19<00:00, 10.19round/s, val_excess=0.

w12 window rolling_2:  97%|▉| 194/200 [00:19<00:00, 10.19round/s, val_excess=0.

w12 window rolling_2:  98%|▉| 195/200 [00:19<00:00, 10.19round/s, val_excess=0.

w12 window rolling_2:  98%|▉| 196/200 [00:19<00:00, 10.08round/s, val_excess=0.

w12 window rolling_2:  98%|▉| 196/200 [00:19<00:00, 10.08round/s, val_excess=0.

w12 window rolling_2:  98%|▉| 197/200 [00:19<00:00, 10.08round/s, val_excess=0.

w12 window rolling_2:  99%|▉| 198/200 [00:19<00:00, 10.15round/s, val_excess=0.

w12 window rolling_2:  99%|▉| 198/200 [00:19<00:00, 10.15round/s, val_excess=0.

w12 window rolling_2: 100%|▉| 199/200 [00:19<00:00, 10.15round/s, val_excess=0.

w12 window rolling_2: 100%|█| 200/200 [00:19<00:00, 10.00round/s, val_excess=0.

w12 window rolling_2: 100%|█| 200/200 [00:19<00:00, 10.00round/s, val_excess=0.

w12 window rolling_2: 100%|█| 200/200 [00:19<00:00, 10.11round/s, val_excess=0.

2026-07-06 17:34:50 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=12 feature_type=window fold=rolling_3

2026-07-06 17:35:11 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=12 feature_type=window fold=rolling_3 features=69

w12 window rolling_3:   0%|                         | 0/200 [00:00<?, ?round/s]

w12 window rolling_3:   0%|                 | 1/200 [00:00<00:23,  8.35round/s]

w12 window rolling_3:   0%| | 1/200 [00:00<00:23,  8.35round/s, val_excess=-0.0

w12 window rolling_3:   1%| | 2/200 [00:00<00:23,  8.35round/s, val_excess=0.00

w12 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.91round/s, val_excess=0.00

w12 window rolling_3:   2%| | 3/200 [00:00<00:18, 10.91round/s, val_excess=0.00

w12 window rolling_3:   2%| | 4/200 [00:00<00:17, 10.91round/s, val_excess=0.01

w12 window rolling_3:   2%| | 5/200 [00:00<00:17, 11.01round/s, val_excess=0.01

w12 window rolling_3:   2%| | 5/200 [00:00<00:17, 11.01round/s, val_excess=-0.0

w12 window rolling_3:   3%| | 6/200 [00:00<00:17, 11.01round/s, val_excess=0.00

w12 window rolling_3:   4%| | 7/200 [00:00<00:17, 10.98round/s, val_excess=0.00

w12 window rolling_3:   4%| | 7/200 [00:00<00:17, 10.98round/s, val_excess=0.00

w12 window rolling_3:   4%| | 8/200 [00:00<00:17, 10.98round/s, val_excess=0.02

w12 window rolling_3:   4%| | 9/200 [00:00<00:17, 10.88round/s, val_excess=0.02

w12 window rolling_3:   4%| | 9/200 [00:00<00:17, 10.88round/s, val_excess=0.01

w12 window rolling_3:   5%| | 10/200 [00:00<00:17, 10.88round/s, val_excess=0.0

w12 window rolling_3:   6%| | 11/200 [00:01<00:17, 10.80round/s, val_excess=0.0

w12 window rolling_3:   6%| | 11/200 [00:01<00:17, 10.80round/s, val_excess=0.0

w12 window rolling_3:   6%| | 12/200 [00:01<00:17, 10.80round/s, val_excess=0.0

w12 window rolling_3:   6%| | 13/200 [00:01<00:17, 10.65round/s, val_excess=0.0

w12 window rolling_3:   6%| | 13/200 [00:01<00:17, 10.65round/s, val_excess=0.0

w12 window rolling_3:   7%| | 14/200 [00:01<00:17, 10.65round/s, val_excess=0.0

w12 window rolling_3:   8%| | 15/200 [00:01<00:17, 10.58round/s, val_excess=0.0

w12 window rolling_3:   8%| | 15/200 [00:01<00:17, 10.58round/s, val_excess=0.0

w12 window rolling_3:   8%| | 16/200 [00:01<00:17, 10.58round/s, val_excess=0.0

w12 window rolling_3:   8%| | 17/200 [00:01<00:17, 10.49round/s, val_excess=0.0

w12 window rolling_3:   8%| | 17/200 [00:01<00:17, 10.49round/s, val_excess=0.0

w12 window rolling_3:   9%| | 18/200 [00:01<00:17, 10.49round/s, val_excess=0.0

w12 window rolling_3:  10%| | 19/200 [00:01<00:17, 10.43round/s, val_excess=0.0

w12 window rolling_3:  10%| | 19/200 [00:01<00:17, 10.43round/s, val_excess=0.0

w12 window rolling_3:  10%| | 20/200 [00:01<00:17, 10.43round/s, val_excess=0.0

w12 window rolling_3:  10%| | 21/200 [00:01<00:17, 10.41round/s, val_excess=0.0

w12 window rolling_3:  10%| | 21/200 [00:01<00:17, 10.41round/s, val_excess=0.0

w12 window rolling_3:  11%| | 22/200 [00:02<00:17, 10.41round/s, val_excess=0.0

w12 window rolling_3:  12%| | 23/200 [00:02<00:17, 10.20round/s, val_excess=0.0

w12 window rolling_3:  12%| | 23/200 [00:02<00:17, 10.20round/s, val_excess=0.0

w12 window rolling_3:  12%| | 24/200 [00:02<00:17, 10.20round/s, val_excess=0.0

w12 window rolling_3:  12%|▏| 25/200 [00:02<00:17, 10.10round/s, val_excess=0.0

w12 window rolling_3:  12%|▏| 25/200 [00:02<00:17, 10.10round/s, val_excess=0.0

w12 window rolling_3:  13%|▏| 26/200 [00:02<00:17, 10.10round/s, val_excess=0.0

w12 window rolling_3:  14%|▏| 27/200 [00:02<00:17, 10.03round/s, val_excess=0.0

w12 window rolling_3:  14%|▏| 27/200 [00:02<00:17, 10.03round/s, val_excess=0.0

w12 window rolling_3:  14%|▏| 28/200 [00:02<00:17, 10.03round/s, val_excess=0.0

w12 window rolling_3:  14%|▏| 29/200 [00:02<00:17, 10.05round/s, val_excess=0.0

w12 window rolling_3:  14%|▏| 29/200 [00:02<00:17, 10.05round/s, val_excess=0.0

w12 window rolling_3:  15%|▏| 30/200 [00:02<00:16, 10.05round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 31/200 [00:03<00:17,  9.88round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 31/200 [00:03<00:17,  9.88round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 32/200 [00:03<00:17,  9.82round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 32/200 [00:03<00:17,  9.82round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 33/200 [00:03<00:17,  9.74round/s, val_excess=0.0

w12 window rolling_3:  16%|▏| 33/200 [00:03<00:17,  9.74round/s, val_excess=0.0

w12 window rolling_3:  17%|▏| 34/200 [00:03<00:16,  9.78round/s, val_excess=0.0

w12 window rolling_3:  17%|▏| 34/200 [00:03<00:16,  9.78round/s, val_excess=0.0

w12 window rolling_3:  18%|▏| 35/200 [00:03<00:16,  9.78round/s, val_excess=0.0

w12 window rolling_3:  18%|▏| 36/200 [00:03<00:16,  9.93round/s, val_excess=0.0

w12 window rolling_3:  18%|▏| 36/200 [00:03<00:16,  9.93round/s, val_excess=0.0

w12 window rolling_3:  18%|▏| 37/200 [00:03<00:16,  9.92round/s, val_excess=0.0

w12 window rolling_3:  18%|▏| 37/200 [00:03<00:16,  9.92round/s, val_excess=0.0

w12 window rolling_3:  19%|▏| 38/200 [00:03<00:16,  9.92round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 39/200 [00:03<00:16, 10.03round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 39/200 [00:03<00:16, 10.03round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 40/200 [00:03<00:16,  9.96round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 40/200 [00:03<00:16,  9.96round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 41/200 [00:04<00:15,  9.95round/s, val_excess=0.0

w12 window rolling_3:  20%|▏| 41/200 [00:04<00:15,  9.95round/s, val_excess=0.0

w12 window rolling_3:  21%|▏| 42/200 [00:04<00:15,  9.96round/s, val_excess=0.0

w12 window rolling_3:  21%|▏| 42/200 [00:04<00:15,  9.96round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 43/200 [00:04<00:15,  9.91round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 43/200 [00:04<00:15,  9.91round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 44/200 [00:04<00:15,  9.86round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 44/200 [00:04<00:15,  9.86round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 45/200 [00:04<00:15,  9.84round/s, val_excess=0.0

w12 window rolling_3:  22%|▏| 45/200 [00:04<00:15,  9.84round/s, val_excess=0.0

w12 window rolling_3:  23%|▏| 46/200 [00:04<00:15,  9.84round/s, val_excess=0.0

w12 window rolling_3:  24%|▏| 47/200 [00:04<00:15,  9.60round/s, val_excess=0.0

w12 window rolling_3:  24%|▏| 47/200 [00:04<00:15,  9.60round/s, val_excess=0.0

w12 window rolling_3:  24%|▏| 48/200 [00:04<00:15,  9.69round/s, val_excess=0.0

w12 window rolling_3:  24%|▏| 48/200 [00:04<00:15,  9.69round/s, val_excess=0.0

w12 window rolling_3:  24%|▏| 49/200 [00:04<00:15,  9.69round/s, val_excess=0.0

w12 window rolling_3:  25%|▎| 50/200 [00:04<00:15,  9.82round/s, val_excess=0.0

w12 window rolling_3:  25%|▎| 50/200 [00:04<00:15,  9.82round/s, val_excess=0.0

w12 window rolling_3:  26%|▎| 51/200 [00:05<00:15,  9.82round/s, val_excess=0.0

w12 window rolling_3:  26%|▎| 52/200 [00:05<00:14, 10.01round/s, val_excess=0.0

w12 window rolling_3:  26%|▎| 52/200 [00:05<00:14, 10.01round/s, val_excess=0.0

w12 window rolling_3:  26%|▎| 53/200 [00:05<00:14, 10.01round/s, val_excess=0.0

w12 window rolling_3:  27%|▎| 54/200 [00:05<00:14, 10.02round/s, val_excess=0.0

w12 window rolling_3:  27%|▎| 54/200 [00:05<00:14, 10.02round/s, val_excess=0.0

w12 window rolling_3:  28%|▎| 55/200 [00:05<00:14, 10.02round/s, val_excess=0.0

w12 window rolling_3:  28%|▎| 56/200 [00:05<00:14,  9.92round/s, val_excess=0.0

w12 window rolling_3:  28%|▎| 56/200 [00:05<00:14,  9.92round/s, val_excess=0.0

w12 window rolling_3:  28%|▎| 57/200 [00:05<00:14,  9.82round/s, val_excess=0.0

w12 window rolling_3:  28%|▎| 57/200 [00:05<00:14,  9.82round/s, val_excess=0.0

w12 window rolling_3:  29%|▎| 58/200 [00:05<00:14,  9.82round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 59/200 [00:05<00:14,  9.97round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 59/200 [00:05<00:14,  9.97round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 60/200 [00:05<00:14,  9.93round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 60/200 [00:05<00:14,  9.93round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 61/200 [00:06<00:14,  9.91round/s, val_excess=0.0

w12 window rolling_3:  30%|▎| 61/200 [00:06<00:14,  9.91round/s, val_excess=0.0

w12 window rolling_3:  31%|▎| 62/200 [00:06<00:13,  9.91round/s, val_excess=0.0

w12 window rolling_3:  32%|▎| 63/200 [00:06<00:13,  9.91round/s, val_excess=0.0

w12 window rolling_3:  32%|▎| 63/200 [00:06<00:13,  9.91round/s, val_excess=0.0

w12 window rolling_3:  32%|▎| 64/200 [00:06<00:13,  9.91round/s, val_excess=0.0

w12 window rolling_3:  32%|▎| 65/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  32%|▎| 65/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  33%|▎| 66/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  34%|▎| 67/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  34%|▎| 67/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  34%|▎| 68/200 [00:06<00:13,  9.96round/s, val_excess=0.0

w12 window rolling_3:  34%|▎| 69/200 [00:06<00:13, 10.01round/s, val_excess=0.0

w12 window rolling_3:  34%|▎| 69/200 [00:06<00:13, 10.01round/s, val_excess=0.0

w12 window rolling_3:  35%|▎| 70/200 [00:06<00:12, 10.01round/s, val_excess=0.0

w12 window rolling_3:  36%|▎| 71/200 [00:07<00:12, 10.02round/s, val_excess=0.0

w12 window rolling_3:  36%|▎| 71/200 [00:07<00:12, 10.02round/s, val_excess=0.0

w12 window rolling_3:  36%|▎| 72/200 [00:07<00:12, 10.02round/s, val_excess=0.0

w12 window rolling_3:  36%|▎| 73/200 [00:07<00:12, 10.14round/s, val_excess=0.0

w12 window rolling_3:  36%|▎| 73/200 [00:07<00:12, 10.14round/s, val_excess=0.0

w12 window rolling_3:  37%|▎| 74/200 [00:07<00:12, 10.14round/s, val_excess=0.0

w12 window rolling_3:  38%|▍| 75/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_3:  38%|▍| 75/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_3:  38%|▍| 76/200 [00:07<00:12, 10.15round/s, val_excess=0.0

w12 window rolling_3:  38%|▍| 77/200 [00:07<00:12, 10.20round/s, val_excess=0.0

w12 window rolling_3:  38%|▍| 77/200 [00:07<00:12, 10.20round/s, val_excess=0.0

w12 window rolling_3:  39%|▍| 78/200 [00:07<00:11, 10.20round/s, val_excess=0.0

w12 window rolling_3:  40%|▍| 79/200 [00:07<00:11, 10.18round/s, val_excess=0.0

w12 window rolling_3:  40%|▍| 79/200 [00:07<00:11, 10.18round/s, val_excess=0.0

w12 window rolling_3:  40%|▍| 80/200 [00:07<00:11, 10.18round/s, val_excess=0.0

w12 window rolling_3:  40%|▍| 81/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_3:  40%|▍| 81/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_3:  41%|▍| 82/200 [00:08<00:11, 10.14round/s, val_excess=0.0

w12 window rolling_3:  42%|▍| 83/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_3:  42%|▍| 83/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_3:  42%|▍| 84/200 [00:08<00:11, 10.10round/s, val_excess=0.0

w12 window rolling_3:  42%|▍| 85/200 [00:08<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_3:  42%|▍| 85/200 [00:08<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_3:  43%|▍| 86/200 [00:08<00:11, 10.15round/s, val_excess=0.0

w12 window rolling_3:  44%|▍| 87/200 [00:08<00:11, 10.12round/s, val_excess=0.0

w12 window rolling_3:  44%|▍| 87/200 [00:08<00:11, 10.12round/s, val_excess=0.0

w12 window rolling_3:  44%|▍| 88/200 [00:08<00:11, 10.12round/s, val_excess=0.0

w12 window rolling_3:  44%|▍| 89/200 [00:08<00:10, 10.19round/s, val_excess=0.0

w12 window rolling_3:  44%|▍| 89/200 [00:08<00:10, 10.19round/s, val_excess=0.0

w12 window rolling_3:  45%|▍| 90/200 [00:08<00:10, 10.19round/s, val_excess=0.0

w12 window rolling_3:  46%|▍| 91/200 [00:09<00:10, 10.14round/s, val_excess=0.0

w12 window rolling_3:  46%|▍| 91/200 [00:09<00:10, 10.14round/s, val_excess=0.0

w12 window rolling_3:  46%|▍| 92/200 [00:09<00:10, 10.14round/s, val_excess=0.0

w12 window rolling_3:  46%|▍| 93/200 [00:09<00:10, 10.12round/s, val_excess=0.0

w12 window rolling_3:  46%|▍| 93/200 [00:09<00:10, 10.12round/s, val_excess=0.0

w12 window rolling_3:  47%|▍| 94/200 [00:09<00:10, 10.12round/s, val_excess=0.0

w12 window rolling_3:  48%|▍| 95/200 [00:09<00:10, 10.08round/s, val_excess=0.0

w12 window rolling_3:  48%|▍| 95/200 [00:09<00:10, 10.08round/s, val_excess=0.0

w12 window rolling_3:  48%|▍| 96/200 [00:09<00:10, 10.08round/s, val_excess=0.0

w12 window rolling_3:  48%|▍| 97/200 [00:09<00:10, 10.17round/s, val_excess=0.0

w12 window rolling_3:  48%|▍| 97/200 [00:09<00:10, 10.17round/s, val_excess=0.0

w12 window rolling_3:  49%|▍| 98/200 [00:09<00:10, 10.17round/s, val_excess=0.0

w12 window rolling_3:  50%|▍| 99/200 [00:09<00:09, 10.24round/s, val_excess=0.0

w12 window rolling_3:  50%|▍| 99/200 [00:09<00:09, 10.24round/s, val_excess=0.0

w12 window rolling_3:  50%|▌| 100/200 [00:09<00:09, 10.24round/s, val_excess=0.

w12 window rolling_3:  50%|▌| 101/200 [00:09<00:09, 10.28round/s, val_excess=0.

w12 window rolling_3:  50%|▌| 101/200 [00:09<00:09, 10.28round/s, val_excess=0.

w12 window rolling_3:  51%|▌| 102/200 [00:10<00:09, 10.28round/s, val_excess=0.

w12 window rolling_3:  52%|▌| 103/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  52%|▌| 103/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  52%|▌| 104/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  52%|▌| 105/200 [00:10<00:09, 10.24round/s, val_excess=0.

w12 window rolling_3:  52%|▌| 105/200 [00:10<00:09, 10.24round/s, val_excess=0.

w12 window rolling_3:  53%|▌| 106/200 [00:10<00:09, 10.24round/s, val_excess=0.

w12 window rolling_3:  54%|▌| 107/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  54%|▌| 107/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  54%|▌| 108/200 [00:10<00:09, 10.20round/s, val_excess=0.

w12 window rolling_3:  55%|▌| 109/200 [00:10<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  55%|▌| 109/200 [00:10<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  55%|▌| 110/200 [00:10<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  56%|▌| 111/200 [00:10<00:08, 10.27round/s, val_excess=0.

w12 window rolling_3:  56%|▌| 111/200 [00:10<00:08, 10.27round/s, val_excess=0.

w12 window rolling_3:  56%|▌| 112/200 [00:11<00:08, 10.27round/s, val_excess=0.

w12 window rolling_3:  56%|▌| 113/200 [00:11<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  56%|▌| 113/200 [00:11<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  57%|▌| 114/200 [00:11<00:08, 10.23round/s, val_excess=0.

w12 window rolling_3:  57%|▌| 115/200 [00:11<00:08, 10.20round/s, val_excess=0.

w12 window rolling_3:  57%|▌| 115/200 [00:11<00:08, 10.20round/s, val_excess=0.

w12 window rolling_3:  58%|▌| 116/200 [00:11<00:08, 10.20round/s, val_excess=0.

w12 window rolling_3:  58%|▌| 117/200 [00:11<00:08, 10.19round/s, val_excess=0.

w12 window rolling_3:  58%|▌| 117/200 [00:11<00:08, 10.19round/s, val_excess=0.

w12 window rolling_3:  59%|▌| 118/200 [00:11<00:08, 10.19round/s, val_excess=0.

w12 window rolling_3:  60%|▌| 119/200 [00:11<00:08, 10.07round/s, val_excess=0.

w12 window rolling_3:  60%|▌| 119/200 [00:11<00:08, 10.07round/s, val_excess=0.

w12 window rolling_3:  60%|▌| 120/200 [00:11<00:07, 10.07round/s, val_excess=0.

w12 window rolling_3:  60%|▌| 121/200 [00:11<00:07, 10.20round/s, val_excess=0.

w12 window rolling_3:  60%|▌| 121/200 [00:11<00:07, 10.20round/s, val_excess=0.

w12 window rolling_3:  61%|▌| 122/200 [00:12<00:07, 10.20round/s, val_excess=0.

w12 window rolling_3:  62%|▌| 123/200 [00:12<00:07, 10.23round/s, val_excess=0.

w12 window rolling_3:  62%|▌| 123/200 [00:12<00:07, 10.23round/s, val_excess=0.

w12 window rolling_3:  62%|▌| 124/200 [00:12<00:07, 10.23round/s, val_excess=0.

w12 window rolling_3:  62%|▋| 125/200 [00:12<00:07, 10.22round/s, val_excess=0.

w12 window rolling_3:  62%|▋| 125/200 [00:12<00:07, 10.22round/s, val_excess=0.

w12 window rolling_3:  63%|▋| 126/200 [00:12<00:07, 10.22round/s, val_excess=0.

w12 window rolling_3:  64%|▋| 127/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_3:  64%|▋| 127/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_3:  64%|▋| 128/200 [00:12<00:07, 10.18round/s, val_excess=0.

w12 window rolling_3:  64%|▋| 129/200 [00:12<00:06, 10.18round/s, val_excess=0.

w12 window rolling_3:  64%|▋| 129/200 [00:12<00:06, 10.18round/s, val_excess=0.

w12 window rolling_3:  65%|▋| 130/200 [00:12<00:06, 10.18round/s, val_excess=0.

w12 window rolling_3:  66%|▋| 131/200 [00:12<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  66%|▋| 131/200 [00:12<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  66%|▋| 132/200 [00:13<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  66%|▋| 133/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_3:  66%|▋| 133/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_3:  67%|▋| 134/200 [00:13<00:06, 10.22round/s, val_excess=0.

w12 window rolling_3:  68%|▋| 135/200 [00:13<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  68%|▋| 135/200 [00:13<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  68%|▋| 136/200 [00:13<00:06, 10.19round/s, val_excess=0.

w12 window rolling_3:  68%|▋| 137/200 [00:13<00:06, 10.25round/s, val_excess=0.

w12 window rolling_3:  68%|▋| 137/200 [00:13<00:06, 10.25round/s, val_excess=0.

w12 window rolling_3:  69%|▋| 138/200 [00:13<00:06, 10.25round/s, val_excess=0.

w12 window rolling_3:  70%|▋| 139/200 [00:13<00:05, 10.29round/s, val_excess=0.

w12 window rolling_3:  70%|▋| 139/200 [00:13<00:05, 10.29round/s, val_excess=0.

w12 window rolling_3:  70%|▋| 140/200 [00:13<00:05, 10.29round/s, val_excess=0.

w12 window rolling_3:  70%|▋| 141/200 [00:13<00:05, 10.30round/s, val_excess=0.

w12 window rolling_3:  70%|▋| 141/200 [00:13<00:05, 10.30round/s, val_excess=0.

w12 window rolling_3:  71%|▋| 142/200 [00:13<00:05, 10.30round/s, val_excess=0.

w12 window rolling_3:  72%|▋| 143/200 [00:14<00:05, 10.24round/s, val_excess=0.

w12 window rolling_3:  72%|▋| 143/200 [00:14<00:05, 10.24round/s, val_excess=0.

w12 window rolling_3:  72%|▋| 144/200 [00:14<00:05, 10.24round/s, val_excess=0.

w12 window rolling_3:  72%|▋| 145/200 [00:14<00:05, 10.21round/s, val_excess=0.

w12 window rolling_3:  72%|▋| 145/200 [00:14<00:05, 10.21round/s, val_excess=0.

w12 window rolling_3:  73%|▋| 146/200 [00:14<00:05, 10.21round/s, val_excess=0.

w12 window rolling_3:  74%|▋| 147/200 [00:14<00:05, 10.10round/s, val_excess=0.

w12 window rolling_3:  74%|▋| 147/200 [00:14<00:05, 10.10round/s, val_excess=0.

w12 window rolling_3:  74%|▋| 148/200 [00:14<00:05, 10.10round/s, val_excess=0.

w12 window rolling_3:  74%|▋| 149/200 [00:14<00:05,  9.95round/s, val_excess=0.

w12 window rolling_3:  74%|▋| 149/200 [00:14<00:05,  9.95round/s, val_excess=0.

w12 window rolling_3:  75%|▊| 150/200 [00:14<00:05,  9.90round/s, val_excess=0.

w12 window rolling_3:  75%|▊| 150/200 [00:14<00:05,  9.90round/s, val_excess=0.

w12 window rolling_3:  76%|▊| 151/200 [00:14<00:04,  9.86round/s, val_excess=0.

w12 window rolling_3:  76%|▊| 151/200 [00:14<00:04,  9.86round/s, val_excess=0.

w12 window rolling_3:  76%|▊| 152/200 [00:15<00:04,  9.86round/s, val_excess=0.

w12 window rolling_3:  76%|▊| 153/200 [00:15<00:04,  9.99round/s, val_excess=0.

w12 window rolling_3:  76%|▊| 153/200 [00:15<00:04,  9.99round/s, val_excess=0.

w12 window rolling_3:  77%|▊| 154/200 [00:15<00:04,  9.99round/s, val_excess=0.

w12 window rolling_3:  78%|▊| 155/200 [00:15<00:04, 10.11round/s, val_excess=0.

w12 window rolling_3:  78%|▊| 155/200 [00:15<00:04, 10.11round/s, val_excess=0.

w12 window rolling_3:  78%|▊| 156/200 [00:15<00:04, 10.11round/s, val_excess=0.

w12 window rolling_3:  78%|▊| 157/200 [00:15<00:04, 10.13round/s, val_excess=0.

w12 window rolling_3:  78%|▊| 157/200 [00:15<00:04, 10.13round/s, val_excess=0.

w12 window rolling_3:  79%|▊| 158/200 [00:15<00:04, 10.13round/s, val_excess=0.

w12 window rolling_3:  80%|▊| 159/200 [00:15<00:04, 10.19round/s, val_excess=0.

w12 window rolling_3:  80%|▊| 159/200 [00:15<00:04, 10.19round/s, val_excess=0.

w12 window rolling_3:  80%|▊| 160/200 [00:15<00:03, 10.19round/s, val_excess=0.

w12 window rolling_3:  80%|▊| 161/200 [00:15<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  80%|▊| 161/200 [00:15<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  81%|▊| 162/200 [00:15<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  82%|▊| 163/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_3:  82%|▊| 163/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_3:  82%|▊| 164/200 [00:16<00:03, 10.24round/s, val_excess=0.

w12 window rolling_3:  82%|▊| 165/200 [00:16<00:03, 10.23round/s, val_excess=0.

w12 window rolling_3:  82%|▊| 165/200 [00:16<00:03, 10.23round/s, val_excess=0.

w12 window rolling_3:  83%|▊| 166/200 [00:16<00:03, 10.23round/s, val_excess=0.

w12 window rolling_3:  84%|▊| 167/200 [00:16<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  84%|▊| 167/200 [00:16<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  84%|▊| 168/200 [00:16<00:03, 10.22round/s, val_excess=0.

w12 window rolling_3:  84%|▊| 169/200 [00:16<00:03, 10.28round/s, val_excess=0.

w12 window rolling_3:  84%|▊| 169/200 [00:16<00:03, 10.28round/s, val_excess=0.

w12 window rolling_3:  85%|▊| 170/200 [00:16<00:02, 10.28round/s, val_excess=0.

w12 window rolling_3:  86%|▊| 171/200 [00:16<00:02, 10.30round/s, val_excess=0.

w12 window rolling_3:  86%|▊| 171/200 [00:16<00:02, 10.30round/s, val_excess=0.

w12 window rolling_3:  86%|▊| 172/200 [00:16<00:02, 10.30round/s, val_excess=0.

w12 window rolling_3:  86%|▊| 173/200 [00:17<00:02, 10.28round/s, val_excess=0.

w12 window rolling_3:  86%|▊| 173/200 [00:17<00:02, 10.28round/s, val_excess=0.

w12 window rolling_3:  87%|▊| 174/200 [00:17<00:02, 10.28round/s, val_excess=0.

w12 window rolling_3:  88%|▉| 175/200 [00:17<00:02, 10.22round/s, val_excess=0.

w12 window rolling_3:  88%|▉| 175/200 [00:17<00:02, 10.22round/s, val_excess=0.

w12 window rolling_3:  88%|▉| 176/200 [00:17<00:02, 10.22round/s, val_excess=0.

w12 window rolling_3:  88%|▉| 177/200 [00:17<00:02, 10.24round/s, val_excess=0.

w12 window rolling_3:  88%|▉| 177/200 [00:17<00:02, 10.24round/s, val_excess=0.

w12 window rolling_3:  89%|▉| 178/200 [00:17<00:02, 10.24round/s, val_excess=0.

w12 window rolling_3:  90%|▉| 179/200 [00:17<00:02, 10.23round/s, val_excess=0.

w12 window rolling_3:  90%|▉| 179/200 [00:17<00:02, 10.23round/s, val_excess=0.

w12 window rolling_3:  90%|▉| 180/200 [00:17<00:01, 10.23round/s, val_excess=0.

w12 window rolling_3:  90%|▉| 181/200 [00:17<00:01, 10.22round/s, val_excess=0.

w12 window rolling_3:  90%|▉| 181/200 [00:17<00:01, 10.22round/s, val_excess=0.

w12 window rolling_3:  91%|▉| 182/200 [00:17<00:01, 10.22round/s, val_excess=0.

w12 window rolling_3:  92%|▉| 183/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_3:  92%|▉| 183/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_3:  92%|▉| 184/200 [00:18<00:01, 10.25round/s, val_excess=0.

w12 window rolling_3:  92%|▉| 185/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  92%|▉| 185/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  93%|▉| 186/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  94%|▉| 187/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  94%|▉| 187/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  94%|▉| 188/200 [00:18<00:01, 10.24round/s, val_excess=0.

w12 window rolling_3:  94%|▉| 189/200 [00:18<00:01, 10.28round/s, val_excess=0.

w12 window rolling_3:  94%|▉| 189/200 [00:18<00:01, 10.28round/s, val_excess=0.

w12 window rolling_3:  95%|▉| 190/200 [00:18<00:00, 10.28round/s, val_excess=0.

w12 window rolling_3:  96%|▉| 191/200 [00:18<00:00, 10.27round/s, val_excess=0.

w12 window rolling_3:  96%|▉| 191/200 [00:18<00:00, 10.27round/s, val_excess=0.

w12 window rolling_3:  96%|▉| 192/200 [00:18<00:00, 10.27round/s, val_excess=0.

w12 window rolling_3:  96%|▉| 193/200 [00:18<00:00, 10.32round/s, val_excess=0.

w12 window rolling_3:  96%|▉| 193/200 [00:18<00:00, 10.32round/s, val_excess=0.

w12 window rolling_3:  97%|▉| 194/200 [00:19<00:00, 10.32round/s, val_excess=0.

w12 window rolling_3:  98%|▉| 195/200 [00:19<00:00, 10.38round/s, val_excess=0.

w12 window rolling_3:  98%|▉| 195/200 [00:19<00:00, 10.38round/s, val_excess=0.

w12 window rolling_3:  98%|▉| 196/200 [00:19<00:00, 10.38round/s, val_excess=0.

w12 window rolling_3:  98%|▉| 197/200 [00:19<00:00, 10.24round/s, val_excess=0.

w12 window rolling_3:  98%|▉| 197/200 [00:19<00:00, 10.24round/s, val_excess=0.

w12 window rolling_3:  99%|▉| 198/200 [00:19<00:00, 10.24round/s, val_excess=0.

w12 window rolling_3: 100%|▉| 199/200 [00:19<00:00, 10.23round/s, val_excess=0.

w12 window rolling_3: 100%|▉| 199/200 [00:19<00:00, 10.23round/s, val_excess=0.

w12 window rolling_3: 100%|█| 200/200 [00:19<00:00, 10.23round/s, val_excess=0.

w12 window rolling_3: 100%|█| 200/200 [00:19<00:00, 10.16round/s, val_excess=0.

2026-07-06 17:35:31 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | prepare input_window=12 feature_type=window fold=rolling_4

2026-07-06 17:35:52 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | train input_window=12 feature_type=window fold=rolling_4 features=69

w12 window rolling_4:   0%|                         | 0/200 [00:00<?, ?round/s]

w12 window rolling_4:   0%|                 | 1/200 [00:00<00:21,  9.23round/s]

w12 window rolling_4:   0%| | 1/200 [00:00<00:21,  9.23round/s, val_excess=0.00

w12 window rolling_4:   1%| | 2/200 [00:00<00:21,  9.23round/s, val_excess=0.02

w12 window rolling_4:   2%| | 3/200 [00:00<00:17, 11.28round/s, val_excess=0.02

w12 window rolling_4:   2%| | 3/200 [00:00<00:17, 11.28round/s, val_excess=0.02

w12 window rolling_4:   2%| | 4/200 [00:00<00:17, 11.28round/s, val_excess=0.04

w12 window rolling_4:   2%| | 5/200 [00:00<00:17, 10.97round/s, val_excess=0.04

w12 window rolling_4:   2%| | 5/200 [00:00<00:17, 10.97round/s, val_excess=0.02

w12 window rolling_4:   3%| | 6/200 [00:00<00:17, 10.97round/s, val_excess=-0.0

w12 window rolling_4:   4%| | 7/200 [00:00<00:18, 10.60round/s, val_excess=-0.0

w12 window rolling_4:   4%| | 7/200 [00:00<00:18, 10.60round/s, val_excess=0.00

w12 window rolling_4:   4%| | 8/200 [00:00<00:18, 10.60round/s, val_excess=0.01

w12 window rolling_4:   4%| | 9/200 [00:00<00:18, 10.11round/s, val_excess=0.01

w12 window rolling_4:   4%| | 9/200 [00:00<00:18, 10.11round/s, val_excess=0.01

w12 window rolling_4:   5%| | 10/200 [00:00<00:18, 10.11round/s, val_excess=0.0

w12 window rolling_4:   6%| | 11/200 [00:01<00:18,  9.99round/s, val_excess=0.0

w12 window rolling_4:   6%| | 11/200 [00:01<00:18,  9.99round/s, val_excess=0.0

w12 window rolling_4:   6%| | 12/200 [00:01<00:18,  9.99round/s, val_excess=0.0

w12 window rolling_4:   6%| | 13/200 [00:01<00:18,  9.88round/s, val_excess=0.0

w12 window rolling_4:   6%| | 13/200 [00:01<00:18,  9.88round/s, val_excess=0.0

w12 window rolling_4:   7%| | 14/200 [00:01<00:18,  9.81round/s, val_excess=0.0

w12 window rolling_4:   7%| | 14/200 [00:01<00:18,  9.81round/s, val_excess=0.0

w12 window rolling_4:   8%| | 15/200 [00:01<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:   8%| | 15/200 [00:01<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:   8%| | 16/200 [00:01<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:   8%| | 16/200 [00:01<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:   8%| | 17/200 [00:01<00:18,  9.79round/s, val_excess=0.0

w12 window rolling_4:   8%| | 17/200 [00:01<00:18,  9.79round/s, val_excess=0.0

w12 window rolling_4:   9%| | 18/200 [00:01<00:18,  9.83round/s, val_excess=0.0

w12 window rolling_4:   9%| | 18/200 [00:01<00:18,  9.83round/s, val_excess=0.0

w12 window rolling_4:  10%| | 19/200 [00:01<00:18,  9.76round/s, val_excess=0.0

w12 window rolling_4:  10%| | 19/200 [00:01<00:18,  9.76round/s, val_excess=0.0

w12 window rolling_4:  10%| | 20/200 [00:01<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:  10%| | 20/200 [00:02<00:18,  9.78round/s, val_excess=0.0

w12 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.60round/s, val_excess=0.0

w12 window rolling_4:  10%| | 21/200 [00:02<00:18,  9.60round/s, val_excess=0.0

w12 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.58round/s, val_excess=0.0

w12 window rolling_4:  11%| | 22/200 [00:02<00:18,  9.58round/s, val_excess=0.0

w12 window rolling_4:  12%| | 23/200 [00:02<00:18,  9.62round/s, val_excess=0.0

w12 window rolling_4:  12%| | 23/200 [00:02<00:18,  9.62round/s, val_excess=0.0

w12 window rolling_4:  12%| | 24/200 [00:02<00:18,  9.62round/s, val_excess=0.0

w12 window rolling_4:  12%|▏| 25/200 [00:02<00:17,  9.79round/s, val_excess=0.0

w12 window rolling_4:  12%|▏| 25/200 [00:02<00:17,  9.79round/s, val_excess=0.0

w12 window rolling_4:  13%|▏| 26/200 [00:02<00:17,  9.74round/s, val_excess=0.0

w12 window rolling_4:  13%|▏| 26/200 [00:02<00:17,  9.74round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 27/200 [00:02<00:17,  9.69round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 27/200 [00:02<00:17,  9.69round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 28/200 [00:02<00:17,  9.77round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 28/200 [00:02<00:17,  9.77round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 29/200 [00:02<00:17,  9.79round/s, val_excess=0.0

w12 window rolling_4:  14%|▏| 29/200 [00:02<00:17,  9.79round/s, val_excess=0.0

w12 window rolling_4:  15%|▏| 30/200 [00:03<00:17,  9.69round/s, val_excess=0.0

w12 window rolling_4:  15%|▏| 30/200 [00:03<00:17,  9.69round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 31/200 [00:03<00:17,  9.62round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 31/200 [00:03<00:17,  9.62round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 32/200 [00:03<00:17,  9.70round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 32/200 [00:03<00:17,  9.70round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 33/200 [00:03<00:17,  9.64round/s, val_excess=0.0

w12 window rolling_4:  16%|▏| 33/200 [00:03<00:17,  9.64round/s, val_excess=0.0

w12 window rolling_4:  17%|▏| 34/200 [00:03<00:17,  9.67round/s, val_excess=0.0

w12 window rolling_4:  17%|▏| 34/200 [00:03<00:17,  9.67round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 35/200 [00:03<00:17,  9.70round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 35/200 [00:03<00:17,  9.70round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 36/200 [00:03<00:16,  9.78round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 36/200 [00:03<00:16,  9.78round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 37/200 [00:03<00:16,  9.74round/s, val_excess=0.0

w12 window rolling_4:  18%|▏| 37/200 [00:03<00:16,  9.74round/s, val_excess=0.0

w12 window rolling_4:  19%|▏| 38/200 [00:03<00:16,  9.59round/s, val_excess=0.0

w12 window rolling_4:  19%|▏| 38/200 [00:03<00:16,  9.59round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 39/200 [00:03<00:16,  9.68round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 39/200 [00:03<00:16,  9.68round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 40/200 [00:04<00:16,  9.75round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 40/200 [00:04<00:16,  9.75round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 41/200 [00:04<00:16,  9.61round/s, val_excess=0.0

w12 window rolling_4:  20%|▏| 41/200 [00:04<00:16,  9.61round/s, val_excess=0.0

w12 window rolling_4:  21%|▏| 42/200 [00:04<00:16,  9.64round/s, val_excess=0.0

w12 window rolling_4:  21%|▏| 42/200 [00:04<00:16,  9.64round/s, val_excess=0.0

w12 window rolling_4:  22%|▏| 43/200 [00:04<00:16,  9.64round/s, val_excess=0.0

w12 window rolling_4:  22%|▏| 44/200 [00:04<00:15,  9.79round/s, val_excess=0.0

w12 window rolling_4:  22%|▏| 44/200 [00:04<00:15,  9.79round/s, val_excess=0.0

w12 window rolling_4:  22%|▏| 45/200 [00:04<00:15,  9.71round/s, val_excess=0.0

w12 window rolling_4:  22%|▏| 45/200 [00:04<00:15,  9.71round/s, val_excess=0.0

w12 window rolling_4:  23%|▏| 46/200 [00:04<00:15,  9.66round/s, val_excess=0.0

w12 window rolling_4:  23%|▏| 46/200 [00:04<00:15,  9.66round/s, val_excess=0.0

w12 window rolling_4:  24%|▏| 47/200 [00:04<00:15,  9.66round/s, val_excess=0.0

w12 window rolling_4:  24%|▏| 48/200 [00:04<00:15,  9.70round/s, val_excess=0.0

w12 window rolling_4:  24%|▏| 48/200 [00:04<00:15,  9.70round/s, val_excess=0.0

w12 window rolling_4:  24%|▏| 49/200 [00:04<00:15,  9.66round/s, val_excess=0.0

w12 window rolling_4:  24%|▏| 49/200 [00:04<00:15,  9.66round/s, val_excess=0.0

w12 window rolling_4:  25%|▎| 50/200 [00:05<00:15,  9.72round/s, val_excess=0.0

w12 window rolling_4:  25%|▎| 50/200 [00:05<00:15,  9.72round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 51/200 [00:05<00:15,  9.76round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 51/200 [00:05<00:15,  9.76round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.70round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 52/200 [00:05<00:15,  9.70round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.74round/s, val_excess=0.0

w12 window rolling_4:  26%|▎| 53/200 [00:05<00:15,  9.74round/s, val_excess=0.0

w12 window rolling_4:  27%|▎| 54/200 [00:05<00:14,  9.79round/s, val_excess=0.0

w12 window rolling_4:  27%|▎| 54/200 [00:05<00:14,  9.79round/s, val_excess=0.0

w12 window rolling_4:  28%|▎| 55/200 [00:05<00:14,  9.80round/s, val_excess=0.0

w12 window rolling_4:  28%|▎| 55/200 [00:05<00:14,  9.80round/s, val_excess=0.0

w12 window rolling_4:  28%|▎| 56/200 [00:05<00:14,  9.80round/s, val_excess=0.0

w12 window rolling_4:  28%|▎| 57/200 [00:05<00:14,  9.93round/s, val_excess=0.0

w12 window rolling_4:  28%|▎| 57/200 [00:05<00:14,  9.93round/s, val_excess=0.0

w12 window rolling_4:  29%|▎| 58/200 [00:05<00:14,  9.61round/s, val_excess=0.0

w12 window rolling_4:  29%|▎| 58/200 [00:05<00:14,  9.61round/s, val_excess=0.0

w12 window rolling_4:  30%|▎| 59/200 [00:06<00:14,  9.66round/s, val_excess=0.0

w12 window rolling_4:  30%|▎| 59/200 [00:06<00:14,  9.66round/s, val_excess=0.0

w12 window rolling_4:  30%|▎| 60/200 [00:06<00:14,  9.66round/s, val_excess=0.0

w12 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.81round/s, val_excess=0.0

w12 window rolling_4:  30%|▎| 61/200 [00:06<00:14,  9.81round/s, val_excess=-0.

w12 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.81round/s, val_excess=-0.

w12 window rolling_4:  31%|▎| 62/200 [00:06<00:14,  9.81round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 63/200 [00:06<00:13,  9.81round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 63/200 [00:06<00:13,  9.81round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 64/200 [00:06<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 64/200 [00:06<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 65/200 [00:06<00:13,  9.79round/s, val_excess=0.0

w12 window rolling_4:  32%|▎| 65/200 [00:06<00:13,  9.79round/s, val_excess=0.0

w12 window rolling_4:  33%|▎| 66/200 [00:06<00:13,  9.83round/s, val_excess=0.0

w12 window rolling_4:  33%|▎| 66/200 [00:06<00:13,  9.83round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 67/200 [00:06<00:13,  9.83round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 67/200 [00:06<00:13,  9.83round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 68/200 [00:06<00:13,  9.78round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 68/200 [00:06<00:13,  9.78round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 69/200 [00:07<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  34%|▎| 69/200 [00:07<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  35%|▎| 70/200 [00:07<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.85round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 71/200 [00:07<00:13,  9.85round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 72/200 [00:07<00:13,  9.82round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 73/200 [00:07<00:13,  9.70round/s, val_excess=0.0

w12 window rolling_4:  36%|▎| 73/200 [00:07<00:13,  9.70round/s, val_excess=0.0

w12 window rolling_4:  37%|▎| 74/200 [00:07<00:13,  9.67round/s, val_excess=0.0

w12 window rolling_4:  37%|▎| 74/200 [00:07<00:13,  9.67round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 75/200 [00:07<00:12,  9.69round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 75/200 [00:07<00:12,  9.69round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 76/200 [00:07<00:12,  9.70round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 76/200 [00:07<00:12,  9.70round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 77/200 [00:07<00:12,  9.70round/s, val_excess=0.0

w12 window rolling_4:  38%|▍| 77/200 [00:07<00:12,  9.70round/s, val_excess=0.0

w12 window rolling_4:  39%|▍| 78/200 [00:07<00:12,  9.65round/s, val_excess=0.0

w12 window rolling_4:  39%|▍| 78/200 [00:07<00:12,  9.65round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 79/200 [00:08<00:12,  9.64round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 79/200 [00:08<00:12,  9.64round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 80/200 [00:08<00:12,  9.60round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.48round/s, val_excess=0.0

w12 window rolling_4:  40%|▍| 81/200 [00:08<00:12,  9.48round/s, val_excess=0.0

w12 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.43round/s, val_excess=0.0

w12 window rolling_4:  41%|▍| 82/200 [00:08<00:12,  9.43round/s, val_excess=0.0

w12 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.55round/s, val_excess=0.0

w12 window rolling_4:  42%|▍| 83/200 [00:08<00:12,  9.55round/s, val_excess=0.0

w12 window rolling_4:  42%|▍| 84/200 [00:08<00:12,  9.57round/s, val_excess=0.0

w12 window rolling_4:  42%|▍| 84/200 [00:08<00:12,  9.57round/s, val_excess=0.0

w12 window rolling_4:  42%|▍| 85/200 [00:08<00:12,  9.57round/s, val_excess=0.0

w12 window rolling_4:  43%|▍| 86/200 [00:08<00:11,  9.79round/s, val_excess=0.0

w12 window rolling_4:  43%|▍| 86/200 [00:08<00:11,  9.79round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 87/200 [00:08<00:11,  9.82round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 87/200 [00:08<00:11,  9.82round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 88/200 [00:08<00:11,  9.81round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 88/200 [00:08<00:11,  9.81round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.82round/s, val_excess=0.0

w12 window rolling_4:  44%|▍| 89/200 [00:09<00:11,  9.82round/s, val_excess=0.0

w12 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.85round/s, val_excess=0.0

w12 window rolling_4:  45%|▍| 90/200 [00:09<00:11,  9.85round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.81round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 91/200 [00:09<00:11,  9.81round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.77round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 92/200 [00:09<00:11,  9.77round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 93/200 [00:09<00:10,  9.80round/s, val_excess=0.0

w12 window rolling_4:  46%|▍| 93/200 [00:09<00:10,  9.80round/s, val_excess=0.0

w12 window rolling_4:  47%|▍| 94/200 [00:09<00:10,  9.83round/s, val_excess=0.0

w12 window rolling_4:  47%|▍| 94/200 [00:09<00:10,  9.83round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 95/200 [00:09<00:10,  9.87round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 95/200 [00:09<00:10,  9.87round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 96/200 [00:09<00:10,  9.86round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 96/200 [00:09<00:10,  9.86round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 97/200 [00:09<00:10,  9.81round/s, val_excess=0.0

w12 window rolling_4:  48%|▍| 97/200 [00:09<00:10,  9.81round/s, val_excess=0.0

w12 window rolling_4:  49%|▍| 98/200 [00:10<00:10,  9.75round/s, val_excess=0.0

w12 window rolling_4:  49%|▍| 98/200 [00:10<00:10,  9.75round/s, val_excess=0.0

w12 window rolling_4:  50%|▍| 99/200 [00:10<00:10,  9.68round/s, val_excess=0.0

w12 window rolling_4:  50%|▍| 99/200 [00:10<00:10,  9.68round/s, val_excess=0.0

w12 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.68round/s, val_excess=0.

w12 window rolling_4:  50%|▌| 100/200 [00:10<00:10,  9.68round/s, val_excess=0.

w12 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.63round/s, val_excess=0.

w12 window rolling_4:  50%|▌| 101/200 [00:10<00:10,  9.63round/s, val_excess=0.

w12 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.59round/s, val_excess=0.

w12 window rolling_4:  51%|▌| 102/200 [00:10<00:10,  9.59round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 103/200 [00:10<00:10,  9.59round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 103/200 [00:10<00:10,  9.59round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 104/200 [00:10<00:09,  9.62round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 104/200 [00:10<00:09,  9.62round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 105/200 [00:10<00:09,  9.71round/s, val_excess=0.

w12 window rolling_4:  52%|▌| 105/200 [00:10<00:09,  9.71round/s, val_excess=0.

w12 window rolling_4:  53%|▌| 106/200 [00:10<00:09,  9.76round/s, val_excess=0.

w12 window rolling_4:  53%|▌| 106/200 [00:10<00:09,  9.76round/s, val_excess=0.

w12 window rolling_4:  54%|▌| 107/200 [00:10<00:09,  9.46round/s, val_excess=0.

w12 window rolling_4:  54%|▌| 107/200 [00:10<00:09,  9.46round/s, val_excess=0.

w12 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.54round/s, val_excess=0.

w12 window rolling_4:  54%|▌| 108/200 [00:11<00:09,  9.54round/s, val_excess=0.

w12 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.66round/s, val_excess=0.

w12 window rolling_4:  55%|▌| 109/200 [00:11<00:09,  9.66round/s, val_excess=0.

w12 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.66round/s, val_excess=0.

w12 window rolling_4:  55%|▌| 110/200 [00:11<00:09,  9.66round/s, val_excess=0.

w12 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.64round/s, val_excess=0.

w12 window rolling_4:  56%|▌| 111/200 [00:11<00:09,  9.64round/s, val_excess=0.

w12 window rolling_4:  56%|▌| 112/200 [00:11<00:09,  9.64round/s, val_excess=0.

w12 window rolling_4:  56%|▌| 113/200 [00:11<00:08,  9.79round/s, val_excess=0.

w12 window rolling_4:  56%|▌| 113/200 [00:11<00:08,  9.79round/s, val_excess=0.

w12 window rolling_4:  57%|▌| 114/200 [00:11<00:08,  9.76round/s, val_excess=0.

w12 window rolling_4:  57%|▌| 114/200 [00:11<00:08,  9.76round/s, val_excess=0.

w12 window rolling_4:  57%|▌| 115/200 [00:11<00:08,  9.68round/s, val_excess=0.

w12 window rolling_4:  57%|▌| 115/200 [00:11<00:08,  9.68round/s, val_excess=-0

w12 window rolling_4:  58%|▌| 116/200 [00:11<00:08,  9.67round/s, val_excess=-0

w12 window rolling_4:  58%|▌| 116/200 [00:11<00:08,  9.67round/s, val_excess=-0

w12 window rolling_4:  58%|▌| 117/200 [00:11<00:08,  9.68round/s, val_excess=-0

w12 window rolling_4:  58%|▌| 117/200 [00:11<00:08,  9.68round/s, val_excess=-0

w12 window rolling_4:  59%|▌| 118/200 [00:12<00:08,  9.68round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.78round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 119/200 [00:12<00:08,  9.78round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.76round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 120/200 [00:12<00:08,  9.76round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.66round/s, val_excess=-0

w12 window rolling_4:  60%|▌| 121/200 [00:12<00:08,  9.66round/s, val_excess=-0

w12 window rolling_4:  61%|▌| 122/200 [00:12<00:08,  9.69round/s, val_excess=-0

w12 window rolling_4:  61%|▌| 122/200 [00:12<00:08,  9.69round/s, val_excess=-0

w12 window rolling_4:  62%|▌| 123/200 [00:12<00:08,  9.59round/s, val_excess=-0

w12 window rolling_4:  62%|▌| 123/200 [00:12<00:08,  9.59round/s, val_excess=-0

w12 window rolling_4:  62%|▌| 124/200 [00:12<00:07,  9.55round/s, val_excess=-0

w12 window rolling_4:  62%|▌| 124/200 [00:12<00:07,  9.55round/s, val_excess=-0

w12 window rolling_4:  62%|▋| 125/200 [00:12<00:07,  9.63round/s, val_excess=-0

w12 window rolling_4:  62%|▋| 125/200 [00:12<00:07,  9.63round/s, val_excess=-0

w12 window rolling_4:  63%|▋| 126/200 [00:12<00:07,  9.66round/s, val_excess=-0

w12 window rolling_4:  63%|▋| 126/200 [00:12<00:07,  9.66round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.64round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 127/200 [00:13<00:07,  9.64round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.62round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 128/200 [00:13<00:07,  9.62round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.68round/s, val_excess=-0

w12 window rolling_4:  64%|▋| 129/200 [00:13<00:07,  9.68round/s, val_excess=-0

w12 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.60round/s, val_excess=-0

w12 window rolling_4:  65%|▋| 130/200 [00:13<00:07,  9.60round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 131/200 [00:13<00:07,  9.56round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 131/200 [00:13<00:07,  9.56round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 132/200 [00:13<00:07,  9.21round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 132/200 [00:13<00:07,  9.21round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 133/200 [00:13<00:07,  9.31round/s, val_excess=-0

w12 window rolling_4:  66%|▋| 133/200 [00:13<00:07,  9.31round/s, val_excess=-0

w12 window rolling_4:  67%|▋| 134/200 [00:13<00:06,  9.51round/s, val_excess=-0

w12 window rolling_4:  67%|▋| 134/200 [00:13<00:06,  9.51round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 135/200 [00:13<00:06,  9.58round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 135/200 [00:13<00:06,  9.58round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 136/200 [00:13<00:06,  9.69round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 136/200 [00:13<00:06,  9.69round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.77round/s, val_excess=-0

w12 window rolling_4:  68%|▋| 137/200 [00:14<00:06,  9.77round/s, val_excess=-0

w12 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.78round/s, val_excess=-0

w12 window rolling_4:  69%|▋| 138/200 [00:14<00:06,  9.78round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.74round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 139/200 [00:14<00:06,  9.74round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.74round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 140/200 [00:14<00:06,  9.74round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 141/200 [00:14<00:06,  9.64round/s, val_excess=-0

w12 window rolling_4:  70%|▋| 141/200 [00:14<00:06,  9.64round/s, val_excess=-0

w12 window rolling_4:  71%|▋| 142/200 [00:14<00:06,  9.63round/s, val_excess=-0

w12 window rolling_4:  71%|▋| 142/200 [00:14<00:06,  9.63round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 143/200 [00:14<00:05,  9.62round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 143/200 [00:14<00:05,  9.62round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 144/200 [00:14<00:05,  9.56round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 144/200 [00:14<00:05,  9.56round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 145/200 [00:14<00:05,  9.57round/s, val_excess=0.

w12 window rolling_4:  72%|▋| 145/200 [00:14<00:05,  9.57round/s, val_excess=0.

w12 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.61round/s, val_excess=0.

w12 window rolling_4:  73%|▋| 146/200 [00:15<00:05,  9.61round/s, val_excess=0.

w12 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.67round/s, val_excess=0.

w12 window rolling_4:  74%|▋| 147/200 [00:15<00:05,  9.67round/s, val_excess=0.

w12 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.67round/s, val_excess=0.

w12 window rolling_4:  74%|▋| 148/200 [00:15<00:05,  9.67round/s, val_excess=-0

w12 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.56round/s, val_excess=-0

w12 window rolling_4:  74%|▋| 149/200 [00:15<00:05,  9.56round/s, val_excess=-0

w12 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.52round/s, val_excess=-0

w12 window rolling_4:  75%|▊| 150/200 [00:15<00:05,  9.52round/s, val_excess=-0

w12 window rolling_4:  76%|▊| 151/200 [00:15<00:05,  9.57round/s, val_excess=-0

w12 window rolling_4:  76%|▊| 151/200 [00:15<00:05,  9.57round/s, val_excess=0.

w12 window rolling_4:  76%|▊| 152/200 [00:15<00:05,  9.57round/s, val_excess=0.

w12 window rolling_4:  76%|▊| 153/200 [00:15<00:04,  9.71round/s, val_excess=0.

w12 window rolling_4:  76%|▊| 153/200 [00:15<00:04,  9.71round/s, val_excess=0.

w12 window rolling_4:  77%|▊| 154/200 [00:15<00:04,  9.72round/s, val_excess=0.

w12 window rolling_4:  77%|▊| 154/200 [00:15<00:04,  9.72round/s, val_excess=-0

w12 window rolling_4:  78%|▊| 155/200 [00:15<00:04,  9.72round/s, val_excess=-0

w12 window rolling_4:  78%|▊| 155/200 [00:15<00:04,  9.72round/s, val_excess=0.

w12 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.30round/s, val_excess=0.

w12 window rolling_4:  78%|▊| 156/200 [00:16<00:04,  9.30round/s, val_excess=0.

w12 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.41round/s, val_excess=0.

w12 window rolling_4:  78%|▊| 157/200 [00:16<00:04,  9.41round/s, val_excess=0.

w12 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.54round/s, val_excess=0.

w12 window rolling_4:  79%|▊| 158/200 [00:16<00:04,  9.54round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.48round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 159/200 [00:16<00:04,  9.48round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 160/200 [00:16<00:04,  9.45round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 160/200 [00:16<00:04,  9.45round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 161/200 [00:16<00:04,  9.42round/s, val_excess=0.

w12 window rolling_4:  80%|▊| 161/200 [00:16<00:04,  9.42round/s, val_excess=0.

w12 window rolling_4:  81%|▊| 162/200 [00:16<00:03,  9.55round/s, val_excess=0.

w12 window rolling_4:  81%|▊| 162/200 [00:16<00:03,  9.55round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 163/200 [00:16<00:03,  9.65round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 163/200 [00:16<00:03,  9.65round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 164/200 [00:16<00:03,  9.71round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 164/200 [00:16<00:03,  9.71round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 165/200 [00:16<00:03,  9.72round/s, val_excess=0.

w12 window rolling_4:  82%|▊| 165/200 [00:16<00:03,  9.72round/s, val_excess=0.

w12 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.64round/s, val_excess=0.

w12 window rolling_4:  83%|▊| 166/200 [00:17<00:03,  9.64round/s, val_excess=0.

w12 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.66round/s, val_excess=0.

w12 window rolling_4:  84%|▊| 167/200 [00:17<00:03,  9.66round/s, val_excess=0.

w12 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.75round/s, val_excess=0.

w12 window rolling_4:  84%|▊| 168/200 [00:17<00:03,  9.75round/s, val_excess=-0

w12 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.74round/s, val_excess=-0

w12 window rolling_4:  84%|▊| 169/200 [00:17<00:03,  9.74round/s, val_excess=0.

w12 window rolling_4:  85%|▊| 170/200 [00:17<00:03,  9.62round/s, val_excess=0.

w12 window rolling_4:  85%|▊| 170/200 [00:17<00:03,  9.62round/s, val_excess=-0

w12 window rolling_4:  86%|▊| 171/200 [00:17<00:03,  9.62round/s, val_excess=-0

w12 window rolling_4:  86%|▊| 171/200 [00:17<00:03,  9.62round/s, val_excess=-0

w12 window rolling_4:  86%|▊| 172/200 [00:17<00:02,  9.66round/s, val_excess=-0

w12 window rolling_4:  86%|▊| 172/200 [00:17<00:02,  9.66round/s, val_excess=0.

w12 window rolling_4:  86%|▊| 173/200 [00:17<00:02,  9.47round/s, val_excess=0.

w12 window rolling_4:  86%|▊| 173/200 [00:17<00:02,  9.47round/s, val_excess=0.

w12 window rolling_4:  87%|▊| 174/200 [00:17<00:02,  9.00round/s, val_excess=0.

w12 window rolling_4:  87%|▊| 174/200 [00:17<00:02,  9.00round/s, val_excess=-0

w12 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  8.69round/s, val_excess=-0

w12 window rolling_4:  88%|▉| 175/200 [00:18<00:02,  8.69round/s, val_excess=-0

w12 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  8.44round/s, val_excess=-0

w12 window rolling_4:  88%|▉| 176/200 [00:18<00:02,  8.44round/s, val_excess=0.

w12 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  8.16round/s, val_excess=0.

w12 window rolling_4:  88%|▉| 177/200 [00:18<00:02,  8.16round/s, val_excess=0.

w12 window rolling_4:  89%|▉| 178/200 [00:18<00:02,  8.08round/s, val_excess=0.

w12 window rolling_4:  89%|▉| 178/200 [00:18<00:02,  8.08round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 179/200 [00:18<00:02,  7.99round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 179/200 [00:18<00:02,  7.99round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 180/200 [00:18<00:02,  8.38round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 180/200 [00:18<00:02,  8.38round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 181/200 [00:18<00:02,  8.74round/s, val_excess=0.

w12 window rolling_4:  90%|▉| 181/200 [00:18<00:02,  8.74round/s, val_excess=0.

w12 window rolling_4:  91%|▉| 182/200 [00:18<00:01,  9.02round/s, val_excess=0.

w12 window rolling_4:  91%|▉| 182/200 [00:18<00:01,  9.02round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 183/200 [00:18<00:01,  9.23round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 183/200 [00:18<00:01,  9.23round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 184/200 [00:19<00:01,  9.24round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 184/200 [00:19<00:01,  9.24round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.44round/s, val_excess=0.

w12 window rolling_4:  92%|▉| 185/200 [00:19<00:01,  9.44round/s, val_excess=0.

w12 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.44round/s, val_excess=0.

w12 window rolling_4:  93%|▉| 186/200 [00:19<00:01,  9.44round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.41round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 187/200 [00:19<00:01,  9.41round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 188/200 [00:19<00:01,  9.47round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 188/200 [00:19<00:01,  9.47round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 189/200 [00:19<00:01,  9.25round/s, val_excess=0.

w12 window rolling_4:  94%|▉| 189/200 [00:19<00:01,  9.25round/s, val_excess=0.

w12 window rolling_4:  95%|▉| 190/200 [00:19<00:01,  9.37round/s, val_excess=0.

w12 window rolling_4:  95%|▉| 190/200 [00:19<00:01,  9.37round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 191/200 [00:19<00:00,  9.54round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 191/200 [00:19<00:00,  9.54round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 192/200 [00:19<00:00,  9.63round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 192/200 [00:19<00:00,  9.63round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.70round/s, val_excess=0.

w12 window rolling_4:  96%|▉| 193/200 [00:20<00:00,  9.70round/s, val_excess=0.

w12 window rolling_4:  97%|▉| 194/200 [00:20<00:00,  9.73round/s, val_excess=0.

w12 window rolling_4:  97%|▉| 194/200 [00:20<00:00,  9.73round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.21round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 195/200 [00:20<00:00,  9.21round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  8.80round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 196/200 [00:20<00:00,  8.80round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 197/200 [00:20<00:00,  8.46round/s, val_excess=0.

w12 window rolling_4:  98%|▉| 197/200 [00:20<00:00,  8.46round/s, val_excess=0.

w12 window rolling_4:  99%|▉| 198/200 [00:20<00:00,  8.24round/s, val_excess=0.

w12 window rolling_4:  99%|▉| 198/200 [00:20<00:00,  8.24round/s, val_excess=0.

w12 window rolling_4: 100%|▉| 199/200 [00:20<00:00,  8.11round/s, val_excess=0.

w12 window rolling_4: 100%|▉| 199/200 [00:20<00:00,  8.11round/s, val_excess=0.

w12 window rolling_4: 100%|█| 200/200 [00:20<00:00,  8.50round/s, val_excess=0.

w12 window rolling_4: 100%|█| 200/200 [00:20<00:00,  8.50round/s, val_excess=0.

w12 window rolling_4: 100%|█| 200/200 [00:20<00:00,  9.58round/s, val_excess=0.

2026-07-06 17:36:13 | INFO | xgb_pairwise_window_factor_validation_rolling_kfold | saved=output/xgb_pairwise_window_factor_validation_rolling_kfold.json elapsed=827.97s

,input_window,feature_type,features,fold_count,validation_top5_excess_return_mean,validation_top5_excess_return_std,validation_top5_excess_return_min,validation_top5_excess_positive_rate_mean,validation_top5_precision_mean,validation_rank_ic_mean,validation_top5_return_mean,validation_universe_return_mean
0,12,window,69,4,0.038844,0.009948,0.028770,0.8125,0.0875,0.084766,0.033477,-0.005367
1,2,window,69,4,0.037731,0.015105,0.019274,0.7500,0.1000,0.044837,0.032343,-0.005388
2,1,window,69,4,0.034167,0.015719,0.019352,0.9375,0.0750,0.042551,0.028778,-0.005388
3,4,window,69,4,0.032193,0.016603,0.010871,0.9375,0.0625,0.048188,0.026804,-0.005388
4,8,window,69,4,0.021752,0.014358,0.004610,0.7500,0.0375,0.089284,0.016360,-0.005392

In [4]:
captured = json.loads(OUTPUT_PATH.read_text(encoding='utf-8'))
leaderboard(pd.DataFrame(captured['summary']))

,input_window,feature_type,features,fold_count,validation_top5_excess_return_mean,validation_top5_excess_return_std,validation_top5_excess_return_min,validation_top5_excess_positive_rate_mean,validation_top5_precision_mean,validation_rank_ic_mean,validation_top5_return_mean,validation_universe_return_mean
0,12,window,69,4,0.038844,0.009948,0.028770,0.8125,0.0875,0.084766,0.033477,-0.005367
1,2,window,69,4,0.037731,0.015105,0.019274,0.7500,0.1000,0.044837,0.032343,-0.005388
2,1,window,69,4,0.034167,0.015719,0.019352,0.9375,0.0750,0.042551,0.028778,-0.005388
3,4,window,69,4,0.032193,0.016603,0.010871,0.9375,0.0625,0.048188,0.026804,-0.005388
4,8,window,69,4,0.021752,0.014358,0.004610,0.7500,0.0375,0.089284,0.016360,-0.005392